;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 15/05/2020 23:05:44
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$04DF	$	_mul_32x32_u:
$04DF	$1303			BCF	STATUS, RP1
$04E0	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$04E1	$3022			MOVLW	34
;math.ppas,1579 :: 		
$04E2	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$04E3	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$04E4	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$04E5	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$04E6	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$04E7	$	_NEXT:
;math.ppas,1589 :: 		
$04E7	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$04E8	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$04E9	$2D15			GOTO	_EXIT2
;math.ppas,1593 :: 		
$04EA	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$04EB	$	_LOOP:
;math.ppas,1603 :: 		
$04EB	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$04EC	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$04ED	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$04EE	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$04EF	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$04F0	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$04F1	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$04F2	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$04F3	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$04F4	$2CE7			GOTO	_NEXT
;math.ppas,1617 :: 		
$04F5	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$04F6	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$04F7	$2D07			GOTO	_EXIT1
;math.ppas,1626 :: 		
$04F8	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$04F9	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$04FA	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$04FB	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$04FC	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$04FD	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$04FE	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$04FF	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$0500	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$0501	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$0502	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$0503	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$0504	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$0505	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$0506	$2CEB			GOTO	_LOOP
;math.ppas,1647 :: 		
$0507	$	_EXIT1:
;math.ppas,1648 :: 		
$0507	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$0508	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$0509	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$050A	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$050B	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$050C	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$050D	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$050E	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$050F	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$0510	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$0511	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$0512	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$0513	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$0514	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$0515	$	_EXIT2:
;math.ppas,1665 :: 		
$0515	$	math_L_13:
;math.ppas,1666 :: 		
$0515	$0008			RETURN
$0134	$	_sdiv3232l:
$0134	$1303			BCF	STATUS, RP1
$0135	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$0136	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0137	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0138	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0139	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$013A	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$013B	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$013C	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$013D	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$013E	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$013F	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$0140	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$0141	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$0142	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$0143	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$0144	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$0145	$3007			MOVLW	7
;math.ppas,559 :: 		
$0146	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0147	$	LOOPS3232A:
;math.ppas,561 :: 		
$0147	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0148	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0149	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$014A	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$014B	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$014C	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$014D	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$014E	$295D			GOTO	SADD22LA
;math.ppas,570 :: 		
$014F	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$0150	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$0151	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$0152	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$0153	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$0154	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$0155	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$0156	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0157	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0158	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0159	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$015A	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$015B	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$015C	$296A			GOTO	SOK22LA
;math.ppas,585 :: 		
$015D	$	SADD22LA:
;math.ppas,586 :: 		
$015D	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$015E	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$015F	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$0160	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$0161	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$0162	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$0163	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$0164	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$0165	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$0166	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$0167	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$0168	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$0169	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$016A	$	SOK22LA:
;math.ppas,602 :: 		
$016A	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$016B	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$016C	$2947			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$016D	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$016E	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$016F	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$0170	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$0171	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$0172	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$0173	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$0174	$2983			GOTO	SADD22L8
;math.ppas,615 :: 		
$0175	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$0176	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$0177	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$0178	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$0179	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$017A	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$017B	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$017C	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$017D	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$017E	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$017F	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$0180	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$0181	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$0182	$2990			GOTO	SOK22L8
;math.ppas,630 :: 		
$0183	$	SADD22L8:
;math.ppas,631 :: 		
$0183	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$0184	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$0185	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$0186	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$0187	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$0188	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$0189	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$018A	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$018B	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$018C	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$018D	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$018E	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$018F	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$0190	$	SOK22L8:
;math.ppas,647 :: 		
$0190	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$0191	$3007			MOVLW	7
;math.ppas,650 :: 		
$0192	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$0193	$	LOOPS3232B:
;math.ppas,652 :: 		
$0193	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$0194	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$0195	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$0196	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$0197	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$0198	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$0199	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$019A	$29A9			GOTO	SADD22LB
;math.ppas,661 :: 		
$019B	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$019C	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$019D	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$019E	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$019F	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$01A0	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$01A1	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$01A2	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$01A3	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$01A4	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$01A5	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$01A6	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$01A7	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$01A8	$29B6			GOTO	SOK22LB
;math.ppas,676 :: 		
$01A9	$	SADD22LB:
;math.ppas,677 :: 		
$01A9	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$01AA	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$01AB	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$01AC	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$01AD	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$01AE	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$01AF	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$01B0	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$01B1	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$01B2	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$01B3	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$01B4	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$01B5	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$01B6	$	SOK22LB:
;math.ppas,693 :: 		
$01B6	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$01B7	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$01B8	$2993			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$01B9	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$01BA	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$01BB	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$01BC	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$01BD	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$01BE	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$01BF	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$01C0	$29CF			GOTO	SADD22L16
;math.ppas,706 :: 		
$01C1	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$01C2	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$01C3	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$01C4	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$01C5	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$01C6	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$01C7	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$01C8	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$01C9	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$01CA	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$01CB	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$01CC	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$01CD	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$01CE	$29DC			GOTO	SOK22L16
;math.ppas,721 :: 		
$01CF	$	SADD22L16:
;math.ppas,722 :: 		
$01CF	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$01D0	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$01D1	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$01D2	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$01D3	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$01D4	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$01D5	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$01D6	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$01D7	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$01D8	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$01D9	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$01DA	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$01DB	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$01DC	$	SOK22L16:
;math.ppas,738 :: 		
$01DC	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$01DD	$3007			MOVLW	7
;math.ppas,741 :: 		
$01DE	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$01DF	$	LOOPS3232C:
;math.ppas,743 :: 		
$01DF	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$01E0	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$01E1	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$01E2	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$01E3	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$01E4	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$01E5	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$01E6	$29F5			GOTO	SADD22LC
;math.ppas,752 :: 		
$01E7	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$01E8	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$01E9	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$01EA	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$01EB	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$01EC	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$01ED	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$01EE	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$01EF	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$01F0	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$01F1	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$01F2	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$01F3	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$01F4	$2A02			GOTO	SOK22LC
;math.ppas,767 :: 		
$01F5	$	SADD22LC:
;math.ppas,768 :: 		
$01F5	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$01F6	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$01F7	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$01F8	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$01F9	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$01FA	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$01FB	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$01FC	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$01FD	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$01FE	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$01FF	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$0200	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$0201	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$0202	$	SOK22LC:
;math.ppas,784 :: 		
$0202	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$0203	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$0204	$29DF			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$0205	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$0206	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$0207	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$0208	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$0209	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$020A	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$020B	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$020C	$2A1B			GOTO	SADD22L24
;math.ppas,797 :: 		
$020D	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$020E	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$020F	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$0210	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$0211	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$0212	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$0213	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$0214	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$0215	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$0216	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$0217	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$0218	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$0219	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$021A	$2A28			GOTO	SOK22L24
;math.ppas,812 :: 		
$021B	$	SADD22L24:
;math.ppas,813 :: 		
$021B	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$021C	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$021D	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$021E	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$021F	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$0220	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$0221	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$0222	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$0223	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$0224	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$0225	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$0226	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$0227	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$0228	$	SOK22L24:
;math.ppas,829 :: 		
$0228	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$0229	$3007			MOVLW	7
;math.ppas,832 :: 		
$022A	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$022B	$	LOOPS3232D:
;math.ppas,834 :: 		
$022B	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$022C	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$022D	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$022E	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$022F	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$0230	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$0231	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$0232	$2A41			GOTO	SADD22LD
;math.ppas,843 :: 		
$0233	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$0234	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$0235	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$0236	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0237	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0238	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0239	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$023A	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$023B	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$023C	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$023D	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$023E	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$023F	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$0240	$2A4E			GOTO	SOK22LD
;math.ppas,858 :: 		
$0241	$	SADD22LD:
;math.ppas,859 :: 		
$0241	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$0242	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$0243	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$0244	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$0245	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$0246	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0247	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0248	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0249	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$024A	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$024B	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$024C	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$024D	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$024E	$	SOK22LD:
;math.ppas,876 :: 		
$024E	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$024F	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$0250	$2A2B			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$0251	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$0252	$2A61			GOTO	SOK22L
;math.ppas,882 :: 		
$0253	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$0254	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$0255	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$0256	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0257	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0258	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0259	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$025A	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$025B	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$025C	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$025D	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$025E	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$025F	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$0260	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$0261	$	SOK22L:
;math.ppas,897 :: 		
$0261	$	math_L_9:
;math.ppas,898 :: 		
$0261	$0008			RETURN
$0588	$	_comfrem:
$0588	$1303			BCF	STATUS, RP1
$0589	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$058A	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$058B	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$058C	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$058D	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$058E	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$058F	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$0590	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$0591	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$0592	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$0593	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$0594	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$0595	$	math_L_10:
;math.ppas,915 :: 		
$0595	$0008			RETURN
$0596	$	_usart_data_ready:
;USART_b75.ppas,48 :: 		
;USART_b75.ppas,50 :: 		
$0596	$1303			BCF	STATUS, RP1
$0597	$1283			BCF	STATUS, RP0
$0598	$080C			MOVF	PIR1, 0
$0599	$00F1			MOVWF	STACK_1
$059A	$3000			MOVLW	0
$059B	$1AF1			BTFSC	STACK_1, 5
$059C	$3001			MOVLW	1
$059D	$00F1			MOVWF	STACK_1
$059E	$0871			MOVF	STACK_1, 0
$059F	$00C9			MOVWF	_usart_data_ready_local_result
$05A0	$	USART_b75_L_18:
;USART_b75.ppas,51 :: 		
$05A0	$0849			MOVF	_usart_data_ready_local_result, 0
$05A1	$00F0			MOVWF	STACK_0
$05A2	$0008			RETURN
$0575	$	_usart_read:
;USART_b75.ppas,54 :: 		
;USART_b75.ppas,55 :: 		
$0575	$1303			BCF	STATUS, RP1
$0576	$1283			BCF	STATUS, RP0
$0577	$081A			MOVF	RCREG, 0
$0578	$00C9			MOVWF	_usart_read_local_result
;USART_b75.ppas,61 :: 		
$0579	$0818			MOVF	RCSTA, 0
$057A	$00F1			MOVWF	STACK_1
$057B	$3000			MOVLW	0
$057C	$18F1			BTFSC	STACK_1, 1
$057D	$3001			MOVLW	1
$057E	$00F1			MOVWF	STACK_1
$057F	$0871			MOVF	STACK_1, 0
$0580	$3A01			XORLW	1
$0581	$1D03			BTFSS	STATUS, Z
$0582	$2D85			GOTO	USART_b75_L_21
$0583	$	USART_b75_L_20:
;USART_b75.ppas,63 :: 		
$0583	$1218			BCF	RCSTA, 4
$0584	$	USART_b75_L_24:
;USART_b75.ppas,64 :: 		
$0584	$	USART_b75_L_25:
$0584	$1618			BSF	RCSTA, 4
$0585	$	USART_b75_L_26:
;USART_b75.ppas,65 :: 		
$0585	$	USART_b75_L_21:
$0585	$	USART_b75_L_22:
$0585	$	USART_b75_L_19:
;USART_b75.ppas,66 :: 		
$0585	$0849			MOVF	_usart_read_local_result, 0
$0586	$00F0			MOVWF	STACK_0
$0587	$0008			RETURN
$04A4	$	_mul_32x32_s:
$04A4	$1303			BCF	STATUS, RP1
$04A5	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$04A6	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$04A7	$	_IF_FIRST:
;math.ppas,1684 :: 		
$04A7	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$04A8	$2CB6			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$04A9	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$04A9	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$04AA	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$04AB	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$04AC	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$04AD	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$04AE	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$04AF	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$04B0	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$04B1	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$04B2	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$04B3	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$04B4	$3081			MOVLW	129
;math.ppas,1711 :: 		
$04B5	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$04B6	$	_IF_SECOND:
;math.ppas,1715 :: 		
$04B6	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$04B7	$2CC4			GOTO	_MULT
;math.ppas,1722 :: 		
$04B8	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$04B8	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$04B9	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$04BA	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$04BB	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$04BC	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$04BD	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$04BE	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$04BF	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$04C0	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$04C1	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$04C2	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$04C3	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$04C4	$	_MULT:
;math.ppas,1744 :: 		
$04C4	$24DF			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$04C5	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$04C6	$2CDE			GOTO	_EXIT
;math.ppas,1755 :: 		
$04C7	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$04C8	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$04C9	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$04CA	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$04CB	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$04CC	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$04CD	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$04CE	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$04CF	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$04D0	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$04D1	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$04D2	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$04D3	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$04D4	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$04D5	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$04D6	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$04D7	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$04D8	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$04D9	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$04DA	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$04DB	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$04DC	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$04DD	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$04DE	$	_EXIT:
;math.ppas,1793 :: 		
$04DE	$	math_L_14:
;math.ppas,1794 :: 		
$04DE	$0008			RETURN
$0543	$	_div_16x16_u:
$0543	$1303			BCF	STATUS, RP1
$0544	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$0545	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$0546	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$0547	$3010			MOVLW	16
;math.ppas,113 :: 		
$0548	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$0549	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$054A	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$054B	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$054C	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$054D	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$054E	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$054F	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$0550	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$0551	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$0552	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$0553	$2D5B			GOTO	$+8
;math.ppas,125 :: 		
$0554	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$0555	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$0556	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$0557	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$0558	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$0559	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$055A	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$055B	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$055C	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$055D	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$055E	$2D49			GOTO	$-21
;math.ppas,136 :: 		
$055F	$	math_L_3:
;math.ppas,137 :: 		
$055F	$0008			RETURN
$0324	$	_div_32x32_s:
$0324	$1303			BCF	STATUS, RP1
$0325	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$0326	$	FXD3232S:
;math.ppas,929 :: 		
$0326	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$0327	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$0328	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$0329	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$032A	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$032B	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$032C	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$032D	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$032E	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$032F	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$0330	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$0331	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0332	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$0333	$2BB8			GOTO	END_ALL
;math.ppas,944 :: 		
$0334	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$0335	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$0336	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$0337	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$0338	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$0339	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$033A	$2B46			GOTO	CA3232S
;math.ppas,955 :: 		
$033B	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$033C	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$033D	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$033E	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$033F	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$0340	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$0341	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0342	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$0343	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$0344	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$0345	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$0346	$	CA3232S:
;math.ppas,968 :: 		
$0346	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$0347	$2B53			GOTO	C3232SX
;math.ppas,971 :: 		
$0348	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$0349	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$034A	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$034B	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$034C	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$034D	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$034E	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$034F	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$0350	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$0351	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$0352	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$0353	$	C3232SX:
;math.ppas,984 :: 		
$0353	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$0354	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$0355	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$0356	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$0357	$2B74			GOTO	C3232SX1
;math.ppas,989 :: 		
$0358	$	C3232S:
;math.ppas,992 :: 		
$0358	$2134			CALL	_sdiv3232l
;math.ppas,995 :: 		
$0359	$	C3232S2:
;math.ppas,996 :: 		
$0359	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$035A	$2B91			GOTO	C3232SX4
;math.ppas,998 :: 		
$035B	$	C3232SOK:
;math.ppas,999 :: 		
$035B	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$035C	$2BB8			GOTO	END_ALL
;math.ppas,1001 :: 		
$035D	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$035E	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$035F	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$0360	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$0361	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$0362	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$0363	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$0364	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$0365	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$0366	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$0367	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$0368	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$0369	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$036A	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$036B	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$036C	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$036D	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$036E	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$036F	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$0370	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$0371	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$0372	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$0373	$2BB8			GOTO	END_ALL
;math.ppas,1026 :: 		
$0374	$	C3232SX1:
;math.ppas,1027 :: 		
$0374	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$0375	$2B8B			GOTO	C3232SX3
;math.ppas,1029 :: 		
$0376	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$0377	$2B85			GOTO	C3232SX2
;math.ppas,1031 :: 		
$0378	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$0379	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$037A	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$037B	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$037C	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$037D	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$037E	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$037F	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$0380	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$0381	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$0382	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$0383	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$0384	$2B5B			GOTO	C3232SOK
;math.ppas,1044 :: 		
$0385	$	C3232SX2:
;math.ppas,1045 :: 		
$0385	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$0386	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$0387	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$0388	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$0389	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$038A	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$038B	$	C3232SX3:
;math.ppas,1053 :: 		
$038B	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$038C	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$038D	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$038E	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$038F	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$0390	$2B58			GOTO	C3232S
;math.ppas,1061 :: 		
$0391	$	C3232SX4:
;math.ppas,1062 :: 		
$0391	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0392	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$0393	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$0394	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$0395	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$0396	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$0397	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$0398	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$0399	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$039A	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$039B	$2B5B			GOTO	C3232SOK
;math.ppas,1073 :: 		
$039C	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$039D	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$039E	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$039F	$2B5B			GOTO	C3232SOK
;math.ppas,1077 :: 		
$03A0	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$03A1	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$03A2	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$03A3	$2B5B			GOTO	C3232SOK
;math.ppas,1081 :: 		
$03A4	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$03A5	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$03A6	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$03A7	$2B5B			GOTO	C3232SOK
;math.ppas,1085 :: 		
$03A8	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$03A9	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$03AA	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$03AB	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$03AC	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$03AD	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$03AE	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$03AF	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$03B0	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$03B1	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$03B2	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$03B3	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$03B4	$2B5B			GOTO	C3232SOK
;math.ppas,1098 :: 		
$03B5	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$03B6	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$03B7	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$03B8	$	END_ALL:
;math.ppas,1102 :: 		
$03B8	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$03B9	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$03BA	$2BBC			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$03BB	$2588			CALL	_comfrem
;math.ppas,1108 :: 		
$03BC	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$03BC	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$03BD	$	math_L_11:
;math.ppas,1111 :: 		
$03BD	$0008			RETURN
$0516	$	_div_16x16_s_l:
$0516	$1303			BCF	STATUS, RP1
$0517	$1283			BCF	STATUS, RP0
;math.ppas,291 :: 		
;math.ppas,293 :: 		
$0518	$0D71			RLF	STACK_1, W
;math.ppas,294 :: 		
$0519	$0DF8			RLF	STACK_8, F
;math.ppas,295 :: 		
$051A	$0DF9			RLF	STACK_9, F
;math.ppas,296 :: 		
$051B	$0874			MOVF	STACK_4, W
;math.ppas,297 :: 		
$051C	$02F8			SUBWF	STACK_8, F
;math.ppas,298 :: 		
$051D	$0875			MOVF	STACK_5, W
;math.ppas,299 :: 		
$051E	$1C03			BTFSS	STATUS, C
;math.ppas,300 :: 		
$051F	$0F75			INCFSZ	STACK_5, W
;math.ppas,301 :: 		
$0520	$02F9			SUBWF	STACK_9, F
;math.ppas,302 :: 		
$0521	$0DF0			RLF	STACK_0, F
;math.ppas,304 :: 		
$0522	$0DF1			RLF	STACK_1, F
;math.ppas,305 :: 		
$0523	$300F			MOVLW	15
;math.ppas,307 :: 		
$0524	$00FC			MOVWF	STACK_12
;math.ppas,308 :: 		
$0525	$0D71			RLF	STACK_1, W
;math.ppas,309 :: 		
$0526	$0DF8			RLF	STACK_8, F
;math.ppas,310 :: 		
$0527	$0DF9			RLF	STACK_9, F
;math.ppas,312 :: 		
$0528	$0874			MOVF	STACK_4, W
;math.ppas,313 :: 		
$0529	$1C70			BTFSS	STACK_0, 0
;math.ppas,314 :: 		
$052A	$2D31			GOTO	$+7
;math.ppas,315 :: 		
$052B	$02F8			SUBWF	STACK_8, F
;math.ppas,316 :: 		
$052C	$0875			MOVF	STACK_5, W
;math.ppas,317 :: 		
$052D	$1C03			BTFSS	STATUS, C
;math.ppas,318 :: 		
$052E	$0F75			INCFSZ	STACK_5, W
;math.ppas,319 :: 		
$052F	$02F9			SUBWF	STACK_9, F
;math.ppas,321 :: 		
$0530	$2D36			GOTO	$+6
;math.ppas,322 :: 		
$0531	$07F8			ADDWF	STACK_8, F
;math.ppas,323 :: 		
$0532	$0875			MOVF	STACK_5, W
;math.ppas,324 :: 		
$0533	$1803			BTFSC	STATUS, C
;math.ppas,325 :: 		
$0534	$0F75			INCFSZ	STACK_5, W
;math.ppas,327 :: 		
$0535	$07F9			ADDWF	STACK_9, F
;math.ppas,328 :: 		
$0536	$0DF0			RLF	STACK_0, F
;math.ppas,330 :: 		
$0537	$0DF1			RLF	STACK_1, F
;math.ppas,331 :: 		
$0538	$0BFC			DECFSZ	STACK_12, F
;math.ppas,333 :: 		
$0539	$2D25			GOTO	$-20
;math.ppas,334 :: 		
$053A	$1870			BTFSC	STACK_0, 0
;math.ppas,335 :: 		
$053B	$2D42			GOTO	$+7
;math.ppas,336 :: 		
$053C	$0874			MOVF	STACK_4, W
;math.ppas,337 :: 		
$053D	$07F8			ADDWF	STACK_8, F
;math.ppas,338 :: 		
$053E	$0875			MOVF	STACK_5, W
;math.ppas,339 :: 		
$053F	$1803			BTFSC	STATUS, C
;math.ppas,340 :: 		
$0540	$0F75			INCFSZ	STACK_5, W
;math.ppas,341 :: 		
$0541	$07F9			ADDWF	STACK_9, F
;math.ppas,342 :: 		
$0542	$	math_L_6:
;math.ppas,343 :: 		
$0542	$0008			RETURN
$0418	$	_usart_read_text:
;USART_b75.ppas,78 :: 		
;USART_b75.ppas,79 :: 		
$0418	$1303			BCF	STATUS, RP1
$0419	$1283			BCF	STATUS, RP0
$041A	$01BE			CLRF	_usart_read_text_local_i, 1
;USART_b75.ppas,80 :: 		
$041B	$01BF			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,81 :: 		
$041C	$01C2			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,82 :: 		
$041D	$083D			MOVF	FARG_Usart_Read_Text+1, 0
$041E	$0084			MOVWF	FSR
$041F	$0800			MOVF	INDF, 0
$0420	$00C1			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,83 :: 		
$0421	$	USART_b75_L_29:
;USART_b75.ppas,85 :: 		
$0421	$2596			CALL	_usart_data_ready
$0422	$0870			MOVF	STACK_0, 0
$0423	$3A00			XORLW	0
$0424	$1903			BTFSC	STATUS, Z
$0425	$2C51			GOTO	USART_b75_L_34
$0426	$	USART_b75_L_33:
;USART_b75.ppas,87 :: 		
$0426	$2575			CALL	_usart_read
$0427	$0870			MOVF	STACK_0, 0
$0428	$00C0			MOVWF	_usart_read_text_local_data
;USART_b75.ppas,88 :: 		
$0429	$083E			MOVF	_usart_read_text_local_i, 0
$042A	$073C			ADDWF	FARG_Usart_Read_Text, 0
$042B	$00F1			MOVWF	STACK_1
$042C	$0871			MOVF	STACK_1, 0
$042D	$0084			MOVWF	FSR
$042E	$0871			MOVF	STACK_1, 0
$042F	$0084			MOVWF	FSR
$0430	$0870			MOVF	STACK_0, 0
$0431	$0080			MOVWF	INDF
;USART_b75.ppas,89 :: 		
$0432	$0840			MOVF	_usart_read_text_local_data, 0
$0433	$0641			XORWF	_usart_read_text_local_data2, 0
$0434	$1D03			BTFSS	STATUS, Z
$0435	$2C3B			GOTO	USART_b75_L_37
$0436	$	USART_b75_L_36:
;USART_b75.ppas,91 :: 		
$0436	$083F			MOVF	_usart_read_text_local_j, 0
$0437	$023E			SUBWF	_usart_read_text_local_i, 0
$0438	$00C2			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,92 :: 		
$0439	$0ABF			INCF	_usart_read_text_local_j, 1
;USART_b75.ppas,93 :: 		
$043A	$2C3D			GOTO	USART_b75_L_38
;USART_b75.ppas,94 :: 		
$043B	$	USART_b75_L_37:
;USART_b75.ppas,96 :: 		
$043B	$01BF			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,97 :: 		
$043C	$01C2			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,98 :: 		
$043D	$	USART_b75_L_38:
;USART_b75.ppas,100 :: 		
$043D	$083F			MOVF	_usart_read_text_local_j, 0
$043E	$073D			ADDWF	FARG_Usart_Read_Text+1, 0
$043F	$0084			MOVWF	FSR
$0440	$0800			MOVF	INDF, 0
$0441	$00F1			MOVWF	STACK_1
$0442	$0871			MOVF	STACK_1, 0
$0443	$00C1			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,102 :: 		
$0444	$0871			MOVF	STACK_1, 0
$0445	$3A00			XORLW	0
$0446	$1D03			BTFSS	STATUS, Z
$0447	$2C49			GOTO	USART_b75_L_40
$0448	$	USART_b75_L_39:
;USART_b75.ppas,103 :: 		
$0448	$2C52			GOTO	USART_b75_L_30
$0449	$	USART_b75_L_40:
$0449	$	USART_b75_L_41:
;USART_b75.ppas,105 :: 		
$0449	$0ABE			INCF	_usart_read_text_local_i, 1
;USART_b75.ppas,106 :: 		
$044A	$083E			MOVF	_usart_read_text_local_i, 0
$044B	$3C14			SUBLW	20
$044C	$1803			BTFSC	STATUS, C
$044D	$2C51			GOTO	USART_b75_L_43
$044E	$	USART_b75_L_42:
;USART_b75.ppas,108 :: 		
$044E	$3013			MOVLW	19
$044F	$00C2			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,109 :: 		
$0450	$2C52			GOTO	USART_b75_L_30
;USART_b75.ppas,110 :: 		
$0451	$	USART_b75_L_43:
$0451	$	USART_b75_L_44:
;USART_b75.ppas,111 :: 		
$0451	$	USART_b75_L_34:
$0451	$	USART_b75_L_35:
;USART_b75.ppas,112 :: 		
$0451	$2C21			GOTO	USART_b75_L_29
$0452	$	USART_b75_L_30:
;USART_b75.ppas,113 :: 		
$0452	$0842			MOVF	_usart_read_text_local_lasti, 0
$0453	$073C			ADDWF	FARG_Usart_Read_Text, 0
$0454	$00F0			MOVWF	STACK_0
$0455	$0870			MOVF	STACK_0, 0
$0456	$0084			MOVWF	FSR
$0457	$0870			MOVF	STACK_0, 0
$0458	$0084			MOVWF	FSR
$0459	$0180			CLRF	INDF, 1
$045A	$	USART_b75_L_27:
;USART_b75.ppas,114 :: 		
$045A	$0008			RETURN
$0262	$	_strtoint:
;conv.ppas,343 :: 		
;conv.ppas,345 :: 		
$0262	$1303			BCF	STATUS, RP1
$0263	$1283			BCF	STATUS, RP0
$0264	$01BD			CLRF	_strtoint_local_result
$0265	$01BE			CLRF	_strtoint_local_result+1
;conv.ppas,346 :: 		
$0266	$3010			MOVLW	16
$0267	$00C1			MOVWF	_strtoint_local_ep
$0268	$3027			MOVLW	39
$0269	$00C2			MOVWF	_strtoint_local_ep+1
;conv.ppas,347 :: 		
$026A	$01BF			CLRF	_strtoint_local_i
$026B	$01C0			CLRF	_strtoint_local_i+1
;conv.ppas,348 :: 		
$026C	$01C5			CLRF	_strtoint_local_tmp
$026D	$01C6			CLRF	_strtoint_local_tmp+1
$026E	$01C7			CLRF	_strtoint_local_tmp+2
$026F	$01C8			CLRF	_strtoint_local_tmp+3
;conv.ppas,349 :: 		
$0270	$01C3			CLRF	_strtoint_local_negative
$0271	$01C4			CLRF	_strtoint_local_negative+1
;conv.ppas,353 :: 		
$0272	$	conv_L_172:
$0272	$083F			MOVF	_strtoint_local_i, 0
$0273	$073C			ADDWF	FARG_StrToInt, 0
$0274	$0084			MOVWF	FSR
$0275	$0800			MOVF	INDF, 0
$0276	$00F4			MOVWF	STACK_4
$0277	$0874			MOVF	STACK_4, 0
$0278	$3A00			XORLW	0
$0279	$1903			BTFSC	STATUS, Z
$027A	$2ADE			GOTO	conv_L_173
;conv.ppas,355 :: 		
$027B	$083F			MOVF	_strtoint_local_i, 0
$027C	$073C			ADDWF	FARG_StrToInt, 0
$027D	$0084			MOVWF	FSR
$027E	$0800			MOVF	INDF, 0
$027F	$00F4			MOVWF	STACK_4
$0280	$0874			MOVF	STACK_4, 0
$0281	$3A2D			XORLW	45
$0282	$1D03			BTFSS	STATUS, Z
$0283	$2A8B			GOTO	conv_L_177
$0284	$	conv_L_176:
;conv.ppas,357 :: 		
$0284	$30FF			MOVLW	255
$0285	$00C3			MOVWF	_strtoint_local_negative
$0286	$01C4			CLRF	_strtoint_local_negative+1
;conv.ppas,358 :: 		
$0287	$0ABF			INCF	_strtoint_local_i, 1
$0288	$1903			BTFSC	STATUS, Z
$0289	$0AC0			INCF	_strtoint_local_i+1, 1
;conv.ppas,359 :: 		
$028A	$2A72			GOTO	conv_L_172
;conv.ppas,360 :: 		
$028B	$	conv_L_177:
$028B	$	conv_L_178:
;conv.ppas,361 :: 		
$028B	$083F			MOVF	_strtoint_local_i, 0
$028C	$073C			ADDWF	FARG_StrToInt, 0
$028D	$0084			MOVWF	FSR
$028E	$0800			MOVF	INDF, 0
$028F	$00F4			MOVWF	STACK_4
$0290	$0874			MOVF	STACK_4, 0
$0291	$3A20			XORLW	32
$0292	$1903			BTFSC	STATUS, Z
$0293	$2ACE			GOTO	conv_L_180
$0294	$	conv_L_179:
;conv.ppas,362 :: 		
$0294	$083F			MOVF	_strtoint_local_i, 0
$0295	$073C			ADDWF	FARG_StrToInt, 0
$0296	$0084			MOVWF	FSR
$0297	$0800			MOVF	INDF, 0
$0298	$00F0			MOVWF	STACK_0
$0299	$3030			MOVLW	48
$029A	$00F8			MOVWF	STACK_8
$029B	$01F9			CLRF	STACK_8+1
$029C	$01FA			CLRF	STACK_8+2
$029D	$01FB			CLRF	STACK_8+3
$029E	$0870			MOVF	STACK_0, 0
$029F	$00F4			MOVWF	STACK_4
$02A0	$01F5			CLRF	STACK_4+1
$02A1	$01F6			CLRF	STACK_4+2
$02A2	$01F7			CLRF	STACK_4+3
$02A3	$0874			MOVF	STACK_4, 0
$02A4	$00F0			MOVWF	STACK_0
$02A5	$0875			MOVF	STACK_4+1, 0
$02A6	$00F1			MOVWF	STACK_0+1
$02A7	$0876			MOVF	STACK_4+2, 0
$02A8	$00F2			MOVWF	STACK_0+2
$02A9	$0877			MOVF	STACK_4+3, 0
$02AA	$00F3			MOVWF	STACK_0+3
$02AB	$0878			MOVF	STACK_8, 0
$02AC	$02F0			SUBWF	STACK_0, 1
$02AD	$0879			MOVF	STACK_8+1, 0
$02AE	$1C03			BTFSS	STATUS, C
$02AF	$0F79			INCFSZ	STACK_8+1, 0
$02B0	$02F1			SUBWF	STACK_0+1, 1
$02B1	$087A			MOVF	STACK_8+2, 0
$02B2	$1C03			BTFSS	STATUS, C
$02B3	$0F7A			INCFSZ	STACK_8+2, 0
$02B4	$02F2			SUBWF	STACK_0+2, 1
$02B5	$087B			MOVF	STACK_8+3, 0
$02B6	$1C03			BTFSS	STATUS, C
$02B7	$0F7B			INCFSZ	STACK_8+3, 0
$02B8	$02F3			SUBWF	STACK_0+3, 1
$02B9	$0841			MOVF	_strtoint_local_ep, 0
$02BA	$00F4			MOVWF	STACK_4
$02BB	$0842			MOVF	_strtoint_local_ep+1, 0
$02BC	$00F5			MOVWF	STACK_4+1
$02BD	$01F6			CLRF	STACK_4+2
$02BE	$01F7			CLRF	STACK_4+3
$02BF	$24A4			CALL	_mul_32x32_s
$02C0	$0870			MOVF	STACK_0, 0
$02C1	$07C5			ADDWF	_strtoint_local_tmp, 1
$02C2	$0871			MOVF	STACK_0+1, 0
$02C3	$1803			BTFSC	STATUS, C
$02C4	$0F71			INCFSZ	STACK_0+1, 0
$02C5	$07C6			ADDWF	_strtoint_local_tmp+1, 1
$02C6	$0872			MOVF	STACK_0+2, 0
$02C7	$1803			BTFSC	STATUS, C
$02C8	$0F72			INCFSZ	STACK_0+2, 0
$02C9	$07C7			ADDWF	_strtoint_local_tmp+2, 1
$02CA	$0873			MOVF	STACK_0+3, 0
$02CB	$1803			BTFSC	STATUS, C
$02CC	$0F73			INCFSZ	STACK_0+3, 0
$02CD	$07C8			ADDWF	_strtoint_local_tmp+3, 1
$02CE	$	conv_L_180:
$02CE	$	conv_L_181:
;conv.ppas,363 :: 		
$02CE	$300A			MOVLW	10
$02CF	$00F4			MOVWF	STACK_4
$02D0	$01F5			CLRF	STACK_4+1
$02D1	$0841			MOVF	_strtoint_local_ep, 0
$02D2	$00F0			MOVWF	STACK_0
$02D3	$0842			MOVF	_strtoint_local_ep+1, 0
$02D4	$00F1			MOVWF	STACK_0+1
$02D5	$2543			CALL	_div_16x16_u
$02D6	$0870			MOVF	STACK_0, 0
$02D7	$00C1			MOVWF	_strtoint_local_ep
$02D8	$0871			MOVF	STACK_0+1, 0
$02D9	$00C2			MOVWF	_strtoint_local_ep+1
;conv.ppas,365 :: 		
$02DA	$0ABF			INCF	_strtoint_local_i, 1
$02DB	$1903			BTFSC	STATUS, Z
$02DC	$0AC0			INCF	_strtoint_local_i+1, 1
;conv.ppas,366 :: 		
$02DD	$2A72			GOTO	conv_L_172
$02DE	$	conv_L_173:
;conv.ppas,370 :: 		
$02DE	$0843			MOVF	_strtoint_local_negative, 0
$02DF	$0444			IORWF	_strtoint_local_negative+1, 0
$02E0	$1903			BTFSC	STATUS, Z
$02E1	$2AE6			GOTO	conv_L_183
$02E2	$	conv_L_182:
$02E2	$3006			MOVLW	6
$02E3	$00C1			MOVWF	_strtoint_local_ep
$02E4	$01C2			CLRF	_strtoint_local_ep+1
$02E5	$2AE9			GOTO	conv_L_184
;conv.ppas,371 :: 		
$02E6	$	conv_L_183:
$02E6	$3005			MOVLW	5
$02E7	$00C1			MOVWF	_strtoint_local_ep
$02E8	$01C2			CLRF	_strtoint_local_ep+1
$02E9	$	conv_L_184:
;conv.ppas,373 :: 		
$02E9	$	conv_L_186:
$02E9	$0840			MOVF	_strtoint_local_i+1, 0
$02EA	$0642			XORWF	_strtoint_local_ep+1, 0
$02EB	$1D03			BTFSS	STATUS, Z
$02EC	$2AEF			GOTO	L_StrToInt_20
$02ED	$0841			MOVF	_strtoint_local_ep, 0
$02EE	$063F			XORWF	_strtoint_local_i, 0
$02EF	$	L_StrToInt_20:
$02EF	$1903			BTFSC	STATUS, Z
$02F0	$2B0B			GOTO	conv_L_187
;conv.ppas,375 :: 		
$02F1	$300A			MOVLW	10
$02F2	$00F4			MOVWF	STACK_4
$02F3	$01F5			CLRF	STACK_4+1
$02F4	$01F6			CLRF	STACK_4+2
$02F5	$01F7			CLRF	STACK_4+3
$02F6	$0845			MOVF	_strtoint_local_tmp, 0
$02F7	$00F0			MOVWF	STACK_0
$02F8	$0846			MOVF	_strtoint_local_tmp+1, 0
$02F9	$00F1			MOVWF	STACK_0+1
$02FA	$0847			MOVF	_strtoint_local_tmp+2, 0
$02FB	$00F2			MOVWF	STACK_0+2
$02FC	$0848			MOVF	_strtoint_local_tmp+3, 0
$02FD	$00F3			MOVWF	STACK_0+3
$02FE	$2324			CALL	_div_32x32_s
$02FF	$0870			MOVF	STACK_0, 0
$0300	$00C5			MOVWF	_strtoint_local_tmp
$0301	$0871			MOVF	STACK_0+1, 0
$0302	$00C6			MOVWF	_strtoint_local_tmp+1
$0303	$0872			MOVF	STACK_0+2, 0
$0304	$00C7			MOVWF	_strtoint_local_tmp+2
$0305	$0873			MOVF	STACK_0+3, 0
$0306	$00C8			MOVWF	_strtoint_local_tmp+3
;conv.ppas,376 :: 		
$0307	$0ABF			INCF	_strtoint_local_i, 1
$0308	$1903			BTFSC	STATUS, Z
$0309	$0AC0			INCF	_strtoint_local_i+1, 1
;conv.ppas,377 :: 		
$030A	$2AE9			GOTO	conv_L_186
$030B	$	conv_L_187:
;conv.ppas,380 :: 		
$030B	$0845			MOVF	_strtoint_local_tmp, 0
$030C	$00BD			MOVWF	_strtoint_local_result
$030D	$0846			MOVF	_strtoint_local_tmp+1, 0
$030E	$00BE			MOVWF	_strtoint_local_result+1
;conv.ppas,382 :: 		
$030F	$3000			MOVLW	0
$0310	$0644			XORWF	_strtoint_local_negative+1, 0
$0311	$1D03			BTFSS	STATUS, Z
$0312	$2B15			GOTO	L_StrToInt_21
$0313	$30FF			MOVLW	255
$0314	$0643			XORWF	_strtoint_local_negative, 0
$0315	$	L_StrToInt_21:
$0315	$1D03			BTFSS	STATUS, Z
$0316	$2B1F			GOTO	conv_L_191
$0317	$	conv_L_190:
;conv.ppas,383 :: 		
$0317	$083D			MOVF	_strtoint_local_result, 0
$0318	$3C00			SUBLW	0
$0319	$00BD			MOVWF	_strtoint_local_result
$031A	$083E			MOVF	_strtoint_local_result+1, 0
$031B	$1C03			BTFSS	STATUS, C
$031C	$3F01			ADDLW	1
$031D	$01BE			CLRF	_strtoint_local_result+1
$031E	$02BE			SUBWF	_strtoint_local_result+1, 1
$031F	$	conv_L_191:
$031F	$	conv_L_192:
$031F	$	conv_L_170:
;conv.ppas,384 :: 		
$031F	$083D			MOVF	_strtoint_local_result, 0
$0320	$00F0			MOVWF	STACK_0
$0321	$083E			MOVF	_strtoint_local_result+1, 0
$0322	$00F1			MOVWF	STACK_0+1
$0323	$0008			RETURN
$0560	$	_usart_init:
;USART_b75.ppas,22 :: 		
;USART_b75.ppas,24 :: 		
$0560	$	USART_b75_L_1:
$0560	$1303			BCF	STATUS, RP1
$0561	$1683			BSF	STATUS, RP0
$0562	$1698			BSF	TXSTA, 5
$0563	$	USART_b75_L_2:
;USART_b75.ppas,25 :: 		
$0563	$3090			MOVLW	144
$0564	$1283			BCF	STATUS, RP0
$0565	$0098			MOVWF	RCSTA
;USART_b75.ppas,31 :: 		
$0566	$	USART_b75_L_3:
$0566	$1683			BSF	STATUS, RP0
$0567	$1686			BSF	TRISB, 5
$0568	$	USART_b75_L_4:
;USART_b75.ppas,32 :: 		
$0568	$	USART_b75_L_5:
$0568	$1786			BSF	TRISB, 7
$0569	$	USART_b75_L_6:
;USART_b75.ppas,35 :: 		
$0569	$	USART_b75_L_8:
$0569	$1283			BCF	STATUS, RP0
$056A	$080C			MOVF	PIR1, 0
$056B	$00F1			MOVWF	STACK_1
$056C	$3000			MOVLW	0
$056D	$1AF1			BTFSC	STACK_1, 5
$056E	$3001			MOVLW	1
$056F	$00F1			MOVWF	STACK_1
$0570	$0871			MOVF	STACK_1, 0
$0571	$3A01			XORLW	1
$0572	$1903			BTFSC	STATUS, Z
$0573	$2D69			GOTO	USART_b75_L_8
;USART_b75.ppas,36 :: 		
$0574	$	USART_b75_L_9:
$0574	$	USART_b75_L_0:
;USART_b75.ppas,37 :: 		
$0574	$0008			RETURN
$03BE	$	_div_16x16_s:
$03BE	$1303			BCF	STATUS, RP1
$03BF	$1283			BCF	STATUS, RP0
;math.ppas,346 :: 		
;math.ppas,348 :: 		
$03C0	$01FD			CLRF	STACK_13
;math.ppas,349 :: 		
$03C1	$01F9			CLRF	STACK_9
;math.ppas,350 :: 		
$03C2	$01F8			CLRF	STACK_8
;math.ppas,351 :: 		
$03C3	$0871			MOVF	STACK_1, W
;math.ppas,352 :: 		
$03C4	$0470			IORWF	STACK_0, W
;math.ppas,353 :: 		
$03C5	$1903			BTFSC	STATUS, Z
;math.ppas,355 :: 		
$03C6	$3400			RETLW	0
;math.ppas,356 :: 		
$03C7	$0871			MOVF	STACK_1, W
;math.ppas,357 :: 		
$03C8	$0675			XORWF	STACK_5, W
;math.ppas,358 :: 		
$03C9	$00FA			MOVWF	STACK_10
;math.ppas,359 :: 		
$03CA	$1BFA			BTFSC	STACK_10, 7
;math.ppas,361 :: 		
$03CB	$09FD			COMF	STACK_13, F
;math.ppas,363 :: 		
$03CC	$01FB			CLRF	STACK_11
;math.ppas,364 :: 		
$03CD	$1FF5			BTFSS	STACK_5, 7
;math.ppas,366 :: 		
$03CE	$2BD4			GOTO	$+6
;math.ppas,367 :: 		
$03CF	$09F4			COMF	STACK_4, F
;math.ppas,368 :: 		
$03D0	$09F5			COMF	STACK_5, F
;math.ppas,369 :: 		
$03D1	$0AF4			INCF	STACK_4, F
;math.ppas,370 :: 		
$03D2	$1903			BTFSC	STATUS, Z
;math.ppas,372 :: 		
$03D3	$0AF5			INCF	STACK_5, F
;math.ppas,373 :: 		
$03D4	$1FF1			BTFSS	STACK_1, 7
;math.ppas,375 :: 		
$03D5	$2BDB			GOTO	$+6
;math.ppas,376 :: 		
$03D6	$09F0			COMF	STACK_0, F
;math.ppas,377 :: 		
$03D7	$09F1			COMF	STACK_1, F
;math.ppas,378 :: 		
$03D8	$0AF0			INCF	STACK_0, F
;math.ppas,379 :: 		
$03D9	$1903			BTFSC	STATUS, Z
;math.ppas,381 :: 		
$03DA	$0AF1			INCF	STACK_1, F
;math.ppas,382 :: 		
$03DB	$0871			MOVF	STACK_1, W
;math.ppas,383 :: 		
$03DC	$0475			IORWF	STACK_5, W
;math.ppas,384 :: 		
$03DD	$00FA			MOVWF	STACK_10
;math.ppas,385 :: 		
$03DE	$1BFA			BTFSC	STACK_10, 7
;math.ppas,386 :: 		
$03DF	$2BF0			GOTO	$+17
;math.ppas,388 :: 		
$03E0	$2516			CALL	_div_16x16_s_l
;math.ppas,390 :: 		
$03E1	$187B			BTFSC	STACK_11, 0
;math.ppas,392 :: 		
$03E2	$2C03			GOTO	$+33
;math.ppas,393 :: 		
$03E3	$1FFD			BTFSS	STACK_13, 7
;math.ppas,395 :: 		
$03E4	$3400			RETLW	0
;math.ppas,396 :: 		
$03E5	$09F0			COMF	STACK_0, F
;math.ppas,397 :: 		
$03E6	$09F1			COMF	STACK_1, F
;math.ppas,398 :: 		
$03E7	$0AF0			INCF	STACK_0, F
;math.ppas,399 :: 		
$03E8	$1903			BTFSC	STATUS, Z
;math.ppas,401 :: 		
$03E9	$0AF1			INCF	STACK_1, F
;math.ppas,402 :: 		
$03EA	$09F8			COMF	STACK_8, F
;math.ppas,403 :: 		
$03EB	$09F9			COMF	STACK_9, F
;math.ppas,404 :: 		
$03EC	$0AF8			INCF	STACK_8, F
;math.ppas,405 :: 		
$03ED	$1903			BTFSC	STATUS, Z
;math.ppas,407 :: 		
$03EE	$0AF9			INCF	STACK_9, F
;math.ppas,409 :: 		
$03EF	$3400			RETLW	0
;math.ppas,410 :: 		
$03F0	$1FF5			BTFSS	STACK_5, 7
;math.ppas,411 :: 		
$03F1	$2BFF			GOTO	$+14
;math.ppas,412 :: 		
$03F2	$1BF1			BTFSC	STACK_1, 7
;math.ppas,413 :: 		
$03F3	$2BFB			GOTO	$+8
;math.ppas,414 :: 		
$03F4	$0871			MOVF	STACK_1, W
;math.ppas,415 :: 		
$03F5	$00F9			MOVWF	STACK_9
;math.ppas,416 :: 		
$03F6	$0870			MOVF	STACK_0, W
;math.ppas,417 :: 		
$03F7	$00F8			MOVWF	STACK_8
;math.ppas,418 :: 		
$03F8	$01F1			CLRF	STACK_1
;math.ppas,419 :: 		
$03F9	$01F0			CLRF	STACK_0
;math.ppas,420 :: 		
$03FA	$2BE3			GOTO	$-23
;math.ppas,421 :: 		
$03FB	$01F1			CLRF	STACK_1
;math.ppas,422 :: 		
$03FC	$01F0			CLRF	STACK_0
;math.ppas,423 :: 		
$03FD	$0AF0			INCF	STACK_0, F
;math.ppas,425 :: 		
$03FE	$3400			RETLW	0
;math.ppas,426 :: 		
$03FF	$09F1			COMF	STACK_1, F
;math.ppas,427 :: 		
$0400	$09F0			COMF	STACK_0, F
;math.ppas,428 :: 		
$0401	$0AFB			INCF	STACK_11, F
;math.ppas,430 :: 		
$0402	$2BE0			GOTO	$-34
;math.ppas,431 :: 		
$0403	$0AF8			INCF	STACK_8, F
;math.ppas,432 :: 		
$0404	$1903			BTFSC	STATUS, Z
;math.ppas,433 :: 		
$0405	$0AF9			INCF	STACK_9, F
;math.ppas,434 :: 		
$0406	$0874			MOVF	STACK_4, W
;math.ppas,435 :: 		
$0407	$0278			SUBWF	STACK_8, W
;math.ppas,436 :: 		
$0408	$1D03			BTFSS	STATUS, Z
;math.ppas,437 :: 		
$0409	$2BE3			GOTO	$-38
;math.ppas,438 :: 		
$040A	$0875			MOVF	STACK_5, W
;math.ppas,439 :: 		
$040B	$0279			SUBWF	STACK_9, W
;math.ppas,440 :: 		
$040C	$1D03			BTFSS	STATUS, Z
;math.ppas,441 :: 		
$040D	$2BE3			GOTO	$-42
;math.ppas,442 :: 		
$040E	$01F9			CLRF	STACK_9
;math.ppas,443 :: 		
$040F	$01F8			CLRF	STACK_8
;math.ppas,444 :: 		
$0410	$0AF0			INCF	STACK_0, F
;math.ppas,445 :: 		
$0411	$1903			BTFSC	STATUS, Z
;math.ppas,446 :: 		
$0412	$0AF1			INCF	STACK_1, F
;math.ppas,447 :: 		
$0413	$1FF1			BTFSS	STACK_1, 7
;math.ppas,448 :: 		
$0414	$2BE3			GOTO	$-49
;math.ppas,449 :: 		
$0415	$0000			NOP
;math.ppas,450 :: 		
$0416	$34FF			RETLW	255
;math.ppas,451 :: 		
$0417	$	math_L_7:
;math.ppas,452 :: 		
$0417	$0008			RETURN
$045B	$	_mul_16x16_s:
$045B	$1303			BCF	STATUS, RP1
$045C	$1283			BCF	STATUS, RP0
;math.ppas,203 :: 		
;math.ppas,205 :: 		
$045D	$01FB			CLRF	STACK_11
;math.ppas,206 :: 		
$045E	$01FA			CLRF	STACK_10
;math.ppas,207 :: 		
$045F	$01F9			CLRF	STACK_9
;math.ppas,208 :: 		
$0460	$3080			MOVLW	128
;math.ppas,210 :: 		
$0461	$00F8			MOVWF	STACK_8
;math.ppas,212 :: 		
$0462	$01FD			CLRF	STACK_13
;math.ppas,213 :: 		
$0463	$1FF1			BTFSS	STACK_1, 7
;math.ppas,214 :: 		
$0464	$2C6B			GOTO	$+7
;math.ppas,215 :: 		
$0465	$09F1			COMF	STACK_1, F
;math.ppas,216 :: 		
$0466	$09F0			COMF	STACK_0, F
;math.ppas,217 :: 		
$0467	$0AF0			INCF	STACK_0, F
;math.ppas,218 :: 		
$0468	$1903			BTFSC	STATUS, Z
;math.ppas,219 :: 		
$0469	$0AF1			INCF	STACK_1, F
;math.ppas,221 :: 		
$046A	$0AFD			INCF	STACK_13, F
;math.ppas,222 :: 		
$046B	$1FF5			BTFSS	STACK_5, 7
;math.ppas,223 :: 		
$046C	$2C73			GOTO	$+7
;math.ppas,224 :: 		
$046D	$09F5			COMF	STACK_5, F
;math.ppas,225 :: 		
$046E	$09F4			COMF	STACK_4, F
;math.ppas,226 :: 		
$046F	$0AF4			INCF	STACK_4, F
;math.ppas,227 :: 		
$0470	$1903			BTFSC	STATUS, Z
;math.ppas,228 :: 		
$0471	$0AF5			INCF	STACK_5, F
;math.ppas,230 :: 		
$0472	$0AFD			INCF	STACK_13, F
;math.ppas,231 :: 		
$0473	$0CF1			RRF	STACK_1, F
;math.ppas,233 :: 		
$0474	$0CF0			RRF	STACK_0, F
;math.ppas,234 :: 		
$0475	$1C03			BTFSS	STATUS, C
;math.ppas,235 :: 		
$0476	$2C80			GOTO	$+10
;math.ppas,236 :: 		
$0477	$0874			MOVF	STACK_4, W
;math.ppas,238 :: 		
$0478	$07F9			ADDWF	STACK_9, F
;math.ppas,239 :: 		
$0479	$0875			MOVF	STACK_5, W
;math.ppas,240 :: 		
$047A	$1803			BTFSC	STATUS, C
;math.ppas,241 :: 		
$047B	$0F75			INCFSZ	STACK_5, W
;math.ppas,242 :: 		
$047C	$07FA			ADDWF	STACK_10, F
;math.ppas,243 :: 		
$047D	$1803			BTFSC	STATUS, C
;math.ppas,244 :: 		
$047E	$0AFB			INCF	STACK_11, F
;math.ppas,246 :: 		
$047F	$1003			BCF	STATUS, C
;math.ppas,247 :: 		
$0480	$1FF0			BTFSS	STACK_0, 7
;math.ppas,248 :: 		
$0481	$2C88			GOTO	$+7
;math.ppas,249 :: 		
$0482	$0874			MOVF	STACK_4, W
;math.ppas,250 :: 		
$0483	$07FA			ADDWF	STACK_10, F
;math.ppas,251 :: 		
$0484	$1803			BTFSC	STATUS, C
;math.ppas,252 :: 		
$0485	$0AFB			INCF	STACK_11, F
;math.ppas,253 :: 		
$0486	$0875			MOVF	STACK_5, W
;math.ppas,255 :: 		
$0487	$07FB			ADDWF	STACK_11, F
;math.ppas,256 :: 		
$0488	$0CFB			RRF	STACK_11, F
;math.ppas,257 :: 		
$0489	$0CFA			RRF	STACK_10, F
;math.ppas,258 :: 		
$048A	$0CF9			RRF	STACK_9, F
;math.ppas,260 :: 		
$048B	$0CF8			RRF	STACK_8, F
;math.ppas,261 :: 		
$048C	$1C03			BTFSS	STATUS, C
;math.ppas,262 :: 		
$048D	$2C73			GOTO	$-26
;math.ppas,263 :: 		
$048E	$1C7D			BTFSS	STACK_13, 0
;math.ppas,265 :: 		
$048F	$2C9B			GOTO	$+12
;math.ppas,266 :: 		
$0490	$09FB			COMF	STACK_11, F
;math.ppas,267 :: 		
$0491	$09FA			COMF	STACK_10, F
;math.ppas,268 :: 		
$0492	$09F9			COMF	STACK_9, F
;math.ppas,270 :: 		
$0493	$09F8			COMF	STACK_8, F
;math.ppas,271 :: 		
$0494	$0AF8			INCF	STACK_8, F
;math.ppas,272 :: 		
$0495	$1903			BTFSC	STATUS, Z
;math.ppas,273 :: 		
$0496	$0AF9			INCF	STACK_9, F
;math.ppas,274 :: 		
$0497	$1903			BTFSC	STATUS, Z
;math.ppas,275 :: 		
$0498	$0AFA			INCF	STACK_10, F
;math.ppas,276 :: 		
$0499	$1903			BTFSC	STATUS, Z
;math.ppas,278 :: 		
$049A	$0AFB			INCF	STACK_11, F
;math.ppas,279 :: 		
$049B	$087B			MOVF	STACK_11, W
;math.ppas,280 :: 		
$049C	$00F3			MOVWF	STACK_3
;math.ppas,281 :: 		
$049D	$087A			MOVF	STACK_10, W
;math.ppas,282 :: 		
$049E	$00F2			MOVWF	STACK_2
;math.ppas,283 :: 		
$049F	$0879			MOVF	STACK_9, W
;math.ppas,284 :: 		
$04A0	$00F1			MOVWF	STACK_1
;math.ppas,285 :: 		
$04A1	$0878			MOVF	STACK_8, W
;math.ppas,286 :: 		
$04A2	$00F0			MOVWF	STACK_0
;math.ppas,287 :: 		
$04A3	$	math_L_5:
;math.ppas,288 :: 		
$04A3	$0008			RETURN
$0004	$	_main:
;MCU2.pbas,9 :: 		dim valor as integer
$0004	$	_main_main:
;MCU2.pbas,11 :: 		inicio:
$0004	$	_main_inicio:
;MCU2.pbas,13 :: 		TRISA=%11011111
$0004	$30DF			MOVLW	223
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0085			MOVWF	TRISA
;MCU2.pbas,14 :: 		TRISB=%00101111
$0008	$302F			MOVLW	47
$0009	$0086			MOVWF	TRISB
;MCU2.pbas,15 :: 		TRISC=%00000000
$000A	$0187			CLRF	TRISC, 1
;MCU2.pbas,16 :: 		INTCON=%00000000
$000B	$018B			CLRF	INTCON, 1
;MCU2.pbas,17 :: 		ANSEL=%00000000
$000C	$1703			BSF	STATUS, RP1
$000D	$1283			BCF	STATUS, RP0
$000E	$019E			CLRF	ANSEL, 1
;MCU2.pbas,18 :: 		ANSELH=%00000000
$000F	$019F			CLRF	ANSELH, 1
;MCU2.pbas,20 :: 		USART_INIT(9600)
$0010	$3019			MOVLW	25
$0011	$1303			BCF	STATUS, RP1
$0012	$1683			BSF	STATUS, RP0
$0013	$0099			MOVWF	SPBRG
$0014	$1518			BSF	TXSTA, BRGH
$0015	$2560			CALL	_usart_init
;MCU2.pbas,21 :: 		portc = 0
$0016	$0187			CLRF	PORTC, 1
;MCU2.pbas,23 :: 		PORTB.4=1
$0017	$	MCU2_L_1:
$0017	$1606			BSF	PORTB, 4
$0018	$	MCU2_L_2:
;MCU2.pbas,25 :: 		executa:
$0018	$	_main_executa:
;MCU2.pbas,27 :: 		if Usart_Data_Ready() > 0 then
$0018	$1303			BCF	STATUS, RP1
$0019	$1283			BCF	STATUS, RP0
$001A	$2596			CALL	_usart_data_ready
$001B	$0870			MOVF	STACK_0, 0
$001C	$3C00			SUBLW	0
$001D	$1803			BTFSC	STATUS, C
$001E	$2853			GOTO	MCU2_L_4
$001F	$	MCU2_L_3:
;MCU2.pbas,28 :: 		Usart_Read_Text(recebe,"/")
$001F	$3021			MOVLW	_recebe
$0020	$00BC			MOVWF	FARG_Usart_Read_Text
$0021	$302F			MOVLW	47
$0022	$00B4			MOVWF	?main_Local_Text+0
$0023	$01B5			CLRF	?main_Local_Text+1
$0024	$3034			MOVLW	?main_Local_Text
$0025	$00BD			MOVWF	FARG_Usart_Read_Text+1
$0026	$2418			CALL	_usart_read_text
;MCU2.pbas,29 :: 		aux = StrToInt(recebe)
$0027	$3021			MOVLW	_recebe
$0028	$00BC			MOVWF	FARG_StrToInt
$0029	$2262			CALL	_strtoint
$002A	$0870			MOVF	STACK_0, 0
$002B	$00A8			MOVWF	_aux
$002C	$0871			MOVF	STACK_0+1, 0
$002D	$00A9			MOVWF	_aux+1
;MCU2.pbas,31 :: 		if (aux >= 1000) and (aux < 3000) then
$002E	$3080			MOVLW	128
$002F	$0671			XORWF	STACK_0+1, 0
$0030	$00F3			MOVWF	STACK_3
$0031	$3080			MOVLW	128
$0032	$3A03			XORLW	3
$0033	$0273			SUBWF	STACK_3, 0
$0034	$1D03			BTFSS	STATUS, Z
$0035	$2838			GOTO	L_main_0
$0036	$30E8			MOVLW	232
$0037	$0270			SUBWF	STACK_0, 0
$0038	$	L_main_0:
$0038	$30FF			MOVLW	255
$0039	$1C03			BTFSS	STATUS, C
$003A	$3000			MOVLW	0
$003B	$00F3			MOVWF	STACK_3
$003C	$3080			MOVLW	128
$003D	$0671			XORWF	STACK_0+1, 0
$003E	$00F2			MOVWF	STACK_2
$003F	$3080			MOVLW	128
$0040	$3A0B			XORLW	11
$0041	$0272			SUBWF	STACK_2, 0
$0042	$1D03			BTFSS	STATUS, Z
$0043	$2846			GOTO	L_main_1
$0044	$30B8			MOVLW	184
$0045	$0270			SUBWF	STACK_0, 0
$0046	$	L_main_1:
$0046	$30FF			MOVLW	255
$0047	$1803			BTFSC	STATUS, C
$0048	$3000			MOVLW	0
$0049	$00F2			MOVWF	STACK_2
$004A	$0872			MOVF	STACK_2, 0
$004B	$0573			ANDWF	STACK_3, 0
$004C	$00F0			MOVWF	STACK_0
$004D	$1903			BTFSC	STATUS, Z
$004E	$2853			GOTO	MCU2_L_7
$004F	$	MCU2_L_6:
;MCU2.pbas,32 :: 		valor = aux
$004F	$0828			MOVF	_aux, 0
$0050	$00AA			MOVWF	_valor
$0051	$0829			MOVF	_aux+1, 0
$0052	$00AB			MOVWF	_valor+1
$0053	$	MCU2_L_7:
;MCU2.pbas,33 :: 		end if
$0053	$	MCU2_L_8:
$0053	$	MCU2_L_4:
;MCU2.pbas,35 :: 		end if
$0053	$	MCU2_L_5:
;MCU2.pbas,37 :: 		gosub exibe
$0053	$2055			CALL	_main_exibe
;MCU2.pbas,40 :: 		goto executa
$0054	$2818			GOTO	_main_executa
;MCU2.pbas,42 :: 		exibe:
$0055	$	_main_exibe:
;MCU2.pbas,44 :: 		mil = valor div 1000
$0055	$30E8			MOVLW	232
$0056	$1303			BCF	STATUS, RP1
$0057	$1283			BCF	STATUS, RP0
$0058	$00F4			MOVWF	STACK_4
$0059	$3003			MOVLW	3
$005A	$00F5			MOVWF	STACK_4+1
$005B	$082A			MOVF	_valor, 0
$005C	$00F0			MOVWF	STACK_0
$005D	$082B			MOVF	_valor+1, 0
$005E	$00F1			MOVWF	STACK_0+1
$005F	$23BE			CALL	_div_16x16_s
$0060	$0870			MOVF	STACK_0, 0
$0061	$00BA			MOVWF	FLOC_main+6
$0062	$0871			MOVF	STACK_0+1, 0
$0063	$00BB			MOVWF	FLOC_main+7
$0064	$083A			MOVF	FLOC_main+6, 0
$0065	$00AC			MOVWF	_mil
$0066	$083B			MOVF	FLOC_main+7, 0
$0067	$00AD			MOVWF	_mil+1
;MCU2.pbas,45 :: 		cent = valor div 100 - (mil * 10)
$0068	$3064			MOVLW	100
$0069	$00F4			MOVWF	STACK_4
$006A	$01F5			CLRF	STACK_4+1
$006B	$082A			MOVF	_valor, 0
$006C	$00F0			MOVWF	STACK_0
$006D	$082B			MOVF	_valor+1, 0
$006E	$00F1			MOVWF	STACK_0+1
$006F	$23BE			CALL	_div_16x16_s
$0070	$0870			MOVF	STACK_0, 0
$0071	$00B6			MOVWF	FLOC_main+2
$0072	$0871			MOVF	STACK_0+1, 0
$0073	$00B7			MOVWF	FLOC_main+3
$0074	$083A			MOVF	FLOC_main+6, 0
$0075	$00F0			MOVWF	STACK_0
$0076	$083B			MOVF	FLOC_main+7, 0
$0077	$00F1			MOVWF	STACK_0+1
$0078	$300A			MOVLW	10
$0079	$00F4			MOVWF	STACK_4
$007A	$01F5			CLRF	STACK_4+1
$007B	$245B			CALL	_mul_16x16_s
$007C	$0870			MOVF	STACK_0, 0
$007D	$0236			SUBWF	FLOC_main+2, 0
$007E	$00B8			MOVWF	FLOC_main+4
$007F	$0871			MOVF	STACK_0+1, 0
$0080	$1C03			BTFSS	STATUS, C
$0081	$3F01			ADDLW	1
$0082	$0237			SUBWF	FLOC_main+3, 0
$0083	$00B9			MOVWF	FLOC_main+5
$0084	$0838			MOVF	FLOC_main+4, 0
$0085	$00AE			MOVWF	_cent
$0086	$0839			MOVF	FLOC_main+5, 0
$0087	$00AF			MOVWF	_cent+1
;MCU2.pbas,46 :: 		dez = valor div 10 - (cent * 10) - (mil * 100)
$0088	$300A			MOVLW	10
$0089	$00F4			MOVWF	STACK_4
$008A	$01F5			CLRF	STACK_4+1
$008B	$082A			MOVF	_valor, 0
$008C	$00F0			MOVWF	STACK_0
$008D	$082B			MOVF	_valor+1, 0
$008E	$00F1			MOVWF	STACK_0+1
$008F	$23BE			CALL	_div_16x16_s
$0090	$0870			MOVF	STACK_0, 0
$0091	$00B6			MOVWF	FLOC_main+2
$0092	$0871			MOVF	STACK_0+1, 0
$0093	$00B7			MOVWF	FLOC_main+3
$0094	$0838			MOVF	FLOC_main+4, 0
$0095	$00F0			MOVWF	STACK_0
$0096	$0839			MOVF	FLOC_main+5, 0
$0097	$00F1			MOVWF	STACK_0+1
$0098	$300A			MOVLW	10
$0099	$00F4			MOVWF	STACK_4
$009A	$01F5			CLRF	STACK_4+1
$009B	$245B			CALL	_mul_16x16_s
$009C	$0870			MOVF	STACK_0, 0
$009D	$02B6			SUBWF	FLOC_main+2, 1
$009E	$1C03			BTFSS	STATUS, C
$009F	$03B7			DECF	FLOC_main+3, 1
$00A0	$0871			MOVF	STACK_0+1, 0
$00A1	$02B7			SUBWF	FLOC_main+3, 1
$00A2	$083A			MOVF	FLOC_main+6, 0
$00A3	$00F0			MOVWF	STACK_0
$00A4	$083B			MOVF	FLOC_main+7, 0
$00A5	$00F1			MOVWF	STACK_0+1
$00A6	$3064			MOVLW	100
$00A7	$00F4			MOVWF	STACK_4
$00A8	$01F5			CLRF	STACK_4+1
$00A9	$245B			CALL	_mul_16x16_s
$00AA	$0870			MOVF	STACK_0, 0
$00AB	$0236			SUBWF	FLOC_main+2, 0
$00AC	$00F0			MOVWF	STACK_0
$00AD	$0871			MOVF	STACK_0+1, 0
$00AE	$1C03			BTFSS	STATUS, C
$00AF	$3F01			ADDLW	1
$00B0	$0237			SUBWF	FLOC_main+3, 0
$00B1	$00F1			MOVWF	STACK_0+1
$00B2	$0870			MOVF	STACK_0, 0
$00B3	$00B0			MOVWF	_dez
$00B4	$0871			MOVF	STACK_0+1, 0
$00B5	$00B1			MOVWF	_dez+1
;MCU2.pbas,47 :: 		uni = valor - (dez * 10) - (cent * 100) - (mil * 1000)
$00B6	$300A			MOVLW	10
$00B7	$00F4			MOVWF	STACK_4
$00B8	$01F5			CLRF	STACK_4+1
$00B9	$245B			CALL	_mul_16x16_s
$00BA	$0870			MOVF	STACK_0, 0
$00BB	$022A			SUBWF	_valor, 0
$00BC	$00B2			MOVWF	_uni
$00BD	$0871			MOVF	STACK_0+1, 0
$00BE	$1C03			BTFSS	STATUS, C
$00BF	$3F01			ADDLW	1
$00C0	$022B			SUBWF	_valor+1, 0
$00C1	$00B3			MOVWF	_uni+1
$00C2	$0838			MOVF	FLOC_main+4, 0
$00C3	$00F0			MOVWF	STACK_0
$00C4	$0839			MOVF	FLOC_main+5, 0
$00C5	$00F1			MOVWF	STACK_0+1
$00C6	$3064			MOVLW	100
$00C7	$00F4			MOVWF	STACK_4
$00C8	$01F5			CLRF	STACK_4+1
$00C9	$245B			CALL	_mul_16x16_s
$00CA	$0870			MOVF	STACK_0, 0
$00CB	$02B2			SUBWF	_uni, 1
$00CC	$1C03			BTFSS	STATUS, C
$00CD	$03B3			DECF	_uni+1, 1
$00CE	$0871			MOVF	STACK_0+1, 0
$00CF	$02B3			SUBWF	_uni+1, 1
$00D0	$083A			MOVF	FLOC_main+6, 0
$00D1	$00F0			MOVWF	STACK_0
$00D2	$083B			MOVF	FLOC_main+7, 0
$00D3	$00F1			MOVWF	STACK_0+1
$00D4	$30E8			MOVLW	232
$00D5	$00F4			MOVWF	STACK_4
$00D6	$3003			MOVLW	3
$00D7	$00F5			MOVWF	STACK_4+1
$00D8	$245B			CALL	_mul_16x16_s
$00D9	$0870			MOVF	STACK_0, 0
$00DA	$02B2			SUBWF	_uni, 1
$00DB	$1C03			BTFSS	STATUS, C
$00DC	$03B3			DECF	_uni+1, 1
$00DD	$0871			MOVF	STACK_0+1, 0
$00DE	$02B3			SUBWF	_uni+1, 1
;MCU2.pbas,50 :: 		if mil = 1 then
$00DF	$3000			MOVLW	0
$00E0	$063B			XORWF	FLOC_main+7, 0
$00E1	$1D03			BTFSS	STATUS, Z
$00E2	$28E5			GOTO	L_main_2
$00E3	$3001			MOVLW	1
$00E4	$063A			XORWF	FLOC_main+6, 0
$00E5	$	L_main_2:
$00E5	$1D03			BTFSS	STATUS, Z
$00E6	$28E9			GOTO	MCU2_L_10
$00E7	$	MCU2_L_9:
;MCU2.pbas,51 :: 		portb.4 = 1
$00E7	$	MCU2_L_12:
$00E7	$1606			BSF	PORTB, 4
$00E8	$	MCU2_L_13:
;MCU2.pbas,52 :: 		portb.6 = 0
$00E8	$1306			BCF	PORTB, 6
$00E9	$	MCU2_L_15:
$00E9	$	MCU2_L_10:
;MCU2.pbas,53 :: 		end if
$00E9	$	MCU2_L_11:
;MCU2.pbas,55 :: 		if mil = 2 then
$00E9	$3000			MOVLW	0
$00EA	$062D			XORWF	_mil+1, 0
$00EB	$1D03			BTFSS	STATUS, Z
$00EC	$28EF			GOTO	L_main_3
$00ED	$3002			MOVLW	2
$00EE	$062C			XORWF	_mil, 0
$00EF	$	L_main_3:
$00EF	$1D03			BTFSS	STATUS, Z
$00F0	$28F3			GOTO	MCU2_L_17
$00F1	$	MCU2_L_16:
;MCU2.pbas,56 :: 		portb.4 = 0
$00F1	$1206			BCF	PORTB, 4
$00F2	$	MCU2_L_20:
;MCU2.pbas,57 :: 		portb.6 = 1
$00F2	$	MCU2_L_21:
$00F2	$1706			BSF	PORTB, 6
$00F3	$	MCU2_L_22:
$00F3	$	MCU2_L_17:
;MCU2.pbas,58 :: 		end if
$00F3	$	MCU2_L_18:
;MCU2.pbas,60 :: 		PORTC = uni
$00F3	$0832			MOVF	_uni, 0
$00F4	$0087			MOVWF	PORTC
;MCU2.pbas,61 :: 		PORTC.4=1 PORTC.5=0 PORTC.6=0
$00F5	$	MCU2_L_23:
$00F5	$1607			BSF	PORTC, 4
$00F6	$	MCU2_L_24:
$00F6	$1287			BCF	PORTC, 5
$00F7	$	MCU2_L_26:
$00F7	$1307			BCF	PORTC, 6
$00F8	$	MCU2_L_28:
;MCU2.pbas,62 :: 		delay_ms(5)
$00F8	$3007			MOVLW	7
$00F9	$00FB			MOVWF	STACK_11
$00FA	$30FF			MOVLW	255
$00FB	$00FA			MOVWF	STACK_10
$00FC	$0BFB			DECFSZ	STACK_11, F
$00FD	$28FF			GOTO	$+2
$00FE	$2902			GOTO	$+4
$00FF	$0BFA			DECFSZ	STACK_10, F
$0100	$28FF			GOTO	$-1
$0101	$28FC			GOTO	$-5
$0102	$3078			MOVLW	120
$0103	$00FA			MOVWF	STACK_10
$0104	$0BFA			DECFSZ	STACK_10, F
$0105	$2904			GOTO	$-1
$0106	$0000			NOP
$0107	$0000			NOP
;MCU2.pbas,64 :: 		PORTC = dez
$0108	$0830			MOVF	_dez, 0
$0109	$0087			MOVWF	PORTC
;MCU2.pbas,65 :: 		PORTC.4=0 PORTC.5=1 PORTC.6=0
$010A	$1207			BCF	PORTC, 4
$010B	$	MCU2_L_30:
$010B	$	MCU2_L_31:
$010B	$1687			BSF	PORTC, 5
$010C	$	MCU2_L_32:
$010C	$1307			BCF	PORTC, 6
$010D	$	MCU2_L_34:
;MCU2.pbas,66 :: 		delay_ms(5)
$010D	$3007			MOVLW	7
$010E	$00FB			MOVWF	STACK_11
$010F	$30FF			MOVLW	255
$0110	$00FA			MOVWF	STACK_10
$0111	$0BFB			DECFSZ	STACK_11, F
$0112	$2914			GOTO	$+2
$0113	$2917			GOTO	$+4
$0114	$0BFA			DECFSZ	STACK_10, F
$0115	$2914			GOTO	$-1
$0116	$2911			GOTO	$-5
$0117	$3078			MOVLW	120
$0118	$00FA			MOVWF	STACK_10
$0119	$0BFA			DECFSZ	STACK_10, F
$011A	$2919			GOTO	$-1
$011B	$0000			NOP
$011C	$0000			NOP
;MCU2.pbas,68 :: 		PORTC = cent
$011D	$082E			MOVF	_cent, 0
$011E	$0087			MOVWF	PORTC
;MCU2.pbas,69 :: 		PORTC.4=0 PORTC.5=0 PORTC.6=1
$011F	$1207			BCF	PORTC, 4
$0120	$	MCU2_L_36:
$0120	$1287			BCF	PORTC, 5
$0121	$	MCU2_L_38:
$0121	$	MCU2_L_39:
$0121	$1707			BSF	PORTC, 6
$0122	$	MCU2_L_40:
;MCU2.pbas,70 :: 		delay_ms(5)
$0122	$3007			MOVLW	7
$0123	$00FB			MOVWF	STACK_11
$0124	$30FF			MOVLW	255
$0125	$00FA			MOVWF	STACK_10
$0126	$0BFB			DECFSZ	STACK_11, F
$0127	$2929			GOTO	$+2
$0128	$292C			GOTO	$+4
$0129	$0BFA			DECFSZ	STACK_10, F
$012A	$2929			GOTO	$-1
$012B	$2926			GOTO	$-5
$012C	$3078			MOVLW	120
$012D	$00FA			MOVWF	STACK_10
$012E	$0BFA			DECFSZ	STACK_10, F
$012F	$292E			GOTO	$-1
$0130	$0000			NOP
$0131	$0000			NOP
;MCU2.pbas,72 :: 		return
$0132	$0008			RETURN
$0133	$	MCU2_L_0:
$0133	$2933			GOTO	$
