;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 16/05/2020 10:11:55
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0734	$	_div_16x16_s_l:
$0734	$1303			BCF	STATUS, RP1
$0735	$1283			BCF	STATUS, RP0
;math.ppas,291 :: 		
;math.ppas,293 :: 		
$0736	$0D71			RLF	STACK_1, W
;math.ppas,294 :: 		
$0737	$0DF8			RLF	STACK_8, F
;math.ppas,295 :: 		
$0738	$0DF9			RLF	STACK_9, F
;math.ppas,296 :: 		
$0739	$0874			MOVF	STACK_4, W
;math.ppas,297 :: 		
$073A	$02F8			SUBWF	STACK_8, F
;math.ppas,298 :: 		
$073B	$0875			MOVF	STACK_5, W
;math.ppas,299 :: 		
$073C	$1C03			BTFSS	STATUS, C
;math.ppas,300 :: 		
$073D	$0F75			INCFSZ	STACK_5, W
;math.ppas,301 :: 		
$073E	$02F9			SUBWF	STACK_9, F
;math.ppas,302 :: 		
$073F	$0DF0			RLF	STACK_0, F
;math.ppas,304 :: 		
$0740	$0DF1			RLF	STACK_1, F
;math.ppas,305 :: 		
$0741	$300F			MOVLW	15
;math.ppas,307 :: 		
$0742	$00FC			MOVWF	STACK_12
;math.ppas,308 :: 		
$0743	$0D71			RLF	STACK_1, W
;math.ppas,309 :: 		
$0744	$0DF8			RLF	STACK_8, F
;math.ppas,310 :: 		
$0745	$0DF9			RLF	STACK_9, F
;math.ppas,312 :: 		
$0746	$0874			MOVF	STACK_4, W
;math.ppas,313 :: 		
$0747	$1C70			BTFSS	STACK_0, 0
;math.ppas,314 :: 		
$0748	$2F4F			GOTO	$+7
;math.ppas,315 :: 		
$0749	$02F8			SUBWF	STACK_8, F
;math.ppas,316 :: 		
$074A	$0875			MOVF	STACK_5, W
;math.ppas,317 :: 		
$074B	$1C03			BTFSS	STATUS, C
;math.ppas,318 :: 		
$074C	$0F75			INCFSZ	STACK_5, W
;math.ppas,319 :: 		
$074D	$02F9			SUBWF	STACK_9, F
;math.ppas,321 :: 		
$074E	$2F54			GOTO	$+6
;math.ppas,322 :: 		
$074F	$07F8			ADDWF	STACK_8, F
;math.ppas,323 :: 		
$0750	$0875			MOVF	STACK_5, W
;math.ppas,324 :: 		
$0751	$1803			BTFSC	STATUS, C
;math.ppas,325 :: 		
$0752	$0F75			INCFSZ	STACK_5, W
;math.ppas,327 :: 		
$0753	$07F9			ADDWF	STACK_9, F
;math.ppas,328 :: 		
$0754	$0DF0			RLF	STACK_0, F
;math.ppas,330 :: 		
$0755	$0DF1			RLF	STACK_1, F
;math.ppas,331 :: 		
$0756	$0BFC			DECFSZ	STACK_12, F
;math.ppas,333 :: 		
$0757	$2F43			GOTO	$-20
;math.ppas,334 :: 		
$0758	$1870			BTFSC	STACK_0, 0
;math.ppas,335 :: 		
$0759	$2F60			GOTO	$+7
;math.ppas,336 :: 		
$075A	$0874			MOVF	STACK_4, W
;math.ppas,337 :: 		
$075B	$07F8			ADDWF	STACK_8, F
;math.ppas,338 :: 		
$075C	$0875			MOVF	STACK_5, W
;math.ppas,339 :: 		
$075D	$1803			BTFSC	STATUS, C
;math.ppas,340 :: 		
$075E	$0F75			INCFSZ	STACK_5, W
;math.ppas,341 :: 		
$075F	$07F9			ADDWF	STACK_9, F
;math.ppas,342 :: 		
$0760	$	math_L_6:
;math.ppas,343 :: 		
$0760	$0008			RETURN
$06FD	$	_mul_32x32_u:
$06FD	$1303			BCF	STATUS, RP1
$06FE	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$06FF	$3022			MOVLW	34
;math.ppas,1579 :: 		
$0700	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$0701	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$0702	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$0703	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$0704	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$0705	$	_NEXT:
;math.ppas,1589 :: 		
$0705	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$0706	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$0707	$2F33			GOTO	_EXIT2
;math.ppas,1593 :: 		
$0708	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$0709	$	_LOOP:
;math.ppas,1603 :: 		
$0709	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$070A	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$070B	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$070C	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$070D	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$070E	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$070F	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$0710	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$0711	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$0712	$2F05			GOTO	_NEXT
;math.ppas,1617 :: 		
$0713	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$0714	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$0715	$2F25			GOTO	_EXIT1
;math.ppas,1626 :: 		
$0716	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$0717	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$0718	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$0719	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$071A	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$071B	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$071C	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$071D	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$071E	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$071F	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$0720	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$0721	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$0722	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$0723	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$0724	$2F09			GOTO	_LOOP
;math.ppas,1647 :: 		
$0725	$	_EXIT1:
;math.ppas,1648 :: 		
$0725	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$0726	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$0727	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$0728	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$0729	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$072A	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$072B	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$072C	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$072D	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$072E	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$072F	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$0730	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$0731	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$0732	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$0733	$	_EXIT2:
;math.ppas,1665 :: 		
$0733	$	math_L_13:
;math.ppas,1666 :: 		
$0733	$0008			RETURN
$0260	$	_sdiv3232l:
$0260	$1303			BCF	STATUS, RP1
$0261	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$0262	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0263	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0264	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0265	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$0266	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$0267	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$0268	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$0269	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$026A	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$026B	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$026C	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$026D	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$026E	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$026F	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$0270	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$0271	$3007			MOVLW	7
;math.ppas,559 :: 		
$0272	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0273	$	LOOPS3232A:
;math.ppas,561 :: 		
$0273	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0274	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0275	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$0276	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$0277	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$0278	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$0279	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$027A	$2A89			GOTO	SADD22LA
;math.ppas,570 :: 		
$027B	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$027C	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$027D	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$027E	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$027F	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$0280	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$0281	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$0282	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0283	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0284	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0285	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$0286	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$0287	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$0288	$2A96			GOTO	SOK22LA
;math.ppas,585 :: 		
$0289	$	SADD22LA:
;math.ppas,586 :: 		
$0289	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$028A	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$028B	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$028C	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$028D	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$028E	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$028F	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$0290	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$0291	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$0292	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$0293	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$0294	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$0295	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$0296	$	SOK22LA:
;math.ppas,602 :: 		
$0296	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$0297	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$0298	$2A73			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$0299	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$029A	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$029B	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$029C	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$029D	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$029E	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$029F	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$02A0	$2AAF			GOTO	SADD22L8
;math.ppas,615 :: 		
$02A1	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$02A2	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$02A3	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$02A4	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$02A5	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$02A6	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$02A7	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$02A8	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$02A9	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$02AA	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$02AB	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$02AC	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$02AD	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$02AE	$2ABC			GOTO	SOK22L8
;math.ppas,630 :: 		
$02AF	$	SADD22L8:
;math.ppas,631 :: 		
$02AF	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$02B0	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$02B1	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$02B2	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$02B3	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$02B4	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$02B5	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$02B6	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$02B7	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$02B8	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$02B9	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$02BA	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$02BB	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$02BC	$	SOK22L8:
;math.ppas,647 :: 		
$02BC	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$02BD	$3007			MOVLW	7
;math.ppas,650 :: 		
$02BE	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$02BF	$	LOOPS3232B:
;math.ppas,652 :: 		
$02BF	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$02C0	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$02C1	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$02C2	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$02C3	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$02C4	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$02C5	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$02C6	$2AD5			GOTO	SADD22LB
;math.ppas,661 :: 		
$02C7	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$02C8	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$02C9	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$02CA	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$02CB	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$02CC	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$02CD	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$02CE	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$02CF	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$02D0	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$02D1	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$02D2	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$02D3	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$02D4	$2AE2			GOTO	SOK22LB
;math.ppas,676 :: 		
$02D5	$	SADD22LB:
;math.ppas,677 :: 		
$02D5	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$02D6	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$02D7	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$02D8	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$02D9	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$02DA	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$02DB	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$02DC	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$02DD	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$02DE	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$02DF	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$02E0	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$02E1	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$02E2	$	SOK22LB:
;math.ppas,693 :: 		
$02E2	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$02E3	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$02E4	$2ABF			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$02E5	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$02E6	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$02E7	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$02E8	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$02E9	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$02EA	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$02EB	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$02EC	$2AFB			GOTO	SADD22L16
;math.ppas,706 :: 		
$02ED	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$02EE	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$02EF	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$02F0	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$02F1	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$02F2	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$02F3	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$02F4	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$02F5	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$02F6	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$02F7	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$02F8	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$02F9	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$02FA	$2B08			GOTO	SOK22L16
;math.ppas,721 :: 		
$02FB	$	SADD22L16:
;math.ppas,722 :: 		
$02FB	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$02FC	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$02FD	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$02FE	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$02FF	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$0300	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$0301	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$0302	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$0303	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$0304	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$0305	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$0306	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$0307	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$0308	$	SOK22L16:
;math.ppas,738 :: 		
$0308	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$0309	$3007			MOVLW	7
;math.ppas,741 :: 		
$030A	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$030B	$	LOOPS3232C:
;math.ppas,743 :: 		
$030B	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$030C	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$030D	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$030E	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$030F	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$0310	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$0311	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$0312	$2B21			GOTO	SADD22LC
;math.ppas,752 :: 		
$0313	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$0314	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$0315	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$0316	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$0317	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$0318	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$0319	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$031A	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$031B	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$031C	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$031D	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$031E	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$031F	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$0320	$2B2E			GOTO	SOK22LC
;math.ppas,767 :: 		
$0321	$	SADD22LC:
;math.ppas,768 :: 		
$0321	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$0322	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$0323	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$0324	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$0325	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$0326	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$0327	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$0328	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$0329	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$032A	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$032B	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$032C	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$032D	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$032E	$	SOK22LC:
;math.ppas,784 :: 		
$032E	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$032F	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$0330	$2B0B			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$0331	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$0332	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$0333	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$0334	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$0335	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$0336	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$0337	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$0338	$2B47			GOTO	SADD22L24
;math.ppas,797 :: 		
$0339	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$033A	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$033B	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$033C	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$033D	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$033E	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$033F	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$0340	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$0341	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$0342	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$0343	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$0344	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$0345	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$0346	$2B54			GOTO	SOK22L24
;math.ppas,812 :: 		
$0347	$	SADD22L24:
;math.ppas,813 :: 		
$0347	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$0348	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$0349	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$034A	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$034B	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$034C	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$034D	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$034E	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$034F	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$0350	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$0351	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$0352	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$0353	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$0354	$	SOK22L24:
;math.ppas,829 :: 		
$0354	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$0355	$3007			MOVLW	7
;math.ppas,832 :: 		
$0356	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$0357	$	LOOPS3232D:
;math.ppas,834 :: 		
$0357	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$0358	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$0359	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$035A	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$035B	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$035C	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$035D	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$035E	$2B6D			GOTO	SADD22LD
;math.ppas,843 :: 		
$035F	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$0360	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$0361	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$0362	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0363	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0364	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0365	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$0366	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$0367	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$0368	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$0369	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$036A	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$036B	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$036C	$2B7A			GOTO	SOK22LD
;math.ppas,858 :: 		
$036D	$	SADD22LD:
;math.ppas,859 :: 		
$036D	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$036E	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$036F	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$0370	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$0371	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$0372	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0373	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0374	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0375	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$0376	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$0377	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$0378	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$0379	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$037A	$	SOK22LD:
;math.ppas,876 :: 		
$037A	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$037B	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$037C	$2B57			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$037D	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$037E	$2B8D			GOTO	SOK22L
;math.ppas,882 :: 		
$037F	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$0380	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$0381	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$0382	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0383	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0384	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0385	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$0386	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$0387	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$0388	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$0389	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$038A	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$038B	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$038C	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$038D	$	SOK22L:
;math.ppas,897 :: 		
$038D	$	math_L_9:
;math.ppas,898 :: 		
$038D	$0008			RETURN
$077E	$	_comfrem:
$077E	$1303			BCF	STATUS, RP1
$077F	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$0780	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$0781	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$0782	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$0783	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$0784	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$0785	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$0786	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$0787	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$0788	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$0789	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$078A	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$078B	$	math_L_10:
;math.ppas,915 :: 		
$078B	$0008			RETURN
$05D8	$	_div_16x16_s:
$05D8	$1303			BCF	STATUS, RP1
$05D9	$1283			BCF	STATUS, RP0
;math.ppas,346 :: 		
;math.ppas,348 :: 		
$05DA	$01FD			CLRF	STACK_13
;math.ppas,349 :: 		
$05DB	$01F9			CLRF	STACK_9
;math.ppas,350 :: 		
$05DC	$01F8			CLRF	STACK_8
;math.ppas,351 :: 		
$05DD	$0871			MOVF	STACK_1, W
;math.ppas,352 :: 		
$05DE	$0470			IORWF	STACK_0, W
;math.ppas,353 :: 		
$05DF	$1903			BTFSC	STATUS, Z
;math.ppas,355 :: 		
$05E0	$3400			RETLW	0
;math.ppas,356 :: 		
$05E1	$0871			MOVF	STACK_1, W
;math.ppas,357 :: 		
$05E2	$0675			XORWF	STACK_5, W
;math.ppas,358 :: 		
$05E3	$00FA			MOVWF	STACK_10
;math.ppas,359 :: 		
$05E4	$1BFA			BTFSC	STACK_10, 7
;math.ppas,361 :: 		
$05E5	$09FD			COMF	STACK_13, F
;math.ppas,363 :: 		
$05E6	$01FB			CLRF	STACK_11
;math.ppas,364 :: 		
$05E7	$1FF5			BTFSS	STACK_5, 7
;math.ppas,366 :: 		
$05E8	$2DEE			GOTO	$+6
;math.ppas,367 :: 		
$05E9	$09F4			COMF	STACK_4, F
;math.ppas,368 :: 		
$05EA	$09F5			COMF	STACK_5, F
;math.ppas,369 :: 		
$05EB	$0AF4			INCF	STACK_4, F
;math.ppas,370 :: 		
$05EC	$1903			BTFSC	STATUS, Z
;math.ppas,372 :: 		
$05ED	$0AF5			INCF	STACK_5, F
;math.ppas,373 :: 		
$05EE	$1FF1			BTFSS	STACK_1, 7
;math.ppas,375 :: 		
$05EF	$2DF5			GOTO	$+6
;math.ppas,376 :: 		
$05F0	$09F0			COMF	STACK_0, F
;math.ppas,377 :: 		
$05F1	$09F1			COMF	STACK_1, F
;math.ppas,378 :: 		
$05F2	$0AF0			INCF	STACK_0, F
;math.ppas,379 :: 		
$05F3	$1903			BTFSC	STATUS, Z
;math.ppas,381 :: 		
$05F4	$0AF1			INCF	STACK_1, F
;math.ppas,382 :: 		
$05F5	$0871			MOVF	STACK_1, W
;math.ppas,383 :: 		
$05F6	$0475			IORWF	STACK_5, W
;math.ppas,384 :: 		
$05F7	$00FA			MOVWF	STACK_10
;math.ppas,385 :: 		
$05F8	$1BFA			BTFSC	STACK_10, 7
;math.ppas,386 :: 		
$05F9	$2E0A			GOTO	$+17
;math.ppas,388 :: 		
$05FA	$2734			CALL	_div_16x16_s_l
;math.ppas,390 :: 		
$05FB	$187B			BTFSC	STACK_11, 0
;math.ppas,392 :: 		
$05FC	$2E1D			GOTO	$+33
;math.ppas,393 :: 		
$05FD	$1FFD			BTFSS	STACK_13, 7
;math.ppas,395 :: 		
$05FE	$3400			RETLW	0
;math.ppas,396 :: 		
$05FF	$09F0			COMF	STACK_0, F
;math.ppas,397 :: 		
$0600	$09F1			COMF	STACK_1, F
;math.ppas,398 :: 		
$0601	$0AF0			INCF	STACK_0, F
;math.ppas,399 :: 		
$0602	$1903			BTFSC	STATUS, Z
;math.ppas,401 :: 		
$0603	$0AF1			INCF	STACK_1, F
;math.ppas,402 :: 		
$0604	$09F8			COMF	STACK_8, F
;math.ppas,403 :: 		
$0605	$09F9			COMF	STACK_9, F
;math.ppas,404 :: 		
$0606	$0AF8			INCF	STACK_8, F
;math.ppas,405 :: 		
$0607	$1903			BTFSC	STATUS, Z
;math.ppas,407 :: 		
$0608	$0AF9			INCF	STACK_9, F
;math.ppas,409 :: 		
$0609	$3400			RETLW	0
;math.ppas,410 :: 		
$060A	$1FF5			BTFSS	STACK_5, 7
;math.ppas,411 :: 		
$060B	$2E19			GOTO	$+14
;math.ppas,412 :: 		
$060C	$1BF1			BTFSC	STACK_1, 7
;math.ppas,413 :: 		
$060D	$2E15			GOTO	$+8
;math.ppas,414 :: 		
$060E	$0871			MOVF	STACK_1, W
;math.ppas,415 :: 		
$060F	$00F9			MOVWF	STACK_9
;math.ppas,416 :: 		
$0610	$0870			MOVF	STACK_0, W
;math.ppas,417 :: 		
$0611	$00F8			MOVWF	STACK_8
;math.ppas,418 :: 		
$0612	$01F1			CLRF	STACK_1
;math.ppas,419 :: 		
$0613	$01F0			CLRF	STACK_0
;math.ppas,420 :: 		
$0614	$2DFD			GOTO	$-23
;math.ppas,421 :: 		
$0615	$01F1			CLRF	STACK_1
;math.ppas,422 :: 		
$0616	$01F0			CLRF	STACK_0
;math.ppas,423 :: 		
$0617	$0AF0			INCF	STACK_0, F
;math.ppas,425 :: 		
$0618	$3400			RETLW	0
;math.ppas,426 :: 		
$0619	$09F1			COMF	STACK_1, F
;math.ppas,427 :: 		
$061A	$09F0			COMF	STACK_0, F
;math.ppas,428 :: 		
$061B	$0AFB			INCF	STACK_11, F
;math.ppas,430 :: 		
$061C	$2DFA			GOTO	$-34
;math.ppas,431 :: 		
$061D	$0AF8			INCF	STACK_8, F
;math.ppas,432 :: 		
$061E	$1903			BTFSC	STATUS, Z
;math.ppas,433 :: 		
$061F	$0AF9			INCF	STACK_9, F
;math.ppas,434 :: 		
$0620	$0874			MOVF	STACK_4, W
;math.ppas,435 :: 		
$0621	$0278			SUBWF	STACK_8, W
;math.ppas,436 :: 		
$0622	$1D03			BTFSS	STATUS, Z
;math.ppas,437 :: 		
$0623	$2DFD			GOTO	$-38
;math.ppas,438 :: 		
$0624	$0875			MOVF	STACK_5, W
;math.ppas,439 :: 		
$0625	$0279			SUBWF	STACK_9, W
;math.ppas,440 :: 		
$0626	$1D03			BTFSS	STATUS, Z
;math.ppas,441 :: 		
$0627	$2DFD			GOTO	$-42
;math.ppas,442 :: 		
$0628	$01F9			CLRF	STACK_9
;math.ppas,443 :: 		
$0629	$01F8			CLRF	STACK_8
;math.ppas,444 :: 		
$062A	$0AF0			INCF	STACK_0, F
;math.ppas,445 :: 		
$062B	$1903			BTFSC	STATUS, Z
;math.ppas,446 :: 		
$062C	$0AF1			INCF	STACK_1, F
;math.ppas,447 :: 		
$062D	$1FF1			BTFSS	STACK_1, 7
;math.ppas,448 :: 		
$062E	$2DFD			GOTO	$-49
;math.ppas,449 :: 		
$062F	$0000			NOP
;math.ppas,450 :: 		
$0630	$34FF			RETLW	255
;math.ppas,451 :: 		
$0631	$	math_L_7:
;math.ppas,452 :: 		
$0631	$0008			RETURN
$083E	$	_usart_write:
;USART_b75.ppas,40 :: 		
;USART_b75.ppas,42 :: 		
$083E	$	USART_b75_L_14:
$083E	$1303			BCF	STATUS, RP1
$083F	$1683			BSF	STATUS, RP0
$0840	$0818			MOVF	TXSTA, 0
$0841	$00F1			MOVWF	STACK_1
$0842	$3000			MOVLW	0
$0843	$18F1			BTFSC	STACK_1, 1
$0844	$3001			MOVLW	1
$0845	$00F1			MOVWF	STACK_1
$0846	$0871			MOVF	STACK_1, 0
$0847	$3A00			XORLW	0
$0848	$1D03			BTFSS	STATUS, Z
$0849	$284C			GOTO	USART_b75_L_15
;USART_b75.ppas,43 :: 		
$084A	$0000			NOP
$084B	$283E			GOTO	USART_b75_L_14
$084C	$	USART_b75_L_15:
;USART_b75.ppas,44 :: 		
$084C	$1283			BCF	STATUS, RP0
$084D	$0863			MOVF	FARG_USART_Write, 0
$084E	$0099			MOVWF	TXREG
$084F	$	USART_b75_L_12:
;USART_b75.ppas,45 :: 		
$084F	$0008			RETURN
$0850	$	_usart_data_ready:
;USART_b75.ppas,48 :: 		
;USART_b75.ppas,50 :: 		
$0850	$1303			BCF	STATUS, RP1
$0851	$1283			BCF	STATUS, RP0
$0852	$080C			MOVF	PIR1, 0
$0853	$00F1			MOVWF	STACK_1
$0854	$3000			MOVLW	0
$0855	$1AF1			BTFSC	STACK_1, 5
$0856	$3001			MOVLW	1
$0857	$00F1			MOVWF	STACK_1
$0858	$0871			MOVF	STACK_1, 0
$0859	$00DE			MOVWF	_usart_data_ready_local_result
$085A	$	USART_b75_L_18:
;USART_b75.ppas,51 :: 		
$085A	$085E			MOVF	_usart_data_ready_local_result, 0
$085B	$00F0			MOVWF	STACK_0
$085C	$0008			RETURN
$082B	$	_usart_read:
;USART_b75.ppas,54 :: 		
;USART_b75.ppas,55 :: 		
$082B	$1303			BCF	STATUS, RP1
$082C	$1283			BCF	STATUS, RP0
$082D	$081A			MOVF	RCREG, 0
$082E	$00DE			MOVWF	_usart_read_local_result
;USART_b75.ppas,61 :: 		
$082F	$0818			MOVF	RCSTA, 0
$0830	$00F1			MOVWF	STACK_1
$0831	$3000			MOVLW	0
$0832	$18F1			BTFSC	STACK_1, 1
$0833	$3001			MOVLW	1
$0834	$00F1			MOVWF	STACK_1
$0835	$0871			MOVF	STACK_1, 0
$0836	$3A01			XORLW	1
$0837	$1D03			BTFSS	STATUS, Z
$0838	$283B			GOTO	USART_b75_L_21
$0839	$	USART_b75_L_20:
;USART_b75.ppas,63 :: 		
$0839	$1218			BCF	RCSTA, 4
$083A	$	USART_b75_L_24:
;USART_b75.ppas,64 :: 		
$083A	$	USART_b75_L_25:
$083A	$1618			BSF	RCSTA, 4
$083B	$	USART_b75_L_26:
;USART_b75.ppas,65 :: 		
$083B	$	USART_b75_L_21:
$083B	$	USART_b75_L_22:
$083B	$	USART_b75_L_19:
;USART_b75.ppas,66 :: 		
$083B	$085E			MOVF	_usart_read_local_result, 0
$083C	$00F0			MOVWF	STACK_0
$083D	$0008			RETURN
$06C2	$	_mul_32x32_s:
$06C2	$1303			BCF	STATUS, RP1
$06C3	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$06C4	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$06C5	$	_IF_FIRST:
;math.ppas,1684 :: 		
$06C5	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$06C6	$2ED4			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$06C7	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$06C7	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$06C8	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$06C9	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$06CA	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$06CB	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$06CC	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$06CD	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$06CE	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$06CF	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$06D0	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$06D1	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$06D2	$3081			MOVLW	129
;math.ppas,1711 :: 		
$06D3	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$06D4	$	_IF_SECOND:
;math.ppas,1715 :: 		
$06D4	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$06D5	$2EE2			GOTO	_MULT
;math.ppas,1722 :: 		
$06D6	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$06D6	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$06D7	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$06D8	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$06D9	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$06DA	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$06DB	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$06DC	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$06DD	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$06DE	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$06DF	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$06E0	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$06E1	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$06E2	$	_MULT:
;math.ppas,1744 :: 		
$06E2	$26FD			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$06E3	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$06E4	$2EFC			GOTO	_EXIT
;math.ppas,1755 :: 		
$06E5	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$06E6	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$06E7	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$06E8	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$06E9	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$06EA	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$06EB	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$06EC	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$06ED	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$06EE	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$06EF	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$06F0	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$06F1	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$06F2	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$06F3	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$06F4	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$06F5	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$06F6	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$06F7	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$06F8	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$06F9	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$06FA	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$06FB	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$06FC	$	_EXIT:
;math.ppas,1793 :: 		
$06FC	$	math_L_14:
;math.ppas,1794 :: 		
$06FC	$0008			RETURN
$0761	$	_div_16x16_u:
$0761	$1303			BCF	STATUS, RP1
$0762	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$0763	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$0764	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$0765	$3010			MOVLW	16
;math.ppas,113 :: 		
$0766	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$0767	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$0768	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$0769	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$076A	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$076B	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$076C	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$076D	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$076E	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$076F	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$0770	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$0771	$2F79			GOTO	$+8
;math.ppas,125 :: 		
$0772	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$0773	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$0774	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$0775	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$0776	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$0777	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$0778	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$0779	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$077A	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$077B	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$077C	$2F67			GOTO	$-21
;math.ppas,136 :: 		
$077D	$	math_L_3:
;math.ppas,137 :: 		
$077D	$0008			RETURN
$04F3	$	_div_32x32_s:
$04F3	$1303			BCF	STATUS, RP1
$04F4	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$04F5	$	FXD3232S:
;math.ppas,929 :: 		
$04F5	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$04F6	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$04F7	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$04F8	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$04F9	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$04FA	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$04FB	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$04FC	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$04FD	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$04FE	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$04FF	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$0500	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0501	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$0502	$2D87			GOTO	END_ALL
;math.ppas,944 :: 		
$0503	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$0504	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$0505	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$0506	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$0507	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$0508	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$0509	$2D15			GOTO	CA3232S
;math.ppas,955 :: 		
$050A	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$050B	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$050C	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$050D	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$050E	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$050F	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$0510	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0511	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$0512	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$0513	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$0514	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$0515	$	CA3232S:
;math.ppas,968 :: 		
$0515	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$0516	$2D22			GOTO	C3232SX
;math.ppas,971 :: 		
$0517	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$0518	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$0519	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$051A	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$051B	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$051C	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$051D	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$051E	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$051F	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$0520	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$0521	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$0522	$	C3232SX:
;math.ppas,984 :: 		
$0522	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$0523	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$0524	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$0525	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$0526	$2D43			GOTO	C3232SX1
;math.ppas,989 :: 		
$0527	$	C3232S:
;math.ppas,992 :: 		
$0527	$2260			CALL	_sdiv3232l
;math.ppas,995 :: 		
$0528	$	C3232S2:
;math.ppas,996 :: 		
$0528	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$0529	$2D60			GOTO	C3232SX4
;math.ppas,998 :: 		
$052A	$	C3232SOK:
;math.ppas,999 :: 		
$052A	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$052B	$2D87			GOTO	END_ALL
;math.ppas,1001 :: 		
$052C	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$052D	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$052E	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$052F	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$0530	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$0531	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$0532	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$0533	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$0534	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$0535	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$0536	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$0537	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$0538	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$0539	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$053A	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$053B	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$053C	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$053D	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$053E	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$053F	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$0540	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$0541	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$0542	$2D87			GOTO	END_ALL
;math.ppas,1026 :: 		
$0543	$	C3232SX1:
;math.ppas,1027 :: 		
$0543	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$0544	$2D5A			GOTO	C3232SX3
;math.ppas,1029 :: 		
$0545	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$0546	$2D54			GOTO	C3232SX2
;math.ppas,1031 :: 		
$0547	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$0548	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$0549	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$054A	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$054B	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$054C	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$054D	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$054E	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$054F	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$0550	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$0551	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$0552	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$0553	$2D2A			GOTO	C3232SOK
;math.ppas,1044 :: 		
$0554	$	C3232SX2:
;math.ppas,1045 :: 		
$0554	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$0555	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$0556	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$0557	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$0558	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$0559	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$055A	$	C3232SX3:
;math.ppas,1053 :: 		
$055A	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$055B	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$055C	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$055D	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$055E	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$055F	$2D27			GOTO	C3232S
;math.ppas,1061 :: 		
$0560	$	C3232SX4:
;math.ppas,1062 :: 		
$0560	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0561	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$0562	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$0563	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$0564	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$0565	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$0566	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$0567	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$0568	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$0569	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$056A	$2D2A			GOTO	C3232SOK
;math.ppas,1073 :: 		
$056B	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$056C	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$056D	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$056E	$2D2A			GOTO	C3232SOK
;math.ppas,1077 :: 		
$056F	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$0570	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$0571	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$0572	$2D2A			GOTO	C3232SOK
;math.ppas,1081 :: 		
$0573	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$0574	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$0575	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$0576	$2D2A			GOTO	C3232SOK
;math.ppas,1085 :: 		
$0577	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$0578	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$0579	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$057A	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$057B	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$057C	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$057D	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$057E	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$057F	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$0580	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0581	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$0582	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$0583	$2D2A			GOTO	C3232SOK
;math.ppas,1098 :: 		
$0584	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$0585	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$0586	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$0587	$	END_ALL:
;math.ppas,1102 :: 		
$0587	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$0588	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$0589	$2D8B			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$058A	$277E			CALL	_comfrem
;math.ppas,1108 :: 		
$058B	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$058B	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$058C	$	math_L_11:
;math.ppas,1111 :: 		
$058C	$0008			RETURN
$0450	$	_inttostr:
;conv.ppas,100 :: 		
;conv.ppas,101 :: 		
$0450	$1303			BCF	STATUS, RP1
$0451	$1283			BCF	STATUS, RP0
$0452	$085F			MOVF	FARG_IntToStr+1, 0
$0453	$3A80			XORLW	128
$0454	$1D03			BTFSS	STATUS, Z
$0455	$2C58			GOTO	L_IntToStr_4
$0456	$3000			MOVLW	0
$0457	$065E			XORWF	FARG_IntToStr, 0
$0458	$	L_IntToStr_4:
$0458	$1D03			BTFSS	STATUS, Z
$0459	$2C70			GOTO	conv_L_57
$045A	$	conv_L_56:
;conv.ppas,103 :: 		
$045A	$0860			MOVF	FARG_IntToStr+2, 0
$045B	$0084			MOVWF	FSR
$045C	$302D			MOVLW	45
$045D	$0080			MOVWF	INDF
$045E	$0A84			INCF	FSR, 1
$045F	$3033			MOVLW	51
$0460	$0080			MOVWF	INDF
$0461	$0A84			INCF	FSR, 1
$0462	$3032			MOVLW	50
$0463	$0080			MOVWF	INDF
$0464	$0A84			INCF	FSR, 1
$0465	$3037			MOVLW	55
$0466	$0080			MOVWF	INDF
$0467	$0A84			INCF	FSR, 1
$0468	$3036			MOVLW	54
$0469	$0080			MOVWF	INDF
$046A	$0A84			INCF	FSR, 1
$046B	$3038			MOVLW	56
$046C	$0080			MOVWF	INDF
$046D	$0A84			INCF	FSR, 1
$046E	$0180			CLRF	INDF
;conv.ppas,104 :: 		
$046F	$2CF2			GOTO	conv_L_55
;conv.ppas,105 :: 		
$0470	$	conv_L_57:
$0470	$	conv_L_58:
;conv.ppas,106 :: 		
$0470	$01E2			CLRF	_inttostr_local_negative, 1
;conv.ppas,107 :: 		
$0471	$3080			MOVLW	128
$0472	$065F			XORWF	FARG_IntToStr+1, 0
$0473	$00F0			MOVWF	STACK_0
$0474	$3080			MOVLW	128
$0475	$0270			SUBWF	STACK_0, 0
$0476	$1D03			BTFSS	STATUS, Z
$0477	$2C7A			GOTO	L_IntToStr_5
$0478	$3000			MOVLW	0
$0479	$025E			SUBWF	FARG_IntToStr, 0
$047A	$	L_IntToStr_5:
$047A	$1803			BTFSC	STATUS, C
$047B	$2C86			GOTO	conv_L_61
$047C	$	conv_L_60:
;conv.ppas,109 :: 		
$047C	$30FF			MOVLW	255
$047D	$00E2			MOVWF	_inttostr_local_negative
;conv.ppas,110 :: 		
$047E	$085E			MOVF	FARG_IntToStr, 0
$047F	$3C00			SUBLW	0
$0480	$00DE			MOVWF	FARG_IntToStr
$0481	$085F			MOVF	FARG_IntToStr+1, 0
$0482	$1C03			BTFSS	STATUS, C
$0483	$3F01			ADDLW	1
$0484	$01DF			CLRF	FARG_IntToStr+1
$0485	$02DF			SUBWF	FARG_IntToStr+1, 1
;conv.ppas,111 :: 		
$0486	$	conv_L_61:
$0486	$	conv_L_62:
;conv.ppas,112 :: 		
$0486	$3001			MOVLW	1
$0487	$00E1			MOVWF	_inttostr_local_len
;conv.ppas,113 :: 		
$0488	$3080			MOVLW	128
$0489	$00F0			MOVWF	STACK_0
$048A	$3080			MOVLW	128
$048B	$065F			XORWF	FARG_IntToStr+1, 0
$048C	$0270			SUBWF	STACK_0, 0
$048D	$1D03			BTFSS	STATUS, Z
$048E	$2C91			GOTO	L_IntToStr_6
$048F	$085E			MOVF	FARG_IntToStr, 0
$0490	$3C09			SUBLW	9
$0491	$	L_IntToStr_6:
$0491	$1803			BTFSC	STATUS, C
$0492	$2C94			GOTO	conv_L_64
$0493	$	conv_L_63:
;conv.ppas,114 :: 		
$0493	$0AE1			INCF	_inttostr_local_len, 1
$0494	$	conv_L_64:
$0494	$	conv_L_65:
;conv.ppas,115 :: 		
$0494	$3080			MOVLW	128
$0495	$00F0			MOVWF	STACK_0
$0496	$3080			MOVLW	128
$0497	$065F			XORWF	FARG_IntToStr+1, 0
$0498	$0270			SUBWF	STACK_0, 0
$0499	$1D03			BTFSS	STATUS, Z
$049A	$2C9D			GOTO	L_IntToStr_7
$049B	$085E			MOVF	FARG_IntToStr, 0
$049C	$3C63			SUBLW	99
$049D	$	L_IntToStr_7:
$049D	$1803			BTFSC	STATUS, C
$049E	$2CA0			GOTO	conv_L_67
$049F	$	conv_L_66:
;conv.ppas,116 :: 		
$049F	$0AE1			INCF	_inttostr_local_len, 1
$04A0	$	conv_L_67:
$04A0	$	conv_L_68:
;conv.ppas,117 :: 		
$04A0	$3080			MOVLW	128
$04A1	$3A03			XORLW	3
$04A2	$00F0			MOVWF	STACK_0
$04A3	$3080			MOVLW	128
$04A4	$065F			XORWF	FARG_IntToStr+1, 0
$04A5	$0270			SUBWF	STACK_0, 0
$04A6	$1D03			BTFSS	STATUS, Z
$04A7	$2CAA			GOTO	L_IntToStr_8
$04A8	$085E			MOVF	FARG_IntToStr, 0
$04A9	$3CE7			SUBLW	231
$04AA	$	L_IntToStr_8:
$04AA	$1803			BTFSC	STATUS, C
$04AB	$2CAD			GOTO	conv_L_70
$04AC	$	conv_L_69:
;conv.ppas,118 :: 		
$04AC	$0AE1			INCF	_inttostr_local_len, 1
$04AD	$	conv_L_70:
$04AD	$	conv_L_71:
;conv.ppas,119 :: 		
$04AD	$3080			MOVLW	128
$04AE	$3A27			XORLW	39
$04AF	$00F0			MOVWF	STACK_0
$04B0	$3080			MOVLW	128
$04B1	$065F			XORWF	FARG_IntToStr+1, 0
$04B2	$0270			SUBWF	STACK_0, 0
$04B3	$1D03			BTFSS	STATUS, Z
$04B4	$2CB7			GOTO	L_IntToStr_9
$04B5	$085E			MOVF	FARG_IntToStr, 0
$04B6	$3C0F			SUBLW	15
$04B7	$	L_IntToStr_9:
$04B7	$1803			BTFSC	STATUS, C
$04B8	$2CBA			GOTO	conv_L_73
$04B9	$	conv_L_72:
;conv.ppas,120 :: 		
$04B9	$0AE1			INCF	_inttostr_local_len, 1
$04BA	$	conv_L_73:
$04BA	$	conv_L_74:
;conv.ppas,121 :: 		
$04BA	$0860			MOVF	FARG_IntToStr+2, 0
$04BB	$0084			MOVWF	FSR
$04BC	$3020			MOVLW	32
$04BD	$0080			MOVWF	INDF
$04BE	$0A84			INCF	FSR, 1
$04BF	$0080			MOVWF	INDF
$04C0	$0A84			INCF	FSR, 1
$04C1	$0080			MOVWF	INDF
$04C2	$0A84			INCF	FSR, 1
$04C3	$0080			MOVWF	INDF
$04C4	$0A84			INCF	FSR, 1
$04C5	$0080			MOVWF	INDF
$04C6	$0A84			INCF	FSR, 1
$04C7	$0080			MOVWF	INDF
$04C8	$0A84			INCF	FSR, 1
$04C9	$0180			CLRF	INDF
;conv.ppas,122 :: 		
$04CA	$0384			DECF	FSR, 1
;conv.ppas,123 :: 		
$04CB	$	conv_L_77:
$04CB	$0861			MOVF	_inttostr_local_len, 0
$04CC	$3C00			SUBLW	0
$04CD	$1803			BTFSC	STATUS, C
$04CE	$2CED			GOTO	conv_L_78
;conv.ppas,125 :: 		
$04CF	$300A			MOVLW	10
$04D0	$00F4			MOVWF	STACK_4
$04D1	$01F5			CLRF	STACK_4+1
$04D2	$085E			MOVF	FARG_IntToStr, 0
$04D3	$00F0			MOVWF	STACK_0
$04D4	$085F			MOVF	FARG_IntToStr+1, 0
$04D5	$00F1			MOVWF	STACK_0+1
$04D6	$25D8			CALL	_div_16x16_s
$04D7	$0878			MOVF	STACK_8, 0
$04D8	$00F0			MOVWF	STACK_0
$04D9	$0879			MOVF	STACK_9, 0
$04DA	$00F1			MOVWF	STACK_1
$04DB	$3030			MOVLW	48
$04DC	$0770			ADDWF	STACK_0, 0
$04DD	$0080			MOVWF	INDF
;conv.ppas,126 :: 		
;conv.ppas,127 :: 		
$04DE	$0384			DECF	FSR, 1
;conv.ppas,128 :: 		
$04DF	$300A			MOVLW	10
$04E0	$00F4			MOVWF	STACK_4
$04E1	$01F5			CLRF	STACK_4+1
$04E2	$085E			MOVF	FARG_IntToStr, 0
$04E3	$00F0			MOVWF	STACK_0
$04E4	$085F			MOVF	FARG_IntToStr+1, 0
$04E5	$00F1			MOVWF	STACK_0+1
$04E6	$25D8			CALL	_div_16x16_s
$04E7	$0870			MOVF	STACK_0, 0
$04E8	$00DE			MOVWF	FARG_IntToStr
$04E9	$0871			MOVF	STACK_0+1, 0
$04EA	$00DF			MOVWF	FARG_IntToStr+1
;conv.ppas,129 :: 		
$04EB	$03E1			DECF	_inttostr_local_len, 1
;conv.ppas,130 :: 		
$04EC	$2CCB			GOTO	conv_L_77
$04ED	$	conv_L_78:
;conv.ppas,131 :: 		
$04ED	$0862			MOVF	_inttostr_local_negative, 0
$04EE	$1903			BTFSC	STATUS, Z
$04EF	$2CF2			GOTO	conv_L_82
$04F0	$	conv_L_81:
;conv.ppas,133 :: 		
$04F0	$302D			MOVLW	45
$04F1	$0080			MOVWF	INDF
;conv.ppas,134 :: 		
$04F2	$	conv_L_82:
$04F2	$	conv_L_83:
$04F2	$	conv_L_55:
;conv.ppas,135 :: 		
$04F2	$0008			RETURN
$0800	$	_usart_write_text:
;USART_b75.ppas,121 :: 		
;USART_b75.ppas,122 :: 		
$0800	$1303			BCF	STATUS, RP1
$0801	$1283			BCF	STATUS, RP0
$0802	$01DF			CLRF	_usart_write_text_local_i, 1
;USART_b75.ppas,123 :: 		
$0803	$085E			MOVF	FARG_Usart_Write_Text, 0
$0804	$0084			MOVWF	FSR
$0805	$0800			MOVF	INDF, 0
$0806	$00E0			MOVWF	_usart_write_text_local_data
;USART_b75.ppas,124 :: 		
$0807	$	USART_b75_L_47:
$0807	$0860			MOVF	_usart_write_text_local_data, 0
$0808	$3A00			XORLW	0
$0809	$1903			BTFSC	STATUS, Z
$080A	$2815			GOTO	USART_b75_L_48
;USART_b75.ppas,126 :: 		
$080B	$0860			MOVF	_usart_write_text_local_data, 0
$080C	$00E3			MOVWF	FARG_USART_Write
$080D	$203E			CALL	_usart_write
;USART_b75.ppas,127 :: 		
$080E	$0ADF			INCF	_usart_write_text_local_i, 1
;USART_b75.ppas,128 :: 		
$080F	$085F			MOVF	_usart_write_text_local_i, 0
$0810	$075E			ADDWF	FARG_Usart_Write_Text, 0
$0811	$0084			MOVWF	FSR
$0812	$0800			MOVF	INDF, 0
$0813	$00E0			MOVWF	_usart_write_text_local_data
;USART_b75.ppas,129 :: 		
$0814	$2807			GOTO	USART_b75_L_47
$0815	$	USART_b75_L_48:
$0815	$	USART_b75_L_45:
;USART_b75.ppas,130 :: 		
$0815	$0008			RETURN
$0632	$	_usart_read_text:
;USART_b75.ppas,78 :: 		
;USART_b75.ppas,79 :: 		
$0632	$1303			BCF	STATUS, RP1
$0633	$1283			BCF	STATUS, RP0
$0634	$01D3			CLRF	_usart_read_text_local_i, 1
;USART_b75.ppas,80 :: 		
$0635	$01D4			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,81 :: 		
$0636	$01D7			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,82 :: 		
$0637	$0852			MOVF	FARG_Usart_Read_Text+1, 0
$0638	$0084			MOVWF	FSR
$0639	$0800			MOVF	INDF, 0
$063A	$00D6			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,83 :: 		
$063B	$	USART_b75_L_29:
;USART_b75.ppas,85 :: 		
$063B	$158A			BSF	PCLATH, 3
$063C	$2050			CALL	_usart_data_ready
$063D	$118A			BCF	PCLATH, 3
$063E	$0870			MOVF	STACK_0, 0
$063F	$3A00			XORLW	0
$0640	$1903			BTFSC	STATUS, Z
$0641	$2E6F			GOTO	USART_b75_L_34
$0642	$	USART_b75_L_33:
;USART_b75.ppas,87 :: 		
$0642	$158A			BSF	PCLATH, 3
$0643	$202B			CALL	_usart_read
$0644	$118A			BCF	PCLATH, 3
$0645	$0870			MOVF	STACK_0, 0
$0646	$00D5			MOVWF	_usart_read_text_local_data
;USART_b75.ppas,88 :: 		
$0647	$0853			MOVF	_usart_read_text_local_i, 0
$0648	$0751			ADDWF	FARG_Usart_Read_Text, 0
$0649	$00F1			MOVWF	STACK_1
$064A	$0871			MOVF	STACK_1, 0
$064B	$0084			MOVWF	FSR
$064C	$0871			MOVF	STACK_1, 0
$064D	$0084			MOVWF	FSR
$064E	$0870			MOVF	STACK_0, 0
$064F	$0080			MOVWF	INDF
;USART_b75.ppas,89 :: 		
$0650	$0855			MOVF	_usart_read_text_local_data, 0
$0651	$0656			XORWF	_usart_read_text_local_data2, 0
$0652	$1D03			BTFSS	STATUS, Z
$0653	$2E59			GOTO	USART_b75_L_37
$0654	$	USART_b75_L_36:
;USART_b75.ppas,91 :: 		
$0654	$0854			MOVF	_usart_read_text_local_j, 0
$0655	$0253			SUBWF	_usart_read_text_local_i, 0
$0656	$00D7			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,92 :: 		
$0657	$0AD4			INCF	_usart_read_text_local_j, 1
;USART_b75.ppas,93 :: 		
$0658	$2E5B			GOTO	USART_b75_L_38
;USART_b75.ppas,94 :: 		
$0659	$	USART_b75_L_37:
;USART_b75.ppas,96 :: 		
$0659	$01D4			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,97 :: 		
$065A	$01D7			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,98 :: 		
$065B	$	USART_b75_L_38:
;USART_b75.ppas,100 :: 		
$065B	$0854			MOVF	_usart_read_text_local_j, 0
$065C	$0752			ADDWF	FARG_Usart_Read_Text+1, 0
$065D	$0084			MOVWF	FSR
$065E	$0800			MOVF	INDF, 0
$065F	$00F1			MOVWF	STACK_1
$0660	$0871			MOVF	STACK_1, 0
$0661	$00D6			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,102 :: 		
$0662	$0871			MOVF	STACK_1, 0
$0663	$3A00			XORLW	0
$0664	$1D03			BTFSS	STATUS, Z
$0665	$2E67			GOTO	USART_b75_L_40
$0666	$	USART_b75_L_39:
;USART_b75.ppas,103 :: 		
$0666	$2E70			GOTO	USART_b75_L_30
$0667	$	USART_b75_L_40:
$0667	$	USART_b75_L_41:
;USART_b75.ppas,105 :: 		
$0667	$0AD3			INCF	_usart_read_text_local_i, 1
;USART_b75.ppas,106 :: 		
$0668	$0853			MOVF	_usart_read_text_local_i, 0
$0669	$3C14			SUBLW	20
$066A	$1803			BTFSC	STATUS, C
$066B	$2E6F			GOTO	USART_b75_L_43
$066C	$	USART_b75_L_42:
;USART_b75.ppas,108 :: 		
$066C	$3013			MOVLW	19
$066D	$00D7			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,109 :: 		
$066E	$2E70			GOTO	USART_b75_L_30
;USART_b75.ppas,110 :: 		
$066F	$	USART_b75_L_43:
$066F	$	USART_b75_L_44:
;USART_b75.ppas,111 :: 		
$066F	$	USART_b75_L_34:
$066F	$	USART_b75_L_35:
;USART_b75.ppas,112 :: 		
$066F	$2E3B			GOTO	USART_b75_L_29
$0670	$	USART_b75_L_30:
;USART_b75.ppas,113 :: 		
$0670	$0857			MOVF	_usart_read_text_local_lasti, 0
$0671	$0751			ADDWF	FARG_Usart_Read_Text, 0
$0672	$00F0			MOVWF	STACK_0
$0673	$0870			MOVF	STACK_0, 0
$0674	$0084			MOVWF	FSR
$0675	$0870			MOVF	STACK_0, 0
$0676	$0084			MOVWF	FSR
$0677	$0180			CLRF	INDF, 1
$0678	$	USART_b75_L_27:
;USART_b75.ppas,114 :: 		
$0678	$0008			RETURN
$038E	$	_strtoint:
;conv.ppas,343 :: 		
;conv.ppas,345 :: 		
$038E	$1303			BCF	STATUS, RP1
$038F	$1283			BCF	STATUS, RP0
$0390	$01D2			CLRF	_strtoint_local_result
$0391	$01D3			CLRF	_strtoint_local_result+1
;conv.ppas,346 :: 		
$0392	$3010			MOVLW	16
$0393	$00D6			MOVWF	_strtoint_local_ep
$0394	$3027			MOVLW	39
$0395	$00D7			MOVWF	_strtoint_local_ep+1
;conv.ppas,347 :: 		
$0396	$01D4			CLRF	_strtoint_local_i
$0397	$01D5			CLRF	_strtoint_local_i+1
;conv.ppas,348 :: 		
$0398	$01DA			CLRF	_strtoint_local_tmp
$0399	$01DB			CLRF	_strtoint_local_tmp+1
$039A	$01DC			CLRF	_strtoint_local_tmp+2
$039B	$01DD			CLRF	_strtoint_local_tmp+3
;conv.ppas,349 :: 		
$039C	$01D8			CLRF	_strtoint_local_negative
$039D	$01D9			CLRF	_strtoint_local_negative+1
;conv.ppas,353 :: 		
$039E	$	conv_L_172:
$039E	$0854			MOVF	_strtoint_local_i, 0
$039F	$0751			ADDWF	FARG_StrToInt, 0
$03A0	$0084			MOVWF	FSR
$03A1	$0800			MOVF	INDF, 0
$03A2	$00F4			MOVWF	STACK_4
$03A3	$0874			MOVF	STACK_4, 0
$03A4	$3A00			XORLW	0
$03A5	$1903			BTFSC	STATUS, Z
$03A6	$2C0A			GOTO	conv_L_173
;conv.ppas,355 :: 		
$03A7	$0854			MOVF	_strtoint_local_i, 0
$03A8	$0751			ADDWF	FARG_StrToInt, 0
$03A9	$0084			MOVWF	FSR
$03AA	$0800			MOVF	INDF, 0
$03AB	$00F4			MOVWF	STACK_4
$03AC	$0874			MOVF	STACK_4, 0
$03AD	$3A2D			XORLW	45
$03AE	$1D03			BTFSS	STATUS, Z
$03AF	$2BB7			GOTO	conv_L_177
$03B0	$	conv_L_176:
;conv.ppas,357 :: 		
$03B0	$30FF			MOVLW	255
$03B1	$00D8			MOVWF	_strtoint_local_negative
$03B2	$01D9			CLRF	_strtoint_local_negative+1
;conv.ppas,358 :: 		
$03B3	$0AD4			INCF	_strtoint_local_i, 1
$03B4	$1903			BTFSC	STATUS, Z
$03B5	$0AD5			INCF	_strtoint_local_i+1, 1
;conv.ppas,359 :: 		
$03B6	$2B9E			GOTO	conv_L_172
;conv.ppas,360 :: 		
$03B7	$	conv_L_177:
$03B7	$	conv_L_178:
;conv.ppas,361 :: 		
$03B7	$0854			MOVF	_strtoint_local_i, 0
$03B8	$0751			ADDWF	FARG_StrToInt, 0
$03B9	$0084			MOVWF	FSR
$03BA	$0800			MOVF	INDF, 0
$03BB	$00F4			MOVWF	STACK_4
$03BC	$0874			MOVF	STACK_4, 0
$03BD	$3A20			XORLW	32
$03BE	$1903			BTFSC	STATUS, Z
$03BF	$2BFA			GOTO	conv_L_180
$03C0	$	conv_L_179:
;conv.ppas,362 :: 		
$03C0	$0854			MOVF	_strtoint_local_i, 0
$03C1	$0751			ADDWF	FARG_StrToInt, 0
$03C2	$0084			MOVWF	FSR
$03C3	$0800			MOVF	INDF, 0
$03C4	$00F0			MOVWF	STACK_0
$03C5	$3030			MOVLW	48
$03C6	$00F8			MOVWF	STACK_8
$03C7	$01F9			CLRF	STACK_8+1
$03C8	$01FA			CLRF	STACK_8+2
$03C9	$01FB			CLRF	STACK_8+3
$03CA	$0870			MOVF	STACK_0, 0
$03CB	$00F4			MOVWF	STACK_4
$03CC	$01F5			CLRF	STACK_4+1
$03CD	$01F6			CLRF	STACK_4+2
$03CE	$01F7			CLRF	STACK_4+3
$03CF	$0874			MOVF	STACK_4, 0
$03D0	$00F0			MOVWF	STACK_0
$03D1	$0875			MOVF	STACK_4+1, 0
$03D2	$00F1			MOVWF	STACK_0+1
$03D3	$0876			MOVF	STACK_4+2, 0
$03D4	$00F2			MOVWF	STACK_0+2
$03D5	$0877			MOVF	STACK_4+3, 0
$03D6	$00F3			MOVWF	STACK_0+3
$03D7	$0878			MOVF	STACK_8, 0
$03D8	$02F0			SUBWF	STACK_0, 1
$03D9	$0879			MOVF	STACK_8+1, 0
$03DA	$1C03			BTFSS	STATUS, C
$03DB	$0F79			INCFSZ	STACK_8+1, 0
$03DC	$02F1			SUBWF	STACK_0+1, 1
$03DD	$087A			MOVF	STACK_8+2, 0
$03DE	$1C03			BTFSS	STATUS, C
$03DF	$0F7A			INCFSZ	STACK_8+2, 0
$03E0	$02F2			SUBWF	STACK_0+2, 1
$03E1	$087B			MOVF	STACK_8+3, 0
$03E2	$1C03			BTFSS	STATUS, C
$03E3	$0F7B			INCFSZ	STACK_8+3, 0
$03E4	$02F3			SUBWF	STACK_0+3, 1
$03E5	$0856			MOVF	_strtoint_local_ep, 0
$03E6	$00F4			MOVWF	STACK_4
$03E7	$0857			MOVF	_strtoint_local_ep+1, 0
$03E8	$00F5			MOVWF	STACK_4+1
$03E9	$01F6			CLRF	STACK_4+2
$03EA	$01F7			CLRF	STACK_4+3
$03EB	$26C2			CALL	_mul_32x32_s
$03EC	$0870			MOVF	STACK_0, 0
$03ED	$07DA			ADDWF	_strtoint_local_tmp, 1
$03EE	$0871			MOVF	STACK_0+1, 0
$03EF	$1803			BTFSC	STATUS, C
$03F0	$0F71			INCFSZ	STACK_0+1, 0
$03F1	$07DB			ADDWF	_strtoint_local_tmp+1, 1
$03F2	$0872			MOVF	STACK_0+2, 0
$03F3	$1803			BTFSC	STATUS, C
$03F4	$0F72			INCFSZ	STACK_0+2, 0
$03F5	$07DC			ADDWF	_strtoint_local_tmp+2, 1
$03F6	$0873			MOVF	STACK_0+3, 0
$03F7	$1803			BTFSC	STATUS, C
$03F8	$0F73			INCFSZ	STACK_0+3, 0
$03F9	$07DD			ADDWF	_strtoint_local_tmp+3, 1
$03FA	$	conv_L_180:
$03FA	$	conv_L_181:
;conv.ppas,363 :: 		
$03FA	$300A			MOVLW	10
$03FB	$00F4			MOVWF	STACK_4
$03FC	$01F5			CLRF	STACK_4+1
$03FD	$0856			MOVF	_strtoint_local_ep, 0
$03FE	$00F0			MOVWF	STACK_0
$03FF	$0857			MOVF	_strtoint_local_ep+1, 0
$0400	$00F1			MOVWF	STACK_0+1
$0401	$2761			CALL	_div_16x16_u
$0402	$0870			MOVF	STACK_0, 0
$0403	$00D6			MOVWF	_strtoint_local_ep
$0404	$0871			MOVF	STACK_0+1, 0
$0405	$00D7			MOVWF	_strtoint_local_ep+1
;conv.ppas,365 :: 		
$0406	$0AD4			INCF	_strtoint_local_i, 1
$0407	$1903			BTFSC	STATUS, Z
$0408	$0AD5			INCF	_strtoint_local_i+1, 1
;conv.ppas,366 :: 		
$0409	$2B9E			GOTO	conv_L_172
$040A	$	conv_L_173:
;conv.ppas,370 :: 		
$040A	$0858			MOVF	_strtoint_local_negative, 0
$040B	$0459			IORWF	_strtoint_local_negative+1, 0
$040C	$1903			BTFSC	STATUS, Z
$040D	$2C12			GOTO	conv_L_183
$040E	$	conv_L_182:
$040E	$3006			MOVLW	6
$040F	$00D6			MOVWF	_strtoint_local_ep
$0410	$01D7			CLRF	_strtoint_local_ep+1
$0411	$2C15			GOTO	conv_L_184
;conv.ppas,371 :: 		
$0412	$	conv_L_183:
$0412	$3005			MOVLW	5
$0413	$00D6			MOVWF	_strtoint_local_ep
$0414	$01D7			CLRF	_strtoint_local_ep+1
$0415	$	conv_L_184:
;conv.ppas,373 :: 		
$0415	$	conv_L_186:
$0415	$0855			MOVF	_strtoint_local_i+1, 0
$0416	$0657			XORWF	_strtoint_local_ep+1, 0
$0417	$1D03			BTFSS	STATUS, Z
$0418	$2C1B			GOTO	L_StrToInt_20
$0419	$0856			MOVF	_strtoint_local_ep, 0
$041A	$0654			XORWF	_strtoint_local_i, 0
$041B	$	L_StrToInt_20:
$041B	$1903			BTFSC	STATUS, Z
$041C	$2C37			GOTO	conv_L_187
;conv.ppas,375 :: 		
$041D	$300A			MOVLW	10
$041E	$00F4			MOVWF	STACK_4
$041F	$01F5			CLRF	STACK_4+1
$0420	$01F6			CLRF	STACK_4+2
$0421	$01F7			CLRF	STACK_4+3
$0422	$085A			MOVF	_strtoint_local_tmp, 0
$0423	$00F0			MOVWF	STACK_0
$0424	$085B			MOVF	_strtoint_local_tmp+1, 0
$0425	$00F1			MOVWF	STACK_0+1
$0426	$085C			MOVF	_strtoint_local_tmp+2, 0
$0427	$00F2			MOVWF	STACK_0+2
$0428	$085D			MOVF	_strtoint_local_tmp+3, 0
$0429	$00F3			MOVWF	STACK_0+3
$042A	$24F3			CALL	_div_32x32_s
$042B	$0870			MOVF	STACK_0, 0
$042C	$00DA			MOVWF	_strtoint_local_tmp
$042D	$0871			MOVF	STACK_0+1, 0
$042E	$00DB			MOVWF	_strtoint_local_tmp+1
$042F	$0872			MOVF	STACK_0+2, 0
$0430	$00DC			MOVWF	_strtoint_local_tmp+2
$0431	$0873			MOVF	STACK_0+3, 0
$0432	$00DD			MOVWF	_strtoint_local_tmp+3
;conv.ppas,376 :: 		
$0433	$0AD4			INCF	_strtoint_local_i, 1
$0434	$1903			BTFSC	STATUS, Z
$0435	$0AD5			INCF	_strtoint_local_i+1, 1
;conv.ppas,377 :: 		
$0436	$2C15			GOTO	conv_L_186
$0437	$	conv_L_187:
;conv.ppas,380 :: 		
$0437	$085A			MOVF	_strtoint_local_tmp, 0
$0438	$00D2			MOVWF	_strtoint_local_result
$0439	$085B			MOVF	_strtoint_local_tmp+1, 0
$043A	$00D3			MOVWF	_strtoint_local_result+1
;conv.ppas,382 :: 		
$043B	$3000			MOVLW	0
$043C	$0659			XORWF	_strtoint_local_negative+1, 0
$043D	$1D03			BTFSS	STATUS, Z
$043E	$2C41			GOTO	L_StrToInt_21
$043F	$30FF			MOVLW	255
$0440	$0658			XORWF	_strtoint_local_negative, 0
$0441	$	L_StrToInt_21:
$0441	$1D03			BTFSS	STATUS, Z
$0442	$2C4B			GOTO	conv_L_191
$0443	$	conv_L_190:
;conv.ppas,383 :: 		
$0443	$0852			MOVF	_strtoint_local_result, 0
$0444	$3C00			SUBLW	0
$0445	$00D2			MOVWF	_strtoint_local_result
$0446	$0853			MOVF	_strtoint_local_result+1, 0
$0447	$1C03			BTFSS	STATUS, C
$0448	$3F01			ADDLW	1
$0449	$01D3			CLRF	_strtoint_local_result+1
$044A	$02D3			SUBWF	_strtoint_local_result+1, 1
$044B	$	conv_L_191:
$044B	$	conv_L_192:
$044B	$	conv_L_170:
;conv.ppas,384 :: 		
$044B	$0852			MOVF	_strtoint_local_result, 0
$044C	$00F0			MOVWF	STACK_0
$044D	$0853			MOVF	_strtoint_local_result+1, 0
$044E	$00F1			MOVWF	STACK_0+1
$044F	$0008			RETURN
$058D	$	_envia:
;Pic1.pbas,9 :: 		sub procedure envia
;Pic1.pbas,10 :: 		if priorit = 1 then
$058D	$3000			MOVLW	0
$058E	$1303			BCF	STATUS, RP1
$058F	$1283			BCF	STATUS, RP0
$0590	$0622			XORWF	_priorit+1, 0
$0591	$1D03			BTFSS	STATUS, Z
$0592	$2D95			GOTO	L_envia_0
$0593	$3001			MOVLW	1
$0594	$0621			XORWF	_priorit, 0
$0595	$	L_envia_0:
$0595	$1D03			BTFSS	STATUS, Z
$0596	$2DB3			GOTO	Pic1_L_2
$0597	$	Pic1_L_1:
;Pic1.pbas,11 :: 		intToStr(incN, txt)
$0597	$0823			MOVF	_incn, 0
$0598	$00DE			MOVWF	FARG_IntToStr
$0599	$0824			MOVF	_incn+1, 0
$059A	$00DF			MOVWF	FARG_IntToStr+1
$059B	$3025			MOVLW	_txt
$059C	$00E0			MOVWF	FARG_IntToStr+2
$059D	$2450			CALL	_inttostr
;Pic1.pbas,12 :: 		Usart_Write_Text("1")
$059E	$3031			MOVLW	49
$059F	$00D1			MOVWF	?envia_Local_Text+0
$05A0	$01D2			CLRF	?envia_Local_Text+1
$05A1	$3051			MOVLW	?envia_Local_Text
$05A2	$00DE			MOVWF	FARG_Usart_Write_Text
$05A3	$158A			BSF	PCLATH, 3
$05A4	$2000			CALL	_usart_write_text
$05A5	$118A			BCF	PCLATH, 3
;Pic1.pbas,13 :: 		Usart_Write_Text(txt)
$05A6	$3025			MOVLW	_txt
$05A7	$00DE			MOVWF	FARG_Usart_Write_Text
$05A8	$158A			BSF	PCLATH, 3
$05A9	$2000			CALL	_usart_write_text
$05AA	$118A			BCF	PCLATH, 3
;Pic1.pbas,14 :: 		Usart_Write_Text("/")
$05AB	$302F			MOVLW	47
$05AC	$00D1			MOVWF	?envia_Local_Text+0
$05AD	$01D2			CLRF	?envia_Local_Text+1
$05AE	$3051			MOVLW	?envia_Local_Text
$05AF	$00DE			MOVWF	FARG_Usart_Write_Text
$05B0	$158A			BSF	PCLATH, 3
$05B1	$2000			CALL	_usart_write_text
$05B2	$118A			BCF	PCLATH, 3
$05B3	$	Pic1_L_2:
;Pic1.pbas,15 :: 		end if
$05B3	$	Pic1_L_3:
;Pic1.pbas,16 :: 		if priorit = 2 then
$05B3	$3000			MOVLW	0
$05B4	$0622			XORWF	_priorit+1, 0
$05B5	$1D03			BTFSS	STATUS, Z
$05B6	$2DB9			GOTO	L_envia_1
$05B7	$3002			MOVLW	2
$05B8	$0621			XORWF	_priorit, 0
$05B9	$	L_envia_1:
$05B9	$1D03			BTFSS	STATUS, Z
$05BA	$2DD7			GOTO	Pic1_L_5
$05BB	$	Pic1_L_4:
;Pic1.pbas,17 :: 		intToStr(incP, txt)
$05BB	$082C			MOVF	_incp, 0
$05BC	$00DE			MOVWF	FARG_IntToStr
$05BD	$082D			MOVF	_incp+1, 0
$05BE	$00DF			MOVWF	FARG_IntToStr+1
$05BF	$3025			MOVLW	_txt
$05C0	$00E0			MOVWF	FARG_IntToStr+2
$05C1	$2450			CALL	_inttostr
;Pic1.pbas,18 :: 		Usart_Write_Text("2")
$05C2	$3032			MOVLW	50
$05C3	$00D1			MOVWF	?envia_Local_Text+0
$05C4	$01D2			CLRF	?envia_Local_Text+1
$05C5	$3051			MOVLW	?envia_Local_Text
$05C6	$00DE			MOVWF	FARG_Usart_Write_Text
$05C7	$158A			BSF	PCLATH, 3
$05C8	$2000			CALL	_usart_write_text
$05C9	$118A			BCF	PCLATH, 3
;Pic1.pbas,19 :: 		Usart_Write_Text(txt)
$05CA	$3025			MOVLW	_txt
$05CB	$00DE			MOVWF	FARG_Usart_Write_Text
$05CC	$158A			BSF	PCLATH, 3
$05CD	$2000			CALL	_usart_write_text
$05CE	$118A			BCF	PCLATH, 3
;Pic1.pbas,20 :: 		Usart_Write_Text("/")
$05CF	$302F			MOVLW	47
$05D0	$00D1			MOVWF	?envia_Local_Text+0
$05D1	$01D2			CLRF	?envia_Local_Text+1
$05D2	$3051			MOVLW	?envia_Local_Text
$05D3	$00DE			MOVWF	FARG_Usart_Write_Text
$05D4	$158A			BSF	PCLATH, 3
$05D5	$2000			CALL	_usart_write_text
$05D6	$118A			BCF	PCLATH, 3
$05D7	$	Pic1_L_5:
;Pic1.pbas,21 :: 		end if
$05D7	$	Pic1_L_6:
$05D7	$	Pic1_L_0:
$05D7	$0008			RETURN
$0816	$	_usart_init:
;USART_b75.ppas,22 :: 		
;USART_b75.ppas,24 :: 		
$0816	$	USART_b75_L_1:
$0816	$1303			BCF	STATUS, RP1
$0817	$1683			BSF	STATUS, RP0
$0818	$1698			BSF	TXSTA, 5
$0819	$	USART_b75_L_2:
;USART_b75.ppas,25 :: 		
$0819	$3090			MOVLW	144
$081A	$1283			BCF	STATUS, RP0
$081B	$0098			MOVWF	RCSTA
;USART_b75.ppas,31 :: 		
$081C	$	USART_b75_L_3:
$081C	$1683			BSF	STATUS, RP0
$081D	$1686			BSF	TRISB, 5
$081E	$	USART_b75_L_4:
;USART_b75.ppas,32 :: 		
$081E	$	USART_b75_L_5:
$081E	$1786			BSF	TRISB, 7
$081F	$	USART_b75_L_6:
;USART_b75.ppas,35 :: 		
$081F	$	USART_b75_L_8:
$081F	$1283			BCF	STATUS, RP0
$0820	$080C			MOVF	PIR1, 0
$0821	$00F1			MOVWF	STACK_1
$0822	$3000			MOVLW	0
$0823	$1AF1			BTFSC	STACK_1, 5
$0824	$3001			MOVLW	1
$0825	$00F1			MOVWF	STACK_1
$0826	$0871			MOVF	STACK_1, 0
$0827	$3A01			XORLW	1
$0828	$1903			BTFSC	STATUS, Z
$0829	$281F			GOTO	USART_b75_L_8
;USART_b75.ppas,36 :: 		
$082A	$	USART_b75_L_9:
$082A	$	USART_b75_L_0:
;USART_b75.ppas,37 :: 		
$082A	$0008			RETURN
$0679	$	_mul_16x16_s:
$0679	$1303			BCF	STATUS, RP1
$067A	$1283			BCF	STATUS, RP0
;math.ppas,203 :: 		
;math.ppas,205 :: 		
$067B	$01FB			CLRF	STACK_11
;math.ppas,206 :: 		
$067C	$01FA			CLRF	STACK_10
;math.ppas,207 :: 		
$067D	$01F9			CLRF	STACK_9
;math.ppas,208 :: 		
$067E	$3080			MOVLW	128
;math.ppas,210 :: 		
$067F	$00F8			MOVWF	STACK_8
;math.ppas,212 :: 		
$0680	$01FD			CLRF	STACK_13
;math.ppas,213 :: 		
$0681	$1FF1			BTFSS	STACK_1, 7
;math.ppas,214 :: 		
$0682	$2E89			GOTO	$+7
;math.ppas,215 :: 		
$0683	$09F1			COMF	STACK_1, F
;math.ppas,216 :: 		
$0684	$09F0			COMF	STACK_0, F
;math.ppas,217 :: 		
$0685	$0AF0			INCF	STACK_0, F
;math.ppas,218 :: 		
$0686	$1903			BTFSC	STATUS, Z
;math.ppas,219 :: 		
$0687	$0AF1			INCF	STACK_1, F
;math.ppas,221 :: 		
$0688	$0AFD			INCF	STACK_13, F
;math.ppas,222 :: 		
$0689	$1FF5			BTFSS	STACK_5, 7
;math.ppas,223 :: 		
$068A	$2E91			GOTO	$+7
;math.ppas,224 :: 		
$068B	$09F5			COMF	STACK_5, F
;math.ppas,225 :: 		
$068C	$09F4			COMF	STACK_4, F
;math.ppas,226 :: 		
$068D	$0AF4			INCF	STACK_4, F
;math.ppas,227 :: 		
$068E	$1903			BTFSC	STATUS, Z
;math.ppas,228 :: 		
$068F	$0AF5			INCF	STACK_5, F
;math.ppas,230 :: 		
$0690	$0AFD			INCF	STACK_13, F
;math.ppas,231 :: 		
$0691	$0CF1			RRF	STACK_1, F
;math.ppas,233 :: 		
$0692	$0CF0			RRF	STACK_0, F
;math.ppas,234 :: 		
$0693	$1C03			BTFSS	STATUS, C
;math.ppas,235 :: 		
$0694	$2E9E			GOTO	$+10
;math.ppas,236 :: 		
$0695	$0874			MOVF	STACK_4, W
;math.ppas,238 :: 		
$0696	$07F9			ADDWF	STACK_9, F
;math.ppas,239 :: 		
$0697	$0875			MOVF	STACK_5, W
;math.ppas,240 :: 		
$0698	$1803			BTFSC	STATUS, C
;math.ppas,241 :: 		
$0699	$0F75			INCFSZ	STACK_5, W
;math.ppas,242 :: 		
$069A	$07FA			ADDWF	STACK_10, F
;math.ppas,243 :: 		
$069B	$1803			BTFSC	STATUS, C
;math.ppas,244 :: 		
$069C	$0AFB			INCF	STACK_11, F
;math.ppas,246 :: 		
$069D	$1003			BCF	STATUS, C
;math.ppas,247 :: 		
$069E	$1FF0			BTFSS	STACK_0, 7
;math.ppas,248 :: 		
$069F	$2EA6			GOTO	$+7
;math.ppas,249 :: 		
$06A0	$0874			MOVF	STACK_4, W
;math.ppas,250 :: 		
$06A1	$07FA			ADDWF	STACK_10, F
;math.ppas,251 :: 		
$06A2	$1803			BTFSC	STATUS, C
;math.ppas,252 :: 		
$06A3	$0AFB			INCF	STACK_11, F
;math.ppas,253 :: 		
$06A4	$0875			MOVF	STACK_5, W
;math.ppas,255 :: 		
$06A5	$07FB			ADDWF	STACK_11, F
;math.ppas,256 :: 		
$06A6	$0CFB			RRF	STACK_11, F
;math.ppas,257 :: 		
$06A7	$0CFA			RRF	STACK_10, F
;math.ppas,258 :: 		
$06A8	$0CF9			RRF	STACK_9, F
;math.ppas,260 :: 		
$06A9	$0CF8			RRF	STACK_8, F
;math.ppas,261 :: 		
$06AA	$1C03			BTFSS	STATUS, C
;math.ppas,262 :: 		
$06AB	$2E91			GOTO	$-26
;math.ppas,263 :: 		
$06AC	$1C7D			BTFSS	STACK_13, 0
;math.ppas,265 :: 		
$06AD	$2EB9			GOTO	$+12
;math.ppas,266 :: 		
$06AE	$09FB			COMF	STACK_11, F
;math.ppas,267 :: 		
$06AF	$09FA			COMF	STACK_10, F
;math.ppas,268 :: 		
$06B0	$09F9			COMF	STACK_9, F
;math.ppas,270 :: 		
$06B1	$09F8			COMF	STACK_8, F
;math.ppas,271 :: 		
$06B2	$0AF8			INCF	STACK_8, F
;math.ppas,272 :: 		
$06B3	$1903			BTFSC	STATUS, Z
;math.ppas,273 :: 		
$06B4	$0AF9			INCF	STACK_9, F
;math.ppas,274 :: 		
$06B5	$1903			BTFSC	STATUS, Z
;math.ppas,275 :: 		
$06B6	$0AFA			INCF	STACK_10, F
;math.ppas,276 :: 		
$06B7	$1903			BTFSC	STATUS, Z
;math.ppas,278 :: 		
$06B8	$0AFB			INCF	STACK_11, F
;math.ppas,279 :: 		
$06B9	$087B			MOVF	STACK_11, W
;math.ppas,280 :: 		
$06BA	$00F3			MOVWF	STACK_3
;math.ppas,281 :: 		
$06BB	$087A			MOVF	STACK_10, W
;math.ppas,282 :: 		
$06BC	$00F2			MOVWF	STACK_2
;math.ppas,283 :: 		
$06BD	$0879			MOVF	STACK_9, W
;math.ppas,284 :: 		
$06BE	$00F1			MOVWF	STACK_1
;math.ppas,285 :: 		
$06BF	$0878			MOVF	STACK_8, W
;math.ppas,286 :: 		
$06C0	$00F0			MOVWF	STACK_0
;math.ppas,287 :: 		
$06C1	$	math_L_5:
;math.ppas,288 :: 		
$06C1	$0008			RETURN
$0004	$	_main:
;Pic1.pbas,24 :: 		main:
$0004	$	_main_main:
;Pic1.pbas,25 :: 		TRISA=%11111111
$0004	$30FF			MOVLW	255
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0085			MOVWF	TRISA
;Pic1.pbas,26 :: 		TRISB=%01101111
$0008	$306F			MOVLW	111
$0009	$0086			MOVWF	TRISB
;Pic1.pbas,27 :: 		TRISC=%00000000
$000A	$0187			CLRF	TRISC, 1
;Pic1.pbas,28 :: 		INTCON=%00000000
$000B	$018B			CLRF	INTCON, 1
;Pic1.pbas,29 :: 		ANSEL=%00000000
$000C	$1703			BSF	STATUS, RP1
$000D	$1283			BCF	STATUS, RP0
$000E	$019E			CLRF	ANSEL, 1
;Pic1.pbas,30 :: 		ANSELH=%00000000
$000F	$019F			CLRF	ANSELH, 1
;Pic1.pbas,31 :: 		PORTC=0
$0010	$1303			BCF	STATUS, RP1
$0011	$0187			CLRF	PORTC, 1
;Pic1.pbas,32 :: 		Usart_Init(9600)
$0012	$3019			MOVLW	25
$0013	$1683			BSF	STATUS, RP0
$0014	$0099			MOVWF	SPBRG
$0015	$1518			BSF	TXSTA, BRGH
$0016	$158A			BSF	PCLATH, 3
$0017	$2016			CALL	_usart_init
$0018	$118A			BCF	PCLATH, 3
;Pic1.pbas,34 :: 		b0=false
$0019	$01AE			CLRF	_b0, 1
;Pic1.pbas,35 :: 		b1=false
$001A	$01AF			CLRF	_b1, 1
;Pic1.pbas,36 :: 		b2=false
$001B	$01B0			CLRF	_b2, 1
;Pic1.pbas,37 :: 		b3=false
$001C	$01B1			CLRF	_b3, 1
;Pic1.pbas,38 :: 		b4=false
$001D	$01B2			CLRF	_b4, 1
;Pic1.pbas,39 :: 		b5=false
$001E	$01B3			CLRF	_b5, 1
;Pic1.pbas,40 :: 		priorit=1
$001F	$3001			MOVLW	1
$0020	$00A1			MOVWF	_priorit
$0021	$01A2			CLRF	_priorit+1
;Pic1.pbas,41 :: 		incP=0
$0022	$01AC			CLRF	_incp
$0023	$01AD			CLRF	_incp+1
;Pic1.pbas,42 :: 		incN=0
$0024	$01A3			CLRF	_incn
$0025	$01A4			CLRF	_incn+1
;Pic1.pbas,44 :: 		executa:
$0026	$	_main_executa:
;Pic1.pbas,46 :: 		if USART_Data_Ready() <> 0 then
$0026	$158A			BSF	PCLATH, 3
$0027	$2050			CALL	_usart_data_ready
$0028	$118A			BCF	PCLATH, 3
$0029	$0870			MOVF	STACK_0, 0
$002A	$3A00			XORLW	0
$002B	$1903			BTFSC	STATUS, Z
$002C	$2844			GOTO	Pic1_L_9
$002D	$	Pic1_L_8:
;Pic1.pbas,47 :: 		Usart_Read_Text(recebe, "/")
$002D	$3034			MOVLW	_recebe
$002E	$00D1			MOVWF	FARG_Usart_Read_Text
$002F	$302F			MOVLW	47
$0030	$00C7			MOVWF	?main_Local_Text+0
$0031	$01C8			CLRF	?main_Local_Text+1
$0032	$3047			MOVLW	?main_Local_Text
$0033	$00D2			MOVWF	FARG_Usart_Read_Text+1
$0034	$2632			CALL	_usart_read_text
;Pic1.pbas,48 :: 		valor = StrToInt(recebe)
$0035	$3034			MOVLW	_recebe
$0036	$00D1			MOVWF	FARG_StrToInt
$0037	$238E			CALL	_strtoint
$0038	$0870			MOVF	STACK_0, 0
$0039	$00BB			MOVWF	_valor
$003A	$0871			MOVF	STACK_0+1, 0
$003B	$00BC			MOVWF	_valor+1
;Pic1.pbas,49 :: 		Usart_Write_Text("/")
$003C	$302F			MOVLW	47
$003D	$00C7			MOVWF	?main_Local_Text+0
$003E	$01C8			CLRF	?main_Local_Text+1
$003F	$3047			MOVLW	?main_Local_Text
$0040	$00DE			MOVWF	FARG_Usart_Write_Text
$0041	$158A			BSF	PCLATH, 3
$0042	$2000			CALL	_usart_write_text
$0043	$118A			BCF	PCLATH, 3
$0044	$	Pic1_L_9:
;Pic1.pbas,50 :: 		end if
$0044	$	Pic1_L_10:
;Pic1.pbas,53 :: 		if testbit(portA,0) = 1 then
$0044	$3001			MOVLW	1
$0045	$0505			ANDWF	PORTA, 0
$0046	$00F2			MOVWF	STACK_2
$0047	$0872			MOVF	STACK_2, 0
$0048	$3A01			XORLW	1
$0049	$1D03			BTFSS	STATUS, Z
$004A	$2860			GOTO	Pic1_L_12
$004B	$	Pic1_L_11:
;Pic1.pbas,54 :: 		if b0 = false then
$004B	$082E			MOVF	_b0, 0
$004C	$3A00			XORLW	0
$004D	$1D03			BTFSS	STATUS, Z
$004E	$2860			GOTO	Pic1_L_15
$004F	$	Pic1_L_14:
;Pic1.pbas,55 :: 		b0 = true
$004F	$30FF			MOVLW	255
$0050	$00AE			MOVWF	_b0
;Pic1.pbas,56 :: 		if priorit = 1 then
$0051	$3000			MOVLW	0
$0052	$0622			XORWF	_priorit+1, 0
$0053	$1D03			BTFSS	STATUS, Z
$0054	$2857			GOTO	L_main_2
$0055	$3001			MOVLW	1
$0056	$0621			XORWF	_priorit, 0
$0057	$	L_main_2:
$0057	$1D03			BTFSS	STATUS, Z
$0058	$285D			GOTO	Pic1_L_18
$0059	$	Pic1_L_17:
;Pic1.pbas,57 :: 		incN = incN + 1
$0059	$0AA3			INCF	_incn, 1
$005A	$1903			BTFSC	STATUS, Z
$005B	$0AA4			INCF	_incn+1, 1
$005C	$2860			GOTO	Pic1_L_19
;Pic1.pbas,58 :: 		else
$005D	$	Pic1_L_18:
;Pic1.pbas,59 :: 		incP = incP + 1
$005D	$0AAC			INCF	_incp, 1
$005E	$1903			BTFSC	STATUS, Z
$005F	$0AAD			INCF	_incp+1, 1
;Pic1.pbas,60 :: 		end if
$0060	$	Pic1_L_19:
$0060	$	Pic1_L_15:
;Pic1.pbas,61 :: 		end if
$0060	$	Pic1_L_16:
$0060	$	Pic1_L_12:
;Pic1.pbas,62 :: 		end if
$0060	$	Pic1_L_13:
;Pic1.pbas,63 :: 		if testbit(portA,0) = 0 then
$0060	$3001			MOVLW	1
$0061	$0505			ANDWF	PORTA, 0
$0062	$00F2			MOVWF	STACK_2
$0063	$0872			MOVF	STACK_2, 0
$0064	$3A00			XORLW	0
$0065	$1D03			BTFSS	STATUS, Z
$0066	$286C			GOTO	Pic1_L_21
$0067	$	Pic1_L_20:
;Pic1.pbas,64 :: 		if b0 = true then
$0067	$082E			MOVF	_b0, 0
$0068	$3AFF			XORLW	255
$0069	$1D03			BTFSS	STATUS, Z
$006A	$286C			GOTO	Pic1_L_24
$006B	$	Pic1_L_23:
;Pic1.pbas,65 :: 		b0 = false
$006B	$01AE			CLRF	_b0, 1
$006C	$	Pic1_L_24:
;Pic1.pbas,66 :: 		end if
$006C	$	Pic1_L_25:
$006C	$	Pic1_L_21:
;Pic1.pbas,67 :: 		end if
$006C	$	Pic1_L_22:
;Pic1.pbas,70 :: 		if testbit(portA,1) = 1 then
$006C	$3000			MOVLW	0
$006D	$1885			BTFSC	PORTA, 1
$006E	$3001			MOVLW	1
$006F	$00F2			MOVWF	STACK_2
$0070	$0872			MOVF	STACK_2, 0
$0071	$3A01			XORLW	1
$0072	$1D03			BTFSS	STATUS, Z
$0073	$288B			GOTO	Pic1_L_27
$0074	$	Pic1_L_26:
;Pic1.pbas,71 :: 		if b1 = false then
$0074	$082F			MOVF	_b1, 0
$0075	$3A00			XORLW	0
$0076	$1D03			BTFSS	STATUS, Z
$0077	$288B			GOTO	Pic1_L_30
$0078	$	Pic1_L_29:
;Pic1.pbas,72 :: 		b1 = true
$0078	$30FF			MOVLW	255
$0079	$00AF			MOVWF	_b1
;Pic1.pbas,73 :: 		if priorit = 1 then
$007A	$3000			MOVLW	0
$007B	$0622			XORWF	_priorit+1, 0
$007C	$1D03			BTFSS	STATUS, Z
$007D	$2880			GOTO	L_main_3
$007E	$3001			MOVLW	1
$007F	$0621			XORWF	_priorit, 0
$0080	$	L_main_3:
$0080	$1D03			BTFSS	STATUS, Z
$0081	$2887			GOTO	Pic1_L_33
$0082	$	Pic1_L_32:
;Pic1.pbas,74 :: 		incN = incN - 1
$0082	$3001			MOVLW	1
$0083	$02A3			SUBWF	_incn, 1
$0084	$1C03			BTFSS	STATUS, C
$0085	$03A4			DECF	_incn+1, 1
$0086	$288B			GOTO	Pic1_L_34
;Pic1.pbas,75 :: 		else
$0087	$	Pic1_L_33:
;Pic1.pbas,76 :: 		incP = incP - 1
$0087	$3001			MOVLW	1
$0088	$02AC			SUBWF	_incp, 1
$0089	$1C03			BTFSS	STATUS, C
$008A	$03AD			DECF	_incp+1, 1
;Pic1.pbas,77 :: 		end if
$008B	$	Pic1_L_34:
$008B	$	Pic1_L_30:
;Pic1.pbas,78 :: 		end if
$008B	$	Pic1_L_31:
$008B	$	Pic1_L_27:
;Pic1.pbas,79 :: 		end if
$008B	$	Pic1_L_28:
;Pic1.pbas,80 :: 		if testbit(portA,1) = 0 then
$008B	$3000			MOVLW	0
$008C	$1885			BTFSC	PORTA, 1
$008D	$3001			MOVLW	1
$008E	$00F2			MOVWF	STACK_2
$008F	$0872			MOVF	STACK_2, 0
$0090	$3A00			XORLW	0
$0091	$1D03			BTFSS	STATUS, Z
$0092	$2898			GOTO	Pic1_L_36
$0093	$	Pic1_L_35:
;Pic1.pbas,81 :: 		if b1 = true then
$0093	$082F			MOVF	_b1, 0
$0094	$3AFF			XORLW	255
$0095	$1D03			BTFSS	STATUS, Z
$0096	$2898			GOTO	Pic1_L_39
$0097	$	Pic1_L_38:
;Pic1.pbas,82 :: 		b1 = false
$0097	$01AF			CLRF	_b1, 1
$0098	$	Pic1_L_39:
;Pic1.pbas,83 :: 		end if
$0098	$	Pic1_L_40:
$0098	$	Pic1_L_36:
;Pic1.pbas,84 :: 		end if
$0098	$	Pic1_L_37:
;Pic1.pbas,87 :: 		if testbit(portA,2) = 1 then
$0098	$3000			MOVLW	0
$0099	$1905			BTFSC	PORTA, 2
$009A	$3001			MOVLW	1
$009B	$00F2			MOVWF	STACK_2
$009C	$0872			MOVF	STACK_2, 0
$009D	$3A01			XORLW	1
$009E	$1D03			BTFSS	STATUS, Z
$009F	$28AA			GOTO	Pic1_L_42
$00A0	$	Pic1_L_41:
;Pic1.pbas,88 :: 		if b2 = false then
$00A0	$0830			MOVF	_b2, 0
$00A1	$3A00			XORLW	0
$00A2	$1D03			BTFSS	STATUS, Z
$00A3	$28AA			GOTO	Pic1_L_45
$00A4	$	Pic1_L_44:
;Pic1.pbas,89 :: 		b2 = true
$00A4	$30FF			MOVLW	255
$00A5	$00B0			MOVWF	_b2
;Pic1.pbas,90 :: 		incN = 0
$00A6	$01A3			CLRF	_incn
$00A7	$01A4			CLRF	_incn+1
;Pic1.pbas,91 :: 		incP = 0
$00A8	$01AC			CLRF	_incp
$00A9	$01AD			CLRF	_incp+1
$00AA	$	Pic1_L_45:
;Pic1.pbas,92 :: 		end if
$00AA	$	Pic1_L_46:
$00AA	$	Pic1_L_42:
;Pic1.pbas,93 :: 		end if
$00AA	$	Pic1_L_43:
;Pic1.pbas,94 :: 		if testbit(portA,2) = 0 then
$00AA	$3000			MOVLW	0
$00AB	$1905			BTFSC	PORTA, 2
$00AC	$3001			MOVLW	1
$00AD	$00F2			MOVWF	STACK_2
$00AE	$0872			MOVF	STACK_2, 0
$00AF	$3A00			XORLW	0
$00B0	$1D03			BTFSS	STATUS, Z
$00B1	$28B7			GOTO	Pic1_L_48
$00B2	$	Pic1_L_47:
;Pic1.pbas,95 :: 		if b2 = true then
$00B2	$0830			MOVF	_b2, 0
$00B3	$3AFF			XORLW	255
$00B4	$1D03			BTFSS	STATUS, Z
$00B5	$28B7			GOTO	Pic1_L_51
$00B6	$	Pic1_L_50:
;Pic1.pbas,96 :: 		b2 = false
$00B6	$01B0			CLRF	_b2, 1
$00B7	$	Pic1_L_51:
;Pic1.pbas,97 :: 		end if
$00B7	$	Pic1_L_52:
$00B7	$	Pic1_L_48:
;Pic1.pbas,98 :: 		end if
$00B7	$	Pic1_L_49:
;Pic1.pbas,101 :: 		if testbit(portA,3) = 1 then
$00B7	$3000			MOVLW	0
$00B8	$1985			BTFSC	PORTA, 3
$00B9	$3001			MOVLW	1
$00BA	$00F2			MOVWF	STACK_2
$00BB	$0872			MOVF	STACK_2, 0
$00BC	$3A01			XORLW	1
$00BD	$1D03			BTFSS	STATUS, Z
$00BE	$28D4			GOTO	Pic1_L_54
$00BF	$	Pic1_L_53:
;Pic1.pbas,102 :: 		if b3 = false then
$00BF	$0831			MOVF	_b3, 0
$00C0	$3A00			XORLW	0
$00C1	$1D03			BTFSS	STATUS, Z
$00C2	$28D4			GOTO	Pic1_L_57
$00C3	$	Pic1_L_56:
;Pic1.pbas,103 :: 		b3 = true
$00C3	$30FF			MOVLW	255
$00C4	$00B1			MOVWF	_b3
;Pic1.pbas,104 :: 		if priorit = 1 then
$00C5	$3000			MOVLW	0
$00C6	$0622			XORWF	_priorit+1, 0
$00C7	$1D03			BTFSS	STATUS, Z
$00C8	$28CB			GOTO	L_main_4
$00C9	$3001			MOVLW	1
$00CA	$0621			XORWF	_priorit, 0
$00CB	$	L_main_4:
$00CB	$1D03			BTFSS	STATUS, Z
$00CC	$28D1			GOTO	Pic1_L_60
$00CD	$	Pic1_L_59:
;Pic1.pbas,105 :: 		priorit = 2
$00CD	$3002			MOVLW	2
$00CE	$00A1			MOVWF	_priorit
$00CF	$01A2			CLRF	_priorit+1
$00D0	$28D4			GOTO	Pic1_L_61
;Pic1.pbas,106 :: 		else
$00D1	$	Pic1_L_60:
;Pic1.pbas,107 :: 		priorit = 1
$00D1	$3001			MOVLW	1
$00D2	$00A1			MOVWF	_priorit
$00D3	$01A2			CLRF	_priorit+1
;Pic1.pbas,108 :: 		end if
$00D4	$	Pic1_L_61:
$00D4	$	Pic1_L_57:
;Pic1.pbas,109 :: 		end if
$00D4	$	Pic1_L_58:
$00D4	$	Pic1_L_54:
;Pic1.pbas,110 :: 		end if
$00D4	$	Pic1_L_55:
;Pic1.pbas,111 :: 		if testbit(portA,3) = 0 then
$00D4	$3000			MOVLW	0
$00D5	$1985			BTFSC	PORTA, 3
$00D6	$3001			MOVLW	1
$00D7	$00F2			MOVWF	STACK_2
$00D8	$0872			MOVF	STACK_2, 0
$00D9	$3A00			XORLW	0
$00DA	$1D03			BTFSS	STATUS, Z
$00DB	$28E1			GOTO	Pic1_L_63
$00DC	$	Pic1_L_62:
;Pic1.pbas,112 :: 		if b3 = true then
$00DC	$0831			MOVF	_b3, 0
$00DD	$3AFF			XORLW	255
$00DE	$1D03			BTFSS	STATUS, Z
$00DF	$28E1			GOTO	Pic1_L_66
$00E0	$	Pic1_L_65:
;Pic1.pbas,113 :: 		b3 = false
$00E0	$01B1			CLRF	_b3, 1
$00E1	$	Pic1_L_66:
;Pic1.pbas,114 :: 		end if
$00E1	$	Pic1_L_67:
$00E1	$	Pic1_L_63:
;Pic1.pbas,115 :: 		end if
$00E1	$	Pic1_L_64:
;Pic1.pbas,118 :: 		if testbit(portA,4) = 1 then
$00E1	$3000			MOVLW	0
$00E2	$1A05			BTFSC	PORTA, 4
$00E3	$3001			MOVLW	1
$00E4	$00F2			MOVWF	STACK_2
$00E5	$0872			MOVF	STACK_2, 0
$00E6	$3A01			XORLW	1
$00E7	$1D03			BTFSS	STATUS, Z
$00E8	$28FA			GOTO	Pic1_L_69
$00E9	$	Pic1_L_68:
;Pic1.pbas,119 :: 		if b4 = false then
$00E9	$0832			MOVF	_b4, 0
$00EA	$3A00			XORLW	0
$00EB	$1D03			BTFSS	STATUS, Z
$00EC	$28FA			GOTO	Pic1_L_72
$00ED	$	Pic1_L_71:
;Pic1.pbas,120 :: 		b4 = true
$00ED	$30FF			MOVLW	255
$00EE	$00B2			MOVWF	_b4
;Pic1.pbas,121 :: 		if portB.4 = 0 then
$00EF	$3000			MOVLW	0
$00F0	$1A06			BTFSC	PORTB, 4
$00F1	$3001			MOVLW	1
$00F2	$00F2			MOVWF	STACK_2
$00F3	$0872			MOVF	STACK_2, 0
$00F4	$3A00			XORLW	0
$00F5	$1D03			BTFSS	STATUS, Z
$00F6	$28F9			GOTO	Pic1_L_75
$00F7	$	Pic1_L_74:
;Pic1.pbas,122 :: 		portB.4 = 1
$00F7	$	Pic1_L_77:
$00F7	$1606			BSF	PORTB, 4
$00F8	$	Pic1_L_78:
$00F8	$28FA			GOTO	Pic1_L_76
;Pic1.pbas,123 :: 		else
$00F9	$	Pic1_L_75:
;Pic1.pbas,124 :: 		portB.4 = 0
$00F9	$1206			BCF	PORTB, 4
$00FA	$	Pic1_L_80:
;Pic1.pbas,125 :: 		end if
$00FA	$	Pic1_L_76:
$00FA	$	Pic1_L_72:
;Pic1.pbas,126 :: 		end if
$00FA	$	Pic1_L_73:
$00FA	$	Pic1_L_69:
;Pic1.pbas,127 :: 		end if
$00FA	$	Pic1_L_70:
;Pic1.pbas,128 :: 		if testbit(portA,4) = 0 then
$00FA	$3000			MOVLW	0
$00FB	$1A05			BTFSC	PORTA, 4
$00FC	$3001			MOVLW	1
$00FD	$00F2			MOVWF	STACK_2
$00FE	$0872			MOVF	STACK_2, 0
$00FF	$3A00			XORLW	0
$0100	$1D03			BTFSS	STATUS, Z
$0101	$2907			GOTO	Pic1_L_82
$0102	$	Pic1_L_81:
;Pic1.pbas,129 :: 		if b4 = true then
$0102	$0832			MOVF	_b4, 0
$0103	$3AFF			XORLW	255
$0104	$1D03			BTFSS	STATUS, Z
$0105	$2907			GOTO	Pic1_L_85
$0106	$	Pic1_L_84:
;Pic1.pbas,130 :: 		b4 = false
$0106	$01B2			CLRF	_b4, 1
$0107	$	Pic1_L_85:
;Pic1.pbas,131 :: 		end if
$0107	$	Pic1_L_86:
$0107	$	Pic1_L_82:
;Pic1.pbas,132 :: 		end if
$0107	$	Pic1_L_83:
;Pic1.pbas,135 :: 		if testbit(portA,5) = 1 then
$0107	$3000			MOVLW	0
$0108	$1A85			BTFSC	PORTA, 5
$0109	$3001			MOVLW	1
$010A	$00F2			MOVWF	STACK_2
$010B	$0872			MOVF	STACK_2, 0
$010C	$3A01			XORLW	1
$010D	$1D03			BTFSS	STATUS, Z
$010E	$2919			GOTO	Pic1_L_88
$010F	$	Pic1_L_87:
;Pic1.pbas,136 :: 		if b5 = false then
$010F	$0833			MOVF	_b5, 0
$0110	$3A00			XORLW	0
$0111	$1D03			BTFSS	STATUS, Z
$0112	$2919			GOTO	Pic1_L_91
$0113	$	Pic1_L_90:
;Pic1.pbas,137 :: 		b5 = true
$0113	$30FF			MOVLW	255
$0114	$00B3			MOVWF	_b5
;Pic1.pbas,138 :: 		envia
$0115	$258D			CALL	_envia
;Pic1.pbas,139 :: 		i = i + 1
$0116	$0ABD			INCF	_i, 1
$0117	$1903			BTFSC	STATUS, Z
$0118	$0ABE			INCF	_i+1, 1
$0119	$	Pic1_L_91:
;Pic1.pbas,140 :: 		end if
$0119	$	Pic1_L_92:
$0119	$	Pic1_L_88:
;Pic1.pbas,141 :: 		end if
$0119	$	Pic1_L_89:
;Pic1.pbas,142 :: 		if testbit(portA,5) = 0 then
$0119	$3000			MOVLW	0
$011A	$1A85			BTFSC	PORTA, 5
$011B	$3001			MOVLW	1
$011C	$00F2			MOVWF	STACK_2
$011D	$0872			MOVF	STACK_2, 0
$011E	$3A00			XORLW	0
$011F	$1D03			BTFSS	STATUS, Z
$0120	$2922			GOTO	Pic1_L_94
$0121	$	Pic1_L_93:
;Pic1.pbas,143 :: 		b5 = false
$0121	$01B3			CLRF	_b5, 1
$0122	$	Pic1_L_94:
;Pic1.pbas,144 :: 		end if
$0122	$	Pic1_L_95:
;Pic1.pbas,146 :: 		if incN > 999 then
$0122	$3080			MOVLW	128
$0123	$3A03			XORLW	3
$0124	$00F0			MOVWF	STACK_0
$0125	$3080			MOVLW	128
$0126	$0624			XORWF	_incn+1, 0
$0127	$0270			SUBWF	STACK_0, 0
$0128	$1D03			BTFSS	STATUS, Z
$0129	$292C			GOTO	L_main_5
$012A	$0823			MOVF	_incn, 0
$012B	$3CE7			SUBLW	231
$012C	$	L_main_5:
$012C	$1803			BTFSC	STATUS, C
$012D	$2932			GOTO	Pic1_L_97
$012E	$	Pic1_L_96:
;Pic1.pbas,147 :: 		incN = 999
$012E	$30E7			MOVLW	231
$012F	$00A3			MOVWF	_incn
$0130	$3003			MOVLW	3
$0131	$00A4			MOVWF	_incn+1
$0132	$	Pic1_L_97:
;Pic1.pbas,148 :: 		end if
$0132	$	Pic1_L_98:
;Pic1.pbas,149 :: 		if incN < 0 then
$0132	$3080			MOVLW	128
$0133	$0624			XORWF	_incn+1, 0
$0134	$00F0			MOVWF	STACK_0
$0135	$3080			MOVLW	128
$0136	$0270			SUBWF	STACK_0, 0
$0137	$1D03			BTFSS	STATUS, Z
$0138	$293B			GOTO	L_main_6
$0139	$3000			MOVLW	0
$013A	$0223			SUBWF	_incn, 0
$013B	$	L_main_6:
$013B	$1803			BTFSC	STATUS, C
$013C	$293F			GOTO	Pic1_L_100
$013D	$	Pic1_L_99:
;Pic1.pbas,150 :: 		incN = 0
$013D	$01A3			CLRF	_incn
$013E	$01A4			CLRF	_incn+1
$013F	$	Pic1_L_100:
;Pic1.pbas,151 :: 		end if
$013F	$	Pic1_L_101:
;Pic1.pbas,153 :: 		if incP > 999 then
$013F	$3080			MOVLW	128
$0140	$3A03			XORLW	3
$0141	$00F0			MOVWF	STACK_0
$0142	$3080			MOVLW	128
$0143	$062D			XORWF	_incp+1, 0
$0144	$0270			SUBWF	STACK_0, 0
$0145	$1D03			BTFSS	STATUS, Z
$0146	$2949			GOTO	L_main_7
$0147	$082C			MOVF	_incp, 0
$0148	$3CE7			SUBLW	231
$0149	$	L_main_7:
$0149	$1803			BTFSC	STATUS, C
$014A	$294F			GOTO	Pic1_L_103
$014B	$	Pic1_L_102:
;Pic1.pbas,154 :: 		incP = 999
$014B	$30E7			MOVLW	231
$014C	$00AC			MOVWF	_incp
$014D	$3003			MOVLW	3
$014E	$00AD			MOVWF	_incp+1
$014F	$	Pic1_L_103:
;Pic1.pbas,155 :: 		end if
$014F	$	Pic1_L_104:
;Pic1.pbas,156 :: 		if incP < 0 then
$014F	$3080			MOVLW	128
$0150	$062D			XORWF	_incp+1, 0
$0151	$00F0			MOVWF	STACK_0
$0152	$3080			MOVLW	128
$0153	$0270			SUBWF	STACK_0, 0
$0154	$1D03			BTFSS	STATUS, Z
$0155	$2958			GOTO	L_main_8
$0156	$3000			MOVLW	0
$0157	$022C			SUBWF	_incp, 0
$0158	$	L_main_8:
$0158	$1803			BTFSC	STATUS, C
$0159	$295C			GOTO	Pic1_L_106
$015A	$	Pic1_L_105:
;Pic1.pbas,157 :: 		incP = 0
$015A	$01AC			CLRF	_incp
$015B	$01AD			CLRF	_incp+1
$015C	$	Pic1_L_106:
;Pic1.pbas,158 :: 		end if
$015C	$	Pic1_L_107:
;Pic1.pbas,161 :: 		if priorit = 1 then
$015C	$3000			MOVLW	0
$015D	$0622			XORWF	_priorit+1, 0
$015E	$1D03			BTFSS	STATUS, Z
$015F	$2962			GOTO	L_main_9
$0160	$3001			MOVLW	1
$0161	$0621			XORWF	_priorit, 0
$0162	$	L_main_9:
$0162	$1D03			BTFSS	STATUS, Z
$0163	$2969			GOTO	Pic1_L_109
$0164	$	Pic1_L_108:
;Pic1.pbas,162 :: 		valor = incN
$0164	$0823			MOVF	_incn, 0
$0165	$00BB			MOVWF	_valor
$0166	$0824			MOVF	_incn+1, 0
$0167	$00BC			MOVWF	_valor+1
$0168	$296D			GOTO	Pic1_L_110
;Pic1.pbas,163 :: 		else
$0169	$	Pic1_L_109:
;Pic1.pbas,164 :: 		valor = incP
$0169	$082C			MOVF	_incp, 0
$016A	$00BB			MOVWF	_valor
$016B	$082D			MOVF	_incp+1, 0
$016C	$00BC			MOVWF	_valor+1
;Pic1.pbas,165 :: 		end if
$016D	$	Pic1_L_110:
;Pic1.pbas,167 :: 		mil = valor div 1000
$016D	$30E8			MOVLW	232
$016E	$00F4			MOVWF	STACK_4
$016F	$3003			MOVLW	3
$0170	$00F5			MOVWF	STACK_4+1
$0171	$083B			MOVF	_valor, 0
$0172	$00F0			MOVWF	STACK_0
$0173	$083C			MOVF	_valor+1, 0
$0174	$00F1			MOVWF	STACK_0+1
$0175	$25D8			CALL	_div_16x16_s
$0176	$0870			MOVF	STACK_0, 0
$0177	$00CF			MOVWF	FLOC_main+8
$0178	$0871			MOVF	STACK_0+1, 0
$0179	$00D0			MOVWF	FLOC_main+9
$017A	$084F			MOVF	FLOC_main+8, 0
$017B	$00BF			MOVWF	_mil
$017C	$0850			MOVF	FLOC_main+9, 0
$017D	$00C0			MOVWF	_mil+1
;Pic1.pbas,168 :: 		cen = valor div 100 - (mil * 10)
$017E	$3064			MOVLW	100
$017F	$00F4			MOVWF	STACK_4
$0180	$01F5			CLRF	STACK_4+1
$0181	$083B			MOVF	_valor, 0
$0182	$00F0			MOVWF	STACK_0
$0183	$083C			MOVF	_valor+1, 0
$0184	$00F1			MOVWF	STACK_0+1
$0185	$25D8			CALL	_div_16x16_s
$0186	$0870			MOVF	STACK_0, 0
$0187	$00C9			MOVWF	FLOC_main+2
$0188	$0871			MOVF	STACK_0+1, 0
$0189	$00CA			MOVWF	FLOC_main+3
$018A	$084F			MOVF	FLOC_main+8, 0
$018B	$00F0			MOVWF	STACK_0
$018C	$0850			MOVF	FLOC_main+9, 0
$018D	$00F1			MOVWF	STACK_0+1
$018E	$300A			MOVLW	10
$018F	$00F4			MOVWF	STACK_4
$0190	$01F5			CLRF	STACK_4+1
$0191	$2679			CALL	_mul_16x16_s
$0192	$0870			MOVF	STACK_0, 0
$0193	$0249			SUBWF	FLOC_main+2, 0
$0194	$00CD			MOVWF	FLOC_main+6
$0195	$0871			MOVF	STACK_0+1, 0
$0196	$1C03			BTFSS	STATUS, C
$0197	$3F01			ADDLW	1
$0198	$024A			SUBWF	FLOC_main+3, 0
$0199	$00CE			MOVWF	FLOC_main+7
$019A	$084D			MOVF	FLOC_main+6, 0
$019B	$00C1			MOVWF	_cen
$019C	$084E			MOVF	FLOC_main+7, 0
$019D	$00C2			MOVWF	_cen+1
;Pic1.pbas,169 :: 		dez = valor div 10 - (cen * 10) - (mil * 100)
$019E	$300A			MOVLW	10
$019F	$00F4			MOVWF	STACK_4
$01A0	$01F5			CLRF	STACK_4+1
$01A1	$083B			MOVF	_valor, 0
$01A2	$00F0			MOVWF	STACK_0
$01A3	$083C			MOVF	_valor+1, 0
$01A4	$00F1			MOVWF	STACK_0+1
$01A5	$25D8			CALL	_div_16x16_s
$01A6	$0870			MOVF	STACK_0, 0
$01A7	$00C9			MOVWF	FLOC_main+2
$01A8	$0871			MOVF	STACK_0+1, 0
$01A9	$00CA			MOVWF	FLOC_main+3
$01AA	$084D			MOVF	FLOC_main+6, 0
$01AB	$00F0			MOVWF	STACK_0
$01AC	$084E			MOVF	FLOC_main+7, 0
$01AD	$00F1			MOVWF	STACK_0+1
$01AE	$300A			MOVLW	10
$01AF	$00F4			MOVWF	STACK_4
$01B0	$01F5			CLRF	STACK_4+1
$01B1	$2679			CALL	_mul_16x16_s
$01B2	$0870			MOVF	STACK_0, 0
$01B3	$02C9			SUBWF	FLOC_main+2, 1
$01B4	$1C03			BTFSS	STATUS, C
$01B5	$03CA			DECF	FLOC_main+3, 1
$01B6	$0871			MOVF	STACK_0+1, 0
$01B7	$02CA			SUBWF	FLOC_main+3, 1
$01B8	$084F			MOVF	FLOC_main+8, 0
$01B9	$00F0			MOVWF	STACK_0
$01BA	$0850			MOVF	FLOC_main+9, 0
$01BB	$00F1			MOVWF	STACK_0+1
$01BC	$3064			MOVLW	100
$01BD	$00F4			MOVWF	STACK_4
$01BE	$01F5			CLRF	STACK_4+1
$01BF	$2679			CALL	_mul_16x16_s
$01C0	$0870			MOVF	STACK_0, 0
$01C1	$0249			SUBWF	FLOC_main+2, 0
$01C2	$00CB			MOVWF	FLOC_main+4
$01C3	$0871			MOVF	STACK_0+1, 0
$01C4	$1C03			BTFSS	STATUS, C
$01C5	$3F01			ADDLW	1
$01C6	$024A			SUBWF	FLOC_main+3, 0
$01C7	$00CC			MOVWF	FLOC_main+5
$01C8	$084B			MOVF	FLOC_main+4, 0
$01C9	$00C3			MOVWF	_dez
$01CA	$084C			MOVF	FLOC_main+5, 0
$01CB	$00C4			MOVWF	_dez+1
;Pic1.pbas,170 :: 		uni = valor - (dez * 10) - (cen * 100) - (mil * 1000)
$01CC	$084B			MOVF	FLOC_main+4, 0
$01CD	$00F0			MOVWF	STACK_0
$01CE	$084C			MOVF	FLOC_main+5, 0
$01CF	$00F1			MOVWF	STACK_0+1
$01D0	$300A			MOVLW	10
$01D1	$00F4			MOVWF	STACK_4
$01D2	$01F5			CLRF	STACK_4+1
$01D3	$2679			CALL	_mul_16x16_s
$01D4	$0870			MOVF	STACK_0, 0
$01D5	$023B			SUBWF	_valor, 0
$01D6	$00C9			MOVWF	FLOC_main+2
$01D7	$0871			MOVF	STACK_0+1, 0
$01D8	$1C03			BTFSS	STATUS, C
$01D9	$3F01			ADDLW	1
$01DA	$023C			SUBWF	_valor+1, 0
$01DB	$00CA			MOVWF	FLOC_main+3
$01DC	$084D			MOVF	FLOC_main+6, 0
$01DD	$00F0			MOVWF	STACK_0
$01DE	$084E			MOVF	FLOC_main+7, 0
$01DF	$00F1			MOVWF	STACK_0+1
$01E0	$3064			MOVLW	100
$01E1	$00F4			MOVWF	STACK_4
$01E2	$01F5			CLRF	STACK_4+1
$01E3	$2679			CALL	_mul_16x16_s
$01E4	$0870			MOVF	STACK_0, 0
$01E5	$02C9			SUBWF	FLOC_main+2, 1
$01E6	$1C03			BTFSS	STATUS, C
$01E7	$03CA			DECF	FLOC_main+3, 1
$01E8	$0871			MOVF	STACK_0+1, 0
$01E9	$02CA			SUBWF	FLOC_main+3, 1
$01EA	$084F			MOVF	FLOC_main+8, 0
$01EB	$00F0			MOVWF	STACK_0
$01EC	$0850			MOVF	FLOC_main+9, 0
$01ED	$00F1			MOVWF	STACK_0+1
$01EE	$30E8			MOVLW	232
$01EF	$00F4			MOVWF	STACK_4
$01F0	$3003			MOVLW	3
$01F1	$00F5			MOVWF	STACK_4+1
$01F2	$2679			CALL	_mul_16x16_s
$01F3	$0870			MOVF	STACK_0, 0
$01F4	$0249			SUBWF	FLOC_main+2, 0
$01F5	$00F0			MOVWF	STACK_0
$01F6	$0871			MOVF	STACK_0+1, 0
$01F7	$1C03			BTFSS	STATUS, C
$01F8	$3F01			ADDLW	1
$01F9	$024A			SUBWF	FLOC_main+3, 0
$01FA	$00F1			MOVWF	STACK_0+1
$01FB	$0870			MOVF	STACK_0, 0
$01FC	$00C5			MOVWF	_uni
$01FD	$0871			MOVF	STACK_0+1, 0
$01FE	$00C6			MOVWF	_uni+1
;Pic1.pbas,172 :: 		PORTC = uni + 16
$01FF	$3010			MOVLW	16
$0200	$07F0			ADDWF	STACK_0, 1
$0201	$1803			BTFSC	STATUS, C
$0202	$0AF1			INCF	STACK_0+1, 1
$0203	$0870			MOVF	STACK_0, 0
$0204	$0087			MOVWF	PORTC
;Pic1.pbas,173 :: 		delay_ms(3)
$0205	$3004			MOVLW	4
$0206	$00FB			MOVWF	STACK_11
$0207	$30FF			MOVLW	255
$0208	$00FA			MOVWF	STACK_10
$0209	$0BFB			DECFSZ	STACK_11, F
$020A	$2A0C			GOTO	$+2
$020B	$2A0F			GOTO	$+4
$020C	$0BFA			DECFSZ	STACK_10, F
$020D	$2A0C			GOTO	$-1
$020E	$2A09			GOTO	$-5
$020F	$30E2			MOVLW	226
$0210	$00FA			MOVWF	STACK_10
$0211	$0BFA			DECFSZ	STACK_10, F
$0212	$2A11			GOTO	$-1
;Pic1.pbas,174 :: 		PORTC = dez + 32
$0213	$3020			MOVLW	32
$0214	$074B			ADDWF	FLOC_main+4, 0
$0215	$00F0			MOVWF	STACK_0
$0216	$084C			MOVF	FLOC_main+5, 0
$0217	$1803			BTFSC	STATUS, C
$0218	$3F01			ADDLW	1
$0219	$00F1			MOVWF	STACK_0+1
$021A	$3000			MOVLW	0
$021B	$07F1			ADDWF	STACK_0+1, 1
$021C	$0870			MOVF	STACK_0, 0
$021D	$0087			MOVWF	PORTC
;Pic1.pbas,175 :: 		delay_ms(3)
$021E	$3004			MOVLW	4
$021F	$00FB			MOVWF	STACK_11
$0220	$30FF			MOVLW	255
$0221	$00FA			MOVWF	STACK_10
$0222	$0BFB			DECFSZ	STACK_11, F
$0223	$2A25			GOTO	$+2
$0224	$2A28			GOTO	$+4
$0225	$0BFA			DECFSZ	STACK_10, F
$0226	$2A25			GOTO	$-1
$0227	$2A22			GOTO	$-5
$0228	$30E2			MOVLW	226
$0229	$00FA			MOVWF	STACK_10
$022A	$0BFA			DECFSZ	STACK_10, F
$022B	$2A2A			GOTO	$-1
;Pic1.pbas,176 :: 		PORTC = cen + 64
$022C	$3040			MOVLW	64
$022D	$074D			ADDWF	FLOC_main+6, 0
$022E	$00F0			MOVWF	STACK_0
$022F	$084E			MOVF	FLOC_main+7, 0
$0230	$1803			BTFSC	STATUS, C
$0231	$3F01			ADDLW	1
$0232	$00F1			MOVWF	STACK_0+1
$0233	$3000			MOVLW	0
$0234	$07F1			ADDWF	STACK_0+1, 1
$0235	$0870			MOVF	STACK_0, 0
$0236	$0087			MOVWF	PORTC
;Pic1.pbas,177 :: 		delay_ms(3)
$0237	$3004			MOVLW	4
$0238	$00FB			MOVWF	STACK_11
$0239	$30FF			MOVLW	255
$023A	$00FA			MOVWF	STACK_10
$023B	$0BFB			DECFSZ	STACK_11, F
$023C	$2A3E			GOTO	$+2
$023D	$2A41			GOTO	$+4
$023E	$0BFA			DECFSZ	STACK_10, F
$023F	$2A3E			GOTO	$-1
$0240	$2A3B			GOTO	$-5
$0241	$30E2			MOVLW	226
$0242	$00FA			MOVWF	STACK_10
$0243	$0BFA			DECFSZ	STACK_10, F
$0244	$2A43			GOTO	$-1
;Pic1.pbas,178 :: 		PORTC = mil + 128
$0245	$3080			MOVLW	128
$0246	$074F			ADDWF	FLOC_main+8, 0
$0247	$00F0			MOVWF	STACK_0
$0248	$0850			MOVF	FLOC_main+9, 0
$0249	$1803			BTFSC	STATUS, C
$024A	$3F01			ADDLW	1
$024B	$00F1			MOVWF	STACK_0+1
$024C	$3000			MOVLW	0
$024D	$07F1			ADDWF	STACK_0+1, 1
$024E	$0870			MOVF	STACK_0, 0
$024F	$0087			MOVWF	PORTC
;Pic1.pbas,179 :: 		delay_ms(3)
$0250	$3004			MOVLW	4
$0251	$00FB			MOVWF	STACK_11
$0252	$30FF			MOVLW	255
$0253	$00FA			MOVWF	STACK_10
$0254	$0BFB			DECFSZ	STACK_11, F
$0255	$2A57			GOTO	$+2
$0256	$2A5A			GOTO	$+4
$0257	$0BFA			DECFSZ	STACK_10, F
$0258	$2A57			GOTO	$-1
$0259	$2A54			GOTO	$-5
$025A	$30E2			MOVLW	226
$025B	$00FA			MOVWF	STACK_10
$025C	$0BFA			DECFSZ	STACK_10, F
$025D	$2A5C			GOTO	$-1
;Pic1.pbas,181 :: 		goto executa
$025E	$2826			GOTO	_main_executa
$025F	$2A5F			GOTO	$
