;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 06/06/2020 16:13:03
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$074D	$	_div_16x16_s_l:
$074D	$1303			BCF	STATUS, RP1
$074E	$1283			BCF	STATUS, RP0
;math.ppas,291 :: 		
;math.ppas,293 :: 		
$074F	$0D71			RLF	STACK_1, W
;math.ppas,294 :: 		
$0750	$0DF8			RLF	STACK_8, F
;math.ppas,295 :: 		
$0751	$0DF9			RLF	STACK_9, F
;math.ppas,296 :: 		
$0752	$0874			MOVF	STACK_4, W
;math.ppas,297 :: 		
$0753	$02F8			SUBWF	STACK_8, F
;math.ppas,298 :: 		
$0754	$0875			MOVF	STACK_5, W
;math.ppas,299 :: 		
$0755	$1C03			BTFSS	STATUS, C
;math.ppas,300 :: 		
$0756	$0F75			INCFSZ	STACK_5, W
;math.ppas,301 :: 		
$0757	$02F9			SUBWF	STACK_9, F
;math.ppas,302 :: 		
$0758	$0DF0			RLF	STACK_0, F
;math.ppas,304 :: 		
$0759	$0DF1			RLF	STACK_1, F
;math.ppas,305 :: 		
$075A	$300F			MOVLW	15
;math.ppas,307 :: 		
$075B	$00FC			MOVWF	STACK_12
;math.ppas,308 :: 		
$075C	$0D71			RLF	STACK_1, W
;math.ppas,309 :: 		
$075D	$0DF8			RLF	STACK_8, F
;math.ppas,310 :: 		
$075E	$0DF9			RLF	STACK_9, F
;math.ppas,312 :: 		
$075F	$0874			MOVF	STACK_4, W
;math.ppas,313 :: 		
$0760	$1C70			BTFSS	STACK_0, 0
;math.ppas,314 :: 		
$0761	$2F68			GOTO	$+7
;math.ppas,315 :: 		
$0762	$02F8			SUBWF	STACK_8, F
;math.ppas,316 :: 		
$0763	$0875			MOVF	STACK_5, W
;math.ppas,317 :: 		
$0764	$1C03			BTFSS	STATUS, C
;math.ppas,318 :: 		
$0765	$0F75			INCFSZ	STACK_5, W
;math.ppas,319 :: 		
$0766	$02F9			SUBWF	STACK_9, F
;math.ppas,321 :: 		
$0767	$2F6D			GOTO	$+6
;math.ppas,322 :: 		
$0768	$07F8			ADDWF	STACK_8, F
;math.ppas,323 :: 		
$0769	$0875			MOVF	STACK_5, W
;math.ppas,324 :: 		
$076A	$1803			BTFSC	STATUS, C
;math.ppas,325 :: 		
$076B	$0F75			INCFSZ	STACK_5, W
;math.ppas,327 :: 		
$076C	$07F9			ADDWF	STACK_9, F
;math.ppas,328 :: 		
$076D	$0DF0			RLF	STACK_0, F
;math.ppas,330 :: 		
$076E	$0DF1			RLF	STACK_1, F
;math.ppas,331 :: 		
$076F	$0BFC			DECFSZ	STACK_12, F
;math.ppas,333 :: 		
$0770	$2F5C			GOTO	$-20
;math.ppas,334 :: 		
$0771	$1870			BTFSC	STACK_0, 0
;math.ppas,335 :: 		
$0772	$2F79			GOTO	$+7
;math.ppas,336 :: 		
$0773	$0874			MOVF	STACK_4, W
;math.ppas,337 :: 		
$0774	$07F8			ADDWF	STACK_8, F
;math.ppas,338 :: 		
$0775	$0875			MOVF	STACK_5, W
;math.ppas,339 :: 		
$0776	$1803			BTFSC	STATUS, C
;math.ppas,340 :: 		
$0777	$0F75			INCFSZ	STACK_5, W
;math.ppas,341 :: 		
$0778	$07F9			ADDWF	STACK_9, F
;math.ppas,342 :: 		
$0779	$	math_L_6:
;math.ppas,343 :: 		
$0779	$0008			RETURN
$0716	$	_mul_32x32_u:
$0716	$1303			BCF	STATUS, RP1
$0717	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$0718	$3022			MOVLW	34
;math.ppas,1579 :: 		
$0719	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$071A	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$071B	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$071C	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$071D	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$071E	$	_NEXT:
;math.ppas,1589 :: 		
$071E	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$071F	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$0720	$2F4C			GOTO	_EXIT2
;math.ppas,1593 :: 		
$0721	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$0722	$	_LOOP:
;math.ppas,1603 :: 		
$0722	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$0723	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$0724	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$0725	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$0726	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$0727	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$0728	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$0729	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$072A	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$072B	$2F1E			GOTO	_NEXT
;math.ppas,1617 :: 		
$072C	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$072D	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$072E	$2F3E			GOTO	_EXIT1
;math.ppas,1626 :: 		
$072F	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$0730	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$0731	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$0732	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$0733	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$0734	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$0735	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$0736	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$0737	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$0738	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$0739	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$073A	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$073B	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$073C	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$073D	$2F22			GOTO	_LOOP
;math.ppas,1647 :: 		
$073E	$	_EXIT1:
;math.ppas,1648 :: 		
$073E	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$073F	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$0740	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$0741	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$0742	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$0743	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$0744	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$0745	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$0746	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$0747	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$0748	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$0749	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$074A	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$074B	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$074C	$	_EXIT2:
;math.ppas,1665 :: 		
$074C	$	math_L_13:
;math.ppas,1666 :: 		
$074C	$0008			RETURN
$026D	$	_sdiv3232l:
$026D	$1303			BCF	STATUS, RP1
$026E	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$026F	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0270	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0271	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0272	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$0273	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$0274	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$0275	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$0276	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$0277	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$0278	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$0279	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$027A	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$027B	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$027C	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$027D	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$027E	$3007			MOVLW	7
;math.ppas,559 :: 		
$027F	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0280	$	LOOPS3232A:
;math.ppas,561 :: 		
$0280	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0281	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0282	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$0283	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$0284	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$0285	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$0286	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$0287	$2A96			GOTO	SADD22LA
;math.ppas,570 :: 		
$0288	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$0289	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$028A	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$028B	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$028C	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$028D	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$028E	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$028F	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0290	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0291	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0292	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$0293	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$0294	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$0295	$2AA3			GOTO	SOK22LA
;math.ppas,585 :: 		
$0296	$	SADD22LA:
;math.ppas,586 :: 		
$0296	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$0297	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$0298	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$0299	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$029A	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$029B	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$029C	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$029D	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$029E	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$029F	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$02A0	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$02A1	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$02A2	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$02A3	$	SOK22LA:
;math.ppas,602 :: 		
$02A3	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$02A4	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$02A5	$2A80			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$02A6	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$02A7	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$02A8	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$02A9	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$02AA	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$02AB	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$02AC	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$02AD	$2ABC			GOTO	SADD22L8
;math.ppas,615 :: 		
$02AE	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$02AF	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$02B0	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$02B1	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$02B2	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$02B3	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$02B4	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$02B5	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$02B6	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$02B7	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$02B8	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$02B9	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$02BA	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$02BB	$2AC9			GOTO	SOK22L8
;math.ppas,630 :: 		
$02BC	$	SADD22L8:
;math.ppas,631 :: 		
$02BC	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$02BD	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$02BE	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$02BF	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$02C0	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$02C1	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$02C2	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$02C3	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$02C4	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$02C5	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$02C6	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$02C7	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$02C8	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$02C9	$	SOK22L8:
;math.ppas,647 :: 		
$02C9	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$02CA	$3007			MOVLW	7
;math.ppas,650 :: 		
$02CB	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$02CC	$	LOOPS3232B:
;math.ppas,652 :: 		
$02CC	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$02CD	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$02CE	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$02CF	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$02D0	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$02D1	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$02D2	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$02D3	$2AE2			GOTO	SADD22LB
;math.ppas,661 :: 		
$02D4	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$02D5	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$02D6	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$02D7	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$02D8	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$02D9	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$02DA	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$02DB	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$02DC	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$02DD	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$02DE	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$02DF	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$02E0	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$02E1	$2AEF			GOTO	SOK22LB
;math.ppas,676 :: 		
$02E2	$	SADD22LB:
;math.ppas,677 :: 		
$02E2	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$02E3	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$02E4	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$02E5	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$02E6	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$02E7	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$02E8	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$02E9	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$02EA	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$02EB	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$02EC	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$02ED	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$02EE	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$02EF	$	SOK22LB:
;math.ppas,693 :: 		
$02EF	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$02F0	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$02F1	$2ACC			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$02F2	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$02F3	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$02F4	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$02F5	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$02F6	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$02F7	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$02F8	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$02F9	$2B08			GOTO	SADD22L16
;math.ppas,706 :: 		
$02FA	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$02FB	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$02FC	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$02FD	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$02FE	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$02FF	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$0300	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$0301	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$0302	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$0303	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$0304	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$0305	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$0306	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$0307	$2B15			GOTO	SOK22L16
;math.ppas,721 :: 		
$0308	$	SADD22L16:
;math.ppas,722 :: 		
$0308	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$0309	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$030A	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$030B	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$030C	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$030D	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$030E	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$030F	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$0310	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$0311	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$0312	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$0313	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$0314	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$0315	$	SOK22L16:
;math.ppas,738 :: 		
$0315	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$0316	$3007			MOVLW	7
;math.ppas,741 :: 		
$0317	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$0318	$	LOOPS3232C:
;math.ppas,743 :: 		
$0318	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$0319	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$031A	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$031B	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$031C	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$031D	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$031E	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$031F	$2B2E			GOTO	SADD22LC
;math.ppas,752 :: 		
$0320	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$0321	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$0322	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$0323	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$0324	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$0325	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$0326	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$0327	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$0328	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$0329	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$032A	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$032B	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$032C	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$032D	$2B3B			GOTO	SOK22LC
;math.ppas,767 :: 		
$032E	$	SADD22LC:
;math.ppas,768 :: 		
$032E	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$032F	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$0330	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$0331	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$0332	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$0333	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$0334	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$0335	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$0336	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$0337	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$0338	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$0339	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$033A	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$033B	$	SOK22LC:
;math.ppas,784 :: 		
$033B	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$033C	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$033D	$2B18			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$033E	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$033F	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$0340	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$0341	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$0342	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$0343	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$0344	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$0345	$2B54			GOTO	SADD22L24
;math.ppas,797 :: 		
$0346	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$0347	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$0348	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$0349	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$034A	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$034B	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$034C	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$034D	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$034E	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$034F	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$0350	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$0351	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$0352	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$0353	$2B61			GOTO	SOK22L24
;math.ppas,812 :: 		
$0354	$	SADD22L24:
;math.ppas,813 :: 		
$0354	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$0355	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$0356	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$0357	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$0358	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$0359	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$035A	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$035B	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$035C	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$035D	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$035E	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$035F	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$0360	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$0361	$	SOK22L24:
;math.ppas,829 :: 		
$0361	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$0362	$3007			MOVLW	7
;math.ppas,832 :: 		
$0363	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$0364	$	LOOPS3232D:
;math.ppas,834 :: 		
$0364	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$0365	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$0366	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$0367	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$0368	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$0369	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$036A	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$036B	$2B7A			GOTO	SADD22LD
;math.ppas,843 :: 		
$036C	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$036D	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$036E	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$036F	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0370	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0371	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0372	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$0373	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$0374	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$0375	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$0376	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$0377	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$0378	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$0379	$2B87			GOTO	SOK22LD
;math.ppas,858 :: 		
$037A	$	SADD22LD:
;math.ppas,859 :: 		
$037A	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$037B	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$037C	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$037D	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$037E	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$037F	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0380	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0381	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0382	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$0383	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$0384	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$0385	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$0386	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$0387	$	SOK22LD:
;math.ppas,876 :: 		
$0387	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$0388	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$0389	$2B64			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$038A	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$038B	$2B9A			GOTO	SOK22L
;math.ppas,882 :: 		
$038C	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$038D	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$038E	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$038F	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0390	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0391	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0392	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$0393	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$0394	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$0395	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$0396	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$0397	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$0398	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$0399	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$039A	$	SOK22L:
;math.ppas,897 :: 		
$039A	$	math_L_9:
;math.ppas,898 :: 		
$039A	$0008			RETURN
$086D	$	_comfrem:
$086D	$1303			BCF	STATUS, RP1
$086E	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$086F	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$0870	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$0871	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$0872	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$0873	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$0874	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$0875	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$0876	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$0877	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$0878	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$0879	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$087A	$	math_L_10:
;math.ppas,915 :: 		
$087A	$0008			RETURN
$085B	$	_usart_write:
;USART_b75.ppas,40 :: 		
;USART_b75.ppas,42 :: 		
$085B	$	USART_b75_L_14:
$085B	$1303			BCF	STATUS, RP1
$085C	$1683			BSF	STATUS, RP0
$085D	$0818			MOVF	TXSTA, 0
$085E	$00F1			MOVWF	STACK_1
$085F	$3000			MOVLW	0
$0860	$18F1			BTFSC	STACK_1, 1
$0861	$3001			MOVLW	1
$0862	$00F1			MOVWF	STACK_1
$0863	$0871			MOVF	STACK_1, 0
$0864	$3A00			XORLW	0
$0865	$1D03			BTFSS	STATUS, Z
$0866	$2869			GOTO	USART_b75_L_15
;USART_b75.ppas,43 :: 		
$0867	$0000			NOP
$0868	$285B			GOTO	USART_b75_L_14
$0869	$	USART_b75_L_15:
;USART_b75.ppas,44 :: 		
$0869	$1283			BCF	STATUS, RP0
$086A	$0865			MOVF	FARG_USART_Write, 0
$086B	$0099			MOVWF	TXREG
$086C	$	USART_b75_L_12:
;USART_b75.ppas,45 :: 		
$086C	$0008			RETURN
$05F1	$	_div_16x16_s:
$05F1	$1303			BCF	STATUS, RP1
$05F2	$1283			BCF	STATUS, RP0
;math.ppas,346 :: 		
;math.ppas,348 :: 		
$05F3	$01FD			CLRF	STACK_13
;math.ppas,349 :: 		
$05F4	$01F9			CLRF	STACK_9
;math.ppas,350 :: 		
$05F5	$01F8			CLRF	STACK_8
;math.ppas,351 :: 		
$05F6	$0871			MOVF	STACK_1, W
;math.ppas,352 :: 		
$05F7	$0470			IORWF	STACK_0, W
;math.ppas,353 :: 		
$05F8	$1903			BTFSC	STATUS, Z
;math.ppas,355 :: 		
$05F9	$3400			RETLW	0
;math.ppas,356 :: 		
$05FA	$0871			MOVF	STACK_1, W
;math.ppas,357 :: 		
$05FB	$0675			XORWF	STACK_5, W
;math.ppas,358 :: 		
$05FC	$00FA			MOVWF	STACK_10
;math.ppas,359 :: 		
$05FD	$1BFA			BTFSC	STACK_10, 7
;math.ppas,361 :: 		
$05FE	$09FD			COMF	STACK_13, F
;math.ppas,363 :: 		
$05FF	$01FB			CLRF	STACK_11
;math.ppas,364 :: 		
$0600	$1FF5			BTFSS	STACK_5, 7
;math.ppas,366 :: 		
$0601	$2E07			GOTO	$+6
;math.ppas,367 :: 		
$0602	$09F4			COMF	STACK_4, F
;math.ppas,368 :: 		
$0603	$09F5			COMF	STACK_5, F
;math.ppas,369 :: 		
$0604	$0AF4			INCF	STACK_4, F
;math.ppas,370 :: 		
$0605	$1903			BTFSC	STATUS, Z
;math.ppas,372 :: 		
$0606	$0AF5			INCF	STACK_5, F
;math.ppas,373 :: 		
$0607	$1FF1			BTFSS	STACK_1, 7
;math.ppas,375 :: 		
$0608	$2E0E			GOTO	$+6
;math.ppas,376 :: 		
$0609	$09F0			COMF	STACK_0, F
;math.ppas,377 :: 		
$060A	$09F1			COMF	STACK_1, F
;math.ppas,378 :: 		
$060B	$0AF0			INCF	STACK_0, F
;math.ppas,379 :: 		
$060C	$1903			BTFSC	STATUS, Z
;math.ppas,381 :: 		
$060D	$0AF1			INCF	STACK_1, F
;math.ppas,382 :: 		
$060E	$0871			MOVF	STACK_1, W
;math.ppas,383 :: 		
$060F	$0475			IORWF	STACK_5, W
;math.ppas,384 :: 		
$0610	$00FA			MOVWF	STACK_10
;math.ppas,385 :: 		
$0611	$1BFA			BTFSC	STACK_10, 7
;math.ppas,386 :: 		
$0612	$2E23			GOTO	$+17
;math.ppas,388 :: 		
$0613	$274D			CALL	_div_16x16_s_l
;math.ppas,390 :: 		
$0614	$187B			BTFSC	STACK_11, 0
;math.ppas,392 :: 		
$0615	$2E36			GOTO	$+33
;math.ppas,393 :: 		
$0616	$1FFD			BTFSS	STACK_13, 7
;math.ppas,395 :: 		
$0617	$3400			RETLW	0
;math.ppas,396 :: 		
$0618	$09F0			COMF	STACK_0, F
;math.ppas,397 :: 		
$0619	$09F1			COMF	STACK_1, F
;math.ppas,398 :: 		
$061A	$0AF0			INCF	STACK_0, F
;math.ppas,399 :: 		
$061B	$1903			BTFSC	STATUS, Z
;math.ppas,401 :: 		
$061C	$0AF1			INCF	STACK_1, F
;math.ppas,402 :: 		
$061D	$09F8			COMF	STACK_8, F
;math.ppas,403 :: 		
$061E	$09F9			COMF	STACK_9, F
;math.ppas,404 :: 		
$061F	$0AF8			INCF	STACK_8, F
;math.ppas,405 :: 		
$0620	$1903			BTFSC	STATUS, Z
;math.ppas,407 :: 		
$0621	$0AF9			INCF	STACK_9, F
;math.ppas,409 :: 		
$0622	$3400			RETLW	0
;math.ppas,410 :: 		
$0623	$1FF5			BTFSS	STACK_5, 7
;math.ppas,411 :: 		
$0624	$2E32			GOTO	$+14
;math.ppas,412 :: 		
$0625	$1BF1			BTFSC	STACK_1, 7
;math.ppas,413 :: 		
$0626	$2E2E			GOTO	$+8
;math.ppas,414 :: 		
$0627	$0871			MOVF	STACK_1, W
;math.ppas,415 :: 		
$0628	$00F9			MOVWF	STACK_9
;math.ppas,416 :: 		
$0629	$0870			MOVF	STACK_0, W
;math.ppas,417 :: 		
$062A	$00F8			MOVWF	STACK_8
;math.ppas,418 :: 		
$062B	$01F1			CLRF	STACK_1
;math.ppas,419 :: 		
$062C	$01F0			CLRF	STACK_0
;math.ppas,420 :: 		
$062D	$2E16			GOTO	$-23
;math.ppas,421 :: 		
$062E	$01F1			CLRF	STACK_1
;math.ppas,422 :: 		
$062F	$01F0			CLRF	STACK_0
;math.ppas,423 :: 		
$0630	$0AF0			INCF	STACK_0, F
;math.ppas,425 :: 		
$0631	$3400			RETLW	0
;math.ppas,426 :: 		
$0632	$09F1			COMF	STACK_1, F
;math.ppas,427 :: 		
$0633	$09F0			COMF	STACK_0, F
;math.ppas,428 :: 		
$0634	$0AFB			INCF	STACK_11, F
;math.ppas,430 :: 		
$0635	$2E13			GOTO	$-34
;math.ppas,431 :: 		
$0636	$0AF8			INCF	STACK_8, F
;math.ppas,432 :: 		
$0637	$1903			BTFSC	STATUS, Z
;math.ppas,433 :: 		
$0638	$0AF9			INCF	STACK_9, F
;math.ppas,434 :: 		
$0639	$0874			MOVF	STACK_4, W
;math.ppas,435 :: 		
$063A	$0278			SUBWF	STACK_8, W
;math.ppas,436 :: 		
$063B	$1D03			BTFSS	STATUS, Z
;math.ppas,437 :: 		
$063C	$2E16			GOTO	$-38
;math.ppas,438 :: 		
$063D	$0875			MOVF	STACK_5, W
;math.ppas,439 :: 		
$063E	$0279			SUBWF	STACK_9, W
;math.ppas,440 :: 		
$063F	$1D03			BTFSS	STATUS, Z
;math.ppas,441 :: 		
$0640	$2E16			GOTO	$-42
;math.ppas,442 :: 		
$0641	$01F9			CLRF	STACK_9
;math.ppas,443 :: 		
$0642	$01F8			CLRF	STACK_8
;math.ppas,444 :: 		
$0643	$0AF0			INCF	STACK_0, F
;math.ppas,445 :: 		
$0644	$1903			BTFSC	STATUS, Z
;math.ppas,446 :: 		
$0645	$0AF1			INCF	STACK_1, F
;math.ppas,447 :: 		
$0646	$1FF1			BTFSS	STACK_1, 7
;math.ppas,448 :: 		
$0647	$2E16			GOTO	$-49
;math.ppas,449 :: 		
$0648	$0000			NOP
;math.ppas,450 :: 		
$0649	$34FF			RETLW	255
;math.ppas,451 :: 		
$064A	$	math_L_7:
;math.ppas,452 :: 		
$064A	$0008			RETURN
$087B	$	_usart_data_ready:
;USART_b75.ppas,48 :: 		
;USART_b75.ppas,50 :: 		
$087B	$1303			BCF	STATUS, RP1
$087C	$1283			BCF	STATUS, RP0
$087D	$080C			MOVF	PIR1, 0
$087E	$00F1			MOVWF	STACK_1
$087F	$3000			MOVLW	0
$0880	$1AF1			BTFSC	STACK_1, 5
$0881	$3001			MOVLW	1
$0882	$00F1			MOVWF	STACK_1
$0883	$0871			MOVF	STACK_1, 0
$0884	$00E0			MOVWF	_usart_data_ready_local_result
$0885	$	USART_b75_L_18:
;USART_b75.ppas,51 :: 		
$0885	$0860			MOVF	_usart_data_ready_local_result, 0
$0886	$00F0			MOVWF	STACK_0
$0887	$0008			RETURN
$0848	$	_usart_read:
;USART_b75.ppas,54 :: 		
;USART_b75.ppas,55 :: 		
$0848	$1303			BCF	STATUS, RP1
$0849	$1283			BCF	STATUS, RP0
$084A	$081A			MOVF	RCREG, 0
$084B	$00E0			MOVWF	_usart_read_local_result
;USART_b75.ppas,61 :: 		
$084C	$0818			MOVF	RCSTA, 0
$084D	$00F1			MOVWF	STACK_1
$084E	$3000			MOVLW	0
$084F	$18F1			BTFSC	STACK_1, 1
$0850	$3001			MOVLW	1
$0851	$00F1			MOVWF	STACK_1
$0852	$0871			MOVF	STACK_1, 0
$0853	$3A01			XORLW	1
$0854	$1D03			BTFSS	STATUS, Z
$0855	$2858			GOTO	USART_b75_L_21
$0856	$	USART_b75_L_20:
;USART_b75.ppas,63 :: 		
$0856	$1218			BCF	RCSTA, 4
$0857	$	USART_b75_L_24:
;USART_b75.ppas,64 :: 		
$0857	$	USART_b75_L_25:
$0857	$1618			BSF	RCSTA, 4
$0858	$	USART_b75_L_26:
;USART_b75.ppas,65 :: 		
$0858	$	USART_b75_L_21:
$0858	$	USART_b75_L_22:
$0858	$	USART_b75_L_19:
;USART_b75.ppas,66 :: 		
$0858	$0860			MOVF	_usart_read_local_result, 0
$0859	$00F0			MOVWF	STACK_0
$085A	$0008			RETURN
$06DB	$	_mul_32x32_s:
$06DB	$1303			BCF	STATUS, RP1
$06DC	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$06DD	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$06DE	$	_IF_FIRST:
;math.ppas,1684 :: 		
$06DE	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$06DF	$2EED			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$06E0	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$06E0	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$06E1	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$06E2	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$06E3	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$06E4	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$06E5	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$06E6	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$06E7	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$06E8	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$06E9	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$06EA	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$06EB	$3081			MOVLW	129
;math.ppas,1711 :: 		
$06EC	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$06ED	$	_IF_SECOND:
;math.ppas,1715 :: 		
$06ED	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$06EE	$2EFB			GOTO	_MULT
;math.ppas,1722 :: 		
$06EF	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$06EF	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$06F0	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$06F1	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$06F2	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$06F3	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$06F4	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$06F5	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$06F6	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$06F7	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$06F8	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$06F9	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$06FA	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$06FB	$	_MULT:
;math.ppas,1744 :: 		
$06FB	$2716			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$06FC	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$06FD	$2F15			GOTO	_EXIT
;math.ppas,1755 :: 		
$06FE	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$06FF	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$0700	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$0701	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$0702	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$0703	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$0704	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$0705	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$0706	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$0707	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$0708	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$0709	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$070A	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$070B	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$070C	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$070D	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$070E	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$070F	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$0710	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$0711	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$0712	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$0713	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$0714	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$0715	$	_EXIT:
;math.ppas,1793 :: 		
$0715	$	math_L_14:
;math.ppas,1794 :: 		
$0715	$0008			RETURN
$0800	$	_div_16x16_u:
$0800	$1303			BCF	STATUS, RP1
$0801	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$0802	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$0803	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$0804	$3010			MOVLW	16
;math.ppas,113 :: 		
$0805	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$0806	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$0807	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$0808	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$0809	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$080A	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$080B	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$080C	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$080D	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$080E	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$080F	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$0810	$2818			GOTO	$+8
;math.ppas,125 :: 		
$0811	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$0812	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$0813	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$0814	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$0815	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$0816	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$0817	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$0818	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$0819	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$081A	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$081B	$2806			GOTO	$-21
;math.ppas,136 :: 		
$081C	$	math_L_3:
;math.ppas,137 :: 		
$081C	$0008			RETURN
$0502	$	_div_32x32_s:
$0502	$1303			BCF	STATUS, RP1
$0503	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$0504	$	FXD3232S:
;math.ppas,929 :: 		
$0504	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$0505	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$0506	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$0507	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$0508	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$0509	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$050A	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$050B	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$050C	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$050D	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$050E	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$050F	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0510	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$0511	$2D96			GOTO	END_ALL
;math.ppas,944 :: 		
$0512	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$0513	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$0514	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$0515	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$0516	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$0517	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$0518	$2D24			GOTO	CA3232S
;math.ppas,955 :: 		
$0519	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$051A	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$051B	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$051C	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$051D	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$051E	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$051F	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0520	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$0521	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$0522	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$0523	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$0524	$	CA3232S:
;math.ppas,968 :: 		
$0524	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$0525	$2D31			GOTO	C3232SX
;math.ppas,971 :: 		
$0526	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$0527	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$0528	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$0529	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$052A	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$052B	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$052C	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$052D	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$052E	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$052F	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$0530	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$0531	$	C3232SX:
;math.ppas,984 :: 		
$0531	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$0532	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$0533	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$0534	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$0535	$2D52			GOTO	C3232SX1
;math.ppas,989 :: 		
$0536	$	C3232S:
;math.ppas,992 :: 		
$0536	$226D			CALL	_sdiv3232l
;math.ppas,995 :: 		
$0537	$	C3232S2:
;math.ppas,996 :: 		
$0537	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$0538	$2D6F			GOTO	C3232SX4
;math.ppas,998 :: 		
$0539	$	C3232SOK:
;math.ppas,999 :: 		
$0539	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$053A	$2D96			GOTO	END_ALL
;math.ppas,1001 :: 		
$053B	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$053C	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$053D	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$053E	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$053F	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$0540	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$0541	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$0542	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$0543	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$0544	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$0545	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$0546	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$0547	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$0548	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$0549	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$054A	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$054B	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$054C	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$054D	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$054E	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$054F	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$0550	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$0551	$2D96			GOTO	END_ALL
;math.ppas,1026 :: 		
$0552	$	C3232SX1:
;math.ppas,1027 :: 		
$0552	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$0553	$2D69			GOTO	C3232SX3
;math.ppas,1029 :: 		
$0554	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$0555	$2D63			GOTO	C3232SX2
;math.ppas,1031 :: 		
$0556	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$0557	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$0558	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$0559	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$055A	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$055B	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$055C	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$055D	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$055E	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$055F	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$0560	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$0561	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$0562	$2D39			GOTO	C3232SOK
;math.ppas,1044 :: 		
$0563	$	C3232SX2:
;math.ppas,1045 :: 		
$0563	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$0564	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$0565	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$0566	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$0567	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$0568	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$0569	$	C3232SX3:
;math.ppas,1053 :: 		
$0569	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$056A	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$056B	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$056C	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$056D	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$056E	$2D36			GOTO	C3232S
;math.ppas,1061 :: 		
$056F	$	C3232SX4:
;math.ppas,1062 :: 		
$056F	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0570	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$0571	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$0572	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$0573	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$0574	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$0575	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$0576	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$0577	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$0578	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$0579	$2D39			GOTO	C3232SOK
;math.ppas,1073 :: 		
$057A	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$057B	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$057C	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$057D	$2D39			GOTO	C3232SOK
;math.ppas,1077 :: 		
$057E	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$057F	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$0580	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$0581	$2D39			GOTO	C3232SOK
;math.ppas,1081 :: 		
$0582	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$0583	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$0584	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$0585	$2D39			GOTO	C3232SOK
;math.ppas,1085 :: 		
$0586	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$0587	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$0588	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$0589	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$058A	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$058B	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$058C	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$058D	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$058E	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$058F	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0590	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$0591	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$0592	$2D39			GOTO	C3232SOK
;math.ppas,1098 :: 		
$0593	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$0594	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$0595	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$0596	$	END_ALL:
;math.ppas,1102 :: 		
$0596	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$0597	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$0598	$2D9C			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$0599	$158A			BSF	PCLATH, 3
$059A	$206D			CALL	_comfrem
$059B	$118A			BCF	PCLATH, 3
;math.ppas,1108 :: 		
$059C	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$059C	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$059D	$	math_L_11:
;math.ppas,1111 :: 		
$059D	$0008			RETURN
$081D	$	_usart_write_text:
;USART_b75.ppas,121 :: 		
;USART_b75.ppas,122 :: 		
$081D	$1303			BCF	STATUS, RP1
$081E	$1283			BCF	STATUS, RP0
$081F	$01E1			CLRF	_usart_write_text_local_i, 1
;USART_b75.ppas,123 :: 		
$0820	$0860			MOVF	FARG_Usart_Write_Text, 0
$0821	$0084			MOVWF	FSR
$0822	$0800			MOVF	INDF, 0
$0823	$00E2			MOVWF	_usart_write_text_local_data
;USART_b75.ppas,124 :: 		
$0824	$	USART_b75_L_47:
$0824	$0862			MOVF	_usart_write_text_local_data, 0
$0825	$3A00			XORLW	0
$0826	$1903			BTFSC	STATUS, Z
$0827	$2832			GOTO	USART_b75_L_48
;USART_b75.ppas,126 :: 		
$0828	$0862			MOVF	_usart_write_text_local_data, 0
$0829	$00E5			MOVWF	FARG_USART_Write
$082A	$205B			CALL	_usart_write
;USART_b75.ppas,127 :: 		
$082B	$0AE1			INCF	_usart_write_text_local_i, 1
;USART_b75.ppas,128 :: 		
$082C	$0861			MOVF	_usart_write_text_local_i, 0
$082D	$0760			ADDWF	FARG_Usart_Write_Text, 0
$082E	$0084			MOVWF	FSR
$082F	$0800			MOVF	INDF, 0
$0830	$00E2			MOVWF	_usart_write_text_local_data
;USART_b75.ppas,129 :: 		
$0831	$2824			GOTO	USART_b75_L_47
$0832	$	USART_b75_L_48:
$0832	$	USART_b75_L_45:
;USART_b75.ppas,130 :: 		
$0832	$0008			RETURN
$045F	$	_inttostr:
;conv.ppas,100 :: 		
;conv.ppas,101 :: 		
$045F	$1303			BCF	STATUS, RP1
$0460	$1283			BCF	STATUS, RP0
$0461	$0861			MOVF	FARG_IntToStr+1, 0
$0462	$3A80			XORLW	128
$0463	$1D03			BTFSS	STATUS, Z
$0464	$2C67			GOTO	L_IntToStr_4
$0465	$3000			MOVLW	0
$0466	$0660			XORWF	FARG_IntToStr, 0
$0467	$	L_IntToStr_4:
$0467	$1D03			BTFSS	STATUS, Z
$0468	$2C7F			GOTO	conv_L_57
$0469	$	conv_L_56:
;conv.ppas,103 :: 		
$0469	$0862			MOVF	FARG_IntToStr+2, 0
$046A	$0084			MOVWF	FSR
$046B	$302D			MOVLW	45
$046C	$0080			MOVWF	INDF
$046D	$0A84			INCF	FSR, 1
$046E	$3033			MOVLW	51
$046F	$0080			MOVWF	INDF
$0470	$0A84			INCF	FSR, 1
$0471	$3032			MOVLW	50
$0472	$0080			MOVWF	INDF
$0473	$0A84			INCF	FSR, 1
$0474	$3037			MOVLW	55
$0475	$0080			MOVWF	INDF
$0476	$0A84			INCF	FSR, 1
$0477	$3036			MOVLW	54
$0478	$0080			MOVWF	INDF
$0479	$0A84			INCF	FSR, 1
$047A	$3038			MOVLW	56
$047B	$0080			MOVWF	INDF
$047C	$0A84			INCF	FSR, 1
$047D	$0180			CLRF	INDF
;conv.ppas,104 :: 		
$047E	$2D01			GOTO	conv_L_55
;conv.ppas,105 :: 		
$047F	$	conv_L_57:
$047F	$	conv_L_58:
;conv.ppas,106 :: 		
$047F	$01E4			CLRF	_inttostr_local_negative, 1
;conv.ppas,107 :: 		
$0480	$3080			MOVLW	128
$0481	$0661			XORWF	FARG_IntToStr+1, 0
$0482	$00F0			MOVWF	STACK_0
$0483	$3080			MOVLW	128
$0484	$0270			SUBWF	STACK_0, 0
$0485	$1D03			BTFSS	STATUS, Z
$0486	$2C89			GOTO	L_IntToStr_5
$0487	$3000			MOVLW	0
$0488	$0260			SUBWF	FARG_IntToStr, 0
$0489	$	L_IntToStr_5:
$0489	$1803			BTFSC	STATUS, C
$048A	$2C95			GOTO	conv_L_61
$048B	$	conv_L_60:
;conv.ppas,109 :: 		
$048B	$30FF			MOVLW	255
$048C	$00E4			MOVWF	_inttostr_local_negative
;conv.ppas,110 :: 		
$048D	$0860			MOVF	FARG_IntToStr, 0
$048E	$3C00			SUBLW	0
$048F	$00E0			MOVWF	FARG_IntToStr
$0490	$0861			MOVF	FARG_IntToStr+1, 0
$0491	$1C03			BTFSS	STATUS, C
$0492	$3F01			ADDLW	1
$0493	$01E1			CLRF	FARG_IntToStr+1
$0494	$02E1			SUBWF	FARG_IntToStr+1, 1
;conv.ppas,111 :: 		
$0495	$	conv_L_61:
$0495	$	conv_L_62:
;conv.ppas,112 :: 		
$0495	$3001			MOVLW	1
$0496	$00E3			MOVWF	_inttostr_local_len
;conv.ppas,113 :: 		
$0497	$3080			MOVLW	128
$0498	$00F0			MOVWF	STACK_0
$0499	$3080			MOVLW	128
$049A	$0661			XORWF	FARG_IntToStr+1, 0
$049B	$0270			SUBWF	STACK_0, 0
$049C	$1D03			BTFSS	STATUS, Z
$049D	$2CA0			GOTO	L_IntToStr_6
$049E	$0860			MOVF	FARG_IntToStr, 0
$049F	$3C09			SUBLW	9
$04A0	$	L_IntToStr_6:
$04A0	$1803			BTFSC	STATUS, C
$04A1	$2CA3			GOTO	conv_L_64
$04A2	$	conv_L_63:
;conv.ppas,114 :: 		
$04A2	$0AE3			INCF	_inttostr_local_len, 1
$04A3	$	conv_L_64:
$04A3	$	conv_L_65:
;conv.ppas,115 :: 		
$04A3	$3080			MOVLW	128
$04A4	$00F0			MOVWF	STACK_0
$04A5	$3080			MOVLW	128
$04A6	$0661			XORWF	FARG_IntToStr+1, 0
$04A7	$0270			SUBWF	STACK_0, 0
$04A8	$1D03			BTFSS	STATUS, Z
$04A9	$2CAC			GOTO	L_IntToStr_7
$04AA	$0860			MOVF	FARG_IntToStr, 0
$04AB	$3C63			SUBLW	99
$04AC	$	L_IntToStr_7:
$04AC	$1803			BTFSC	STATUS, C
$04AD	$2CAF			GOTO	conv_L_67
$04AE	$	conv_L_66:
;conv.ppas,116 :: 		
$04AE	$0AE3			INCF	_inttostr_local_len, 1
$04AF	$	conv_L_67:
$04AF	$	conv_L_68:
;conv.ppas,117 :: 		
$04AF	$3080			MOVLW	128
$04B0	$3A03			XORLW	3
$04B1	$00F0			MOVWF	STACK_0
$04B2	$3080			MOVLW	128
$04B3	$0661			XORWF	FARG_IntToStr+1, 0
$04B4	$0270			SUBWF	STACK_0, 0
$04B5	$1D03			BTFSS	STATUS, Z
$04B6	$2CB9			GOTO	L_IntToStr_8
$04B7	$0860			MOVF	FARG_IntToStr, 0
$04B8	$3CE7			SUBLW	231
$04B9	$	L_IntToStr_8:
$04B9	$1803			BTFSC	STATUS, C
$04BA	$2CBC			GOTO	conv_L_70
$04BB	$	conv_L_69:
;conv.ppas,118 :: 		
$04BB	$0AE3			INCF	_inttostr_local_len, 1
$04BC	$	conv_L_70:
$04BC	$	conv_L_71:
;conv.ppas,119 :: 		
$04BC	$3080			MOVLW	128
$04BD	$3A27			XORLW	39
$04BE	$00F0			MOVWF	STACK_0
$04BF	$3080			MOVLW	128
$04C0	$0661			XORWF	FARG_IntToStr+1, 0
$04C1	$0270			SUBWF	STACK_0, 0
$04C2	$1D03			BTFSS	STATUS, Z
$04C3	$2CC6			GOTO	L_IntToStr_9
$04C4	$0860			MOVF	FARG_IntToStr, 0
$04C5	$3C0F			SUBLW	15
$04C6	$	L_IntToStr_9:
$04C6	$1803			BTFSC	STATUS, C
$04C7	$2CC9			GOTO	conv_L_73
$04C8	$	conv_L_72:
;conv.ppas,120 :: 		
$04C8	$0AE3			INCF	_inttostr_local_len, 1
$04C9	$	conv_L_73:
$04C9	$	conv_L_74:
;conv.ppas,121 :: 		
$04C9	$0862			MOVF	FARG_IntToStr+2, 0
$04CA	$0084			MOVWF	FSR
$04CB	$3020			MOVLW	32
$04CC	$0080			MOVWF	INDF
$04CD	$0A84			INCF	FSR, 1
$04CE	$0080			MOVWF	INDF
$04CF	$0A84			INCF	FSR, 1
$04D0	$0080			MOVWF	INDF
$04D1	$0A84			INCF	FSR, 1
$04D2	$0080			MOVWF	INDF
$04D3	$0A84			INCF	FSR, 1
$04D4	$0080			MOVWF	INDF
$04D5	$0A84			INCF	FSR, 1
$04D6	$0080			MOVWF	INDF
$04D7	$0A84			INCF	FSR, 1
$04D8	$0180			CLRF	INDF
;conv.ppas,122 :: 		
$04D9	$0384			DECF	FSR, 1
;conv.ppas,123 :: 		
$04DA	$	conv_L_77:
$04DA	$0863			MOVF	_inttostr_local_len, 0
$04DB	$3C00			SUBLW	0
$04DC	$1803			BTFSC	STATUS, C
$04DD	$2CFC			GOTO	conv_L_78
;conv.ppas,125 :: 		
$04DE	$300A			MOVLW	10
$04DF	$00F4			MOVWF	STACK_4
$04E0	$01F5			CLRF	STACK_4+1
$04E1	$0860			MOVF	FARG_IntToStr, 0
$04E2	$00F0			MOVWF	STACK_0
$04E3	$0861			MOVF	FARG_IntToStr+1, 0
$04E4	$00F1			MOVWF	STACK_0+1
$04E5	$25F1			CALL	_div_16x16_s
$04E6	$0878			MOVF	STACK_8, 0
$04E7	$00F0			MOVWF	STACK_0
$04E8	$0879			MOVF	STACK_9, 0
$04E9	$00F1			MOVWF	STACK_1
$04EA	$3030			MOVLW	48
$04EB	$0770			ADDWF	STACK_0, 0
$04EC	$0080			MOVWF	INDF
;conv.ppas,126 :: 		
;conv.ppas,127 :: 		
$04ED	$0384			DECF	FSR, 1
;conv.ppas,128 :: 		
$04EE	$300A			MOVLW	10
$04EF	$00F4			MOVWF	STACK_4
$04F0	$01F5			CLRF	STACK_4+1
$04F1	$0860			MOVF	FARG_IntToStr, 0
$04F2	$00F0			MOVWF	STACK_0
$04F3	$0861			MOVF	FARG_IntToStr+1, 0
$04F4	$00F1			MOVWF	STACK_0+1
$04F5	$25F1			CALL	_div_16x16_s
$04F6	$0870			MOVF	STACK_0, 0
$04F7	$00E0			MOVWF	FARG_IntToStr
$04F8	$0871			MOVF	STACK_0+1, 0
$04F9	$00E1			MOVWF	FARG_IntToStr+1
;conv.ppas,129 :: 		
$04FA	$03E3			DECF	_inttostr_local_len, 1
;conv.ppas,130 :: 		
$04FB	$2CDA			GOTO	conv_L_77
$04FC	$	conv_L_78:
;conv.ppas,131 :: 		
$04FC	$0864			MOVF	_inttostr_local_negative, 0
$04FD	$1903			BTFSC	STATUS, Z
$04FE	$2D01			GOTO	conv_L_82
$04FF	$	conv_L_81:
;conv.ppas,133 :: 		
$04FF	$302D			MOVLW	45
$0500	$0080			MOVWF	INDF
;conv.ppas,134 :: 		
$0501	$	conv_L_82:
$0501	$	conv_L_83:
$0501	$	conv_L_55:
;conv.ppas,135 :: 		
$0501	$0008			RETURN
$064B	$	_usart_read_text:
;USART_b75.ppas,78 :: 		
;USART_b75.ppas,79 :: 		
$064B	$1303			BCF	STATUS, RP1
$064C	$1283			BCF	STATUS, RP0
$064D	$01D5			CLRF	_usart_read_text_local_i, 1
;USART_b75.ppas,80 :: 		
$064E	$01D6			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,81 :: 		
$064F	$01D9			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,82 :: 		
$0650	$0854			MOVF	FARG_Usart_Read_Text+1, 0
$0651	$0084			MOVWF	FSR
$0652	$0800			MOVF	INDF, 0
$0653	$00D8			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,83 :: 		
$0654	$	USART_b75_L_29:
;USART_b75.ppas,85 :: 		
$0654	$158A			BSF	PCLATH, 3
$0655	$207B			CALL	_usart_data_ready
$0656	$118A			BCF	PCLATH, 3
$0657	$0870			MOVF	STACK_0, 0
$0658	$3A00			XORLW	0
$0659	$1903			BTFSC	STATUS, Z
$065A	$2E88			GOTO	USART_b75_L_34
$065B	$	USART_b75_L_33:
;USART_b75.ppas,87 :: 		
$065B	$158A			BSF	PCLATH, 3
$065C	$2048			CALL	_usart_read
$065D	$118A			BCF	PCLATH, 3
$065E	$0870			MOVF	STACK_0, 0
$065F	$00D7			MOVWF	_usart_read_text_local_data
;USART_b75.ppas,88 :: 		
$0660	$0855			MOVF	_usart_read_text_local_i, 0
$0661	$0753			ADDWF	FARG_Usart_Read_Text, 0
$0662	$00F1			MOVWF	STACK_1
$0663	$0871			MOVF	STACK_1, 0
$0664	$0084			MOVWF	FSR
$0665	$0871			MOVF	STACK_1, 0
$0666	$0084			MOVWF	FSR
$0667	$0870			MOVF	STACK_0, 0
$0668	$0080			MOVWF	INDF
;USART_b75.ppas,89 :: 		
$0669	$0857			MOVF	_usart_read_text_local_data, 0
$066A	$0658			XORWF	_usart_read_text_local_data2, 0
$066B	$1D03			BTFSS	STATUS, Z
$066C	$2E72			GOTO	USART_b75_L_37
$066D	$	USART_b75_L_36:
;USART_b75.ppas,91 :: 		
$066D	$0856			MOVF	_usart_read_text_local_j, 0
$066E	$0255			SUBWF	_usart_read_text_local_i, 0
$066F	$00D9			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,92 :: 		
$0670	$0AD6			INCF	_usart_read_text_local_j, 1
;USART_b75.ppas,93 :: 		
$0671	$2E74			GOTO	USART_b75_L_38
;USART_b75.ppas,94 :: 		
$0672	$	USART_b75_L_37:
;USART_b75.ppas,96 :: 		
$0672	$01D6			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,97 :: 		
$0673	$01D9			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,98 :: 		
$0674	$	USART_b75_L_38:
;USART_b75.ppas,100 :: 		
$0674	$0856			MOVF	_usart_read_text_local_j, 0
$0675	$0754			ADDWF	FARG_Usart_Read_Text+1, 0
$0676	$0084			MOVWF	FSR
$0677	$0800			MOVF	INDF, 0
$0678	$00F1			MOVWF	STACK_1
$0679	$0871			MOVF	STACK_1, 0
$067A	$00D8			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,102 :: 		
$067B	$0871			MOVF	STACK_1, 0
$067C	$3A00			XORLW	0
$067D	$1D03			BTFSS	STATUS, Z
$067E	$2E80			GOTO	USART_b75_L_40
$067F	$	USART_b75_L_39:
;USART_b75.ppas,103 :: 		
$067F	$2E89			GOTO	USART_b75_L_30
$0680	$	USART_b75_L_40:
$0680	$	USART_b75_L_41:
;USART_b75.ppas,105 :: 		
$0680	$0AD5			INCF	_usart_read_text_local_i, 1
;USART_b75.ppas,106 :: 		
$0681	$0855			MOVF	_usart_read_text_local_i, 0
$0682	$3C14			SUBLW	20
$0683	$1803			BTFSC	STATUS, C
$0684	$2E88			GOTO	USART_b75_L_43
$0685	$	USART_b75_L_42:
;USART_b75.ppas,108 :: 		
$0685	$3013			MOVLW	19
$0686	$00D9			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,109 :: 		
$0687	$2E89			GOTO	USART_b75_L_30
;USART_b75.ppas,110 :: 		
$0688	$	USART_b75_L_43:
$0688	$	USART_b75_L_44:
;USART_b75.ppas,111 :: 		
$0688	$	USART_b75_L_34:
$0688	$	USART_b75_L_35:
;USART_b75.ppas,112 :: 		
$0688	$2E54			GOTO	USART_b75_L_29
$0689	$	USART_b75_L_30:
;USART_b75.ppas,113 :: 		
$0689	$0859			MOVF	_usart_read_text_local_lasti, 0
$068A	$0753			ADDWF	FARG_Usart_Read_Text, 0
$068B	$00F0			MOVWF	STACK_0
$068C	$0870			MOVF	STACK_0, 0
$068D	$0084			MOVWF	FSR
$068E	$0870			MOVF	STACK_0, 0
$068F	$0084			MOVWF	FSR
$0690	$0180			CLRF	INDF, 1
$0691	$	USART_b75_L_27:
;USART_b75.ppas,114 :: 		
$0691	$0008			RETURN
$039B	$	_strtoint:
;conv.ppas,343 :: 		
;conv.ppas,345 :: 		
$039B	$1303			BCF	STATUS, RP1
$039C	$1283			BCF	STATUS, RP0
$039D	$01D4			CLRF	_strtoint_local_result
$039E	$01D5			CLRF	_strtoint_local_result+1
;conv.ppas,346 :: 		
$039F	$3010			MOVLW	16
$03A0	$00D8			MOVWF	_strtoint_local_ep
$03A1	$3027			MOVLW	39
$03A2	$00D9			MOVWF	_strtoint_local_ep+1
;conv.ppas,347 :: 		
$03A3	$01D6			CLRF	_strtoint_local_i
$03A4	$01D7			CLRF	_strtoint_local_i+1
;conv.ppas,348 :: 		
$03A5	$01DC			CLRF	_strtoint_local_tmp
$03A6	$01DD			CLRF	_strtoint_local_tmp+1
$03A7	$01DE			CLRF	_strtoint_local_tmp+2
$03A8	$01DF			CLRF	_strtoint_local_tmp+3
;conv.ppas,349 :: 		
$03A9	$01DA			CLRF	_strtoint_local_negative
$03AA	$01DB			CLRF	_strtoint_local_negative+1
;conv.ppas,353 :: 		
$03AB	$	conv_L_172:
$03AB	$0856			MOVF	_strtoint_local_i, 0
$03AC	$0753			ADDWF	FARG_StrToInt, 0
$03AD	$0084			MOVWF	FSR
$03AE	$0800			MOVF	INDF, 0
$03AF	$00F4			MOVWF	STACK_4
$03B0	$0874			MOVF	STACK_4, 0
$03B1	$3A00			XORLW	0
$03B2	$1903			BTFSC	STATUS, Z
$03B3	$2C19			GOTO	conv_L_173
;conv.ppas,355 :: 		
$03B4	$0856			MOVF	_strtoint_local_i, 0
$03B5	$0753			ADDWF	FARG_StrToInt, 0
$03B6	$0084			MOVWF	FSR
$03B7	$0800			MOVF	INDF, 0
$03B8	$00F4			MOVWF	STACK_4
$03B9	$0874			MOVF	STACK_4, 0
$03BA	$3A2D			XORLW	45
$03BB	$1D03			BTFSS	STATUS, Z
$03BC	$2BC4			GOTO	conv_L_177
$03BD	$	conv_L_176:
;conv.ppas,357 :: 		
$03BD	$30FF			MOVLW	255
$03BE	$00DA			MOVWF	_strtoint_local_negative
$03BF	$01DB			CLRF	_strtoint_local_negative+1
;conv.ppas,358 :: 		
$03C0	$0AD6			INCF	_strtoint_local_i, 1
$03C1	$1903			BTFSC	STATUS, Z
$03C2	$0AD7			INCF	_strtoint_local_i+1, 1
;conv.ppas,359 :: 		
$03C3	$2BAB			GOTO	conv_L_172
;conv.ppas,360 :: 		
$03C4	$	conv_L_177:
$03C4	$	conv_L_178:
;conv.ppas,361 :: 		
$03C4	$0856			MOVF	_strtoint_local_i, 0
$03C5	$0753			ADDWF	FARG_StrToInt, 0
$03C6	$0084			MOVWF	FSR
$03C7	$0800			MOVF	INDF, 0
$03C8	$00F4			MOVWF	STACK_4
$03C9	$0874			MOVF	STACK_4, 0
$03CA	$3A20			XORLW	32
$03CB	$1903			BTFSC	STATUS, Z
$03CC	$2C07			GOTO	conv_L_180
$03CD	$	conv_L_179:
;conv.ppas,362 :: 		
$03CD	$0856			MOVF	_strtoint_local_i, 0
$03CE	$0753			ADDWF	FARG_StrToInt, 0
$03CF	$0084			MOVWF	FSR
$03D0	$0800			MOVF	INDF, 0
$03D1	$00F0			MOVWF	STACK_0
$03D2	$3030			MOVLW	48
$03D3	$00F8			MOVWF	STACK_8
$03D4	$01F9			CLRF	STACK_8+1
$03D5	$01FA			CLRF	STACK_8+2
$03D6	$01FB			CLRF	STACK_8+3
$03D7	$0870			MOVF	STACK_0, 0
$03D8	$00F4			MOVWF	STACK_4
$03D9	$01F5			CLRF	STACK_4+1
$03DA	$01F6			CLRF	STACK_4+2
$03DB	$01F7			CLRF	STACK_4+3
$03DC	$0874			MOVF	STACK_4, 0
$03DD	$00F0			MOVWF	STACK_0
$03DE	$0875			MOVF	STACK_4+1, 0
$03DF	$00F1			MOVWF	STACK_0+1
$03E0	$0876			MOVF	STACK_4+2, 0
$03E1	$00F2			MOVWF	STACK_0+2
$03E2	$0877			MOVF	STACK_4+3, 0
$03E3	$00F3			MOVWF	STACK_0+3
$03E4	$0878			MOVF	STACK_8, 0
$03E5	$02F0			SUBWF	STACK_0, 1
$03E6	$0879			MOVF	STACK_8+1, 0
$03E7	$1C03			BTFSS	STATUS, C
$03E8	$0F79			INCFSZ	STACK_8+1, 0
$03E9	$02F1			SUBWF	STACK_0+1, 1
$03EA	$087A			MOVF	STACK_8+2, 0
$03EB	$1C03			BTFSS	STATUS, C
$03EC	$0F7A			INCFSZ	STACK_8+2, 0
$03ED	$02F2			SUBWF	STACK_0+2, 1
$03EE	$087B			MOVF	STACK_8+3, 0
$03EF	$1C03			BTFSS	STATUS, C
$03F0	$0F7B			INCFSZ	STACK_8+3, 0
$03F1	$02F3			SUBWF	STACK_0+3, 1
$03F2	$0858			MOVF	_strtoint_local_ep, 0
$03F3	$00F4			MOVWF	STACK_4
$03F4	$0859			MOVF	_strtoint_local_ep+1, 0
$03F5	$00F5			MOVWF	STACK_4+1
$03F6	$01F6			CLRF	STACK_4+2
$03F7	$01F7			CLRF	STACK_4+3
$03F8	$26DB			CALL	_mul_32x32_s
$03F9	$0870			MOVF	STACK_0, 0
$03FA	$07DC			ADDWF	_strtoint_local_tmp, 1
$03FB	$0871			MOVF	STACK_0+1, 0
$03FC	$1803			BTFSC	STATUS, C
$03FD	$0F71			INCFSZ	STACK_0+1, 0
$03FE	$07DD			ADDWF	_strtoint_local_tmp+1, 1
$03FF	$0872			MOVF	STACK_0+2, 0
$0400	$1803			BTFSC	STATUS, C
$0401	$0F72			INCFSZ	STACK_0+2, 0
$0402	$07DE			ADDWF	_strtoint_local_tmp+2, 1
$0403	$0873			MOVF	STACK_0+3, 0
$0404	$1803			BTFSC	STATUS, C
$0405	$0F73			INCFSZ	STACK_0+3, 0
$0406	$07DF			ADDWF	_strtoint_local_tmp+3, 1
$0407	$	conv_L_180:
$0407	$	conv_L_181:
;conv.ppas,363 :: 		
$0407	$300A			MOVLW	10
$0408	$00F4			MOVWF	STACK_4
$0409	$01F5			CLRF	STACK_4+1
$040A	$0858			MOVF	_strtoint_local_ep, 0
$040B	$00F0			MOVWF	STACK_0
$040C	$0859			MOVF	_strtoint_local_ep+1, 0
$040D	$00F1			MOVWF	STACK_0+1
$040E	$158A			BSF	PCLATH, 3
$040F	$2000			CALL	_div_16x16_u
$0410	$118A			BCF	PCLATH, 3
$0411	$0870			MOVF	STACK_0, 0
$0412	$00D8			MOVWF	_strtoint_local_ep
$0413	$0871			MOVF	STACK_0+1, 0
$0414	$00D9			MOVWF	_strtoint_local_ep+1
;conv.ppas,365 :: 		
$0415	$0AD6			INCF	_strtoint_local_i, 1
$0416	$1903			BTFSC	STATUS, Z
$0417	$0AD7			INCF	_strtoint_local_i+1, 1
;conv.ppas,366 :: 		
$0418	$2BAB			GOTO	conv_L_172
$0419	$	conv_L_173:
;conv.ppas,370 :: 		
$0419	$085A			MOVF	_strtoint_local_negative, 0
$041A	$045B			IORWF	_strtoint_local_negative+1, 0
$041B	$1903			BTFSC	STATUS, Z
$041C	$2C21			GOTO	conv_L_183
$041D	$	conv_L_182:
$041D	$3006			MOVLW	6
$041E	$00D8			MOVWF	_strtoint_local_ep
$041F	$01D9			CLRF	_strtoint_local_ep+1
$0420	$2C24			GOTO	conv_L_184
;conv.ppas,371 :: 		
$0421	$	conv_L_183:
$0421	$3005			MOVLW	5
$0422	$00D8			MOVWF	_strtoint_local_ep
$0423	$01D9			CLRF	_strtoint_local_ep+1
$0424	$	conv_L_184:
;conv.ppas,373 :: 		
$0424	$	conv_L_186:
$0424	$0857			MOVF	_strtoint_local_i+1, 0
$0425	$0659			XORWF	_strtoint_local_ep+1, 0
$0426	$1D03			BTFSS	STATUS, Z
$0427	$2C2A			GOTO	L_StrToInt_20
$0428	$0858			MOVF	_strtoint_local_ep, 0
$0429	$0656			XORWF	_strtoint_local_i, 0
$042A	$	L_StrToInt_20:
$042A	$1903			BTFSC	STATUS, Z
$042B	$2C46			GOTO	conv_L_187
;conv.ppas,375 :: 		
$042C	$300A			MOVLW	10
$042D	$00F4			MOVWF	STACK_4
$042E	$01F5			CLRF	STACK_4+1
$042F	$01F6			CLRF	STACK_4+2
$0430	$01F7			CLRF	STACK_4+3
$0431	$085C			MOVF	_strtoint_local_tmp, 0
$0432	$00F0			MOVWF	STACK_0
$0433	$085D			MOVF	_strtoint_local_tmp+1, 0
$0434	$00F1			MOVWF	STACK_0+1
$0435	$085E			MOVF	_strtoint_local_tmp+2, 0
$0436	$00F2			MOVWF	STACK_0+2
$0437	$085F			MOVF	_strtoint_local_tmp+3, 0
$0438	$00F3			MOVWF	STACK_0+3
$0439	$2502			CALL	_div_32x32_s
$043A	$0870			MOVF	STACK_0, 0
$043B	$00DC			MOVWF	_strtoint_local_tmp
$043C	$0871			MOVF	STACK_0+1, 0
$043D	$00DD			MOVWF	_strtoint_local_tmp+1
$043E	$0872			MOVF	STACK_0+2, 0
$043F	$00DE			MOVWF	_strtoint_local_tmp+2
$0440	$0873			MOVF	STACK_0+3, 0
$0441	$00DF			MOVWF	_strtoint_local_tmp+3
;conv.ppas,376 :: 		
$0442	$0AD6			INCF	_strtoint_local_i, 1
$0443	$1903			BTFSC	STATUS, Z
$0444	$0AD7			INCF	_strtoint_local_i+1, 1
;conv.ppas,377 :: 		
$0445	$2C24			GOTO	conv_L_186
$0446	$	conv_L_187:
;conv.ppas,380 :: 		
$0446	$085C			MOVF	_strtoint_local_tmp, 0
$0447	$00D4			MOVWF	_strtoint_local_result
$0448	$085D			MOVF	_strtoint_local_tmp+1, 0
$0449	$00D5			MOVWF	_strtoint_local_result+1
;conv.ppas,382 :: 		
$044A	$3000			MOVLW	0
$044B	$065B			XORWF	_strtoint_local_negative+1, 0
$044C	$1D03			BTFSS	STATUS, Z
$044D	$2C50			GOTO	L_StrToInt_21
$044E	$30FF			MOVLW	255
$044F	$065A			XORWF	_strtoint_local_negative, 0
$0450	$	L_StrToInt_21:
$0450	$1D03			BTFSS	STATUS, Z
$0451	$2C5A			GOTO	conv_L_191
$0452	$	conv_L_190:
;conv.ppas,383 :: 		
$0452	$0854			MOVF	_strtoint_local_result, 0
$0453	$3C00			SUBLW	0
$0454	$00D4			MOVWF	_strtoint_local_result
$0455	$0855			MOVF	_strtoint_local_result+1, 0
$0456	$1C03			BTFSS	STATUS, C
$0457	$3F01			ADDLW	1
$0458	$01D5			CLRF	_strtoint_local_result+1
$0459	$02D5			SUBWF	_strtoint_local_result+1, 1
$045A	$	conv_L_191:
$045A	$	conv_L_192:
$045A	$	conv_L_170:
;conv.ppas,384 :: 		
$045A	$0854			MOVF	_strtoint_local_result, 0
$045B	$00F0			MOVWF	STACK_0
$045C	$0855			MOVF	_strtoint_local_result+1, 0
$045D	$00F1			MOVWF	STACK_0+1
$045E	$0008			RETURN
$077A	$	_alerta:
;Pic1.pbas,25 :: 		sub procedure alerta
;Pic1.pbas,26 :: 		Usart_Write_Text("R")
$077A	$3052			MOVLW	82
$077B	$1303			BCF	STATUS, RP1
$077C	$1283			BCF	STATUS, RP0
$077D	$00D3			MOVWF	?alerta_Local_Text+0
$077E	$01D4			CLRF	?alerta_Local_Text+1
$077F	$3053			MOVLW	?alerta_Local_Text
$0780	$00E0			MOVWF	FARG_Usart_Write_Text
$0781	$158A			BSF	PCLATH, 3
$0782	$201D			CALL	_usart_write_text
$0783	$118A			BCF	PCLATH, 3
;Pic1.pbas,27 :: 		Usart_Write_Text("/")
$0784	$302F			MOVLW	47
$0785	$00D3			MOVWF	?alerta_Local_Text+0
$0786	$01D4			CLRF	?alerta_Local_Text+1
$0787	$3053			MOVLW	?alerta_Local_Text
$0788	$00E0			MOVWF	FARG_Usart_Write_Text
$0789	$158A			BSF	PCLATH, 3
$078A	$201D			CALL	_usart_write_text
$078B	$118A			BCF	PCLATH, 3
$078C	$	Pic1_L_7:
$078C	$0008			RETURN
$059E	$	_envia:
;Pic1.pbas,10 :: 		sub procedure envia
;Pic1.pbas,11 :: 		if priorit = 1 then
$059E	$3000			MOVLW	0
$059F	$1303			BCF	STATUS, RP1
$05A0	$1283			BCF	STATUS, RP0
$05A1	$0622			XORWF	_priorit+1, 0
$05A2	$1D03			BTFSS	STATUS, Z
$05A3	$2DA6			GOTO	L_envia_0
$05A4	$3001			MOVLW	1
$05A5	$0621			XORWF	_priorit, 0
$05A6	$	L_envia_0:
$05A6	$1D03			BTFSS	STATUS, Z
$05A7	$2DC8			GOTO	Pic1_L_2
$05A8	$	Pic1_L_1:
;Pic1.pbas,12 :: 		valorN = 1000 + incN
$05A8	$0825			MOVF	_incn, 0
$05A9	$3FE8			ADDLW	232
$05AA	$00F0			MOVWF	STACK_0
$05AB	$3003			MOVLW	3
$05AC	$1803			BTFSC	STATUS, C
$05AD	$3F01			ADDLW	1
$05AE	$0726			ADDWF	_incn+1, 0
$05AF	$00F1			MOVWF	STACK_0+1
$05B0	$0870			MOVF	STACK_0, 0
$05B1	$00A3			MOVWF	_valorn
$05B2	$0871			MOVF	STACK_0+1, 0
$05B3	$00A4			MOVWF	_valorn+1
;Pic1.pbas,13 :: 		IntToStr(valorN, txt)
$05B4	$0870			MOVF	STACK_0, 0
$05B5	$00E0			MOVWF	FARG_IntToStr
$05B6	$0871			MOVF	STACK_0+1, 0
$05B7	$00E1			MOVWF	FARG_IntToStr+1
$05B8	$3027			MOVLW	_txt
$05B9	$00E2			MOVWF	FARG_IntToStr+2
$05BA	$245F			CALL	_inttostr
;Pic1.pbas,14 :: 		Usart_Write_Text(txt)
$05BB	$3027			MOVLW	_txt
$05BC	$00E0			MOVWF	FARG_Usart_Write_Text
$05BD	$158A			BSF	PCLATH, 3
$05BE	$201D			CALL	_usart_write_text
$05BF	$118A			BCF	PCLATH, 3
;Pic1.pbas,15 :: 		Usart_Write_Text("/")
$05C0	$302F			MOVLW	47
$05C1	$00D3			MOVWF	?envia_Local_Text+0
$05C2	$01D4			CLRF	?envia_Local_Text+1
$05C3	$3053			MOVLW	?envia_Local_Text
$05C4	$00E0			MOVWF	FARG_Usart_Write_Text
$05C5	$158A			BSF	PCLATH, 3
$05C6	$201D			CALL	_usart_write_text
$05C7	$118A			BCF	PCLATH, 3
$05C8	$	Pic1_L_2:
;Pic1.pbas,16 :: 		end if
$05C8	$	Pic1_L_3:
;Pic1.pbas,17 :: 		if priorit = 2 then
$05C8	$3000			MOVLW	0
$05C9	$0622			XORWF	_priorit+1, 0
$05CA	$1D03			BTFSS	STATUS, Z
$05CB	$2DCE			GOTO	L_envia_1
$05CC	$3002			MOVLW	2
$05CD	$0621			XORWF	_priorit, 0
$05CE	$	L_envia_1:
$05CE	$1D03			BTFSS	STATUS, Z
$05CF	$2DF0			GOTO	Pic1_L_5
$05D0	$	Pic1_L_4:
;Pic1.pbas,18 :: 		valorP = 2000 + incP
$05D0	$0830			MOVF	_incp, 0
$05D1	$3FD0			ADDLW	208
$05D2	$00F0			MOVWF	STACK_0
$05D3	$3007			MOVLW	7
$05D4	$1803			BTFSC	STATUS, C
$05D5	$3F01			ADDLW	1
$05D6	$0731			ADDWF	_incp+1, 0
$05D7	$00F1			MOVWF	STACK_0+1
$05D8	$0870			MOVF	STACK_0, 0
$05D9	$00AE			MOVWF	_valorp
$05DA	$0871			MOVF	STACK_0+1, 0
$05DB	$00AF			MOVWF	_valorp+1
;Pic1.pbas,19 :: 		IntToStr(valorP, txt)
$05DC	$0870			MOVF	STACK_0, 0
$05DD	$00E0			MOVWF	FARG_IntToStr
$05DE	$0871			MOVF	STACK_0+1, 0
$05DF	$00E1			MOVWF	FARG_IntToStr+1
$05E0	$3027			MOVLW	_txt
$05E1	$00E2			MOVWF	FARG_IntToStr+2
$05E2	$245F			CALL	_inttostr
;Pic1.pbas,20 :: 		Usart_Write_Text(txt)
$05E3	$3027			MOVLW	_txt
$05E4	$00E0			MOVWF	FARG_Usart_Write_Text
$05E5	$158A			BSF	PCLATH, 3
$05E6	$201D			CALL	_usart_write_text
$05E7	$118A			BCF	PCLATH, 3
;Pic1.pbas,21 :: 		Usart_Write_Text("/")
$05E8	$302F			MOVLW	47
$05E9	$00D3			MOVWF	?envia_Local_Text+0
$05EA	$01D4			CLRF	?envia_Local_Text+1
$05EB	$3053			MOVLW	?envia_Local_Text
$05EC	$00E0			MOVWF	FARG_Usart_Write_Text
$05ED	$158A			BSF	PCLATH, 3
$05EE	$201D			CALL	_usart_write_text
$05EF	$118A			BCF	PCLATH, 3
$05F0	$	Pic1_L_5:
;Pic1.pbas,22 :: 		end if
$05F0	$	Pic1_L_6:
$05F0	$	Pic1_L_0:
$05F0	$0008			RETURN
$0833	$	_usart_init:
;USART_b75.ppas,22 :: 		
;USART_b75.ppas,24 :: 		
$0833	$	USART_b75_L_1:
$0833	$1303			BCF	STATUS, RP1
$0834	$1683			BSF	STATUS, RP0
$0835	$1698			BSF	TXSTA, 5
$0836	$	USART_b75_L_2:
;USART_b75.ppas,25 :: 		
$0836	$3090			MOVLW	144
$0837	$1283			BCF	STATUS, RP0
$0838	$0098			MOVWF	RCSTA
;USART_b75.ppas,31 :: 		
$0839	$	USART_b75_L_3:
$0839	$1683			BSF	STATUS, RP0
$083A	$1686			BSF	TRISB, 5
$083B	$	USART_b75_L_4:
;USART_b75.ppas,32 :: 		
$083B	$	USART_b75_L_5:
$083B	$1786			BSF	TRISB, 7
$083C	$	USART_b75_L_6:
;USART_b75.ppas,35 :: 		
$083C	$	USART_b75_L_8:
$083C	$1283			BCF	STATUS, RP0
$083D	$080C			MOVF	PIR1, 0
$083E	$00F1			MOVWF	STACK_1
$083F	$3000			MOVLW	0
$0840	$1AF1			BTFSC	STACK_1, 5
$0841	$3001			MOVLW	1
$0842	$00F1			MOVWF	STACK_1
$0843	$0871			MOVF	STACK_1, 0
$0844	$3A01			XORLW	1
$0845	$1903			BTFSC	STATUS, Z
$0846	$283C			GOTO	USART_b75_L_8
;USART_b75.ppas,36 :: 		
$0847	$	USART_b75_L_9:
$0847	$	USART_b75_L_0:
;USART_b75.ppas,37 :: 		
$0847	$0008			RETURN
$0692	$	_mul_16x16_s:
$0692	$1303			BCF	STATUS, RP1
$0693	$1283			BCF	STATUS, RP0
;math.ppas,203 :: 		
;math.ppas,205 :: 		
$0694	$01FB			CLRF	STACK_11
;math.ppas,206 :: 		
$0695	$01FA			CLRF	STACK_10
;math.ppas,207 :: 		
$0696	$01F9			CLRF	STACK_9
;math.ppas,208 :: 		
$0697	$3080			MOVLW	128
;math.ppas,210 :: 		
$0698	$00F8			MOVWF	STACK_8
;math.ppas,212 :: 		
$0699	$01FD			CLRF	STACK_13
;math.ppas,213 :: 		
$069A	$1FF1			BTFSS	STACK_1, 7
;math.ppas,214 :: 		
$069B	$2EA2			GOTO	$+7
;math.ppas,215 :: 		
$069C	$09F1			COMF	STACK_1, F
;math.ppas,216 :: 		
$069D	$09F0			COMF	STACK_0, F
;math.ppas,217 :: 		
$069E	$0AF0			INCF	STACK_0, F
;math.ppas,218 :: 		
$069F	$1903			BTFSC	STATUS, Z
;math.ppas,219 :: 		
$06A0	$0AF1			INCF	STACK_1, F
;math.ppas,221 :: 		
$06A1	$0AFD			INCF	STACK_13, F
;math.ppas,222 :: 		
$06A2	$1FF5			BTFSS	STACK_5, 7
;math.ppas,223 :: 		
$06A3	$2EAA			GOTO	$+7
;math.ppas,224 :: 		
$06A4	$09F5			COMF	STACK_5, F
;math.ppas,225 :: 		
$06A5	$09F4			COMF	STACK_4, F
;math.ppas,226 :: 		
$06A6	$0AF4			INCF	STACK_4, F
;math.ppas,227 :: 		
$06A7	$1903			BTFSC	STATUS, Z
;math.ppas,228 :: 		
$06A8	$0AF5			INCF	STACK_5, F
;math.ppas,230 :: 		
$06A9	$0AFD			INCF	STACK_13, F
;math.ppas,231 :: 		
$06AA	$0CF1			RRF	STACK_1, F
;math.ppas,233 :: 		
$06AB	$0CF0			RRF	STACK_0, F
;math.ppas,234 :: 		
$06AC	$1C03			BTFSS	STATUS, C
;math.ppas,235 :: 		
$06AD	$2EB7			GOTO	$+10
;math.ppas,236 :: 		
$06AE	$0874			MOVF	STACK_4, W
;math.ppas,238 :: 		
$06AF	$07F9			ADDWF	STACK_9, F
;math.ppas,239 :: 		
$06B0	$0875			MOVF	STACK_5, W
;math.ppas,240 :: 		
$06B1	$1803			BTFSC	STATUS, C
;math.ppas,241 :: 		
$06B2	$0F75			INCFSZ	STACK_5, W
;math.ppas,242 :: 		
$06B3	$07FA			ADDWF	STACK_10, F
;math.ppas,243 :: 		
$06B4	$1803			BTFSC	STATUS, C
;math.ppas,244 :: 		
$06B5	$0AFB			INCF	STACK_11, F
;math.ppas,246 :: 		
$06B6	$1003			BCF	STATUS, C
;math.ppas,247 :: 		
$06B7	$1FF0			BTFSS	STACK_0, 7
;math.ppas,248 :: 		
$06B8	$2EBF			GOTO	$+7
;math.ppas,249 :: 		
$06B9	$0874			MOVF	STACK_4, W
;math.ppas,250 :: 		
$06BA	$07FA			ADDWF	STACK_10, F
;math.ppas,251 :: 		
$06BB	$1803			BTFSC	STATUS, C
;math.ppas,252 :: 		
$06BC	$0AFB			INCF	STACK_11, F
;math.ppas,253 :: 		
$06BD	$0875			MOVF	STACK_5, W
;math.ppas,255 :: 		
$06BE	$07FB			ADDWF	STACK_11, F
;math.ppas,256 :: 		
$06BF	$0CFB			RRF	STACK_11, F
;math.ppas,257 :: 		
$06C0	$0CFA			RRF	STACK_10, F
;math.ppas,258 :: 		
$06C1	$0CF9			RRF	STACK_9, F
;math.ppas,260 :: 		
$06C2	$0CF8			RRF	STACK_8, F
;math.ppas,261 :: 		
$06C3	$1C03			BTFSS	STATUS, C
;math.ppas,262 :: 		
$06C4	$2EAA			GOTO	$-26
;math.ppas,263 :: 		
$06C5	$1C7D			BTFSS	STACK_13, 0
;math.ppas,265 :: 		
$06C6	$2ED2			GOTO	$+12
;math.ppas,266 :: 		
$06C7	$09FB			COMF	STACK_11, F
;math.ppas,267 :: 		
$06C8	$09FA			COMF	STACK_10, F
;math.ppas,268 :: 		
$06C9	$09F9			COMF	STACK_9, F
;math.ppas,270 :: 		
$06CA	$09F8			COMF	STACK_8, F
;math.ppas,271 :: 		
$06CB	$0AF8			INCF	STACK_8, F
;math.ppas,272 :: 		
$06CC	$1903			BTFSC	STATUS, Z
;math.ppas,273 :: 		
$06CD	$0AF9			INCF	STACK_9, F
;math.ppas,274 :: 		
$06CE	$1903			BTFSC	STATUS, Z
;math.ppas,275 :: 		
$06CF	$0AFA			INCF	STACK_10, F
;math.ppas,276 :: 		
$06D0	$1903			BTFSC	STATUS, Z
;math.ppas,278 :: 		
$06D1	$0AFB			INCF	STACK_11, F
;math.ppas,279 :: 		
$06D2	$087B			MOVF	STACK_11, W
;math.ppas,280 :: 		
$06D3	$00F3			MOVWF	STACK_3
;math.ppas,281 :: 		
$06D4	$087A			MOVF	STACK_10, W
;math.ppas,282 :: 		
$06D5	$00F2			MOVWF	STACK_2
;math.ppas,283 :: 		
$06D6	$0879			MOVF	STACK_9, W
;math.ppas,284 :: 		
$06D7	$00F1			MOVWF	STACK_1
;math.ppas,285 :: 		
$06D8	$0878			MOVF	STACK_8, W
;math.ppas,286 :: 		
$06D9	$00F0			MOVWF	STACK_0
;math.ppas,287 :: 		
$06DA	$	math_L_5:
;math.ppas,288 :: 		
$06DA	$0008			RETURN
$0004	$	_main:
;Pic1.pbas,30 :: 		main:
$0004	$	_main_main:
;Pic1.pbas,31 :: 		TRISA=%11111111
$0004	$30FF			MOVLW	255
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0085			MOVWF	TRISA
;Pic1.pbas,32 :: 		TRISB=%01101111
$0008	$306F			MOVLW	111
$0009	$0086			MOVWF	TRISB
;Pic1.pbas,33 :: 		TRISC=%00000000
$000A	$0187			CLRF	TRISC, 1
;Pic1.pbas,34 :: 		INTCON=%00000000
$000B	$018B			CLRF	INTCON, 1
;Pic1.pbas,35 :: 		ANSEL=%00000000
$000C	$1703			BSF	STATUS, RP1
$000D	$1283			BCF	STATUS, RP0
$000E	$019E			CLRF	ANSEL, 1
;Pic1.pbas,36 :: 		ANSELH=%00000000
$000F	$019F			CLRF	ANSELH, 1
;Pic1.pbas,37 :: 		PORTC=0
$0010	$1303			BCF	STATUS, RP1
$0011	$0187			CLRF	PORTC, 1
;Pic1.pbas,38 :: 		Usart_Init(9600)
$0012	$3019			MOVLW	25
$0013	$1683			BSF	STATUS, RP0
$0014	$0099			MOVWF	SPBRG
$0015	$1518			BSF	TXSTA, BRGH
$0016	$158A			BSF	PCLATH, 3
$0017	$2033			CALL	_usart_init
$0018	$118A			BCF	PCLATH, 3
;Pic1.pbas,40 :: 		b0=false
$0019	$01B2			CLRF	_b0, 1
;Pic1.pbas,41 :: 		b1=false
$001A	$01B3			CLRF	_b1, 1
;Pic1.pbas,42 :: 		b2=false
$001B	$01B4			CLRF	_b2, 1
;Pic1.pbas,43 :: 		b3=false
$001C	$01B5			CLRF	_b3, 1
;Pic1.pbas,44 :: 		b4=false
$001D	$01B6			CLRF	_b4, 1
;Pic1.pbas,45 :: 		b5=false
$001E	$01B7			CLRF	_b5, 1
;Pic1.pbas,46 :: 		priorit=1
$001F	$3001			MOVLW	1
$0020	$00A1			MOVWF	_priorit
$0021	$01A2			CLRF	_priorit+1
;Pic1.pbas,47 :: 		incP=0
$0022	$01B0			CLRF	_incp
$0023	$01B1			CLRF	_incp+1
;Pic1.pbas,48 :: 		incN=0
$0024	$01A5			CLRF	_incn
$0025	$01A6			CLRF	_incn+1
;Pic1.pbas,50 :: 		executa:
$0026	$	_main_executa:
;Pic1.pbas,52 :: 		if USART_Data_Ready() > 0 then
$0026	$158A			BSF	PCLATH, 3
$0027	$207B			CALL	_usart_data_ready
$0028	$118A			BCF	PCLATH, 3
$0029	$0870			MOVF	STACK_0, 0
$002A	$3C00			SUBLW	0
$002B	$1803			BTFSC	STATUS, C
$002C	$283C			GOTO	Pic1_L_10
$002D	$	Pic1_L_9:
;Pic1.pbas,53 :: 		Usart_Read_Text(recebe, "/")
$002D	$3038			MOVLW	_recebe
$002E	$00D3			MOVWF	FARG_Usart_Read_Text
$002F	$302F			MOVLW	47
$0030	$00C9			MOVWF	?main_Local_Text+0
$0031	$01CA			CLRF	?main_Local_Text+1
$0032	$3049			MOVLW	?main_Local_Text
$0033	$00D4			MOVWF	FARG_Usart_Read_Text+1
$0034	$264B			CALL	_usart_read_text
;Pic1.pbas,54 :: 		valor = StrToInt(recebe)
$0035	$3038			MOVLW	_recebe
$0036	$00D3			MOVWF	FARG_StrToInt
$0037	$239B			CALL	_strtoint
$0038	$0870			MOVF	STACK_0, 0
$0039	$00BF			MOVWF	_valor
$003A	$0871			MOVF	STACK_0+1, 0
$003B	$00C0			MOVWF	_valor+1
$003C	$	Pic1_L_10:
;Pic1.pbas,55 :: 		end if
$003C	$	Pic1_L_11:
;Pic1.pbas,58 :: 		if testbit(portA,0) = 1 then
$003C	$3001			MOVLW	1
$003D	$0505			ANDWF	PORTA, 0
$003E	$00F2			MOVWF	STACK_2
$003F	$0872			MOVF	STACK_2, 0
$0040	$3A01			XORLW	1
$0041	$1D03			BTFSS	STATUS, Z
$0042	$28A4			GOTO	Pic1_L_13
$0043	$	Pic1_L_12:
;Pic1.pbas,59 :: 		if b0 = false then
$0043	$0832			MOVF	_b0, 0
$0044	$3A00			XORLW	0
$0045	$1D03			BTFSS	STATUS, Z
$0046	$28A4			GOTO	Pic1_L_16
$0047	$	Pic1_L_15:
;Pic1.pbas,60 :: 		b0 = true
$0047	$30FF			MOVLW	255
$0048	$00B2			MOVWF	_b0
;Pic1.pbas,61 :: 		if priorit = 1 then
$0049	$3000			MOVLW	0
$004A	$0622			XORWF	_priorit+1, 0
$004B	$1D03			BTFSS	STATUS, Z
$004C	$284F			GOTO	L_main_2
$004D	$3001			MOVLW	1
$004E	$0621			XORWF	_priorit, 0
$004F	$	L_main_2:
$004F	$1D03			BTFSS	STATUS, Z
$0050	$287B			GOTO	Pic1_L_19
$0051	$	Pic1_L_18:
;Pic1.pbas,62 :: 		incN = incN + 1
$0051	$0825			MOVF	_incn, 0
$0052	$3F01			ADDLW	1
$0053	$00F2			MOVWF	STACK_2
$0054	$3000			MOVLW	0
$0055	$1803			BTFSC	STATUS, C
$0056	$3F01			ADDLW	1
$0057	$0726			ADDWF	_incn+1, 0
$0058	$00F3			MOVWF	STACK_2+1
$0059	$0872			MOVF	STACK_2, 0
$005A	$00A5			MOVWF	_incn
$005B	$0873			MOVF	STACK_2+1, 0
$005C	$00A6			MOVWF	_incn+1
;Pic1.pbas,63 :: 		if incN > 999 then
$005D	$3080			MOVLW	128
$005E	$3A03			XORLW	3
$005F	$00F0			MOVWF	STACK_0
$0060	$3080			MOVLW	128
$0061	$0673			XORWF	STACK_2+1, 0
$0062	$0270			SUBWF	STACK_0, 0
$0063	$1D03			BTFSS	STATUS, Z
$0064	$2867			GOTO	L_main_3
$0065	$0872			MOVF	STACK_2, 0
$0066	$3CE7			SUBLW	231
$0067	$	L_main_3:
$0067	$1803			BTFSC	STATUS, C
$0068	$286D			GOTO	Pic1_L_22
$0069	$	Pic1_L_21:
;Pic1.pbas,64 :: 		incN = 999
$0069	$30E7			MOVLW	231
$006A	$00A5			MOVWF	_incn
$006B	$3003			MOVLW	3
$006C	$00A6			MOVWF	_incn+1
$006D	$	Pic1_L_22:
;Pic1.pbas,65 :: 		end if
$006D	$	Pic1_L_23:
;Pic1.pbas,66 :: 		if incN < 0 then
$006D	$3080			MOVLW	128
$006E	$0626			XORWF	_incn+1, 0
$006F	$00F0			MOVWF	STACK_0
$0070	$3080			MOVLW	128
$0071	$0270			SUBWF	STACK_0, 0
$0072	$1D03			BTFSS	STATUS, Z
$0073	$2876			GOTO	L_main_4
$0074	$3000			MOVLW	0
$0075	$0225			SUBWF	_incn, 0
$0076	$	L_main_4:
$0076	$1803			BTFSC	STATUS, C
$0077	$287A			GOTO	Pic1_L_25
$0078	$	Pic1_L_24:
;Pic1.pbas,67 :: 		incN = 0
$0078	$01A5			CLRF	_incn
$0079	$01A6			CLRF	_incn+1
$007A	$	Pic1_L_25:
;Pic1.pbas,68 :: 		end if
$007A	$	Pic1_L_26:
$007A	$28A4			GOTO	Pic1_L_20
;Pic1.pbas,69 :: 		else
$007B	$	Pic1_L_19:
;Pic1.pbas,70 :: 		incP = incP + 1
$007B	$0830			MOVF	_incp, 0
$007C	$3F01			ADDLW	1
$007D	$00F2			MOVWF	STACK_2
$007E	$3000			MOVLW	0
$007F	$1803			BTFSC	STATUS, C
$0080	$3F01			ADDLW	1
$0081	$0731			ADDWF	_incp+1, 0
$0082	$00F3			MOVWF	STACK_2+1
$0083	$0872			MOVF	STACK_2, 0
$0084	$00B0			MOVWF	_incp
$0085	$0873			MOVF	STACK_2+1, 0
$0086	$00B1			MOVWF	_incp+1
;Pic1.pbas,71 :: 		if incP > 999 then
$0087	$3080			MOVLW	128
$0088	$3A03			XORLW	3
$0089	$00F0			MOVWF	STACK_0
$008A	$3080			MOVLW	128
$008B	$0673			XORWF	STACK_2+1, 0
$008C	$0270			SUBWF	STACK_0, 0
$008D	$1D03			BTFSS	STATUS, Z
$008E	$2891			GOTO	L_main_5
$008F	$0872			MOVF	STACK_2, 0
$0090	$3CE7			SUBLW	231
$0091	$	L_main_5:
$0091	$1803			BTFSC	STATUS, C
$0092	$2897			GOTO	Pic1_L_28
$0093	$	Pic1_L_27:
;Pic1.pbas,72 :: 		incP = 999
$0093	$30E7			MOVLW	231
$0094	$00B0			MOVWF	_incp
$0095	$3003			MOVLW	3
$0096	$00B1			MOVWF	_incp+1
$0097	$	Pic1_L_28:
;Pic1.pbas,73 :: 		end if
$0097	$	Pic1_L_29:
;Pic1.pbas,74 :: 		if incP < 0 then
$0097	$3080			MOVLW	128
$0098	$0631			XORWF	_incp+1, 0
$0099	$00F0			MOVWF	STACK_0
$009A	$3080			MOVLW	128
$009B	$0270			SUBWF	STACK_0, 0
$009C	$1D03			BTFSS	STATUS, Z
$009D	$28A0			GOTO	L_main_6
$009E	$3000			MOVLW	0
$009F	$0230			SUBWF	_incp, 0
$00A0	$	L_main_6:
$00A0	$1803			BTFSC	STATUS, C
$00A1	$28A4			GOTO	Pic1_L_31
$00A2	$	Pic1_L_30:
;Pic1.pbas,75 :: 		incP = 0
$00A2	$01B0			CLRF	_incp
$00A3	$01B1			CLRF	_incp+1
$00A4	$	Pic1_L_31:
;Pic1.pbas,76 :: 		end if
$00A4	$	Pic1_L_32:
;Pic1.pbas,77 :: 		end if
$00A4	$	Pic1_L_20:
$00A4	$	Pic1_L_16:
;Pic1.pbas,78 :: 		end if
$00A4	$	Pic1_L_17:
$00A4	$	Pic1_L_13:
;Pic1.pbas,79 :: 		end if
$00A4	$	Pic1_L_14:
;Pic1.pbas,80 :: 		if testbit(portA,0) = 0 then
$00A4	$3001			MOVLW	1
$00A5	$0505			ANDWF	PORTA, 0
$00A6	$00F2			MOVWF	STACK_2
$00A7	$0872			MOVF	STACK_2, 0
$00A8	$3A00			XORLW	0
$00A9	$1D03			BTFSS	STATUS, Z
$00AA	$28B0			GOTO	Pic1_L_34
$00AB	$	Pic1_L_33:
;Pic1.pbas,81 :: 		if b0 = true then
$00AB	$0832			MOVF	_b0, 0
$00AC	$3AFF			XORLW	255
$00AD	$1D03			BTFSS	STATUS, Z
$00AE	$28B0			GOTO	Pic1_L_37
$00AF	$	Pic1_L_36:
;Pic1.pbas,82 :: 		b0 = false
$00AF	$01B2			CLRF	_b0, 1
$00B0	$	Pic1_L_37:
;Pic1.pbas,83 :: 		end if
$00B0	$	Pic1_L_38:
$00B0	$	Pic1_L_34:
;Pic1.pbas,84 :: 		end if
$00B0	$	Pic1_L_35:
;Pic1.pbas,87 :: 		if testbit(portA,1) = 1 then
$00B0	$3000			MOVLW	0
$00B1	$1885			BTFSC	PORTA, 1
$00B2	$3001			MOVLW	1
$00B3	$00F2			MOVWF	STACK_2
$00B4	$0872			MOVF	STACK_2, 0
$00B5	$3A01			XORLW	1
$00B6	$1D03			BTFSS	STATUS, Z
$00B7	$28CF			GOTO	Pic1_L_40
$00B8	$	Pic1_L_39:
;Pic1.pbas,88 :: 		if b1 = false then
$00B8	$0833			MOVF	_b1, 0
$00B9	$3A00			XORLW	0
$00BA	$1D03			BTFSS	STATUS, Z
$00BB	$28CF			GOTO	Pic1_L_43
$00BC	$	Pic1_L_42:
;Pic1.pbas,89 :: 		b1 = true
$00BC	$30FF			MOVLW	255
$00BD	$00B3			MOVWF	_b1
;Pic1.pbas,90 :: 		if priorit = 1 then
$00BE	$3000			MOVLW	0
$00BF	$0622			XORWF	_priorit+1, 0
$00C0	$1D03			BTFSS	STATUS, Z
$00C1	$28C4			GOTO	L_main_7
$00C2	$3001			MOVLW	1
$00C3	$0621			XORWF	_priorit, 0
$00C4	$	L_main_7:
$00C4	$1D03			BTFSS	STATUS, Z
$00C5	$28CB			GOTO	Pic1_L_46
$00C6	$	Pic1_L_45:
;Pic1.pbas,91 :: 		incN = incN - 1
$00C6	$3001			MOVLW	1
$00C7	$02A5			SUBWF	_incn, 1
$00C8	$1C03			BTFSS	STATUS, C
$00C9	$03A6			DECF	_incn+1, 1
$00CA	$28CF			GOTO	Pic1_L_47
;Pic1.pbas,92 :: 		else
$00CB	$	Pic1_L_46:
;Pic1.pbas,93 :: 		incP = incP - 1
$00CB	$3001			MOVLW	1
$00CC	$02B0			SUBWF	_incp, 1
$00CD	$1C03			BTFSS	STATUS, C
$00CE	$03B1			DECF	_incp+1, 1
;Pic1.pbas,94 :: 		end if
$00CF	$	Pic1_L_47:
$00CF	$	Pic1_L_43:
;Pic1.pbas,95 :: 		end if
$00CF	$	Pic1_L_44:
$00CF	$	Pic1_L_40:
;Pic1.pbas,96 :: 		end if
$00CF	$	Pic1_L_41:
;Pic1.pbas,97 :: 		if testbit(portA,1) = 0 then
$00CF	$3000			MOVLW	0
$00D0	$1885			BTFSC	PORTA, 1
$00D1	$3001			MOVLW	1
$00D2	$00F2			MOVWF	STACK_2
$00D3	$0872			MOVF	STACK_2, 0
$00D4	$3A00			XORLW	0
$00D5	$1D03			BTFSS	STATUS, Z
$00D6	$28DC			GOTO	Pic1_L_49
$00D7	$	Pic1_L_48:
;Pic1.pbas,98 :: 		if b1 = true then
$00D7	$0833			MOVF	_b1, 0
$00D8	$3AFF			XORLW	255
$00D9	$1D03			BTFSS	STATUS, Z
$00DA	$28DC			GOTO	Pic1_L_52
$00DB	$	Pic1_L_51:
;Pic1.pbas,99 :: 		b1 = false
$00DB	$01B3			CLRF	_b1, 1
$00DC	$	Pic1_L_52:
;Pic1.pbas,100 :: 		end if
$00DC	$	Pic1_L_53:
$00DC	$	Pic1_L_49:
;Pic1.pbas,101 :: 		end if
$00DC	$	Pic1_L_50:
;Pic1.pbas,104 :: 		if testbit(portA,2) = 1 then
$00DC	$3000			MOVLW	0
$00DD	$1905			BTFSC	PORTA, 2
$00DE	$3001			MOVLW	1
$00DF	$00F2			MOVWF	STACK_2
$00E0	$0872			MOVF	STACK_2, 0
$00E1	$3A01			XORLW	1
$00E2	$1D03			BTFSS	STATUS, Z
$00E3	$28EE			GOTO	Pic1_L_55
$00E4	$	Pic1_L_54:
;Pic1.pbas,105 :: 		if b2 = false then
$00E4	$0834			MOVF	_b2, 0
$00E5	$3A00			XORLW	0
$00E6	$1D03			BTFSS	STATUS, Z
$00E7	$28EE			GOTO	Pic1_L_58
$00E8	$	Pic1_L_57:
;Pic1.pbas,106 :: 		b2 = true
$00E8	$30FF			MOVLW	255
$00E9	$00B4			MOVWF	_b2
;Pic1.pbas,107 :: 		incN = 0
$00EA	$01A5			CLRF	_incn
$00EB	$01A6			CLRF	_incn+1
;Pic1.pbas,108 :: 		incP = 0
$00EC	$01B0			CLRF	_incp
$00ED	$01B1			CLRF	_incp+1
$00EE	$	Pic1_L_58:
;Pic1.pbas,109 :: 		end if
$00EE	$	Pic1_L_59:
$00EE	$	Pic1_L_55:
;Pic1.pbas,110 :: 		end if
$00EE	$	Pic1_L_56:
;Pic1.pbas,111 :: 		if testbit(portA,2) = 0 then
$00EE	$3000			MOVLW	0
$00EF	$1905			BTFSC	PORTA, 2
$00F0	$3001			MOVLW	1
$00F1	$00F2			MOVWF	STACK_2
$00F2	$0872			MOVF	STACK_2, 0
$00F3	$3A00			XORLW	0
$00F4	$1D03			BTFSS	STATUS, Z
$00F5	$28FB			GOTO	Pic1_L_61
$00F6	$	Pic1_L_60:
;Pic1.pbas,112 :: 		if b2 = true then
$00F6	$0834			MOVF	_b2, 0
$00F7	$3AFF			XORLW	255
$00F8	$1D03			BTFSS	STATUS, Z
$00F9	$28FB			GOTO	Pic1_L_64
$00FA	$	Pic1_L_63:
;Pic1.pbas,113 :: 		b2 = false
$00FA	$01B4			CLRF	_b2, 1
$00FB	$	Pic1_L_64:
;Pic1.pbas,114 :: 		end if
$00FB	$	Pic1_L_65:
$00FB	$	Pic1_L_61:
;Pic1.pbas,115 :: 		end if
$00FB	$	Pic1_L_62:
;Pic1.pbas,118 :: 		if testbit(portA,3) = 1 then
$00FB	$3000			MOVLW	0
$00FC	$1985			BTFSC	PORTA, 3
$00FD	$3001			MOVLW	1
$00FE	$00F2			MOVWF	STACK_2
$00FF	$0872			MOVF	STACK_2, 0
$0100	$3A01			XORLW	1
$0101	$1D03			BTFSS	STATUS, Z
$0102	$2918			GOTO	Pic1_L_67
$0103	$	Pic1_L_66:
;Pic1.pbas,119 :: 		if b3 = false then
$0103	$0835			MOVF	_b3, 0
$0104	$3A00			XORLW	0
$0105	$1D03			BTFSS	STATUS, Z
$0106	$2918			GOTO	Pic1_L_70
$0107	$	Pic1_L_69:
;Pic1.pbas,120 :: 		b3 = true
$0107	$30FF			MOVLW	255
$0108	$00B5			MOVWF	_b3
;Pic1.pbas,121 :: 		if priorit = 1 then
$0109	$3000			MOVLW	0
$010A	$0622			XORWF	_priorit+1, 0
$010B	$1D03			BTFSS	STATUS, Z
$010C	$290F			GOTO	L_main_8
$010D	$3001			MOVLW	1
$010E	$0621			XORWF	_priorit, 0
$010F	$	L_main_8:
$010F	$1D03			BTFSS	STATUS, Z
$0110	$2915			GOTO	Pic1_L_73
$0111	$	Pic1_L_72:
;Pic1.pbas,122 :: 		priorit = 2
$0111	$3002			MOVLW	2
$0112	$00A1			MOVWF	_priorit
$0113	$01A2			CLRF	_priorit+1
$0114	$2918			GOTO	Pic1_L_74
;Pic1.pbas,123 :: 		else
$0115	$	Pic1_L_73:
;Pic1.pbas,124 :: 		priorit = 1
$0115	$3001			MOVLW	1
$0116	$00A1			MOVWF	_priorit
$0117	$01A2			CLRF	_priorit+1
;Pic1.pbas,125 :: 		end if
$0118	$	Pic1_L_74:
$0118	$	Pic1_L_70:
;Pic1.pbas,126 :: 		end if
$0118	$	Pic1_L_71:
$0118	$	Pic1_L_67:
;Pic1.pbas,127 :: 		end if
$0118	$	Pic1_L_68:
;Pic1.pbas,128 :: 		if testbit(portA,3) = 0 then
$0118	$3000			MOVLW	0
$0119	$1985			BTFSC	PORTA, 3
$011A	$3001			MOVLW	1
$011B	$00F2			MOVWF	STACK_2
$011C	$0872			MOVF	STACK_2, 0
$011D	$3A00			XORLW	0
$011E	$1D03			BTFSS	STATUS, Z
$011F	$2925			GOTO	Pic1_L_76
$0120	$	Pic1_L_75:
;Pic1.pbas,129 :: 		if b3 = true then
$0120	$0835			MOVF	_b3, 0
$0121	$3AFF			XORLW	255
$0122	$1D03			BTFSS	STATUS, Z
$0123	$2925			GOTO	Pic1_L_79
$0124	$	Pic1_L_78:
;Pic1.pbas,130 :: 		b3 = false
$0124	$01B5			CLRF	_b3, 1
$0125	$	Pic1_L_79:
;Pic1.pbas,131 :: 		end if
$0125	$	Pic1_L_80:
$0125	$	Pic1_L_76:
;Pic1.pbas,132 :: 		end if
$0125	$	Pic1_L_77:
;Pic1.pbas,135 :: 		if testbit(portA,4) = 1 then
$0125	$3000			MOVLW	0
$0126	$1A05			BTFSC	PORTA, 4
$0127	$3001			MOVLW	1
$0128	$00F2			MOVWF	STACK_2
$0129	$0872			MOVF	STACK_2, 0
$012A	$3A01			XORLW	1
$012B	$1D03			BTFSS	STATUS, Z
$012C	$2934			GOTO	Pic1_L_82
$012D	$	Pic1_L_81:
;Pic1.pbas,136 :: 		if b4 = false then
$012D	$0836			MOVF	_b4, 0
$012E	$3A00			XORLW	0
$012F	$1D03			BTFSS	STATUS, Z
$0130	$2934			GOTO	Pic1_L_85
$0131	$	Pic1_L_84:
;Pic1.pbas,137 :: 		b4 = true
$0131	$30FF			MOVLW	255
$0132	$00B6			MOVWF	_b4
;Pic1.pbas,138 :: 		alerta
$0133	$277A			CALL	_alerta
$0134	$	Pic1_L_85:
;Pic1.pbas,139 :: 		end if
$0134	$	Pic1_L_86:
$0134	$	Pic1_L_82:
;Pic1.pbas,140 :: 		end if
$0134	$	Pic1_L_83:
;Pic1.pbas,141 :: 		if testbit(portA,4) = 0 then
$0134	$3000			MOVLW	0
$0135	$1A05			BTFSC	PORTA, 4
$0136	$3001			MOVLW	1
$0137	$00F2			MOVWF	STACK_2
$0138	$0872			MOVF	STACK_2, 0
$0139	$3A00			XORLW	0
$013A	$1D03			BTFSS	STATUS, Z
$013B	$2941			GOTO	Pic1_L_88
$013C	$	Pic1_L_87:
;Pic1.pbas,142 :: 		if b4 = true then
$013C	$0836			MOVF	_b4, 0
$013D	$3AFF			XORLW	255
$013E	$1D03			BTFSS	STATUS, Z
$013F	$2941			GOTO	Pic1_L_91
$0140	$	Pic1_L_90:
;Pic1.pbas,143 :: 		b4 = false
$0140	$01B6			CLRF	_b4, 1
$0141	$	Pic1_L_91:
;Pic1.pbas,144 :: 		end if
$0141	$	Pic1_L_92:
$0141	$	Pic1_L_88:
;Pic1.pbas,145 :: 		end if
$0141	$	Pic1_L_89:
;Pic1.pbas,148 :: 		if testbit(portA,5) = 1 then
$0141	$3000			MOVLW	0
$0142	$1A85			BTFSC	PORTA, 5
$0143	$3001			MOVLW	1
$0144	$00F2			MOVWF	STACK_2
$0145	$0872			MOVF	STACK_2, 0
$0146	$3A01			XORLW	1
$0147	$1D03			BTFSS	STATUS, Z
$0148	$2950			GOTO	Pic1_L_94
$0149	$	Pic1_L_93:
;Pic1.pbas,149 :: 		if b5 = false then
$0149	$0837			MOVF	_b5, 0
$014A	$3A00			XORLW	0
$014B	$1D03			BTFSS	STATUS, Z
$014C	$2950			GOTO	Pic1_L_97
$014D	$	Pic1_L_96:
;Pic1.pbas,150 :: 		b5 = true
$014D	$30FF			MOVLW	255
$014E	$00B7			MOVWF	_b5
;Pic1.pbas,151 :: 		envia
$014F	$259E			CALL	_envia
$0150	$	Pic1_L_97:
;Pic1.pbas,152 :: 		end if
$0150	$	Pic1_L_98:
$0150	$	Pic1_L_94:
;Pic1.pbas,153 :: 		end if
$0150	$	Pic1_L_95:
;Pic1.pbas,154 :: 		if testbit(portA,5) = 0 then
$0150	$3000			MOVLW	0
$0151	$1A85			BTFSC	PORTA, 5
$0152	$3001			MOVLW	1
$0153	$00F2			MOVWF	STACK_2
$0154	$0872			MOVF	STACK_2, 0
$0155	$3A00			XORLW	0
$0156	$1D03			BTFSS	STATUS, Z
$0157	$2959			GOTO	Pic1_L_100
$0158	$	Pic1_L_99:
;Pic1.pbas,155 :: 		b5 = false
$0158	$01B7			CLRF	_b5, 1
$0159	$	Pic1_L_100:
;Pic1.pbas,156 :: 		end if
$0159	$	Pic1_L_101:
;Pic1.pbas,159 :: 		if priorit = 1 then
$0159	$3000			MOVLW	0
$015A	$0622			XORWF	_priorit+1, 0
$015B	$1D03			BTFSS	STATUS, Z
$015C	$295F			GOTO	L_main_9
$015D	$3001			MOVLW	1
$015E	$0621			XORWF	_priorit, 0
$015F	$	L_main_9:
$015F	$1D03			BTFSS	STATUS, Z
$0160	$296A			GOTO	Pic1_L_103
$0161	$	Pic1_L_102:
;Pic1.pbas,160 :: 		valor = incN + 1000
$0161	$30E8			MOVLW	232
$0162	$0725			ADDWF	_incn, 0
$0163	$00BF			MOVWF	_valor
$0164	$0826			MOVF	_incn+1, 0
$0165	$1803			BTFSC	STATUS, C
$0166	$3F01			ADDLW	1
$0167	$3F03			ADDLW	3
$0168	$00C0			MOVWF	_valor+1
$0169	$2972			GOTO	Pic1_L_104
;Pic1.pbas,161 :: 		else
$016A	$	Pic1_L_103:
;Pic1.pbas,162 :: 		valor = incP + 2000
$016A	$30D0			MOVLW	208
$016B	$0730			ADDWF	_incp, 0
$016C	$00BF			MOVWF	_valor
$016D	$0831			MOVF	_incp+1, 0
$016E	$1803			BTFSC	STATUS, C
$016F	$3F01			ADDLW	1
$0170	$3F07			ADDLW	7
$0171	$00C0			MOVWF	_valor+1
;Pic1.pbas,163 :: 		end if
$0172	$	Pic1_L_104:
;Pic1.pbas,165 :: 		mil = valor div 1000
$0172	$30E8			MOVLW	232
$0173	$00F4			MOVWF	STACK_4
$0174	$3003			MOVLW	3
$0175	$00F5			MOVWF	STACK_4+1
$0176	$083F			MOVF	_valor, 0
$0177	$00F0			MOVWF	STACK_0
$0178	$0840			MOVF	_valor+1, 0
$0179	$00F1			MOVWF	STACK_0+1
$017A	$25F1			CALL	_div_16x16_s
$017B	$0870			MOVF	STACK_0, 0
$017C	$00D1			MOVWF	FLOC_main+8
$017D	$0871			MOVF	STACK_0+1, 0
$017E	$00D2			MOVWF	FLOC_main+9
$017F	$0851			MOVF	FLOC_main+8, 0
$0180	$00C1			MOVWF	_mil
$0181	$0852			MOVF	FLOC_main+9, 0
$0182	$00C2			MOVWF	_mil+1
;Pic1.pbas,166 :: 		cen = valor div 100 - (mil * 10)
$0183	$3064			MOVLW	100
$0184	$00F4			MOVWF	STACK_4
$0185	$01F5			CLRF	STACK_4+1
$0186	$083F			MOVF	_valor, 0
$0187	$00F0			MOVWF	STACK_0
$0188	$0840			MOVF	_valor+1, 0
$0189	$00F1			MOVWF	STACK_0+1
$018A	$25F1			CALL	_div_16x16_s
$018B	$0870			MOVF	STACK_0, 0
$018C	$00CB			MOVWF	FLOC_main+2
$018D	$0871			MOVF	STACK_0+1, 0
$018E	$00CC			MOVWF	FLOC_main+3
$018F	$0851			MOVF	FLOC_main+8, 0
$0190	$00F0			MOVWF	STACK_0
$0191	$0852			MOVF	FLOC_main+9, 0
$0192	$00F1			MOVWF	STACK_0+1
$0193	$300A			MOVLW	10
$0194	$00F4			MOVWF	STACK_4
$0195	$01F5			CLRF	STACK_4+1
$0196	$2692			CALL	_mul_16x16_s
$0197	$0870			MOVF	STACK_0, 0
$0198	$024B			SUBWF	FLOC_main+2, 0
$0199	$00CF			MOVWF	FLOC_main+6
$019A	$0871			MOVF	STACK_0+1, 0
$019B	$1C03			BTFSS	STATUS, C
$019C	$3F01			ADDLW	1
$019D	$024C			SUBWF	FLOC_main+3, 0
$019E	$00D0			MOVWF	FLOC_main+7
$019F	$084F			MOVF	FLOC_main+6, 0
$01A0	$00C3			MOVWF	_cen
$01A1	$0850			MOVF	FLOC_main+7, 0
$01A2	$00C4			MOVWF	_cen+1
;Pic1.pbas,167 :: 		dez = valor div 10 - (cen * 10) - (mil * 100)
$01A3	$300A			MOVLW	10
$01A4	$00F4			MOVWF	STACK_4
$01A5	$01F5			CLRF	STACK_4+1
$01A6	$083F			MOVF	_valor, 0
$01A7	$00F0			MOVWF	STACK_0
$01A8	$0840			MOVF	_valor+1, 0
$01A9	$00F1			MOVWF	STACK_0+1
$01AA	$25F1			CALL	_div_16x16_s
$01AB	$0870			MOVF	STACK_0, 0
$01AC	$00CB			MOVWF	FLOC_main+2
$01AD	$0871			MOVF	STACK_0+1, 0
$01AE	$00CC			MOVWF	FLOC_main+3
$01AF	$084F			MOVF	FLOC_main+6, 0
$01B0	$00F0			MOVWF	STACK_0
$01B1	$0850			MOVF	FLOC_main+7, 0
$01B2	$00F1			MOVWF	STACK_0+1
$01B3	$300A			MOVLW	10
$01B4	$00F4			MOVWF	STACK_4
$01B5	$01F5			CLRF	STACK_4+1
$01B6	$2692			CALL	_mul_16x16_s
$01B7	$0870			MOVF	STACK_0, 0
$01B8	$02CB			SUBWF	FLOC_main+2, 1
$01B9	$1C03			BTFSS	STATUS, C
$01BA	$03CC			DECF	FLOC_main+3, 1
$01BB	$0871			MOVF	STACK_0+1, 0
$01BC	$02CC			SUBWF	FLOC_main+3, 1
$01BD	$0851			MOVF	FLOC_main+8, 0
$01BE	$00F0			MOVWF	STACK_0
$01BF	$0852			MOVF	FLOC_main+9, 0
$01C0	$00F1			MOVWF	STACK_0+1
$01C1	$3064			MOVLW	100
$01C2	$00F4			MOVWF	STACK_4
$01C3	$01F5			CLRF	STACK_4+1
$01C4	$2692			CALL	_mul_16x16_s
$01C5	$0870			MOVF	STACK_0, 0
$01C6	$024B			SUBWF	FLOC_main+2, 0
$01C7	$00CD			MOVWF	FLOC_main+4
$01C8	$0871			MOVF	STACK_0+1, 0
$01C9	$1C03			BTFSS	STATUS, C
$01CA	$3F01			ADDLW	1
$01CB	$024C			SUBWF	FLOC_main+3, 0
$01CC	$00CE			MOVWF	FLOC_main+5
$01CD	$084D			MOVF	FLOC_main+4, 0
$01CE	$00C5			MOVWF	_dez
$01CF	$084E			MOVF	FLOC_main+5, 0
$01D0	$00C6			MOVWF	_dez+1
;Pic1.pbas,168 :: 		uni = valor - (dez * 10) - (cen * 100) - (mil * 1000)
$01D1	$084D			MOVF	FLOC_main+4, 0
$01D2	$00F0			MOVWF	STACK_0
$01D3	$084E			MOVF	FLOC_main+5, 0
$01D4	$00F1			MOVWF	STACK_0+1
$01D5	$300A			MOVLW	10
$01D6	$00F4			MOVWF	STACK_4
$01D7	$01F5			CLRF	STACK_4+1
$01D8	$2692			CALL	_mul_16x16_s
$01D9	$0870			MOVF	STACK_0, 0
$01DA	$023F			SUBWF	_valor, 0
$01DB	$00CB			MOVWF	FLOC_main+2
$01DC	$0871			MOVF	STACK_0+1, 0
$01DD	$1C03			BTFSS	STATUS, C
$01DE	$3F01			ADDLW	1
$01DF	$0240			SUBWF	_valor+1, 0
$01E0	$00CC			MOVWF	FLOC_main+3
$01E1	$084F			MOVF	FLOC_main+6, 0
$01E2	$00F0			MOVWF	STACK_0
$01E3	$0850			MOVF	FLOC_main+7, 0
$01E4	$00F1			MOVWF	STACK_0+1
$01E5	$3064			MOVLW	100
$01E6	$00F4			MOVWF	STACK_4
$01E7	$01F5			CLRF	STACK_4+1
$01E8	$2692			CALL	_mul_16x16_s
$01E9	$0870			MOVF	STACK_0, 0
$01EA	$02CB			SUBWF	FLOC_main+2, 1
$01EB	$1C03			BTFSS	STATUS, C
$01EC	$03CC			DECF	FLOC_main+3, 1
$01ED	$0871			MOVF	STACK_0+1, 0
$01EE	$02CC			SUBWF	FLOC_main+3, 1
$01EF	$0851			MOVF	FLOC_main+8, 0
$01F0	$00F0			MOVWF	STACK_0
$01F1	$0852			MOVF	FLOC_main+9, 0
$01F2	$00F1			MOVWF	STACK_0+1
$01F3	$30E8			MOVLW	232
$01F4	$00F4			MOVWF	STACK_4
$01F5	$3003			MOVLW	3
$01F6	$00F5			MOVWF	STACK_4+1
$01F7	$2692			CALL	_mul_16x16_s
$01F8	$0870			MOVF	STACK_0, 0
$01F9	$024B			SUBWF	FLOC_main+2, 0
$01FA	$00F0			MOVWF	STACK_0
$01FB	$0871			MOVF	STACK_0+1, 0
$01FC	$1C03			BTFSS	STATUS, C
$01FD	$3F01			ADDLW	1
$01FE	$024C			SUBWF	FLOC_main+3, 0
$01FF	$00F1			MOVWF	STACK_0+1
$0200	$0870			MOVF	STACK_0, 0
$0201	$00C7			MOVWF	_uni
$0202	$0871			MOVF	STACK_0+1, 0
$0203	$00C8			MOVWF	_uni+1
;Pic1.pbas,170 :: 		PORTC = uni + 16
$0204	$3010			MOVLW	16
$0205	$07F0			ADDWF	STACK_0, 1
$0206	$1803			BTFSC	STATUS, C
$0207	$0AF1			INCF	STACK_0+1, 1
$0208	$0870			MOVF	STACK_0, 0
$0209	$0087			MOVWF	PORTC
;Pic1.pbas,171 :: 		delay_ms(5)
$020A	$3007			MOVLW	7
$020B	$00FB			MOVWF	STACK_11
$020C	$30FF			MOVLW	255
$020D	$00FA			MOVWF	STACK_10
$020E	$0BFB			DECFSZ	STACK_11, F
$020F	$2A11			GOTO	$+2
$0210	$2A14			GOTO	$+4
$0211	$0BFA			DECFSZ	STACK_10, F
$0212	$2A11			GOTO	$-1
$0213	$2A0E			GOTO	$-5
$0214	$3078			MOVLW	120
$0215	$00FA			MOVWF	STACK_10
$0216	$0BFA			DECFSZ	STACK_10, F
$0217	$2A16			GOTO	$-1
$0218	$0000			NOP
$0219	$0000			NOP
;Pic1.pbas,172 :: 		PORTC = dez + 32
$021A	$3020			MOVLW	32
$021B	$074D			ADDWF	FLOC_main+4, 0
$021C	$00F0			MOVWF	STACK_0
$021D	$084E			MOVF	FLOC_main+5, 0
$021E	$1803			BTFSC	STATUS, C
$021F	$3F01			ADDLW	1
$0220	$00F1			MOVWF	STACK_0+1
$0221	$3000			MOVLW	0
$0222	$07F1			ADDWF	STACK_0+1, 1
$0223	$0870			MOVF	STACK_0, 0
$0224	$0087			MOVWF	PORTC
;Pic1.pbas,173 :: 		delay_ms(5)
$0225	$3007			MOVLW	7
$0226	$00FB			MOVWF	STACK_11
$0227	$30FF			MOVLW	255
$0228	$00FA			MOVWF	STACK_10
$0229	$0BFB			DECFSZ	STACK_11, F
$022A	$2A2C			GOTO	$+2
$022B	$2A2F			GOTO	$+4
$022C	$0BFA			DECFSZ	STACK_10, F
$022D	$2A2C			GOTO	$-1
$022E	$2A29			GOTO	$-5
$022F	$3078			MOVLW	120
$0230	$00FA			MOVWF	STACK_10
$0231	$0BFA			DECFSZ	STACK_10, F
$0232	$2A31			GOTO	$-1
$0233	$0000			NOP
$0234	$0000			NOP
;Pic1.pbas,174 :: 		PORTC = cen + 64
$0235	$3040			MOVLW	64
$0236	$074F			ADDWF	FLOC_main+6, 0
$0237	$00F0			MOVWF	STACK_0
$0238	$0850			MOVF	FLOC_main+7, 0
$0239	$1803			BTFSC	STATUS, C
$023A	$3F01			ADDLW	1
$023B	$00F1			MOVWF	STACK_0+1
$023C	$3000			MOVLW	0
$023D	$07F1			ADDWF	STACK_0+1, 1
$023E	$0870			MOVF	STACK_0, 0
$023F	$0087			MOVWF	PORTC
;Pic1.pbas,175 :: 		delay_ms(5)
$0240	$3007			MOVLW	7
$0241	$00FB			MOVWF	STACK_11
$0242	$30FF			MOVLW	255
$0243	$00FA			MOVWF	STACK_10
$0244	$0BFB			DECFSZ	STACK_11, F
$0245	$2A47			GOTO	$+2
$0246	$2A4A			GOTO	$+4
$0247	$0BFA			DECFSZ	STACK_10, F
$0248	$2A47			GOTO	$-1
$0249	$2A44			GOTO	$-5
$024A	$3078			MOVLW	120
$024B	$00FA			MOVWF	STACK_10
$024C	$0BFA			DECFSZ	STACK_10, F
$024D	$2A4C			GOTO	$-1
$024E	$0000			NOP
$024F	$0000			NOP
;Pic1.pbas,176 :: 		PORTC = mil + 128
$0250	$3080			MOVLW	128
$0251	$0751			ADDWF	FLOC_main+8, 0
$0252	$00F0			MOVWF	STACK_0
$0253	$0852			MOVF	FLOC_main+9, 0
$0254	$1803			BTFSC	STATUS, C
$0255	$3F01			ADDLW	1
$0256	$00F1			MOVWF	STACK_0+1
$0257	$3000			MOVLW	0
$0258	$07F1			ADDWF	STACK_0+1, 1
$0259	$0870			MOVF	STACK_0, 0
$025A	$0087			MOVWF	PORTC
;Pic1.pbas,177 :: 		delay_ms(5)
$025B	$3007			MOVLW	7
$025C	$00FB			MOVWF	STACK_11
$025D	$30FF			MOVLW	255
$025E	$00FA			MOVWF	STACK_10
$025F	$0BFB			DECFSZ	STACK_11, F
$0260	$2A62			GOTO	$+2
$0261	$2A65			GOTO	$+4
$0262	$0BFA			DECFSZ	STACK_10, F
$0263	$2A62			GOTO	$-1
$0264	$2A5F			GOTO	$-5
$0265	$3078			MOVLW	120
$0266	$00FA			MOVWF	STACK_10
$0267	$0BFA			DECFSZ	STACK_10, F
$0268	$2A67			GOTO	$-1
$0269	$0000			NOP
$026A	$0000			NOP
;Pic1.pbas,179 :: 		goto executa
$026B	$2826			GOTO	_main_executa
$026C	$2A6C			GOTO	$
