;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 26/05/2020 14:46:31
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0748	$	_div_16x16_s_l:
$0748	$1303			BCF	STATUS, RP1
$0749	$1283			BCF	STATUS, RP0
;math.ppas,291 :: 		
;math.ppas,293 :: 		
$074A	$0D71			RLF	STACK_1, W
;math.ppas,294 :: 		
$074B	$0DF8			RLF	STACK_8, F
;math.ppas,295 :: 		
$074C	$0DF9			RLF	STACK_9, F
;math.ppas,296 :: 		
$074D	$0874			MOVF	STACK_4, W
;math.ppas,297 :: 		
$074E	$02F8			SUBWF	STACK_8, F
;math.ppas,298 :: 		
$074F	$0875			MOVF	STACK_5, W
;math.ppas,299 :: 		
$0750	$1C03			BTFSS	STATUS, C
;math.ppas,300 :: 		
$0751	$0F75			INCFSZ	STACK_5, W
;math.ppas,301 :: 		
$0752	$02F9			SUBWF	STACK_9, F
;math.ppas,302 :: 		
$0753	$0DF0			RLF	STACK_0, F
;math.ppas,304 :: 		
$0754	$0DF1			RLF	STACK_1, F
;math.ppas,305 :: 		
$0755	$300F			MOVLW	15
;math.ppas,307 :: 		
$0756	$00FC			MOVWF	STACK_12
;math.ppas,308 :: 		
$0757	$0D71			RLF	STACK_1, W
;math.ppas,309 :: 		
$0758	$0DF8			RLF	STACK_8, F
;math.ppas,310 :: 		
$0759	$0DF9			RLF	STACK_9, F
;math.ppas,312 :: 		
$075A	$0874			MOVF	STACK_4, W
;math.ppas,313 :: 		
$075B	$1C70			BTFSS	STACK_0, 0
;math.ppas,314 :: 		
$075C	$2F63			GOTO	$+7
;math.ppas,315 :: 		
$075D	$02F8			SUBWF	STACK_8, F
;math.ppas,316 :: 		
$075E	$0875			MOVF	STACK_5, W
;math.ppas,317 :: 		
$075F	$1C03			BTFSS	STATUS, C
;math.ppas,318 :: 		
$0760	$0F75			INCFSZ	STACK_5, W
;math.ppas,319 :: 		
$0761	$02F9			SUBWF	STACK_9, F
;math.ppas,321 :: 		
$0762	$2F68			GOTO	$+6
;math.ppas,322 :: 		
$0763	$07F8			ADDWF	STACK_8, F
;math.ppas,323 :: 		
$0764	$0875			MOVF	STACK_5, W
;math.ppas,324 :: 		
$0765	$1803			BTFSC	STATUS, C
;math.ppas,325 :: 		
$0766	$0F75			INCFSZ	STACK_5, W
;math.ppas,327 :: 		
$0767	$07F9			ADDWF	STACK_9, F
;math.ppas,328 :: 		
$0768	$0DF0			RLF	STACK_0, F
;math.ppas,330 :: 		
$0769	$0DF1			RLF	STACK_1, F
;math.ppas,331 :: 		
$076A	$0BFC			DECFSZ	STACK_12, F
;math.ppas,333 :: 		
$076B	$2F57			GOTO	$-20
;math.ppas,334 :: 		
$076C	$1870			BTFSC	STACK_0, 0
;math.ppas,335 :: 		
$076D	$2F74			GOTO	$+7
;math.ppas,336 :: 		
$076E	$0874			MOVF	STACK_4, W
;math.ppas,337 :: 		
$076F	$07F8			ADDWF	STACK_8, F
;math.ppas,338 :: 		
$0770	$0875			MOVF	STACK_5, W
;math.ppas,339 :: 		
$0771	$1803			BTFSC	STATUS, C
;math.ppas,340 :: 		
$0772	$0F75			INCFSZ	STACK_5, W
;math.ppas,341 :: 		
$0773	$07F9			ADDWF	STACK_9, F
;math.ppas,342 :: 		
$0774	$	math_L_6:
;math.ppas,343 :: 		
$0774	$0008			RETURN
$0711	$	_mul_32x32_u:
$0711	$1303			BCF	STATUS, RP1
$0712	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$0713	$3022			MOVLW	34
;math.ppas,1579 :: 		
$0714	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$0715	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$0716	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$0717	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$0718	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$0719	$	_NEXT:
;math.ppas,1589 :: 		
$0719	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$071A	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$071B	$2F47			GOTO	_EXIT2
;math.ppas,1593 :: 		
$071C	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$071D	$	_LOOP:
;math.ppas,1603 :: 		
$071D	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$071E	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$071F	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$0720	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$0721	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$0722	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$0723	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$0724	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$0725	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$0726	$2F19			GOTO	_NEXT
;math.ppas,1617 :: 		
$0727	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$0728	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$0729	$2F39			GOTO	_EXIT1
;math.ppas,1626 :: 		
$072A	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$072B	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$072C	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$072D	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$072E	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$072F	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$0730	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$0731	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$0732	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$0733	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$0734	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$0735	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$0736	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$0737	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$0738	$2F1D			GOTO	_LOOP
;math.ppas,1647 :: 		
$0739	$	_EXIT1:
;math.ppas,1648 :: 		
$0739	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$073A	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$073B	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$073C	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$073D	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$073E	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$073F	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$0740	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$0741	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$0742	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$0743	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$0744	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$0745	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$0746	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$0747	$	_EXIT2:
;math.ppas,1665 :: 		
$0747	$	math_L_13:
;math.ppas,1666 :: 		
$0747	$0008			RETURN
$0270	$	_sdiv3232l:
$0270	$1303			BCF	STATUS, RP1
$0271	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$0272	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$0273	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$0274	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$0275	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$0276	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$0277	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$0278	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$0279	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$027A	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$027B	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$027C	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$027D	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$027E	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$027F	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$0280	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$0281	$3007			MOVLW	7
;math.ppas,559 :: 		
$0282	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$0283	$	LOOPS3232A:
;math.ppas,561 :: 		
$0283	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$0284	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$0285	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$0286	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$0287	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$0288	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$0289	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$028A	$2A99			GOTO	SADD22LA
;math.ppas,570 :: 		
$028B	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$028C	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$028D	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$028E	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$028F	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$0290	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$0291	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$0292	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$0293	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$0294	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$0295	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$0296	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$0297	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$0298	$2AA6			GOTO	SOK22LA
;math.ppas,585 :: 		
$0299	$	SADD22LA:
;math.ppas,586 :: 		
$0299	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$029A	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$029B	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$029C	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$029D	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$029E	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$029F	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$02A0	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$02A1	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$02A2	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$02A3	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$02A4	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$02A5	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$02A6	$	SOK22LA:
;math.ppas,602 :: 		
$02A6	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$02A7	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$02A8	$2A83			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$02A9	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$02AA	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$02AB	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$02AC	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$02AD	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$02AE	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$02AF	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$02B0	$2ABF			GOTO	SADD22L8
;math.ppas,615 :: 		
$02B1	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$02B2	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$02B3	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$02B4	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$02B5	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$02B6	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$02B7	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$02B8	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$02B9	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$02BA	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$02BB	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$02BC	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$02BD	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$02BE	$2ACC			GOTO	SOK22L8
;math.ppas,630 :: 		
$02BF	$	SADD22L8:
;math.ppas,631 :: 		
$02BF	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$02C0	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$02C1	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$02C2	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$02C3	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$02C4	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$02C5	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$02C6	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$02C7	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$02C8	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$02C9	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$02CA	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$02CB	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$02CC	$	SOK22L8:
;math.ppas,647 :: 		
$02CC	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$02CD	$3007			MOVLW	7
;math.ppas,650 :: 		
$02CE	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$02CF	$	LOOPS3232B:
;math.ppas,652 :: 		
$02CF	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$02D0	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$02D1	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$02D2	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$02D3	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$02D4	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$02D5	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$02D6	$2AE5			GOTO	SADD22LB
;math.ppas,661 :: 		
$02D7	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$02D8	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$02D9	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$02DA	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$02DB	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$02DC	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$02DD	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$02DE	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$02DF	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$02E0	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$02E1	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$02E2	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$02E3	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$02E4	$2AF2			GOTO	SOK22LB
;math.ppas,676 :: 		
$02E5	$	SADD22LB:
;math.ppas,677 :: 		
$02E5	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$02E6	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$02E7	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$02E8	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$02E9	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$02EA	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$02EB	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$02EC	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$02ED	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$02EE	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$02EF	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$02F0	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$02F1	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$02F2	$	SOK22LB:
;math.ppas,693 :: 		
$02F2	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$02F3	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$02F4	$2ACF			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$02F5	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$02F6	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$02F7	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$02F8	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$02F9	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$02FA	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$02FB	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$02FC	$2B0B			GOTO	SADD22L16
;math.ppas,706 :: 		
$02FD	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$02FE	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$02FF	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$0300	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$0301	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$0302	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$0303	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$0304	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$0305	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$0306	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$0307	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$0308	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$0309	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$030A	$2B18			GOTO	SOK22L16
;math.ppas,721 :: 		
$030B	$	SADD22L16:
;math.ppas,722 :: 		
$030B	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$030C	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$030D	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$030E	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$030F	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$0310	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$0311	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$0312	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$0313	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$0314	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$0315	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$0316	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$0317	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$0318	$	SOK22L16:
;math.ppas,738 :: 		
$0318	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$0319	$3007			MOVLW	7
;math.ppas,741 :: 		
$031A	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$031B	$	LOOPS3232C:
;math.ppas,743 :: 		
$031B	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$031C	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$031D	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$031E	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$031F	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$0320	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$0321	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$0322	$2B31			GOTO	SADD22LC
;math.ppas,752 :: 		
$0323	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$0324	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$0325	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$0326	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$0327	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$0328	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$0329	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$032A	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$032B	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$032C	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$032D	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$032E	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$032F	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$0330	$2B3E			GOTO	SOK22LC
;math.ppas,767 :: 		
$0331	$	SADD22LC:
;math.ppas,768 :: 		
$0331	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$0332	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$0333	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$0334	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$0335	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$0336	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$0337	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$0338	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$0339	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$033A	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$033B	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$033C	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$033D	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$033E	$	SOK22LC:
;math.ppas,784 :: 		
$033E	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$033F	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$0340	$2B1B			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$0341	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$0342	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$0343	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$0344	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$0345	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$0346	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$0347	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$0348	$2B57			GOTO	SADD22L24
;math.ppas,797 :: 		
$0349	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$034A	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$034B	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$034C	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$034D	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$034E	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$034F	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$0350	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$0351	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$0352	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$0353	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$0354	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$0355	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$0356	$2B64			GOTO	SOK22L24
;math.ppas,812 :: 		
$0357	$	SADD22L24:
;math.ppas,813 :: 		
$0357	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$0358	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$0359	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$035A	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$035B	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$035C	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$035D	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$035E	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$035F	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$0360	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$0361	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$0362	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$0363	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$0364	$	SOK22L24:
;math.ppas,829 :: 		
$0364	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$0365	$3007			MOVLW	7
;math.ppas,832 :: 		
$0366	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$0367	$	LOOPS3232D:
;math.ppas,834 :: 		
$0367	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$0368	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$0369	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$036A	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$036B	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$036C	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$036D	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$036E	$2B7D			GOTO	SADD22LD
;math.ppas,843 :: 		
$036F	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$0370	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$0371	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$0372	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$0373	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$0374	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$0375	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$0376	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$0377	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$0378	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$0379	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$037A	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$037B	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$037C	$2B8A			GOTO	SOK22LD
;math.ppas,858 :: 		
$037D	$	SADD22LD:
;math.ppas,859 :: 		
$037D	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$037E	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$037F	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$0380	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$0381	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$0382	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$0383	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$0384	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$0385	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$0386	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$0387	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$0388	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$0389	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$038A	$	SOK22LD:
;math.ppas,876 :: 		
$038A	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$038B	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$038C	$2B67			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$038D	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$038E	$2B9D			GOTO	SOK22L
;math.ppas,882 :: 		
$038F	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$0390	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$0391	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$0392	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$0393	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$0394	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$0395	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$0396	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$0397	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$0398	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$0399	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$039A	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$039B	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$039C	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$039D	$	SOK22L:
;math.ppas,897 :: 		
$039D	$	math_L_9:
;math.ppas,898 :: 		
$039D	$0008			RETURN
$0857	$	_comfrem:
$0857	$1303			BCF	STATUS, RP1
$0858	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$0859	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$085A	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$085B	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$085C	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$085D	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$085E	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$085F	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$0860	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$0861	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$0862	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$0863	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$0864	$	math_L_10:
;math.ppas,915 :: 		
$0864	$0008			RETURN
$05EC	$	_div_16x16_s:
$05EC	$1303			BCF	STATUS, RP1
$05ED	$1283			BCF	STATUS, RP0
;math.ppas,346 :: 		
;math.ppas,348 :: 		
$05EE	$01FD			CLRF	STACK_13
;math.ppas,349 :: 		
$05EF	$01F9			CLRF	STACK_9
;math.ppas,350 :: 		
$05F0	$01F8			CLRF	STACK_8
;math.ppas,351 :: 		
$05F1	$0871			MOVF	STACK_1, W
;math.ppas,352 :: 		
$05F2	$0470			IORWF	STACK_0, W
;math.ppas,353 :: 		
$05F3	$1903			BTFSC	STATUS, Z
;math.ppas,355 :: 		
$05F4	$3400			RETLW	0
;math.ppas,356 :: 		
$05F5	$0871			MOVF	STACK_1, W
;math.ppas,357 :: 		
$05F6	$0675			XORWF	STACK_5, W
;math.ppas,358 :: 		
$05F7	$00FA			MOVWF	STACK_10
;math.ppas,359 :: 		
$05F8	$1BFA			BTFSC	STACK_10, 7
;math.ppas,361 :: 		
$05F9	$09FD			COMF	STACK_13, F
;math.ppas,363 :: 		
$05FA	$01FB			CLRF	STACK_11
;math.ppas,364 :: 		
$05FB	$1FF5			BTFSS	STACK_5, 7
;math.ppas,366 :: 		
$05FC	$2E02			GOTO	$+6
;math.ppas,367 :: 		
$05FD	$09F4			COMF	STACK_4, F
;math.ppas,368 :: 		
$05FE	$09F5			COMF	STACK_5, F
;math.ppas,369 :: 		
$05FF	$0AF4			INCF	STACK_4, F
;math.ppas,370 :: 		
$0600	$1903			BTFSC	STATUS, Z
;math.ppas,372 :: 		
$0601	$0AF5			INCF	STACK_5, F
;math.ppas,373 :: 		
$0602	$1FF1			BTFSS	STACK_1, 7
;math.ppas,375 :: 		
$0603	$2E09			GOTO	$+6
;math.ppas,376 :: 		
$0604	$09F0			COMF	STACK_0, F
;math.ppas,377 :: 		
$0605	$09F1			COMF	STACK_1, F
;math.ppas,378 :: 		
$0606	$0AF0			INCF	STACK_0, F
;math.ppas,379 :: 		
$0607	$1903			BTFSC	STATUS, Z
;math.ppas,381 :: 		
$0608	$0AF1			INCF	STACK_1, F
;math.ppas,382 :: 		
$0609	$0871			MOVF	STACK_1, W
;math.ppas,383 :: 		
$060A	$0475			IORWF	STACK_5, W
;math.ppas,384 :: 		
$060B	$00FA			MOVWF	STACK_10
;math.ppas,385 :: 		
$060C	$1BFA			BTFSC	STACK_10, 7
;math.ppas,386 :: 		
$060D	$2E1E			GOTO	$+17
;math.ppas,388 :: 		
$060E	$2748			CALL	_div_16x16_s_l
;math.ppas,390 :: 		
$060F	$187B			BTFSC	STACK_11, 0
;math.ppas,392 :: 		
$0610	$2E31			GOTO	$+33
;math.ppas,393 :: 		
$0611	$1FFD			BTFSS	STACK_13, 7
;math.ppas,395 :: 		
$0612	$3400			RETLW	0
;math.ppas,396 :: 		
$0613	$09F0			COMF	STACK_0, F
;math.ppas,397 :: 		
$0614	$09F1			COMF	STACK_1, F
;math.ppas,398 :: 		
$0615	$0AF0			INCF	STACK_0, F
;math.ppas,399 :: 		
$0616	$1903			BTFSC	STATUS, Z
;math.ppas,401 :: 		
$0617	$0AF1			INCF	STACK_1, F
;math.ppas,402 :: 		
$0618	$09F8			COMF	STACK_8, F
;math.ppas,403 :: 		
$0619	$09F9			COMF	STACK_9, F
;math.ppas,404 :: 		
$061A	$0AF8			INCF	STACK_8, F
;math.ppas,405 :: 		
$061B	$1903			BTFSC	STATUS, Z
;math.ppas,407 :: 		
$061C	$0AF9			INCF	STACK_9, F
;math.ppas,409 :: 		
$061D	$3400			RETLW	0
;math.ppas,410 :: 		
$061E	$1FF5			BTFSS	STACK_5, 7
;math.ppas,411 :: 		
$061F	$2E2D			GOTO	$+14
;math.ppas,412 :: 		
$0620	$1BF1			BTFSC	STACK_1, 7
;math.ppas,413 :: 		
$0621	$2E29			GOTO	$+8
;math.ppas,414 :: 		
$0622	$0871			MOVF	STACK_1, W
;math.ppas,415 :: 		
$0623	$00F9			MOVWF	STACK_9
;math.ppas,416 :: 		
$0624	$0870			MOVF	STACK_0, W
;math.ppas,417 :: 		
$0625	$00F8			MOVWF	STACK_8
;math.ppas,418 :: 		
$0626	$01F1			CLRF	STACK_1
;math.ppas,419 :: 		
$0627	$01F0			CLRF	STACK_0
;math.ppas,420 :: 		
$0628	$2E11			GOTO	$-23
;math.ppas,421 :: 		
$0629	$01F1			CLRF	STACK_1
;math.ppas,422 :: 		
$062A	$01F0			CLRF	STACK_0
;math.ppas,423 :: 		
$062B	$0AF0			INCF	STACK_0, F
;math.ppas,425 :: 		
$062C	$3400			RETLW	0
;math.ppas,426 :: 		
$062D	$09F1			COMF	STACK_1, F
;math.ppas,427 :: 		
$062E	$09F0			COMF	STACK_0, F
;math.ppas,428 :: 		
$062F	$0AFB			INCF	STACK_11, F
;math.ppas,430 :: 		
$0630	$2E0E			GOTO	$-34
;math.ppas,431 :: 		
$0631	$0AF8			INCF	STACK_8, F
;math.ppas,432 :: 		
$0632	$1903			BTFSC	STATUS, Z
;math.ppas,433 :: 		
$0633	$0AF9			INCF	STACK_9, F
;math.ppas,434 :: 		
$0634	$0874			MOVF	STACK_4, W
;math.ppas,435 :: 		
$0635	$0278			SUBWF	STACK_8, W
;math.ppas,436 :: 		
$0636	$1D03			BTFSS	STATUS, Z
;math.ppas,437 :: 		
$0637	$2E11			GOTO	$-38
;math.ppas,438 :: 		
$0638	$0875			MOVF	STACK_5, W
;math.ppas,439 :: 		
$0639	$0279			SUBWF	STACK_9, W
;math.ppas,440 :: 		
$063A	$1D03			BTFSS	STATUS, Z
;math.ppas,441 :: 		
$063B	$2E11			GOTO	$-42
;math.ppas,442 :: 		
$063C	$01F9			CLRF	STACK_9
;math.ppas,443 :: 		
$063D	$01F8			CLRF	STACK_8
;math.ppas,444 :: 		
$063E	$0AF0			INCF	STACK_0, F
;math.ppas,445 :: 		
$063F	$1903			BTFSC	STATUS, Z
;math.ppas,446 :: 		
$0640	$0AF1			INCF	STACK_1, F
;math.ppas,447 :: 		
$0641	$1FF1			BTFSS	STACK_1, 7
;math.ppas,448 :: 		
$0642	$2E11			GOTO	$-49
;math.ppas,449 :: 		
$0643	$0000			NOP
;math.ppas,450 :: 		
$0644	$34FF			RETLW	255
;math.ppas,451 :: 		
$0645	$	math_L_7:
;math.ppas,452 :: 		
$0645	$0008			RETURN
$0845	$	_usart_write:
;USART_b75.ppas,40 :: 		
;USART_b75.ppas,42 :: 		
$0845	$	USART_b75_L_14:
$0845	$1303			BCF	STATUS, RP1
$0846	$1683			BSF	STATUS, RP0
$0847	$0818			MOVF	TXSTA, 0
$0848	$00F1			MOVWF	STACK_1
$0849	$3000			MOVLW	0
$084A	$18F1			BTFSC	STACK_1, 1
$084B	$3001			MOVLW	1
$084C	$00F1			MOVWF	STACK_1
$084D	$0871			MOVF	STACK_1, 0
$084E	$3A00			XORLW	0
$084F	$1D03			BTFSS	STATUS, Z
$0850	$2853			GOTO	USART_b75_L_15
;USART_b75.ppas,43 :: 		
$0851	$0000			NOP
$0852	$2845			GOTO	USART_b75_L_14
$0853	$	USART_b75_L_15:
;USART_b75.ppas,44 :: 		
$0853	$1283			BCF	STATUS, RP0
$0854	$0869			MOVF	FARG_USART_Write, 0
$0855	$0099			MOVWF	TXREG
$0856	$	USART_b75_L_12:
;USART_b75.ppas,45 :: 		
$0856	$0008			RETURN
$0865	$	_usart_data_ready:
;USART_b75.ppas,48 :: 		
;USART_b75.ppas,50 :: 		
$0865	$1303			BCF	STATUS, RP1
$0866	$1283			BCF	STATUS, RP0
$0867	$080C			MOVF	PIR1, 0
$0868	$00F1			MOVWF	STACK_1
$0869	$3000			MOVLW	0
$086A	$1AF1			BTFSC	STACK_1, 5
$086B	$3001			MOVLW	1
$086C	$00F1			MOVWF	STACK_1
$086D	$0871			MOVF	STACK_1, 0
$086E	$00E4			MOVWF	_usart_data_ready_local_result
$086F	$	USART_b75_L_18:
;USART_b75.ppas,51 :: 		
$086F	$0864			MOVF	_usart_data_ready_local_result, 0
$0870	$00F0			MOVWF	STACK_0
$0871	$0008			RETURN
$0832	$	_usart_read:
;USART_b75.ppas,54 :: 		
;USART_b75.ppas,55 :: 		
$0832	$1303			BCF	STATUS, RP1
$0833	$1283			BCF	STATUS, RP0
$0834	$081A			MOVF	RCREG, 0
$0835	$00E4			MOVWF	_usart_read_local_result
;USART_b75.ppas,61 :: 		
$0836	$0818			MOVF	RCSTA, 0
$0837	$00F1			MOVWF	STACK_1
$0838	$3000			MOVLW	0
$0839	$18F1			BTFSC	STACK_1, 1
$083A	$3001			MOVLW	1
$083B	$00F1			MOVWF	STACK_1
$083C	$0871			MOVF	STACK_1, 0
$083D	$3A01			XORLW	1
$083E	$1D03			BTFSS	STATUS, Z
$083F	$2842			GOTO	USART_b75_L_21
$0840	$	USART_b75_L_20:
;USART_b75.ppas,63 :: 		
$0840	$1218			BCF	RCSTA, 4
$0841	$	USART_b75_L_24:
;USART_b75.ppas,64 :: 		
$0841	$	USART_b75_L_25:
$0841	$1618			BSF	RCSTA, 4
$0842	$	USART_b75_L_26:
;USART_b75.ppas,65 :: 		
$0842	$	USART_b75_L_21:
$0842	$	USART_b75_L_22:
$0842	$	USART_b75_L_19:
;USART_b75.ppas,66 :: 		
$0842	$0864			MOVF	_usart_read_local_result, 0
$0843	$00F0			MOVWF	STACK_0
$0844	$0008			RETURN
$06D6	$	_mul_32x32_s:
$06D6	$1303			BCF	STATUS, RP1
$06D7	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$06D8	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$06D9	$	_IF_FIRST:
;math.ppas,1684 :: 		
$06D9	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$06DA	$2EE8			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$06DB	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$06DB	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$06DC	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$06DD	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$06DE	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$06DF	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$06E0	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$06E1	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$06E2	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$06E3	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$06E4	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$06E5	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$06E6	$3081			MOVLW	129
;math.ppas,1711 :: 		
$06E7	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$06E8	$	_IF_SECOND:
;math.ppas,1715 :: 		
$06E8	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$06E9	$2EF6			GOTO	_MULT
;math.ppas,1722 :: 		
$06EA	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$06EA	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$06EB	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$06EC	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$06ED	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$06EE	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$06EF	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$06F0	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$06F1	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$06F2	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$06F3	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$06F4	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$06F5	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$06F6	$	_MULT:
;math.ppas,1744 :: 		
$06F6	$2711			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$06F7	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$06F8	$2F10			GOTO	_EXIT
;math.ppas,1755 :: 		
$06F9	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$06FA	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$06FB	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$06FC	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$06FD	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$06FE	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$06FF	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$0700	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$0701	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$0702	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$0703	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$0704	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$0705	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$0706	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$0707	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$0708	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$0709	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$070A	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$070B	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$070C	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$070D	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$070E	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$070F	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$0710	$	_EXIT:
;math.ppas,1793 :: 		
$0710	$	math_L_14:
;math.ppas,1794 :: 		
$0710	$0008			RETURN
$0800	$	_div_16x16_u:
$0800	$1303			BCF	STATUS, RP1
$0801	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$0802	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$0803	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$0804	$3010			MOVLW	16
;math.ppas,113 :: 		
$0805	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$0806	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$0807	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$0808	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$0809	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$080A	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$080B	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$080C	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$080D	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$080E	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$080F	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$0810	$2818			GOTO	$+8
;math.ppas,125 :: 		
$0811	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$0812	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$0813	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$0814	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$0815	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$0816	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$0817	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$0818	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$0819	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$081A	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$081B	$2806			GOTO	$-21
;math.ppas,136 :: 		
$081C	$	math_L_3:
;math.ppas,137 :: 		
$081C	$0008			RETURN
$0505	$	_div_32x32_s:
$0505	$1303			BCF	STATUS, RP1
$0506	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$0507	$	FXD3232S:
;math.ppas,929 :: 		
$0507	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$0508	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$0509	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$050A	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$050B	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$050C	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$050D	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$050E	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$050F	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$0510	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$0511	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$0512	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0513	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$0514	$2D99			GOTO	END_ALL
;math.ppas,944 :: 		
$0515	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$0516	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$0517	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$0518	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$0519	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$051A	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$051B	$2D27			GOTO	CA3232S
;math.ppas,955 :: 		
$051C	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$051D	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$051E	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$051F	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$0520	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$0521	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$0522	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0523	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$0524	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$0525	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$0526	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$0527	$	CA3232S:
;math.ppas,968 :: 		
$0527	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$0528	$2D34			GOTO	C3232SX
;math.ppas,971 :: 		
$0529	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$052A	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$052B	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$052C	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$052D	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$052E	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$052F	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$0530	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$0531	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$0532	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$0533	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$0534	$	C3232SX:
;math.ppas,984 :: 		
$0534	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$0535	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$0536	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$0537	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$0538	$2D55			GOTO	C3232SX1
;math.ppas,989 :: 		
$0539	$	C3232S:
;math.ppas,992 :: 		
$0539	$2270			CALL	_sdiv3232l
;math.ppas,995 :: 		
$053A	$	C3232S2:
;math.ppas,996 :: 		
$053A	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$053B	$2D72			GOTO	C3232SX4
;math.ppas,998 :: 		
$053C	$	C3232SOK:
;math.ppas,999 :: 		
$053C	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$053D	$2D99			GOTO	END_ALL
;math.ppas,1001 :: 		
$053E	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$053F	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$0540	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$0541	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$0542	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$0543	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$0544	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$0545	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$0546	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$0547	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$0548	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$0549	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$054A	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$054B	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$054C	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$054D	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$054E	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$054F	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$0550	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$0551	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$0552	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$0553	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$0554	$2D99			GOTO	END_ALL
;math.ppas,1026 :: 		
$0555	$	C3232SX1:
;math.ppas,1027 :: 		
$0555	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$0556	$2D6C			GOTO	C3232SX3
;math.ppas,1029 :: 		
$0557	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$0558	$2D66			GOTO	C3232SX2
;math.ppas,1031 :: 		
$0559	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$055A	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$055B	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$055C	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$055D	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$055E	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$055F	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$0560	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$0561	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$0562	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$0563	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$0564	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$0565	$2D3C			GOTO	C3232SOK
;math.ppas,1044 :: 		
$0566	$	C3232SX2:
;math.ppas,1045 :: 		
$0566	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$0567	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$0568	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$0569	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$056A	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$056B	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$056C	$	C3232SX3:
;math.ppas,1053 :: 		
$056C	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$056D	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$056E	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$056F	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$0570	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$0571	$2D39			GOTO	C3232S
;math.ppas,1061 :: 		
$0572	$	C3232SX4:
;math.ppas,1062 :: 		
$0572	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0573	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$0574	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$0575	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$0576	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$0577	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$0578	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$0579	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$057A	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$057B	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$057C	$2D3C			GOTO	C3232SOK
;math.ppas,1073 :: 		
$057D	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$057E	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$057F	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$0580	$2D3C			GOTO	C3232SOK
;math.ppas,1077 :: 		
$0581	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$0582	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$0583	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$0584	$2D3C			GOTO	C3232SOK
;math.ppas,1081 :: 		
$0585	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$0586	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$0587	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$0588	$2D3C			GOTO	C3232SOK
;math.ppas,1085 :: 		
$0589	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$058A	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$058B	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$058C	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$058D	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$058E	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$058F	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$0590	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$0591	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$0592	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0593	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$0594	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$0595	$2D3C			GOTO	C3232SOK
;math.ppas,1098 :: 		
$0596	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$0597	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$0598	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$0599	$	END_ALL:
;math.ppas,1102 :: 		
$0599	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$059A	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$059B	$2D9F			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$059C	$158A			BSF	PCLATH, 3
$059D	$2057			CALL	_comfrem
$059E	$118A			BCF	PCLATH, 3
;math.ppas,1108 :: 		
$059F	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$059F	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$05A0	$	math_L_11:
;math.ppas,1111 :: 		
$05A0	$0008			RETURN
$0462	$	_inttostr:
;conv.ppas,100 :: 		
;conv.ppas,101 :: 		
$0462	$1303			BCF	STATUS, RP1
$0463	$1283			BCF	STATUS, RP0
$0464	$0865			MOVF	FARG_IntToStr+1, 0
$0465	$3A80			XORLW	128
$0466	$1D03			BTFSS	STATUS, Z
$0467	$2C6A			GOTO	L_IntToStr_4
$0468	$3000			MOVLW	0
$0469	$0664			XORWF	FARG_IntToStr, 0
$046A	$	L_IntToStr_4:
$046A	$1D03			BTFSS	STATUS, Z
$046B	$2C82			GOTO	conv_L_57
$046C	$	conv_L_56:
;conv.ppas,103 :: 		
$046C	$0866			MOVF	FARG_IntToStr+2, 0
$046D	$0084			MOVWF	FSR
$046E	$302D			MOVLW	45
$046F	$0080			MOVWF	INDF
$0470	$0A84			INCF	FSR, 1
$0471	$3033			MOVLW	51
$0472	$0080			MOVWF	INDF
$0473	$0A84			INCF	FSR, 1
$0474	$3032			MOVLW	50
$0475	$0080			MOVWF	INDF
$0476	$0A84			INCF	FSR, 1
$0477	$3037			MOVLW	55
$0478	$0080			MOVWF	INDF
$0479	$0A84			INCF	FSR, 1
$047A	$3036			MOVLW	54
$047B	$0080			MOVWF	INDF
$047C	$0A84			INCF	FSR, 1
$047D	$3038			MOVLW	56
$047E	$0080			MOVWF	INDF
$047F	$0A84			INCF	FSR, 1
$0480	$0180			CLRF	INDF
;conv.ppas,104 :: 		
$0481	$2D04			GOTO	conv_L_55
;conv.ppas,105 :: 		
$0482	$	conv_L_57:
$0482	$	conv_L_58:
;conv.ppas,106 :: 		
$0482	$01E8			CLRF	_inttostr_local_negative, 1
;conv.ppas,107 :: 		
$0483	$3080			MOVLW	128
$0484	$0665			XORWF	FARG_IntToStr+1, 0
$0485	$00F0			MOVWF	STACK_0
$0486	$3080			MOVLW	128
$0487	$0270			SUBWF	STACK_0, 0
$0488	$1D03			BTFSS	STATUS, Z
$0489	$2C8C			GOTO	L_IntToStr_5
$048A	$3000			MOVLW	0
$048B	$0264			SUBWF	FARG_IntToStr, 0
$048C	$	L_IntToStr_5:
$048C	$1803			BTFSC	STATUS, C
$048D	$2C98			GOTO	conv_L_61
$048E	$	conv_L_60:
;conv.ppas,109 :: 		
$048E	$30FF			MOVLW	255
$048F	$00E8			MOVWF	_inttostr_local_negative
;conv.ppas,110 :: 		
$0490	$0864			MOVF	FARG_IntToStr, 0
$0491	$3C00			SUBLW	0
$0492	$00E4			MOVWF	FARG_IntToStr
$0493	$0865			MOVF	FARG_IntToStr+1, 0
$0494	$1C03			BTFSS	STATUS, C
$0495	$3F01			ADDLW	1
$0496	$01E5			CLRF	FARG_IntToStr+1
$0497	$02E5			SUBWF	FARG_IntToStr+1, 1
;conv.ppas,111 :: 		
$0498	$	conv_L_61:
$0498	$	conv_L_62:
;conv.ppas,112 :: 		
$0498	$3001			MOVLW	1
$0499	$00E7			MOVWF	_inttostr_local_len
;conv.ppas,113 :: 		
$049A	$3080			MOVLW	128
$049B	$00F0			MOVWF	STACK_0
$049C	$3080			MOVLW	128
$049D	$0665			XORWF	FARG_IntToStr+1, 0
$049E	$0270			SUBWF	STACK_0, 0
$049F	$1D03			BTFSS	STATUS, Z
$04A0	$2CA3			GOTO	L_IntToStr_6
$04A1	$0864			MOVF	FARG_IntToStr, 0
$04A2	$3C09			SUBLW	9
$04A3	$	L_IntToStr_6:
$04A3	$1803			BTFSC	STATUS, C
$04A4	$2CA6			GOTO	conv_L_64
$04A5	$	conv_L_63:
;conv.ppas,114 :: 		
$04A5	$0AE7			INCF	_inttostr_local_len, 1
$04A6	$	conv_L_64:
$04A6	$	conv_L_65:
;conv.ppas,115 :: 		
$04A6	$3080			MOVLW	128
$04A7	$00F0			MOVWF	STACK_0
$04A8	$3080			MOVLW	128
$04A9	$0665			XORWF	FARG_IntToStr+1, 0
$04AA	$0270			SUBWF	STACK_0, 0
$04AB	$1D03			BTFSS	STATUS, Z
$04AC	$2CAF			GOTO	L_IntToStr_7
$04AD	$0864			MOVF	FARG_IntToStr, 0
$04AE	$3C63			SUBLW	99
$04AF	$	L_IntToStr_7:
$04AF	$1803			BTFSC	STATUS, C
$04B0	$2CB2			GOTO	conv_L_67
$04B1	$	conv_L_66:
;conv.ppas,116 :: 		
$04B1	$0AE7			INCF	_inttostr_local_len, 1
$04B2	$	conv_L_67:
$04B2	$	conv_L_68:
;conv.ppas,117 :: 		
$04B2	$3080			MOVLW	128
$04B3	$3A03			XORLW	3
$04B4	$00F0			MOVWF	STACK_0
$04B5	$3080			MOVLW	128
$04B6	$0665			XORWF	FARG_IntToStr+1, 0
$04B7	$0270			SUBWF	STACK_0, 0
$04B8	$1D03			BTFSS	STATUS, Z
$04B9	$2CBC			GOTO	L_IntToStr_8
$04BA	$0864			MOVF	FARG_IntToStr, 0
$04BB	$3CE7			SUBLW	231
$04BC	$	L_IntToStr_8:
$04BC	$1803			BTFSC	STATUS, C
$04BD	$2CBF			GOTO	conv_L_70
$04BE	$	conv_L_69:
;conv.ppas,118 :: 		
$04BE	$0AE7			INCF	_inttostr_local_len, 1
$04BF	$	conv_L_70:
$04BF	$	conv_L_71:
;conv.ppas,119 :: 		
$04BF	$3080			MOVLW	128
$04C0	$3A27			XORLW	39
$04C1	$00F0			MOVWF	STACK_0
$04C2	$3080			MOVLW	128
$04C3	$0665			XORWF	FARG_IntToStr+1, 0
$04C4	$0270			SUBWF	STACK_0, 0
$04C5	$1D03			BTFSS	STATUS, Z
$04C6	$2CC9			GOTO	L_IntToStr_9
$04C7	$0864			MOVF	FARG_IntToStr, 0
$04C8	$3C0F			SUBLW	15
$04C9	$	L_IntToStr_9:
$04C9	$1803			BTFSC	STATUS, C
$04CA	$2CCC			GOTO	conv_L_73
$04CB	$	conv_L_72:
;conv.ppas,120 :: 		
$04CB	$0AE7			INCF	_inttostr_local_len, 1
$04CC	$	conv_L_73:
$04CC	$	conv_L_74:
;conv.ppas,121 :: 		
$04CC	$0866			MOVF	FARG_IntToStr+2, 0
$04CD	$0084			MOVWF	FSR
$04CE	$3020			MOVLW	32
$04CF	$0080			MOVWF	INDF
$04D0	$0A84			INCF	FSR, 1
$04D1	$0080			MOVWF	INDF
$04D2	$0A84			INCF	FSR, 1
$04D3	$0080			MOVWF	INDF
$04D4	$0A84			INCF	FSR, 1
$04D5	$0080			MOVWF	INDF
$04D6	$0A84			INCF	FSR, 1
$04D7	$0080			MOVWF	INDF
$04D8	$0A84			INCF	FSR, 1
$04D9	$0080			MOVWF	INDF
$04DA	$0A84			INCF	FSR, 1
$04DB	$0180			CLRF	INDF
;conv.ppas,122 :: 		
$04DC	$0384			DECF	FSR, 1
;conv.ppas,123 :: 		
$04DD	$	conv_L_77:
$04DD	$0867			MOVF	_inttostr_local_len, 0
$04DE	$3C00			SUBLW	0
$04DF	$1803			BTFSC	STATUS, C
$04E0	$2CFF			GOTO	conv_L_78
;conv.ppas,125 :: 		
$04E1	$300A			MOVLW	10
$04E2	$00F4			MOVWF	STACK_4
$04E3	$01F5			CLRF	STACK_4+1
$04E4	$0864			MOVF	FARG_IntToStr, 0
$04E5	$00F0			MOVWF	STACK_0
$04E6	$0865			MOVF	FARG_IntToStr+1, 0
$04E7	$00F1			MOVWF	STACK_0+1
$04E8	$25EC			CALL	_div_16x16_s
$04E9	$0878			MOVF	STACK_8, 0
$04EA	$00F0			MOVWF	STACK_0
$04EB	$0879			MOVF	STACK_9, 0
$04EC	$00F1			MOVWF	STACK_1
$04ED	$3030			MOVLW	48
$04EE	$0770			ADDWF	STACK_0, 0
$04EF	$0080			MOVWF	INDF
;conv.ppas,126 :: 		
;conv.ppas,127 :: 		
$04F0	$0384			DECF	FSR, 1
;conv.ppas,128 :: 		
$04F1	$300A			MOVLW	10
$04F2	$00F4			MOVWF	STACK_4
$04F3	$01F5			CLRF	STACK_4+1
$04F4	$0864			MOVF	FARG_IntToStr, 0
$04F5	$00F0			MOVWF	STACK_0
$04F6	$0865			MOVF	FARG_IntToStr+1, 0
$04F7	$00F1			MOVWF	STACK_0+1
$04F8	$25EC			CALL	_div_16x16_s
$04F9	$0870			MOVF	STACK_0, 0
$04FA	$00E4			MOVWF	FARG_IntToStr
$04FB	$0871			MOVF	STACK_0+1, 0
$04FC	$00E5			MOVWF	FARG_IntToStr+1
;conv.ppas,129 :: 		
$04FD	$03E7			DECF	_inttostr_local_len, 1
;conv.ppas,130 :: 		
$04FE	$2CDD			GOTO	conv_L_77
$04FF	$	conv_L_78:
;conv.ppas,131 :: 		
$04FF	$0868			MOVF	_inttostr_local_negative, 0
$0500	$1903			BTFSC	STATUS, Z
$0501	$2D04			GOTO	conv_L_82
$0502	$	conv_L_81:
;conv.ppas,133 :: 		
$0502	$302D			MOVLW	45
$0503	$0080			MOVWF	INDF
;conv.ppas,134 :: 		
$0504	$	conv_L_82:
$0504	$	conv_L_83:
$0504	$	conv_L_55:
;conv.ppas,135 :: 		
$0504	$0008			RETURN
$0775	$	_usart_write_text:
;USART_b75.ppas,121 :: 		
;USART_b75.ppas,122 :: 		
$0775	$1303			BCF	STATUS, RP1
$0776	$1283			BCF	STATUS, RP0
$0777	$01E5			CLRF	_usart_write_text_local_i, 1
;USART_b75.ppas,123 :: 		
$0778	$0864			MOVF	FARG_Usart_Write_Text, 0
$0779	$0084			MOVWF	FSR
$077A	$0800			MOVF	INDF, 0
$077B	$00E6			MOVWF	_usart_write_text_local_data
;USART_b75.ppas,124 :: 		
$077C	$	USART_b75_L_47:
$077C	$0866			MOVF	_usart_write_text_local_data, 0
$077D	$3A00			XORLW	0
$077E	$1903			BTFSC	STATUS, Z
$077F	$2F8C			GOTO	USART_b75_L_48
;USART_b75.ppas,126 :: 		
$0780	$0866			MOVF	_usart_write_text_local_data, 0
$0781	$00E9			MOVWF	FARG_USART_Write
$0782	$158A			BSF	PCLATH, 3
$0783	$2045			CALL	_usart_write
$0784	$118A			BCF	PCLATH, 3
;USART_b75.ppas,127 :: 		
$0785	$0AE5			INCF	_usart_write_text_local_i, 1
;USART_b75.ppas,128 :: 		
$0786	$0865			MOVF	_usart_write_text_local_i, 0
$0787	$0764			ADDWF	FARG_Usart_Write_Text, 0
$0788	$0084			MOVWF	FSR
$0789	$0800			MOVF	INDF, 0
$078A	$00E6			MOVWF	_usart_write_text_local_data
;USART_b75.ppas,129 :: 		
$078B	$2F7C			GOTO	USART_b75_L_47
$078C	$	USART_b75_L_48:
$078C	$	USART_b75_L_45:
;USART_b75.ppas,130 :: 		
$078C	$0008			RETURN
$0646	$	_usart_read_text:
;USART_b75.ppas,78 :: 		
;USART_b75.ppas,79 :: 		
$0646	$1303			BCF	STATUS, RP1
$0647	$1283			BCF	STATUS, RP0
$0648	$01D9			CLRF	_usart_read_text_local_i, 1
;USART_b75.ppas,80 :: 		
$0649	$01DA			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,81 :: 		
$064A	$01DD			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,82 :: 		
$064B	$0858			MOVF	FARG_Usart_Read_Text+1, 0
$064C	$0084			MOVWF	FSR
$064D	$0800			MOVF	INDF, 0
$064E	$00DC			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,83 :: 		
$064F	$	USART_b75_L_29:
;USART_b75.ppas,85 :: 		
$064F	$158A			BSF	PCLATH, 3
$0650	$2065			CALL	_usart_data_ready
$0651	$118A			BCF	PCLATH, 3
$0652	$0870			MOVF	STACK_0, 0
$0653	$3A00			XORLW	0
$0654	$1903			BTFSC	STATUS, Z
$0655	$2E83			GOTO	USART_b75_L_34
$0656	$	USART_b75_L_33:
;USART_b75.ppas,87 :: 		
$0656	$158A			BSF	PCLATH, 3
$0657	$2032			CALL	_usart_read
$0658	$118A			BCF	PCLATH, 3
$0659	$0870			MOVF	STACK_0, 0
$065A	$00DB			MOVWF	_usart_read_text_local_data
;USART_b75.ppas,88 :: 		
$065B	$0859			MOVF	_usart_read_text_local_i, 0
$065C	$0757			ADDWF	FARG_Usart_Read_Text, 0
$065D	$00F1			MOVWF	STACK_1
$065E	$0871			MOVF	STACK_1, 0
$065F	$0084			MOVWF	FSR
$0660	$0871			MOVF	STACK_1, 0
$0661	$0084			MOVWF	FSR
$0662	$0870			MOVF	STACK_0, 0
$0663	$0080			MOVWF	INDF
;USART_b75.ppas,89 :: 		
$0664	$085B			MOVF	_usart_read_text_local_data, 0
$0665	$065C			XORWF	_usart_read_text_local_data2, 0
$0666	$1D03			BTFSS	STATUS, Z
$0667	$2E6D			GOTO	USART_b75_L_37
$0668	$	USART_b75_L_36:
;USART_b75.ppas,91 :: 		
$0668	$085A			MOVF	_usart_read_text_local_j, 0
$0669	$0259			SUBWF	_usart_read_text_local_i, 0
$066A	$00DD			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,92 :: 		
$066B	$0ADA			INCF	_usart_read_text_local_j, 1
;USART_b75.ppas,93 :: 		
$066C	$2E6F			GOTO	USART_b75_L_38
;USART_b75.ppas,94 :: 		
$066D	$	USART_b75_L_37:
;USART_b75.ppas,96 :: 		
$066D	$01DA			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,97 :: 		
$066E	$01DD			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,98 :: 		
$066F	$	USART_b75_L_38:
;USART_b75.ppas,100 :: 		
$066F	$085A			MOVF	_usart_read_text_local_j, 0
$0670	$0758			ADDWF	FARG_Usart_Read_Text+1, 0
$0671	$0084			MOVWF	FSR
$0672	$0800			MOVF	INDF, 0
$0673	$00F1			MOVWF	STACK_1
$0674	$0871			MOVF	STACK_1, 0
$0675	$00DC			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,102 :: 		
$0676	$0871			MOVF	STACK_1, 0
$0677	$3A00			XORLW	0
$0678	$1D03			BTFSS	STATUS, Z
$0679	$2E7B			GOTO	USART_b75_L_40
$067A	$	USART_b75_L_39:
;USART_b75.ppas,103 :: 		
$067A	$2E84			GOTO	USART_b75_L_30
$067B	$	USART_b75_L_40:
$067B	$	USART_b75_L_41:
;USART_b75.ppas,105 :: 		
$067B	$0AD9			INCF	_usart_read_text_local_i, 1
;USART_b75.ppas,106 :: 		
$067C	$0859			MOVF	_usart_read_text_local_i, 0
$067D	$3C14			SUBLW	20
$067E	$1803			BTFSC	STATUS, C
$067F	$2E83			GOTO	USART_b75_L_43
$0680	$	USART_b75_L_42:
;USART_b75.ppas,108 :: 		
$0680	$3013			MOVLW	19
$0681	$00DD			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,109 :: 		
$0682	$2E84			GOTO	USART_b75_L_30
;USART_b75.ppas,110 :: 		
$0683	$	USART_b75_L_43:
$0683	$	USART_b75_L_44:
;USART_b75.ppas,111 :: 		
$0683	$	USART_b75_L_34:
$0683	$	USART_b75_L_35:
;USART_b75.ppas,112 :: 		
$0683	$2E4F			GOTO	USART_b75_L_29
$0684	$	USART_b75_L_30:
;USART_b75.ppas,113 :: 		
$0684	$085D			MOVF	_usart_read_text_local_lasti, 0
$0685	$0757			ADDWF	FARG_Usart_Read_Text, 0
$0686	$00F0			MOVWF	STACK_0
$0687	$0870			MOVF	STACK_0, 0
$0688	$0084			MOVWF	FSR
$0689	$0870			MOVF	STACK_0, 0
$068A	$0084			MOVWF	FSR
$068B	$0180			CLRF	INDF, 1
$068C	$	USART_b75_L_27:
;USART_b75.ppas,114 :: 		
$068C	$0008			RETURN
$039E	$	_strtoint:
;conv.ppas,343 :: 		
;conv.ppas,345 :: 		
$039E	$1303			BCF	STATUS, RP1
$039F	$1283			BCF	STATUS, RP0
$03A0	$01D8			CLRF	_strtoint_local_result
$03A1	$01D9			CLRF	_strtoint_local_result+1
;conv.ppas,346 :: 		
$03A2	$3010			MOVLW	16
$03A3	$00DC			MOVWF	_strtoint_local_ep
$03A4	$3027			MOVLW	39
$03A5	$00DD			MOVWF	_strtoint_local_ep+1
;conv.ppas,347 :: 		
$03A6	$01DA			CLRF	_strtoint_local_i
$03A7	$01DB			CLRF	_strtoint_local_i+1
;conv.ppas,348 :: 		
$03A8	$01E0			CLRF	_strtoint_local_tmp
$03A9	$01E1			CLRF	_strtoint_local_tmp+1
$03AA	$01E2			CLRF	_strtoint_local_tmp+2
$03AB	$01E3			CLRF	_strtoint_local_tmp+3
;conv.ppas,349 :: 		
$03AC	$01DE			CLRF	_strtoint_local_negative
$03AD	$01DF			CLRF	_strtoint_local_negative+1
;conv.ppas,353 :: 		
$03AE	$	conv_L_172:
$03AE	$085A			MOVF	_strtoint_local_i, 0
$03AF	$0757			ADDWF	FARG_StrToInt, 0
$03B0	$0084			MOVWF	FSR
$03B1	$0800			MOVF	INDF, 0
$03B2	$00F4			MOVWF	STACK_4
$03B3	$0874			MOVF	STACK_4, 0
$03B4	$3A00			XORLW	0
$03B5	$1903			BTFSC	STATUS, Z
$03B6	$2C1C			GOTO	conv_L_173
;conv.ppas,355 :: 		
$03B7	$085A			MOVF	_strtoint_local_i, 0
$03B8	$0757			ADDWF	FARG_StrToInt, 0
$03B9	$0084			MOVWF	FSR
$03BA	$0800			MOVF	INDF, 0
$03BB	$00F4			MOVWF	STACK_4
$03BC	$0874			MOVF	STACK_4, 0
$03BD	$3A2D			XORLW	45
$03BE	$1D03			BTFSS	STATUS, Z
$03BF	$2BC7			GOTO	conv_L_177
$03C0	$	conv_L_176:
;conv.ppas,357 :: 		
$03C0	$30FF			MOVLW	255
$03C1	$00DE			MOVWF	_strtoint_local_negative
$03C2	$01DF			CLRF	_strtoint_local_negative+1
;conv.ppas,358 :: 		
$03C3	$0ADA			INCF	_strtoint_local_i, 1
$03C4	$1903			BTFSC	STATUS, Z
$03C5	$0ADB			INCF	_strtoint_local_i+1, 1
;conv.ppas,359 :: 		
$03C6	$2BAE			GOTO	conv_L_172
;conv.ppas,360 :: 		
$03C7	$	conv_L_177:
$03C7	$	conv_L_178:
;conv.ppas,361 :: 		
$03C7	$085A			MOVF	_strtoint_local_i, 0
$03C8	$0757			ADDWF	FARG_StrToInt, 0
$03C9	$0084			MOVWF	FSR
$03CA	$0800			MOVF	INDF, 0
$03CB	$00F4			MOVWF	STACK_4
$03CC	$0874			MOVF	STACK_4, 0
$03CD	$3A20			XORLW	32
$03CE	$1903			BTFSC	STATUS, Z
$03CF	$2C0A			GOTO	conv_L_180
$03D0	$	conv_L_179:
;conv.ppas,362 :: 		
$03D0	$085A			MOVF	_strtoint_local_i, 0
$03D1	$0757			ADDWF	FARG_StrToInt, 0
$03D2	$0084			MOVWF	FSR
$03D3	$0800			MOVF	INDF, 0
$03D4	$00F0			MOVWF	STACK_0
$03D5	$3030			MOVLW	48
$03D6	$00F8			MOVWF	STACK_8
$03D7	$01F9			CLRF	STACK_8+1
$03D8	$01FA			CLRF	STACK_8+2
$03D9	$01FB			CLRF	STACK_8+3
$03DA	$0870			MOVF	STACK_0, 0
$03DB	$00F4			MOVWF	STACK_4
$03DC	$01F5			CLRF	STACK_4+1
$03DD	$01F6			CLRF	STACK_4+2
$03DE	$01F7			CLRF	STACK_4+3
$03DF	$0874			MOVF	STACK_4, 0
$03E0	$00F0			MOVWF	STACK_0
$03E1	$0875			MOVF	STACK_4+1, 0
$03E2	$00F1			MOVWF	STACK_0+1
$03E3	$0876			MOVF	STACK_4+2, 0
$03E4	$00F2			MOVWF	STACK_0+2
$03E5	$0877			MOVF	STACK_4+3, 0
$03E6	$00F3			MOVWF	STACK_0+3
$03E7	$0878			MOVF	STACK_8, 0
$03E8	$02F0			SUBWF	STACK_0, 1
$03E9	$0879			MOVF	STACK_8+1, 0
$03EA	$1C03			BTFSS	STATUS, C
$03EB	$0F79			INCFSZ	STACK_8+1, 0
$03EC	$02F1			SUBWF	STACK_0+1, 1
$03ED	$087A			MOVF	STACK_8+2, 0
$03EE	$1C03			BTFSS	STATUS, C
$03EF	$0F7A			INCFSZ	STACK_8+2, 0
$03F0	$02F2			SUBWF	STACK_0+2, 1
$03F1	$087B			MOVF	STACK_8+3, 0
$03F2	$1C03			BTFSS	STATUS, C
$03F3	$0F7B			INCFSZ	STACK_8+3, 0
$03F4	$02F3			SUBWF	STACK_0+3, 1
$03F5	$085C			MOVF	_strtoint_local_ep, 0
$03F6	$00F4			MOVWF	STACK_4
$03F7	$085D			MOVF	_strtoint_local_ep+1, 0
$03F8	$00F5			MOVWF	STACK_4+1
$03F9	$01F6			CLRF	STACK_4+2
$03FA	$01F7			CLRF	STACK_4+3
$03FB	$26D6			CALL	_mul_32x32_s
$03FC	$0870			MOVF	STACK_0, 0
$03FD	$07E0			ADDWF	_strtoint_local_tmp, 1
$03FE	$0871			MOVF	STACK_0+1, 0
$03FF	$1803			BTFSC	STATUS, C
$0400	$0F71			INCFSZ	STACK_0+1, 0
$0401	$07E1			ADDWF	_strtoint_local_tmp+1, 1
$0402	$0872			MOVF	STACK_0+2, 0
$0403	$1803			BTFSC	STATUS, C
$0404	$0F72			INCFSZ	STACK_0+2, 0
$0405	$07E2			ADDWF	_strtoint_local_tmp+2, 1
$0406	$0873			MOVF	STACK_0+3, 0
$0407	$1803			BTFSC	STATUS, C
$0408	$0F73			INCFSZ	STACK_0+3, 0
$0409	$07E3			ADDWF	_strtoint_local_tmp+3, 1
$040A	$	conv_L_180:
$040A	$	conv_L_181:
;conv.ppas,363 :: 		
$040A	$300A			MOVLW	10
$040B	$00F4			MOVWF	STACK_4
$040C	$01F5			CLRF	STACK_4+1
$040D	$085C			MOVF	_strtoint_local_ep, 0
$040E	$00F0			MOVWF	STACK_0
$040F	$085D			MOVF	_strtoint_local_ep+1, 0
$0410	$00F1			MOVWF	STACK_0+1
$0411	$158A			BSF	PCLATH, 3
$0412	$2000			CALL	_div_16x16_u
$0413	$118A			BCF	PCLATH, 3
$0414	$0870			MOVF	STACK_0, 0
$0415	$00DC			MOVWF	_strtoint_local_ep
$0416	$0871			MOVF	STACK_0+1, 0
$0417	$00DD			MOVWF	_strtoint_local_ep+1
;conv.ppas,365 :: 		
$0418	$0ADA			INCF	_strtoint_local_i, 1
$0419	$1903			BTFSC	STATUS, Z
$041A	$0ADB			INCF	_strtoint_local_i+1, 1
;conv.ppas,366 :: 		
$041B	$2BAE			GOTO	conv_L_172
$041C	$	conv_L_173:
;conv.ppas,370 :: 		
$041C	$085E			MOVF	_strtoint_local_negative, 0
$041D	$045F			IORWF	_strtoint_local_negative+1, 0
$041E	$1903			BTFSC	STATUS, Z
$041F	$2C24			GOTO	conv_L_183
$0420	$	conv_L_182:
$0420	$3006			MOVLW	6
$0421	$00DC			MOVWF	_strtoint_local_ep
$0422	$01DD			CLRF	_strtoint_local_ep+1
$0423	$2C27			GOTO	conv_L_184
;conv.ppas,371 :: 		
$0424	$	conv_L_183:
$0424	$3005			MOVLW	5
$0425	$00DC			MOVWF	_strtoint_local_ep
$0426	$01DD			CLRF	_strtoint_local_ep+1
$0427	$	conv_L_184:
;conv.ppas,373 :: 		
$0427	$	conv_L_186:
$0427	$085B			MOVF	_strtoint_local_i+1, 0
$0428	$065D			XORWF	_strtoint_local_ep+1, 0
$0429	$1D03			BTFSS	STATUS, Z
$042A	$2C2D			GOTO	L_StrToInt_20
$042B	$085C			MOVF	_strtoint_local_ep, 0
$042C	$065A			XORWF	_strtoint_local_i, 0
$042D	$	L_StrToInt_20:
$042D	$1903			BTFSC	STATUS, Z
$042E	$2C49			GOTO	conv_L_187
;conv.ppas,375 :: 		
$042F	$300A			MOVLW	10
$0430	$00F4			MOVWF	STACK_4
$0431	$01F5			CLRF	STACK_4+1
$0432	$01F6			CLRF	STACK_4+2
$0433	$01F7			CLRF	STACK_4+3
$0434	$0860			MOVF	_strtoint_local_tmp, 0
$0435	$00F0			MOVWF	STACK_0
$0436	$0861			MOVF	_strtoint_local_tmp+1, 0
$0437	$00F1			MOVWF	STACK_0+1
$0438	$0862			MOVF	_strtoint_local_tmp+2, 0
$0439	$00F2			MOVWF	STACK_0+2
$043A	$0863			MOVF	_strtoint_local_tmp+3, 0
$043B	$00F3			MOVWF	STACK_0+3
$043C	$2505			CALL	_div_32x32_s
$043D	$0870			MOVF	STACK_0, 0
$043E	$00E0			MOVWF	_strtoint_local_tmp
$043F	$0871			MOVF	STACK_0+1, 0
$0440	$00E1			MOVWF	_strtoint_local_tmp+1
$0441	$0872			MOVF	STACK_0+2, 0
$0442	$00E2			MOVWF	_strtoint_local_tmp+2
$0443	$0873			MOVF	STACK_0+3, 0
$0444	$00E3			MOVWF	_strtoint_local_tmp+3
;conv.ppas,376 :: 		
$0445	$0ADA			INCF	_strtoint_local_i, 1
$0446	$1903			BTFSC	STATUS, Z
$0447	$0ADB			INCF	_strtoint_local_i+1, 1
;conv.ppas,377 :: 		
$0448	$2C27			GOTO	conv_L_186
$0449	$	conv_L_187:
;conv.ppas,380 :: 		
$0449	$0860			MOVF	_strtoint_local_tmp, 0
$044A	$00D8			MOVWF	_strtoint_local_result
$044B	$0861			MOVF	_strtoint_local_tmp+1, 0
$044C	$00D9			MOVWF	_strtoint_local_result+1
;conv.ppas,382 :: 		
$044D	$3000			MOVLW	0
$044E	$065F			XORWF	_strtoint_local_negative+1, 0
$044F	$1D03			BTFSS	STATUS, Z
$0450	$2C53			GOTO	L_StrToInt_21
$0451	$30FF			MOVLW	255
$0452	$065E			XORWF	_strtoint_local_negative, 0
$0453	$	L_StrToInt_21:
$0453	$1D03			BTFSS	STATUS, Z
$0454	$2C5D			GOTO	conv_L_191
$0455	$	conv_L_190:
;conv.ppas,383 :: 		
$0455	$0858			MOVF	_strtoint_local_result, 0
$0456	$3C00			SUBLW	0
$0457	$00D8			MOVWF	_strtoint_local_result
$0458	$0859			MOVF	_strtoint_local_result+1, 0
$0459	$1C03			BTFSS	STATUS, C
$045A	$3F01			ADDLW	1
$045B	$01D9			CLRF	_strtoint_local_result+1
$045C	$02D9			SUBWF	_strtoint_local_result+1, 1
$045D	$	conv_L_191:
$045D	$	conv_L_192:
$045D	$	conv_L_170:
;conv.ppas,384 :: 		
$045D	$0858			MOVF	_strtoint_local_result, 0
$045E	$00F0			MOVWF	STACK_0
$045F	$0859			MOVF	_strtoint_local_result+1, 0
$0460	$00F1			MOVWF	STACK_0+1
$0461	$0008			RETURN
$05A1	$	_envia:
;Pic1.pbas,10 :: 		sub procedure envia
;Pic1.pbas,11 :: 		if priorit = 1 then
$05A1	$3000			MOVLW	0
$05A2	$1303			BCF	STATUS, RP1
$05A3	$1283			BCF	STATUS, RP0
$05A4	$0622			XORWF	_priorit+1, 0
$05A5	$1D03			BTFSS	STATUS, Z
$05A6	$2DA9			GOTO	L_envia_0
$05A7	$3001			MOVLW	1
$05A8	$0621			XORWF	_priorit, 0
$05A9	$	L_envia_0:
$05A9	$1D03			BTFSS	STATUS, Z
$05AA	$2DC7			GOTO	Pic1_L_2
$05AB	$	Pic1_L_1:
;Pic1.pbas,12 :: 		valorN = 1000 + incN
$05AB	$0825			MOVF	_incn, 0
$05AC	$3FE8			ADDLW	232
$05AD	$00F0			MOVWF	STACK_0
$05AE	$3003			MOVLW	3
$05AF	$1803			BTFSC	STATUS, C
$05B0	$3F01			ADDLW	1
$05B1	$0726			ADDWF	_incn+1, 0
$05B2	$00F1			MOVWF	STACK_0+1
$05B3	$0870			MOVF	STACK_0, 0
$05B4	$00A3			MOVWF	_valorn
$05B5	$0871			MOVF	STACK_0+1, 0
$05B6	$00A4			MOVWF	_valorn+1
;Pic1.pbas,13 :: 		IntToStr(valorN, txt)
$05B7	$0870			MOVF	STACK_0, 0
$05B8	$00E4			MOVWF	FARG_IntToStr
$05B9	$0871			MOVF	STACK_0+1, 0
$05BA	$00E5			MOVWF	FARG_IntToStr+1
$05BB	$3027			MOVLW	_txt
$05BC	$00E6			MOVWF	FARG_IntToStr+2
$05BD	$2462			CALL	_inttostr
;Pic1.pbas,14 :: 		Usart_Write_Text(txt)
$05BE	$3027			MOVLW	_txt
$05BF	$00E4			MOVWF	FARG_Usart_Write_Text
$05C0	$2775			CALL	_usart_write_text
;Pic1.pbas,15 :: 		Usart_Write_Text("/")
$05C1	$302F			MOVLW	47
$05C2	$00D7			MOVWF	?envia_Local_Text+0
$05C3	$01D8			CLRF	?envia_Local_Text+1
$05C4	$3057			MOVLW	?envia_Local_Text
$05C5	$00E4			MOVWF	FARG_Usart_Write_Text
$05C6	$2775			CALL	_usart_write_text
$05C7	$	Pic1_L_2:
;Pic1.pbas,16 :: 		end if
$05C7	$	Pic1_L_3:
;Pic1.pbas,17 :: 		if priorit = 2 then
$05C7	$3000			MOVLW	0
$05C8	$0622			XORWF	_priorit+1, 0
$05C9	$1D03			BTFSS	STATUS, Z
$05CA	$2DCD			GOTO	L_envia_1
$05CB	$3002			MOVLW	2
$05CC	$0621			XORWF	_priorit, 0
$05CD	$	L_envia_1:
$05CD	$1D03			BTFSS	STATUS, Z
$05CE	$2DEB			GOTO	Pic1_L_5
$05CF	$	Pic1_L_4:
;Pic1.pbas,18 :: 		valorP = 2000 + incP
$05CF	$0830			MOVF	_incp, 0
$05D0	$3FD0			ADDLW	208
$05D1	$00F0			MOVWF	STACK_0
$05D2	$3007			MOVLW	7
$05D3	$1803			BTFSC	STATUS, C
$05D4	$3F01			ADDLW	1
$05D5	$0731			ADDWF	_incp+1, 0
$05D6	$00F1			MOVWF	STACK_0+1
$05D7	$0870			MOVF	STACK_0, 0
$05D8	$00AE			MOVWF	_valorp
$05D9	$0871			MOVF	STACK_0+1, 0
$05DA	$00AF			MOVWF	_valorp+1
;Pic1.pbas,19 :: 		IntToStr(valorP, txt)
$05DB	$0870			MOVF	STACK_0, 0
$05DC	$00E4			MOVWF	FARG_IntToStr
$05DD	$0871			MOVF	STACK_0+1, 0
$05DE	$00E5			MOVWF	FARG_IntToStr+1
$05DF	$3027			MOVLW	_txt
$05E0	$00E6			MOVWF	FARG_IntToStr+2
$05E1	$2462			CALL	_inttostr
;Pic1.pbas,20 :: 		Usart_Write_Text(txt)
$05E2	$3027			MOVLW	_txt
$05E3	$00E4			MOVWF	FARG_Usart_Write_Text
$05E4	$2775			CALL	_usart_write_text
;Pic1.pbas,21 :: 		Usart_Write_Text("/")
$05E5	$302F			MOVLW	47
$05E6	$00D7			MOVWF	?envia_Local_Text+0
$05E7	$01D8			CLRF	?envia_Local_Text+1
$05E8	$3057			MOVLW	?envia_Local_Text
$05E9	$00E4			MOVWF	FARG_Usart_Write_Text
$05EA	$2775			CALL	_usart_write_text
$05EB	$	Pic1_L_5:
;Pic1.pbas,22 :: 		end if
$05EB	$	Pic1_L_6:
$05EB	$	Pic1_L_0:
$05EB	$0008			RETURN
$081D	$	_usart_init:
;USART_b75.ppas,22 :: 		
;USART_b75.ppas,24 :: 		
$081D	$	USART_b75_L_1:
$081D	$1303			BCF	STATUS, RP1
$081E	$1683			BSF	STATUS, RP0
$081F	$1698			BSF	TXSTA, 5
$0820	$	USART_b75_L_2:
;USART_b75.ppas,25 :: 		
$0820	$3090			MOVLW	144
$0821	$1283			BCF	STATUS, RP0
$0822	$0098			MOVWF	RCSTA
;USART_b75.ppas,31 :: 		
$0823	$	USART_b75_L_3:
$0823	$1683			BSF	STATUS, RP0
$0824	$1686			BSF	TRISB, 5
$0825	$	USART_b75_L_4:
;USART_b75.ppas,32 :: 		
$0825	$	USART_b75_L_5:
$0825	$1786			BSF	TRISB, 7
$0826	$	USART_b75_L_6:
;USART_b75.ppas,35 :: 		
$0826	$	USART_b75_L_8:
$0826	$1283			BCF	STATUS, RP0
$0827	$080C			MOVF	PIR1, 0
$0828	$00F1			MOVWF	STACK_1
$0829	$3000			MOVLW	0
$082A	$1AF1			BTFSC	STACK_1, 5
$082B	$3001			MOVLW	1
$082C	$00F1			MOVWF	STACK_1
$082D	$0871			MOVF	STACK_1, 0
$082E	$3A01			XORLW	1
$082F	$1903			BTFSC	STATUS, Z
$0830	$2826			GOTO	USART_b75_L_8
;USART_b75.ppas,36 :: 		
$0831	$	USART_b75_L_9:
$0831	$	USART_b75_L_0:
;USART_b75.ppas,37 :: 		
$0831	$0008			RETURN
$068D	$	_mul_16x16_s:
$068D	$1303			BCF	STATUS, RP1
$068E	$1283			BCF	STATUS, RP0
;math.ppas,203 :: 		
;math.ppas,205 :: 		
$068F	$01FB			CLRF	STACK_11
;math.ppas,206 :: 		
$0690	$01FA			CLRF	STACK_10
;math.ppas,207 :: 		
$0691	$01F9			CLRF	STACK_9
;math.ppas,208 :: 		
$0692	$3080			MOVLW	128
;math.ppas,210 :: 		
$0693	$00F8			MOVWF	STACK_8
;math.ppas,212 :: 		
$0694	$01FD			CLRF	STACK_13
;math.ppas,213 :: 		
$0695	$1FF1			BTFSS	STACK_1, 7
;math.ppas,214 :: 		
$0696	$2E9D			GOTO	$+7
;math.ppas,215 :: 		
$0697	$09F1			COMF	STACK_1, F
;math.ppas,216 :: 		
$0698	$09F0			COMF	STACK_0, F
;math.ppas,217 :: 		
$0699	$0AF0			INCF	STACK_0, F
;math.ppas,218 :: 		
$069A	$1903			BTFSC	STATUS, Z
;math.ppas,219 :: 		
$069B	$0AF1			INCF	STACK_1, F
;math.ppas,221 :: 		
$069C	$0AFD			INCF	STACK_13, F
;math.ppas,222 :: 		
$069D	$1FF5			BTFSS	STACK_5, 7
;math.ppas,223 :: 		
$069E	$2EA5			GOTO	$+7
;math.ppas,224 :: 		
$069F	$09F5			COMF	STACK_5, F
;math.ppas,225 :: 		
$06A0	$09F4			COMF	STACK_4, F
;math.ppas,226 :: 		
$06A1	$0AF4			INCF	STACK_4, F
;math.ppas,227 :: 		
$06A2	$1903			BTFSC	STATUS, Z
;math.ppas,228 :: 		
$06A3	$0AF5			INCF	STACK_5, F
;math.ppas,230 :: 		
$06A4	$0AFD			INCF	STACK_13, F
;math.ppas,231 :: 		
$06A5	$0CF1			RRF	STACK_1, F
;math.ppas,233 :: 		
$06A6	$0CF0			RRF	STACK_0, F
;math.ppas,234 :: 		
$06A7	$1C03			BTFSS	STATUS, C
;math.ppas,235 :: 		
$06A8	$2EB2			GOTO	$+10
;math.ppas,236 :: 		
$06A9	$0874			MOVF	STACK_4, W
;math.ppas,238 :: 		
$06AA	$07F9			ADDWF	STACK_9, F
;math.ppas,239 :: 		
$06AB	$0875			MOVF	STACK_5, W
;math.ppas,240 :: 		
$06AC	$1803			BTFSC	STATUS, C
;math.ppas,241 :: 		
$06AD	$0F75			INCFSZ	STACK_5, W
;math.ppas,242 :: 		
$06AE	$07FA			ADDWF	STACK_10, F
;math.ppas,243 :: 		
$06AF	$1803			BTFSC	STATUS, C
;math.ppas,244 :: 		
$06B0	$0AFB			INCF	STACK_11, F
;math.ppas,246 :: 		
$06B1	$1003			BCF	STATUS, C
;math.ppas,247 :: 		
$06B2	$1FF0			BTFSS	STACK_0, 7
;math.ppas,248 :: 		
$06B3	$2EBA			GOTO	$+7
;math.ppas,249 :: 		
$06B4	$0874			MOVF	STACK_4, W
;math.ppas,250 :: 		
$06B5	$07FA			ADDWF	STACK_10, F
;math.ppas,251 :: 		
$06B6	$1803			BTFSC	STATUS, C
;math.ppas,252 :: 		
$06B7	$0AFB			INCF	STACK_11, F
;math.ppas,253 :: 		
$06B8	$0875			MOVF	STACK_5, W
;math.ppas,255 :: 		
$06B9	$07FB			ADDWF	STACK_11, F
;math.ppas,256 :: 		
$06BA	$0CFB			RRF	STACK_11, F
;math.ppas,257 :: 		
$06BB	$0CFA			RRF	STACK_10, F
;math.ppas,258 :: 		
$06BC	$0CF9			RRF	STACK_9, F
;math.ppas,260 :: 		
$06BD	$0CF8			RRF	STACK_8, F
;math.ppas,261 :: 		
$06BE	$1C03			BTFSS	STATUS, C
;math.ppas,262 :: 		
$06BF	$2EA5			GOTO	$-26
;math.ppas,263 :: 		
$06C0	$1C7D			BTFSS	STACK_13, 0
;math.ppas,265 :: 		
$06C1	$2ECD			GOTO	$+12
;math.ppas,266 :: 		
$06C2	$09FB			COMF	STACK_11, F
;math.ppas,267 :: 		
$06C3	$09FA			COMF	STACK_10, F
;math.ppas,268 :: 		
$06C4	$09F9			COMF	STACK_9, F
;math.ppas,270 :: 		
$06C5	$09F8			COMF	STACK_8, F
;math.ppas,271 :: 		
$06C6	$0AF8			INCF	STACK_8, F
;math.ppas,272 :: 		
$06C7	$1903			BTFSC	STATUS, Z
;math.ppas,273 :: 		
$06C8	$0AF9			INCF	STACK_9, F
;math.ppas,274 :: 		
$06C9	$1903			BTFSC	STATUS, Z
;math.ppas,275 :: 		
$06CA	$0AFA			INCF	STACK_10, F
;math.ppas,276 :: 		
$06CB	$1903			BTFSC	STATUS, Z
;math.ppas,278 :: 		
$06CC	$0AFB			INCF	STACK_11, F
;math.ppas,279 :: 		
$06CD	$087B			MOVF	STACK_11, W
;math.ppas,280 :: 		
$06CE	$00F3			MOVWF	STACK_3
;math.ppas,281 :: 		
$06CF	$087A			MOVF	STACK_10, W
;math.ppas,282 :: 		
$06D0	$00F2			MOVWF	STACK_2
;math.ppas,283 :: 		
$06D1	$0879			MOVF	STACK_9, W
;math.ppas,284 :: 		
$06D2	$00F1			MOVWF	STACK_1
;math.ppas,285 :: 		
$06D3	$0878			MOVF	STACK_8, W
;math.ppas,286 :: 		
$06D4	$00F0			MOVWF	STACK_0
;math.ppas,287 :: 		
$06D5	$	math_L_5:
;math.ppas,288 :: 		
$06D5	$0008			RETURN
$0004	$	_main:
;Pic1.pbas,25 :: 		main:
$0004	$	_main_main:
;Pic1.pbas,26 :: 		TRISA=%11111111
$0004	$30FF			MOVLW	255
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0085			MOVWF	TRISA
;Pic1.pbas,27 :: 		TRISB=%01101111
$0008	$306F			MOVLW	111
$0009	$0086			MOVWF	TRISB
;Pic1.pbas,28 :: 		TRISC=%00000000
$000A	$0187			CLRF	TRISC, 1
;Pic1.pbas,29 :: 		INTCON=%00000000
$000B	$018B			CLRF	INTCON, 1
;Pic1.pbas,30 :: 		ANSEL=%00000000
$000C	$1703			BSF	STATUS, RP1
$000D	$1283			BCF	STATUS, RP0
$000E	$019E			CLRF	ANSEL, 1
;Pic1.pbas,31 :: 		ANSELH=%00000000
$000F	$019F			CLRF	ANSELH, 1
;Pic1.pbas,32 :: 		PORTC=0
$0010	$1303			BCF	STATUS, RP1
$0011	$0187			CLRF	PORTC, 1
;Pic1.pbas,33 :: 		Usart_Init(9600)
$0012	$3019			MOVLW	25
$0013	$1683			BSF	STATUS, RP0
$0014	$0099			MOVWF	SPBRG
$0015	$1518			BSF	TXSTA, BRGH
$0016	$158A			BSF	PCLATH, 3
$0017	$201D			CALL	_usart_init
$0018	$118A			BCF	PCLATH, 3
;Pic1.pbas,35 :: 		b0=false
$0019	$01B2			CLRF	_b0, 1
;Pic1.pbas,36 :: 		b1=false
$001A	$01B3			CLRF	_b1, 1
;Pic1.pbas,37 :: 		b2=false
$001B	$01B4			CLRF	_b2, 1
;Pic1.pbas,38 :: 		b3=false
$001C	$01B5			CLRF	_b3, 1
;Pic1.pbas,39 :: 		b4=false
$001D	$01B6			CLRF	_b4, 1
;Pic1.pbas,40 :: 		b5=false
$001E	$01B7			CLRF	_b5, 1
;Pic1.pbas,41 :: 		priorit=1
$001F	$3001			MOVLW	1
$0020	$00A1			MOVWF	_priorit
$0021	$01A2			CLRF	_priorit+1
;Pic1.pbas,42 :: 		incP=0
$0022	$01B0			CLRF	_incp
$0023	$01B1			CLRF	_incp+1
;Pic1.pbas,43 :: 		incN=0
$0024	$01A5			CLRF	_incn
$0025	$01A6			CLRF	_incn+1
;Pic1.pbas,45 :: 		executa:
$0026	$	_main_executa:
;Pic1.pbas,47 :: 		if USART_Data_Ready() > 0 then
$0026	$158A			BSF	PCLATH, 3
$0027	$2065			CALL	_usart_data_ready
$0028	$118A			BCF	PCLATH, 3
$0029	$0870			MOVF	STACK_0, 0
$002A	$3C00			SUBLW	0
$002B	$1803			BTFSC	STATUS, C
$002C	$2893			GOTO	Pic1_L_9
$002D	$	Pic1_L_8:
;Pic1.pbas,48 :: 		Usart_Read_Text(recebe, "/")
$002D	$3038			MOVLW	_recebe
$002E	$00D7			MOVWF	FARG_Usart_Read_Text
$002F	$302F			MOVLW	47
$0030	$00CD			MOVWF	?main_Local_Text+0
$0031	$01CE			CLRF	?main_Local_Text+1
$0032	$304D			MOVLW	?main_Local_Text
$0033	$00D8			MOVWF	FARG_Usart_Read_Text+1
$0034	$2646			CALL	_usart_read_text
;Pic1.pbas,49 :: 		valor = StrToInt(recebe)
$0035	$3038			MOVLW	_recebe
$0036	$00D7			MOVWF	FARG_StrToInt
$0037	$239E			CALL	_strtoint
$0038	$0870			MOVF	STACK_0, 0
$0039	$00BF			MOVWF	_valor
$003A	$0871			MOVF	STACK_0+1, 0
$003B	$00C0			MOVWF	_valor+1
;Pic1.pbas,50 :: 		if (valor < 2000) and (valor >= 1000) then
$003C	$3080			MOVLW	128
$003D	$0671			XORWF	STACK_0+1, 0
$003E	$00F4			MOVWF	STACK_4
$003F	$3080			MOVLW	128
$0040	$3A07			XORLW	7
$0041	$0274			SUBWF	STACK_4, 0
$0042	$1D03			BTFSS	STATUS, Z
$0043	$2846			GOTO	L_main_2
$0044	$30D0			MOVLW	208
$0045	$0270			SUBWF	STACK_0, 0
$0046	$	L_main_2:
$0046	$30FF			MOVLW	255
$0047	$1803			BTFSC	STATUS, C
$0048	$3000			MOVLW	0
$0049	$00F4			MOVWF	STACK_4
$004A	$3080			MOVLW	128
$004B	$0671			XORWF	STACK_0+1, 0
$004C	$00F2			MOVWF	STACK_2
$004D	$3080			MOVLW	128
$004E	$3A03			XORLW	3
$004F	$0272			SUBWF	STACK_2, 0
$0050	$1D03			BTFSS	STATUS, Z
$0051	$2854			GOTO	L_main_3
$0052	$30E8			MOVLW	232
$0053	$0270			SUBWF	STACK_0, 0
$0054	$	L_main_3:
$0054	$30FF			MOVLW	255
$0055	$1C03			BTFSS	STATUS, C
$0056	$3000			MOVLW	0
$0057	$00F2			MOVWF	STACK_2
$0058	$0872			MOVF	STACK_2, 0
$0059	$0574			ANDWF	STACK_4, 0
$005A	$00F0			MOVWF	STACK_0
$005B	$1903			BTFSC	STATUS, Z
$005C	$2868			GOTO	Pic1_L_12
$005D	$	Pic1_L_11:
;Pic1.pbas,51 :: 		priorit = 1
$005D	$3001			MOVLW	1
$005E	$00A1			MOVWF	_priorit
$005F	$01A2			CLRF	_priorit+1
;Pic1.pbas,52 :: 		Norm = valor - 1000
$0060	$30E8			MOVLW	232
$0061	$023F			SUBWF	_valor, 0
$0062	$00C1			MOVWF	_norm
$0063	$3003			MOVLW	3
$0064	$1C03			BTFSS	STATUS, C
$0065	$3F01			ADDLW	1
$0066	$0240			SUBWF	_valor+1, 0
$0067	$00C2			MOVWF	_norm+1
$0068	$	Pic1_L_12:
;Pic1.pbas,53 :: 		end if
$0068	$	Pic1_L_13:
;Pic1.pbas,54 :: 		if (valor < 3000) and (valor >= 2000) then
$0068	$3080			MOVLW	128
$0069	$0640			XORWF	_valor+1, 0
$006A	$00F2			MOVWF	STACK_2
$006B	$3080			MOVLW	128
$006C	$3A0B			XORLW	11
$006D	$0272			SUBWF	STACK_2, 0
$006E	$1D03			BTFSS	STATUS, Z
$006F	$2872			GOTO	L_main_4
$0070	$30B8			MOVLW	184
$0071	$023F			SUBWF	_valor, 0
$0072	$	L_main_4:
$0072	$30FF			MOVLW	255
$0073	$1803			BTFSC	STATUS, C
$0074	$3000			MOVLW	0
$0075	$00F2			MOVWF	STACK_2
$0076	$3080			MOVLW	128
$0077	$0640			XORWF	_valor+1, 0
$0078	$00F0			MOVWF	STACK_0
$0079	$3080			MOVLW	128
$007A	$3A07			XORLW	7
$007B	$0270			SUBWF	STACK_0, 0
$007C	$1D03			BTFSS	STATUS, Z
$007D	$2880			GOTO	L_main_5
$007E	$30D0			MOVLW	208
$007F	$023F			SUBWF	_valor, 0
$0080	$	L_main_5:
$0080	$30FF			MOVLW	255
$0081	$1C03			BTFSS	STATUS, C
$0082	$3000			MOVLW	0
$0083	$00F0			MOVWF	STACK_0
$0084	$0872			MOVF	STACK_2, 0
$0085	$05F0			ANDWF	STACK_0, 1
$0086	$1903			BTFSC	STATUS, Z
$0087	$2893			GOTO	Pic1_L_15
$0088	$	Pic1_L_14:
;Pic1.pbas,55 :: 		priorit = 2
$0088	$3002			MOVLW	2
$0089	$00A1			MOVWF	_priorit
$008A	$01A2			CLRF	_priorit+1
;Pic1.pbas,56 :: 		Pref = valor - 2000
$008B	$30D0			MOVLW	208
$008C	$023F			SUBWF	_valor, 0
$008D	$00C3			MOVWF	_pref
$008E	$3007			MOVLW	7
$008F	$1C03			BTFSS	STATUS, C
$0090	$3F01			ADDLW	1
$0091	$0240			SUBWF	_valor+1, 0
$0092	$00C4			MOVWF	_pref+1
$0093	$	Pic1_L_15:
;Pic1.pbas,57 :: 		end if
$0093	$	Pic1_L_16:
$0093	$	Pic1_L_9:
;Pic1.pbas,58 :: 		end if
$0093	$	Pic1_L_10:
;Pic1.pbas,61 :: 		if testbit(portA,0) = 1 then
$0093	$3001			MOVLW	1
$0094	$0505			ANDWF	PORTA, 0
$0095	$00F2			MOVWF	STACK_2
$0096	$0872			MOVF	STACK_2, 0
$0097	$3A01			XORLW	1
$0098	$1D03			BTFSS	STATUS, Z
$0099	$28FB			GOTO	Pic1_L_18
$009A	$	Pic1_L_17:
;Pic1.pbas,62 :: 		if b0 = false then
$009A	$0832			MOVF	_b0, 0
$009B	$3A00			XORLW	0
$009C	$1D03			BTFSS	STATUS, Z
$009D	$28FB			GOTO	Pic1_L_21
$009E	$	Pic1_L_20:
;Pic1.pbas,63 :: 		b0 = true
$009E	$30FF			MOVLW	255
$009F	$00B2			MOVWF	_b0
;Pic1.pbas,64 :: 		if priorit = 1 then
$00A0	$3000			MOVLW	0
$00A1	$0622			XORWF	_priorit+1, 0
$00A2	$1D03			BTFSS	STATUS, Z
$00A3	$28A6			GOTO	L_main_6
$00A4	$3001			MOVLW	1
$00A5	$0621			XORWF	_priorit, 0
$00A6	$	L_main_6:
$00A6	$1D03			BTFSS	STATUS, Z
$00A7	$28D2			GOTO	Pic1_L_24
$00A8	$	Pic1_L_23:
;Pic1.pbas,65 :: 		incN = incN + 1
$00A8	$0825			MOVF	_incn, 0
$00A9	$3F01			ADDLW	1
$00AA	$00F2			MOVWF	STACK_2
$00AB	$3000			MOVLW	0
$00AC	$1803			BTFSC	STATUS, C
$00AD	$3F01			ADDLW	1
$00AE	$0726			ADDWF	_incn+1, 0
$00AF	$00F3			MOVWF	STACK_2+1
$00B0	$0872			MOVF	STACK_2, 0
$00B1	$00A5			MOVWF	_incn
$00B2	$0873			MOVF	STACK_2+1, 0
$00B3	$00A6			MOVWF	_incn+1
;Pic1.pbas,66 :: 		if incN > 999 then
$00B4	$3080			MOVLW	128
$00B5	$3A03			XORLW	3
$00B6	$00F0			MOVWF	STACK_0
$00B7	$3080			MOVLW	128
$00B8	$0673			XORWF	STACK_2+1, 0
$00B9	$0270			SUBWF	STACK_0, 0
$00BA	$1D03			BTFSS	STATUS, Z
$00BB	$28BE			GOTO	L_main_7
$00BC	$0872			MOVF	STACK_2, 0
$00BD	$3CE7			SUBLW	231
$00BE	$	L_main_7:
$00BE	$1803			BTFSC	STATUS, C
$00BF	$28C4			GOTO	Pic1_L_27
$00C0	$	Pic1_L_26:
;Pic1.pbas,67 :: 		incN = 999
$00C0	$30E7			MOVLW	231
$00C1	$00A5			MOVWF	_incn
$00C2	$3003			MOVLW	3
$00C3	$00A6			MOVWF	_incn+1
$00C4	$	Pic1_L_27:
;Pic1.pbas,68 :: 		end if
$00C4	$	Pic1_L_28:
;Pic1.pbas,69 :: 		if incN < 0 then
$00C4	$3080			MOVLW	128
$00C5	$0626			XORWF	_incn+1, 0
$00C6	$00F0			MOVWF	STACK_0
$00C7	$3080			MOVLW	128
$00C8	$0270			SUBWF	STACK_0, 0
$00C9	$1D03			BTFSS	STATUS, Z
$00CA	$28CD			GOTO	L_main_8
$00CB	$3000			MOVLW	0
$00CC	$0225			SUBWF	_incn, 0
$00CD	$	L_main_8:
$00CD	$1803			BTFSC	STATUS, C
$00CE	$28D1			GOTO	Pic1_L_30
$00CF	$	Pic1_L_29:
;Pic1.pbas,70 :: 		incN = 0
$00CF	$01A5			CLRF	_incn
$00D0	$01A6			CLRF	_incn+1
$00D1	$	Pic1_L_30:
;Pic1.pbas,71 :: 		end if
$00D1	$	Pic1_L_31:
$00D1	$28FB			GOTO	Pic1_L_25
;Pic1.pbas,72 :: 		else
$00D2	$	Pic1_L_24:
;Pic1.pbas,73 :: 		incP = incP + 1
$00D2	$0830			MOVF	_incp, 0
$00D3	$3F01			ADDLW	1
$00D4	$00F2			MOVWF	STACK_2
$00D5	$3000			MOVLW	0
$00D6	$1803			BTFSC	STATUS, C
$00D7	$3F01			ADDLW	1
$00D8	$0731			ADDWF	_incp+1, 0
$00D9	$00F3			MOVWF	STACK_2+1
$00DA	$0872			MOVF	STACK_2, 0
$00DB	$00B0			MOVWF	_incp
$00DC	$0873			MOVF	STACK_2+1, 0
$00DD	$00B1			MOVWF	_incp+1
;Pic1.pbas,74 :: 		if incP > 999 then
$00DE	$3080			MOVLW	128
$00DF	$3A03			XORLW	3
$00E0	$00F0			MOVWF	STACK_0
$00E1	$3080			MOVLW	128
$00E2	$0673			XORWF	STACK_2+1, 0
$00E3	$0270			SUBWF	STACK_0, 0
$00E4	$1D03			BTFSS	STATUS, Z
$00E5	$28E8			GOTO	L_main_9
$00E6	$0872			MOVF	STACK_2, 0
$00E7	$3CE7			SUBLW	231
$00E8	$	L_main_9:
$00E8	$1803			BTFSC	STATUS, C
$00E9	$28EE			GOTO	Pic1_L_33
$00EA	$	Pic1_L_32:
;Pic1.pbas,75 :: 		incP = 999
$00EA	$30E7			MOVLW	231
$00EB	$00B0			MOVWF	_incp
$00EC	$3003			MOVLW	3
$00ED	$00B1			MOVWF	_incp+1
$00EE	$	Pic1_L_33:
;Pic1.pbas,76 :: 		end if
$00EE	$	Pic1_L_34:
;Pic1.pbas,77 :: 		if incP < 0 then
$00EE	$3080			MOVLW	128
$00EF	$0631			XORWF	_incp+1, 0
$00F0	$00F0			MOVWF	STACK_0
$00F1	$3080			MOVLW	128
$00F2	$0270			SUBWF	STACK_0, 0
$00F3	$1D03			BTFSS	STATUS, Z
$00F4	$28F7			GOTO	L_main_10
$00F5	$3000			MOVLW	0
$00F6	$0230			SUBWF	_incp, 0
$00F7	$	L_main_10:
$00F7	$1803			BTFSC	STATUS, C
$00F8	$28FB			GOTO	Pic1_L_36
$00F9	$	Pic1_L_35:
;Pic1.pbas,78 :: 		incP = 0
$00F9	$01B0			CLRF	_incp
$00FA	$01B1			CLRF	_incp+1
$00FB	$	Pic1_L_36:
;Pic1.pbas,79 :: 		end if
$00FB	$	Pic1_L_37:
;Pic1.pbas,80 :: 		end if
$00FB	$	Pic1_L_25:
$00FB	$	Pic1_L_21:
;Pic1.pbas,81 :: 		end if
$00FB	$	Pic1_L_22:
$00FB	$	Pic1_L_18:
;Pic1.pbas,82 :: 		end if
$00FB	$	Pic1_L_19:
;Pic1.pbas,83 :: 		if testbit(portA,0) = 0 then
$00FB	$3001			MOVLW	1
$00FC	$0505			ANDWF	PORTA, 0
$00FD	$00F2			MOVWF	STACK_2
$00FE	$0872			MOVF	STACK_2, 0
$00FF	$3A00			XORLW	0
$0100	$1D03			BTFSS	STATUS, Z
$0101	$2907			GOTO	Pic1_L_39
$0102	$	Pic1_L_38:
;Pic1.pbas,84 :: 		if b0 = true then
$0102	$0832			MOVF	_b0, 0
$0103	$3AFF			XORLW	255
$0104	$1D03			BTFSS	STATUS, Z
$0105	$2907			GOTO	Pic1_L_42
$0106	$	Pic1_L_41:
;Pic1.pbas,85 :: 		b0 = false
$0106	$01B2			CLRF	_b0, 1
$0107	$	Pic1_L_42:
;Pic1.pbas,86 :: 		end if
$0107	$	Pic1_L_43:
$0107	$	Pic1_L_39:
;Pic1.pbas,87 :: 		end if
$0107	$	Pic1_L_40:
;Pic1.pbas,90 :: 		if testbit(portA,1) = 1 then
$0107	$3000			MOVLW	0
$0108	$1885			BTFSC	PORTA, 1
$0109	$3001			MOVLW	1
$010A	$00F2			MOVWF	STACK_2
$010B	$0872			MOVF	STACK_2, 0
$010C	$3A01			XORLW	1
$010D	$1D03			BTFSS	STATUS, Z
$010E	$2926			GOTO	Pic1_L_45
$010F	$	Pic1_L_44:
;Pic1.pbas,91 :: 		if b1 = false then
$010F	$0833			MOVF	_b1, 0
$0110	$3A00			XORLW	0
$0111	$1D03			BTFSS	STATUS, Z
$0112	$2926			GOTO	Pic1_L_48
$0113	$	Pic1_L_47:
;Pic1.pbas,92 :: 		b1 = true
$0113	$30FF			MOVLW	255
$0114	$00B3			MOVWF	_b1
;Pic1.pbas,93 :: 		if priorit = 1 then
$0115	$3000			MOVLW	0
$0116	$0622			XORWF	_priorit+1, 0
$0117	$1D03			BTFSS	STATUS, Z
$0118	$291B			GOTO	L_main_11
$0119	$3001			MOVLW	1
$011A	$0621			XORWF	_priorit, 0
$011B	$	L_main_11:
$011B	$1D03			BTFSS	STATUS, Z
$011C	$2922			GOTO	Pic1_L_51
$011D	$	Pic1_L_50:
;Pic1.pbas,94 :: 		incN = incN - 1
$011D	$3001			MOVLW	1
$011E	$02A5			SUBWF	_incn, 1
$011F	$1C03			BTFSS	STATUS, C
$0120	$03A6			DECF	_incn+1, 1
$0121	$2926			GOTO	Pic1_L_52
;Pic1.pbas,95 :: 		else
$0122	$	Pic1_L_51:
;Pic1.pbas,96 :: 		incP = incP - 1
$0122	$3001			MOVLW	1
$0123	$02B0			SUBWF	_incp, 1
$0124	$1C03			BTFSS	STATUS, C
$0125	$03B1			DECF	_incp+1, 1
;Pic1.pbas,97 :: 		end if
$0126	$	Pic1_L_52:
$0126	$	Pic1_L_48:
;Pic1.pbas,98 :: 		end if
$0126	$	Pic1_L_49:
$0126	$	Pic1_L_45:
;Pic1.pbas,99 :: 		end if
$0126	$	Pic1_L_46:
;Pic1.pbas,100 :: 		if testbit(portA,1) = 0 then
$0126	$3000			MOVLW	0
$0127	$1885			BTFSC	PORTA, 1
$0128	$3001			MOVLW	1
$0129	$00F2			MOVWF	STACK_2
$012A	$0872			MOVF	STACK_2, 0
$012B	$3A00			XORLW	0
$012C	$1D03			BTFSS	STATUS, Z
$012D	$2933			GOTO	Pic1_L_54
$012E	$	Pic1_L_53:
;Pic1.pbas,101 :: 		if b1 = true then
$012E	$0833			MOVF	_b1, 0
$012F	$3AFF			XORLW	255
$0130	$1D03			BTFSS	STATUS, Z
$0131	$2933			GOTO	Pic1_L_57
$0132	$	Pic1_L_56:
;Pic1.pbas,102 :: 		b1 = false
$0132	$01B3			CLRF	_b1, 1
$0133	$	Pic1_L_57:
;Pic1.pbas,103 :: 		end if
$0133	$	Pic1_L_58:
$0133	$	Pic1_L_54:
;Pic1.pbas,104 :: 		end if
$0133	$	Pic1_L_55:
;Pic1.pbas,107 :: 		if testbit(portA,3) = 1 then
$0133	$3000			MOVLW	0
$0134	$1985			BTFSC	PORTA, 3
$0135	$3001			MOVLW	1
$0136	$00F2			MOVWF	STACK_2
$0137	$0872			MOVF	STACK_2, 0
$0138	$3A01			XORLW	1
$0139	$1D03			BTFSS	STATUS, Z
$013A	$2950			GOTO	Pic1_L_60
$013B	$	Pic1_L_59:
;Pic1.pbas,108 :: 		if b3 = false then
$013B	$0835			MOVF	_b3, 0
$013C	$3A00			XORLW	0
$013D	$1D03			BTFSS	STATUS, Z
$013E	$2950			GOTO	Pic1_L_63
$013F	$	Pic1_L_62:
;Pic1.pbas,109 :: 		b3 = true
$013F	$30FF			MOVLW	255
$0140	$00B5			MOVWF	_b3
;Pic1.pbas,110 :: 		if priorit = 1 then
$0141	$3000			MOVLW	0
$0142	$0622			XORWF	_priorit+1, 0
$0143	$1D03			BTFSS	STATUS, Z
$0144	$2947			GOTO	L_main_12
$0145	$3001			MOVLW	1
$0146	$0621			XORWF	_priorit, 0
$0147	$	L_main_12:
$0147	$1D03			BTFSS	STATUS, Z
$0148	$294D			GOTO	Pic1_L_66
$0149	$	Pic1_L_65:
;Pic1.pbas,111 :: 		priorit = 2
$0149	$3002			MOVLW	2
$014A	$00A1			MOVWF	_priorit
$014B	$01A2			CLRF	_priorit+1
$014C	$2950			GOTO	Pic1_L_67
;Pic1.pbas,112 :: 		else
$014D	$	Pic1_L_66:
;Pic1.pbas,113 :: 		priorit = 1
$014D	$3001			MOVLW	1
$014E	$00A1			MOVWF	_priorit
$014F	$01A2			CLRF	_priorit+1
;Pic1.pbas,114 :: 		end if
$0150	$	Pic1_L_67:
$0150	$	Pic1_L_63:
;Pic1.pbas,115 :: 		end if
$0150	$	Pic1_L_64:
$0150	$	Pic1_L_60:
;Pic1.pbas,116 :: 		end if
$0150	$	Pic1_L_61:
;Pic1.pbas,117 :: 		if testbit(portA,3) = 0 then
$0150	$3000			MOVLW	0
$0151	$1985			BTFSC	PORTA, 3
$0152	$3001			MOVLW	1
$0153	$00F2			MOVWF	STACK_2
$0154	$0872			MOVF	STACK_2, 0
$0155	$3A00			XORLW	0
$0156	$1D03			BTFSS	STATUS, Z
$0157	$295D			GOTO	Pic1_L_69
$0158	$	Pic1_L_68:
;Pic1.pbas,118 :: 		if b3 = true then
$0158	$0835			MOVF	_b3, 0
$0159	$3AFF			XORLW	255
$015A	$1D03			BTFSS	STATUS, Z
$015B	$295D			GOTO	Pic1_L_72
$015C	$	Pic1_L_71:
;Pic1.pbas,119 :: 		b3 = false
$015C	$01B5			CLRF	_b3, 1
$015D	$	Pic1_L_72:
;Pic1.pbas,120 :: 		end if
$015D	$	Pic1_L_73:
$015D	$	Pic1_L_69:
;Pic1.pbas,121 :: 		end if
$015D	$	Pic1_L_70:
;Pic1.pbas,141 :: 		if testbit(portA,5) = 1 then
$015D	$3000			MOVLW	0
$015E	$1A85			BTFSC	PORTA, 5
$015F	$3001			MOVLW	1
$0160	$00F2			MOVWF	STACK_2
$0161	$0872			MOVF	STACK_2, 0
$0162	$3A01			XORLW	1
$0163	$1D03			BTFSS	STATUS, Z
$0164	$296C			GOTO	Pic1_L_75
$0165	$	Pic1_L_74:
;Pic1.pbas,142 :: 		if b5 = false then
$0165	$0837			MOVF	_b5, 0
$0166	$3A00			XORLW	0
$0167	$1D03			BTFSS	STATUS, Z
$0168	$296C			GOTO	Pic1_L_78
$0169	$	Pic1_L_77:
;Pic1.pbas,143 :: 		b5 = true
$0169	$30FF			MOVLW	255
$016A	$00B7			MOVWF	_b5
;Pic1.pbas,144 :: 		envia
$016B	$25A1			CALL	_envia
$016C	$	Pic1_L_78:
;Pic1.pbas,145 :: 		end if
$016C	$	Pic1_L_79:
$016C	$	Pic1_L_75:
;Pic1.pbas,146 :: 		end if
$016C	$	Pic1_L_76:
;Pic1.pbas,147 :: 		if testbit(portA,5) = 0 then
$016C	$3000			MOVLW	0
$016D	$1A85			BTFSC	PORTA, 5
$016E	$3001			MOVLW	1
$016F	$00F2			MOVWF	STACK_2
$0170	$0872			MOVF	STACK_2, 0
$0171	$3A00			XORLW	0
$0172	$1D03			BTFSS	STATUS, Z
$0173	$2975			GOTO	Pic1_L_81
$0174	$	Pic1_L_80:
;Pic1.pbas,148 :: 		b5 = false
$0174	$01B7			CLRF	_b5, 1
$0175	$	Pic1_L_81:
;Pic1.pbas,149 :: 		end if
$0175	$	Pic1_L_82:
;Pic1.pbas,158 :: 		mil = valor div 1000
$0175	$30E8			MOVLW	232
$0176	$00F4			MOVWF	STACK_4
$0177	$3003			MOVLW	3
$0178	$00F5			MOVWF	STACK_4+1
$0179	$083F			MOVF	_valor, 0
$017A	$00F0			MOVWF	STACK_0
$017B	$0840			MOVF	_valor+1, 0
$017C	$00F1			MOVWF	STACK_0+1
$017D	$25EC			CALL	_div_16x16_s
$017E	$0870			MOVF	STACK_0, 0
$017F	$00D5			MOVWF	FLOC_main+8
$0180	$0871			MOVF	STACK_0+1, 0
$0181	$00D6			MOVWF	FLOC_main+9
$0182	$0855			MOVF	FLOC_main+8, 0
$0183	$00C5			MOVWF	_mil
$0184	$0856			MOVF	FLOC_main+9, 0
$0185	$00C6			MOVWF	_mil+1
;Pic1.pbas,159 :: 		cen = valor div 100 - (mil * 10)
$0186	$3064			MOVLW	100
$0187	$00F4			MOVWF	STACK_4
$0188	$01F5			CLRF	STACK_4+1
$0189	$083F			MOVF	_valor, 0
$018A	$00F0			MOVWF	STACK_0
$018B	$0840			MOVF	_valor+1, 0
$018C	$00F1			MOVWF	STACK_0+1
$018D	$25EC			CALL	_div_16x16_s
$018E	$0870			MOVF	STACK_0, 0
$018F	$00CF			MOVWF	FLOC_main+2
$0190	$0871			MOVF	STACK_0+1, 0
$0191	$00D0			MOVWF	FLOC_main+3
$0192	$0855			MOVF	FLOC_main+8, 0
$0193	$00F0			MOVWF	STACK_0
$0194	$0856			MOVF	FLOC_main+9, 0
$0195	$00F1			MOVWF	STACK_0+1
$0196	$300A			MOVLW	10
$0197	$00F4			MOVWF	STACK_4
$0198	$01F5			CLRF	STACK_4+1
$0199	$268D			CALL	_mul_16x16_s
$019A	$0870			MOVF	STACK_0, 0
$019B	$024F			SUBWF	FLOC_main+2, 0
$019C	$00D3			MOVWF	FLOC_main+6
$019D	$0871			MOVF	STACK_0+1, 0
$019E	$1C03			BTFSS	STATUS, C
$019F	$3F01			ADDLW	1
$01A0	$0250			SUBWF	FLOC_main+3, 0
$01A1	$00D4			MOVWF	FLOC_main+7
$01A2	$0853			MOVF	FLOC_main+6, 0
$01A3	$00C7			MOVWF	_cen
$01A4	$0854			MOVF	FLOC_main+7, 0
$01A5	$00C8			MOVWF	_cen+1
;Pic1.pbas,160 :: 		dez = valor div 10 - (cen * 10) - (mil * 100)
$01A6	$300A			MOVLW	10
$01A7	$00F4			MOVWF	STACK_4
$01A8	$01F5			CLRF	STACK_4+1
$01A9	$083F			MOVF	_valor, 0
$01AA	$00F0			MOVWF	STACK_0
$01AB	$0840			MOVF	_valor+1, 0
$01AC	$00F1			MOVWF	STACK_0+1
$01AD	$25EC			CALL	_div_16x16_s
$01AE	$0870			MOVF	STACK_0, 0
$01AF	$00CF			MOVWF	FLOC_main+2
$01B0	$0871			MOVF	STACK_0+1, 0
$01B1	$00D0			MOVWF	FLOC_main+3
$01B2	$0853			MOVF	FLOC_main+6, 0
$01B3	$00F0			MOVWF	STACK_0
$01B4	$0854			MOVF	FLOC_main+7, 0
$01B5	$00F1			MOVWF	STACK_0+1
$01B6	$300A			MOVLW	10
$01B7	$00F4			MOVWF	STACK_4
$01B8	$01F5			CLRF	STACK_4+1
$01B9	$268D			CALL	_mul_16x16_s
$01BA	$0870			MOVF	STACK_0, 0
$01BB	$02CF			SUBWF	FLOC_main+2, 1
$01BC	$1C03			BTFSS	STATUS, C
$01BD	$03D0			DECF	FLOC_main+3, 1
$01BE	$0871			MOVF	STACK_0+1, 0
$01BF	$02D0			SUBWF	FLOC_main+3, 1
$01C0	$0855			MOVF	FLOC_main+8, 0
$01C1	$00F0			MOVWF	STACK_0
$01C2	$0856			MOVF	FLOC_main+9, 0
$01C3	$00F1			MOVWF	STACK_0+1
$01C4	$3064			MOVLW	100
$01C5	$00F4			MOVWF	STACK_4
$01C6	$01F5			CLRF	STACK_4+1
$01C7	$268D			CALL	_mul_16x16_s
$01C8	$0870			MOVF	STACK_0, 0
$01C9	$024F			SUBWF	FLOC_main+2, 0
$01CA	$00D1			MOVWF	FLOC_main+4
$01CB	$0871			MOVF	STACK_0+1, 0
$01CC	$1C03			BTFSS	STATUS, C
$01CD	$3F01			ADDLW	1
$01CE	$0250			SUBWF	FLOC_main+3, 0
$01CF	$00D2			MOVWF	FLOC_main+5
$01D0	$0851			MOVF	FLOC_main+4, 0
$01D1	$00C9			MOVWF	_dez
$01D2	$0852			MOVF	FLOC_main+5, 0
$01D3	$00CA			MOVWF	_dez+1
;Pic1.pbas,161 :: 		uni = valor - (dez * 10) - (cen * 100) - (mil * 1000)
$01D4	$0851			MOVF	FLOC_main+4, 0
$01D5	$00F0			MOVWF	STACK_0
$01D6	$0852			MOVF	FLOC_main+5, 0
$01D7	$00F1			MOVWF	STACK_0+1
$01D8	$300A			MOVLW	10
$01D9	$00F4			MOVWF	STACK_4
$01DA	$01F5			CLRF	STACK_4+1
$01DB	$268D			CALL	_mul_16x16_s
$01DC	$0870			MOVF	STACK_0, 0
$01DD	$023F			SUBWF	_valor, 0
$01DE	$00CF			MOVWF	FLOC_main+2
$01DF	$0871			MOVF	STACK_0+1, 0
$01E0	$1C03			BTFSS	STATUS, C
$01E1	$3F01			ADDLW	1
$01E2	$0240			SUBWF	_valor+1, 0
$01E3	$00D0			MOVWF	FLOC_main+3
$01E4	$0853			MOVF	FLOC_main+6, 0
$01E5	$00F0			MOVWF	STACK_0
$01E6	$0854			MOVF	FLOC_main+7, 0
$01E7	$00F1			MOVWF	STACK_0+1
$01E8	$3064			MOVLW	100
$01E9	$00F4			MOVWF	STACK_4
$01EA	$01F5			CLRF	STACK_4+1
$01EB	$268D			CALL	_mul_16x16_s
$01EC	$0870			MOVF	STACK_0, 0
$01ED	$02CF			SUBWF	FLOC_main+2, 1
$01EE	$1C03			BTFSS	STATUS, C
$01EF	$03D0			DECF	FLOC_main+3, 1
$01F0	$0871			MOVF	STACK_0+1, 0
$01F1	$02D0			SUBWF	FLOC_main+3, 1
$01F2	$0855			MOVF	FLOC_main+8, 0
$01F3	$00F0			MOVWF	STACK_0
$01F4	$0856			MOVF	FLOC_main+9, 0
$01F5	$00F1			MOVWF	STACK_0+1
$01F6	$30E8			MOVLW	232
$01F7	$00F4			MOVWF	STACK_4
$01F8	$3003			MOVLW	3
$01F9	$00F5			MOVWF	STACK_4+1
$01FA	$268D			CALL	_mul_16x16_s
$01FB	$0870			MOVF	STACK_0, 0
$01FC	$024F			SUBWF	FLOC_main+2, 0
$01FD	$00F0			MOVWF	STACK_0
$01FE	$0871			MOVF	STACK_0+1, 0
$01FF	$1C03			BTFSS	STATUS, C
$0200	$3F01			ADDLW	1
$0201	$0250			SUBWF	FLOC_main+3, 0
$0202	$00F1			MOVWF	STACK_0+1
$0203	$0870			MOVF	STACK_0, 0
$0204	$00CB			MOVWF	_uni
$0205	$0871			MOVF	STACK_0+1, 0
$0206	$00CC			MOVWF	_uni+1
;Pic1.pbas,163 :: 		PORTC = uni + 16
$0207	$3010			MOVLW	16
$0208	$07F0			ADDWF	STACK_0, 1
$0209	$1803			BTFSC	STATUS, C
$020A	$0AF1			INCF	STACK_0+1, 1
$020B	$0870			MOVF	STACK_0, 0
$020C	$0087			MOVWF	PORTC
;Pic1.pbas,164 :: 		delay_ms(5)
$020D	$3007			MOVLW	7
$020E	$00FB			MOVWF	STACK_11
$020F	$30FF			MOVLW	255
$0210	$00FA			MOVWF	STACK_10
$0211	$0BFB			DECFSZ	STACK_11, F
$0212	$2A14			GOTO	$+2
$0213	$2A17			GOTO	$+4
$0214	$0BFA			DECFSZ	STACK_10, F
$0215	$2A14			GOTO	$-1
$0216	$2A11			GOTO	$-5
$0217	$3078			MOVLW	120
$0218	$00FA			MOVWF	STACK_10
$0219	$0BFA			DECFSZ	STACK_10, F
$021A	$2A19			GOTO	$-1
$021B	$0000			NOP
$021C	$0000			NOP
;Pic1.pbas,165 :: 		PORTC = dez + 32
$021D	$3020			MOVLW	32
$021E	$0751			ADDWF	FLOC_main+4, 0
$021F	$00F0			MOVWF	STACK_0
$0220	$0852			MOVF	FLOC_main+5, 0
$0221	$1803			BTFSC	STATUS, C
$0222	$3F01			ADDLW	1
$0223	$00F1			MOVWF	STACK_0+1
$0224	$3000			MOVLW	0
$0225	$07F1			ADDWF	STACK_0+1, 1
$0226	$0870			MOVF	STACK_0, 0
$0227	$0087			MOVWF	PORTC
;Pic1.pbas,166 :: 		delay_ms(5)
$0228	$3007			MOVLW	7
$0229	$00FB			MOVWF	STACK_11
$022A	$30FF			MOVLW	255
$022B	$00FA			MOVWF	STACK_10
$022C	$0BFB			DECFSZ	STACK_11, F
$022D	$2A2F			GOTO	$+2
$022E	$2A32			GOTO	$+4
$022F	$0BFA			DECFSZ	STACK_10, F
$0230	$2A2F			GOTO	$-1
$0231	$2A2C			GOTO	$-5
$0232	$3078			MOVLW	120
$0233	$00FA			MOVWF	STACK_10
$0234	$0BFA			DECFSZ	STACK_10, F
$0235	$2A34			GOTO	$-1
$0236	$0000			NOP
$0237	$0000			NOP
;Pic1.pbas,167 :: 		PORTC = cen + 64
$0238	$3040			MOVLW	64
$0239	$0753			ADDWF	FLOC_main+6, 0
$023A	$00F0			MOVWF	STACK_0
$023B	$0854			MOVF	FLOC_main+7, 0
$023C	$1803			BTFSC	STATUS, C
$023D	$3F01			ADDLW	1
$023E	$00F1			MOVWF	STACK_0+1
$023F	$3000			MOVLW	0
$0240	$07F1			ADDWF	STACK_0+1, 1
$0241	$0870			MOVF	STACK_0, 0
$0242	$0087			MOVWF	PORTC
;Pic1.pbas,168 :: 		delay_ms(5)
$0243	$3007			MOVLW	7
$0244	$00FB			MOVWF	STACK_11
$0245	$30FF			MOVLW	255
$0246	$00FA			MOVWF	STACK_10
$0247	$0BFB			DECFSZ	STACK_11, F
$0248	$2A4A			GOTO	$+2
$0249	$2A4D			GOTO	$+4
$024A	$0BFA			DECFSZ	STACK_10, F
$024B	$2A4A			GOTO	$-1
$024C	$2A47			GOTO	$-5
$024D	$3078			MOVLW	120
$024E	$00FA			MOVWF	STACK_10
$024F	$0BFA			DECFSZ	STACK_10, F
$0250	$2A4F			GOTO	$-1
$0251	$0000			NOP
$0252	$0000			NOP
;Pic1.pbas,169 :: 		PORTC = mil + 128
$0253	$3080			MOVLW	128
$0254	$0755			ADDWF	FLOC_main+8, 0
$0255	$00F0			MOVWF	STACK_0
$0256	$0856			MOVF	FLOC_main+9, 0
$0257	$1803			BTFSC	STATUS, C
$0258	$3F01			ADDLW	1
$0259	$00F1			MOVWF	STACK_0+1
$025A	$3000			MOVLW	0
$025B	$07F1			ADDWF	STACK_0+1, 1
$025C	$0870			MOVF	STACK_0, 0
$025D	$0087			MOVWF	PORTC
;Pic1.pbas,170 :: 		delay_ms(5)
$025E	$3007			MOVLW	7
$025F	$00FB			MOVWF	STACK_11
$0260	$30FF			MOVLW	255
$0261	$00FA			MOVWF	STACK_10
$0262	$0BFB			DECFSZ	STACK_11, F
$0263	$2A65			GOTO	$+2
$0264	$2A68			GOTO	$+4
$0265	$0BFA			DECFSZ	STACK_10, F
$0266	$2A65			GOTO	$-1
$0267	$2A62			GOTO	$-5
$0268	$3078			MOVLW	120
$0269	$00FA			MOVWF	STACK_10
$026A	$0BFA			DECFSZ	STACK_10, F
$026B	$2A6A			GOTO	$-1
$026C	$0000			NOP
$026D	$0000			NOP
;Pic1.pbas,172 :: 		goto executa
$026E	$2826			GOTO	_main_executa
$026F	$2A6F			GOTO	$
