;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 17/04/2020 20:32:38
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;Pic2.pbas,1 :: 		program Pic2
$0004	$	_main_main:
;Pic2.pbas,3 :: 		inicio:
$0004	$	_main_inicio:
;Pic2.pbas,5 :: 		TRISA=%11011111
$0004	$30DF			MOVLW	223
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0085			MOVWF	TRISA
;Pic2.pbas,6 :: 		TRISB=%01111111
$0008	$307F			MOVLW	127
$0009	$0086			MOVWF	TRISB
;Pic2.pbas,7 :: 		TRISC=%00000000
$000A	$0187			CLRF	TRISC, 1
;Pic2.pbas,8 :: 		INTCON=%00000000
$000B	$018B			CLRF	INTCON, 1
;Pic2.pbas,9 :: 		ANSEL=%00000000
$000C	$1703			BSF	STATUS, RP1
$000D	$1283			BCF	STATUS, RP0
$000E	$019E			CLRF	ANSEL, 1
;Pic2.pbas,10 :: 		ANSELH=%00000000
$000F	$019F			CLRF	ANSELH, 1
;Pic2.pbas,12 :: 		executa:
$0010	$	_main_executa:
;Pic2.pbas,16 :: 		goto executa
$0010	$2810			GOTO	_main_executa
$0011	$2811			GOTO	$
