;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 25/04/2020 00:06:10
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$05B4	$	_mul_32x32_u:
$05B4	$1303			BCF	STATUS, RP1
$05B5	$1283			BCF	STATUS, RP0
;math.ppas,1570 :: 		
;math.ppas,1578 :: 		
$05B6	$3022			MOVLW	34
;math.ppas,1579 :: 		
$05B7	$00FC			MOVWF	STACK_12
;math.ppas,1580 :: 		
$05B8	$01F8			CLRF	STACK_8
;math.ppas,1581 :: 		
$05B9	$01F9			CLRF	STACK_9
;math.ppas,1582 :: 		
$05BA	$01FA			CLRF	STACK_10
;math.ppas,1584 :: 		
$05BB	$01FB			CLRF	STACK_11
;math.ppas,1588 :: 		
$05BC	$	_NEXT:
;math.ppas,1589 :: 		
$05BC	$03FC			DECF	STACK_12, F
;math.ppas,1590 :: 		
$05BD	$1903			BTFSC	STATUS, Z
;math.ppas,1591 :: 		
$05BE	$2DEA			GOTO	_EXIT2
;math.ppas,1593 :: 		
$05BF	$1003			BCF	STATUS, C
;math.ppas,1602 :: 		
$05C0	$	_LOOP:
;math.ppas,1603 :: 		
$05C0	$0CFB			RRF	STACK_11, F
;math.ppas,1604 :: 		
$05C1	$0CFA			RRF	STACK_10, F
;math.ppas,1605 :: 		
$05C2	$0CF9			RRF	STACK_9, F
;math.ppas,1606 :: 		
$05C3	$0CF8			RRF	STACK_8, F
;math.ppas,1607 :: 		
$05C4	$0CF3			RRF	STACK_3, F
;math.ppas,1608 :: 		
$05C5	$0CF2			RRF	STACK_2, F
;math.ppas,1609 :: 		
$05C6	$0CF1			RRF	STACK_1, F
;math.ppas,1614 :: 		
$05C7	$0CF0			RRF	STACK_0, F
;math.ppas,1615 :: 		
$05C8	$1C03			BTFSS	STATUS, C
;math.ppas,1616 :: 		
$05C9	$2DBC			GOTO	_NEXT
;math.ppas,1617 :: 		
$05CA	$03FC			DECF	STACK_12, F
;math.ppas,1618 :: 		
$05CB	$1903			BTFSC	STATUS, Z
;math.ppas,1625 :: 		
$05CC	$2DDC			GOTO	_EXIT1
;math.ppas,1626 :: 		
$05CD	$0874			MOVF	STACK_4, W
;math.ppas,1627 :: 		
$05CE	$07F8			ADDWF	STACK_8, F
;math.ppas,1628 :: 		
$05CF	$0875			MOVF	STACK_5, W
;math.ppas,1629 :: 		
$05D0	$1803			BTFSC	STATUS, C
;math.ppas,1630 :: 		
$05D1	$0F75			INCFSZ	STACK_5, W
;math.ppas,1631 :: 		
$05D2	$07F9			ADDWF	STACK_9, F
;math.ppas,1632 :: 		
$05D3	$0876			MOVF	STACK_6, W
;math.ppas,1633 :: 		
$05D4	$1803			BTFSC	STATUS, C
;math.ppas,1634 :: 		
$05D5	$0F76			INCFSZ	STACK_6, W
;math.ppas,1635 :: 		
$05D6	$07FA			ADDWF	STACK_10, F
;math.ppas,1636 :: 		
$05D7	$0877			MOVF	STACK_7, W
;math.ppas,1637 :: 		
$05D8	$1803			BTFSC	STATUS, C
;math.ppas,1638 :: 		
$05D9	$0F77			INCFSZ	STACK_7, W
;math.ppas,1640 :: 		
$05DA	$07FB			ADDWF	STACK_11, F
;math.ppas,1642 :: 		
$05DB	$2DC0			GOTO	_LOOP
;math.ppas,1647 :: 		
$05DC	$	_EXIT1:
;math.ppas,1648 :: 		
$05DC	$0874			MOVF	STACK_4, W
;math.ppas,1649 :: 		
$05DD	$07F8			ADDWF	STACK_8, F
;math.ppas,1650 :: 		
$05DE	$0875			MOVF	STACK_5, W
;math.ppas,1651 :: 		
$05DF	$1803			BTFSC	STATUS, C
;math.ppas,1652 :: 		
$05E0	$0F75			INCFSZ	STACK_5, W
;math.ppas,1653 :: 		
$05E1	$07F9			ADDWF	STACK_9, F
;math.ppas,1654 :: 		
$05E2	$0876			MOVF	STACK_6, W
;math.ppas,1655 :: 		
$05E3	$1803			BTFSC	STATUS, C
;math.ppas,1656 :: 		
$05E4	$0F76			INCFSZ	STACK_6, W
;math.ppas,1657 :: 		
$05E5	$07FA			ADDWF	STACK_10, F
;math.ppas,1658 :: 		
$05E6	$0877			MOVF	STACK_7, W
;math.ppas,1659 :: 		
$05E7	$1803			BTFSC	STATUS, C
;math.ppas,1660 :: 		
$05E8	$0F77			INCFSZ	STACK_7, W
;math.ppas,1663 :: 		
$05E9	$07FB			ADDWF	STACK_11, F
;math.ppas,1664 :: 		
$05EA	$	_EXIT2:
;math.ppas,1665 :: 		
$05EA	$	math_L_13:
;math.ppas,1666 :: 		
$05EA	$0008			RETURN
$0209	$	_sdiv3232l:
$0209	$1303			BCF	STATUS, RP1
$020A	$1283			BCF	STATUS, RP0
;math.ppas,539 :: 		
;math.ppas,541 :: 		
$020B	$0874			MOVF	STACK_4, W
;math.ppas,542 :: 		
$020C	$02F8			SUBWF	STACK_8, F
;math.ppas,543 :: 		
$020D	$0875			MOVF	STACK_5, W
;math.ppas,544 :: 		
$020E	$1C03			BTFSS	STATUS, C
;math.ppas,545 :: 		
$020F	$0F75			INCFSZ	STACK_5, W
;math.ppas,546 :: 		
$0210	$02F9			SUBWF	STACK_9, F
;math.ppas,547 :: 		
$0211	$0876			MOVF	STACK_6, W
;math.ppas,548 :: 		
$0212	$1C03			BTFSS	STATUS, C
;math.ppas,549 :: 		
$0213	$0F76			INCFSZ	STACK_6, W
;math.ppas,550 :: 		
$0214	$02FA			SUBWF	STACK_10, F
;math.ppas,551 :: 		
$0215	$0877			MOVF	STACK_7, W
;math.ppas,552 :: 		
$0216	$1C03			BTFSS	STATUS, C
;math.ppas,553 :: 		
$0217	$0F77			INCFSZ	STACK_7, W
;math.ppas,554 :: 		
$0218	$02FB			SUBWF	STACK_11, F
;math.ppas,556 :: 		
$0219	$0DF3			RLF	STACK_3, F
;math.ppas,557 :: 		
$021A	$3007			MOVLW	7
;math.ppas,559 :: 		
$021B	$00FC			MOVWF	STACK_12
;math.ppas,560 :: 		
$021C	$	LOOPS3232A:
;math.ppas,561 :: 		
$021C	$0D73			RLF	STACK_3, W
;math.ppas,562 :: 		
$021D	$0DF8			RLF	STACK_8, F
;math.ppas,563 :: 		
$021E	$0DF9			RLF	STACK_9, F
;math.ppas,564 :: 		
$021F	$0DFA			RLF	STACK_10, F
;math.ppas,565 :: 		
$0220	$0DFB			RLF	STACK_11, F
;math.ppas,566 :: 		
$0221	$0874			MOVF	STACK_4, W
;math.ppas,567 :: 		
$0222	$1C73			BTFSS	STACK_3, 0
;math.ppas,569 :: 		
$0223	$2A32			GOTO	SADD22LA
;math.ppas,570 :: 		
$0224	$02F8			SUBWF	STACK_8, F
;math.ppas,571 :: 		
$0225	$0875			MOVF	STACK_5, W
;math.ppas,572 :: 		
$0226	$1C03			BTFSS	STATUS, C
;math.ppas,573 :: 		
$0227	$0F75			INCFSZ	STACK_5, W
;math.ppas,574 :: 		
$0228	$02F9			SUBWF	STACK_9, F
;math.ppas,575 :: 		
$0229	$0876			MOVF	STACK_6, W
;math.ppas,576 :: 		
$022A	$1C03			BTFSS	STATUS, C
;math.ppas,577 :: 		
$022B	$0F76			INCFSZ	STACK_6, W
;math.ppas,578 :: 		
$022C	$02FA			SUBWF	STACK_10, F
;math.ppas,579 :: 		
$022D	$0877			MOVF	STACK_7, W
;math.ppas,580 :: 		
$022E	$1C03			BTFSS	STATUS, C
;math.ppas,581 :: 		
$022F	$0F77			INCFSZ	STACK_7, W
;math.ppas,582 :: 		
$0230	$02FB			SUBWF	STACK_11, F
;math.ppas,584 :: 		
$0231	$2A3F			GOTO	SOK22LA
;math.ppas,585 :: 		
$0232	$	SADD22LA:
;math.ppas,586 :: 		
$0232	$07F8			ADDWF	STACK_8, F
;math.ppas,587 :: 		
$0233	$0875			MOVF	STACK_5, W
;math.ppas,588 :: 		
$0234	$1803			BTFSC	STATUS, C
;math.ppas,589 :: 		
$0235	$0F75			INCFSZ	STACK_5, W
;math.ppas,590 :: 		
$0236	$07F9			ADDWF	STACK_9, F
;math.ppas,591 :: 		
$0237	$0876			MOVF	STACK_6, W
;math.ppas,592 :: 		
$0238	$1803			BTFSC	STATUS, C
;math.ppas,593 :: 		
$0239	$0F76			INCFSZ	STACK_6, W
;math.ppas,594 :: 		
$023A	$07FA			ADDWF	STACK_10, F
;math.ppas,595 :: 		
$023B	$0877			MOVF	STACK_7, W
;math.ppas,596 :: 		
$023C	$1803			BTFSC	STATUS, C
;math.ppas,597 :: 		
$023D	$0F77			INCFSZ	STACK_7, W
;math.ppas,599 :: 		
$023E	$07FB			ADDWF	STACK_11, F
;math.ppas,600 :: 		
$023F	$	SOK22LA:
;math.ppas,602 :: 		
$023F	$0DF3			RLF	STACK_3, F
;math.ppas,603 :: 		
$0240	$0BFC			DECFSZ	STACK_12, F
;math.ppas,605 :: 		
$0241	$2A1C			GOTO	LOOPS3232A
;math.ppas,606 :: 		
$0242	$0D72			RLF	STACK_2, W
;math.ppas,607 :: 		
$0243	$0DF8			RLF	STACK_8, F
;math.ppas,608 :: 		
$0244	$0DF9			RLF	STACK_9, F
;math.ppas,609 :: 		
$0245	$0DFA			RLF	STACK_10, F
;math.ppas,610 :: 		
$0246	$0DFB			RLF	STACK_11, F
;math.ppas,611 :: 		
$0247	$0874			MOVF	STACK_4, W
;math.ppas,612 :: 		
$0248	$1C73			BTFSS	STACK_3, 0
;math.ppas,614 :: 		
$0249	$2A58			GOTO	SADD22L8
;math.ppas,615 :: 		
$024A	$02F8			SUBWF	STACK_8, F
;math.ppas,616 :: 		
$024B	$0875			MOVF	STACK_5, W
;math.ppas,617 :: 		
$024C	$1C03			BTFSS	STATUS, C
;math.ppas,618 :: 		
$024D	$0F75			INCFSZ	STACK_5, W
;math.ppas,619 :: 		
$024E	$02F9			SUBWF	STACK_9, F
;math.ppas,620 :: 		
$024F	$0876			MOVF	STACK_6, W
;math.ppas,621 :: 		
$0250	$1C03			BTFSS	STATUS, C
;math.ppas,622 :: 		
$0251	$0F76			INCFSZ	STACK_6, W
;math.ppas,623 :: 		
$0252	$02FA			SUBWF	STACK_10, F
;math.ppas,624 :: 		
$0253	$0877			MOVF	STACK_7, W
;math.ppas,625 :: 		
$0254	$1C03			BTFSS	STATUS, C
;math.ppas,626 :: 		
$0255	$0F77			INCFSZ	STACK_7, W
;math.ppas,627 :: 		
$0256	$02FB			SUBWF	STACK_11, F
;math.ppas,629 :: 		
$0257	$2A65			GOTO	SOK22L8
;math.ppas,630 :: 		
$0258	$	SADD22L8:
;math.ppas,631 :: 		
$0258	$07F8			ADDWF	STACK_8, F
;math.ppas,632 :: 		
$0259	$0875			MOVF	STACK_5, W
;math.ppas,633 :: 		
$025A	$1803			BTFSC	STATUS, C
;math.ppas,634 :: 		
$025B	$0F75			INCFSZ	STACK_5, W
;math.ppas,635 :: 		
$025C	$07F9			ADDWF	STACK_9, F
;math.ppas,636 :: 		
$025D	$0876			MOVF	STACK_6, W
;math.ppas,637 :: 		
$025E	$1803			BTFSC	STATUS, C
;math.ppas,638 :: 		
$025F	$0F76			INCFSZ	STACK_6, W
;math.ppas,639 :: 		
$0260	$07FA			ADDWF	STACK_10, F
;math.ppas,640 :: 		
$0261	$0877			MOVF	STACK_7, W
;math.ppas,641 :: 		
$0262	$1803			BTFSC	STATUS, C
;math.ppas,642 :: 		
$0263	$0F77			INCFSZ	STACK_7, W
;math.ppas,644 :: 		
$0264	$07FB			ADDWF	STACK_11, F
;math.ppas,645 :: 		
$0265	$	SOK22L8:
;math.ppas,647 :: 		
$0265	$0DF2			RLF	STACK_2, F
;math.ppas,648 :: 		
$0266	$3007			MOVLW	7
;math.ppas,650 :: 		
$0267	$00FC			MOVWF	STACK_12
;math.ppas,651 :: 		
$0268	$	LOOPS3232B:
;math.ppas,652 :: 		
$0268	$0D72			RLF	STACK_2, W
;math.ppas,653 :: 		
$0269	$0DF8			RLF	STACK_8, F
;math.ppas,654 :: 		
$026A	$0DF9			RLF	STACK_9, F
;math.ppas,655 :: 		
$026B	$0DFA			RLF	STACK_10, F
;math.ppas,656 :: 		
$026C	$0DFB			RLF	STACK_11, F
;math.ppas,657 :: 		
$026D	$0874			MOVF	STACK_4, W
;math.ppas,658 :: 		
$026E	$1C72			BTFSS	STACK_2, 0
;math.ppas,660 :: 		
$026F	$2A7E			GOTO	SADD22LB
;math.ppas,661 :: 		
$0270	$02F8			SUBWF	STACK_8, F
;math.ppas,662 :: 		
$0271	$0875			MOVF	STACK_5, W
;math.ppas,663 :: 		
$0272	$1C03			BTFSS	STATUS, C
;math.ppas,664 :: 		
$0273	$0F75			INCFSZ	STACK_5, W
;math.ppas,665 :: 		
$0274	$02F9			SUBWF	STACK_9, F
;math.ppas,666 :: 		
$0275	$0876			MOVF	STACK_6, W
;math.ppas,667 :: 		
$0276	$1C03			BTFSS	STATUS, C
;math.ppas,668 :: 		
$0277	$0F76			INCFSZ	STACK_6, W
;math.ppas,669 :: 		
$0278	$02FA			SUBWF	STACK_10, F
;math.ppas,670 :: 		
$0279	$0877			MOVF	STACK_7, W
;math.ppas,671 :: 		
$027A	$1C03			BTFSS	STATUS, C
;math.ppas,672 :: 		
$027B	$0F77			INCFSZ	STACK_7, W
;math.ppas,673 :: 		
$027C	$02FB			SUBWF	STACK_11, F
;math.ppas,675 :: 		
$027D	$2A8B			GOTO	SOK22LB
;math.ppas,676 :: 		
$027E	$	SADD22LB:
;math.ppas,677 :: 		
$027E	$07F8			ADDWF	STACK_8, F
;math.ppas,678 :: 		
$027F	$0875			MOVF	STACK_5, W
;math.ppas,679 :: 		
$0280	$1803			BTFSC	STATUS, C
;math.ppas,680 :: 		
$0281	$0F75			INCFSZ	STACK_5, W
;math.ppas,681 :: 		
$0282	$07F9			ADDWF	STACK_9, F
;math.ppas,682 :: 		
$0283	$0876			MOVF	STACK_6, W
;math.ppas,683 :: 		
$0284	$1803			BTFSC	STATUS, C
;math.ppas,684 :: 		
$0285	$0F76			INCFSZ	STACK_6, W
;math.ppas,685 :: 		
$0286	$07FA			ADDWF	STACK_10, F
;math.ppas,686 :: 		
$0287	$0877			MOVF	STACK_7, W
;math.ppas,687 :: 		
$0288	$1803			BTFSC	STATUS, C
;math.ppas,688 :: 		
$0289	$0F77			INCFSZ	STACK_7, W
;math.ppas,690 :: 		
$028A	$07FB			ADDWF	STACK_11, F
;math.ppas,691 :: 		
$028B	$	SOK22LB:
;math.ppas,693 :: 		
$028B	$0DF2			RLF	STACK_2, F
;math.ppas,694 :: 		
$028C	$0BFC			DECFSZ	STACK_12, F
;math.ppas,696 :: 		
$028D	$2A68			GOTO	LOOPS3232B
;math.ppas,697 :: 		
$028E	$0D71			RLF	STACK_1, W
;math.ppas,698 :: 		
$028F	$0DF8			RLF	STACK_8, F
;math.ppas,699 :: 		
$0290	$0DF9			RLF	STACK_9, F
;math.ppas,700 :: 		
$0291	$0DFA			RLF	STACK_10, F
;math.ppas,701 :: 		
$0292	$0DFB			RLF	STACK_11, F
;math.ppas,702 :: 		
$0293	$0874			MOVF	STACK_4, W
;math.ppas,703 :: 		
$0294	$1C72			BTFSS	STACK_2, 0
;math.ppas,705 :: 		
$0295	$2AA4			GOTO	SADD22L16
;math.ppas,706 :: 		
$0296	$02F8			SUBWF	STACK_8, F
;math.ppas,707 :: 		
$0297	$0875			MOVF	STACK_5, W
;math.ppas,708 :: 		
$0298	$1C03			BTFSS	STATUS, C
;math.ppas,709 :: 		
$0299	$0F75			INCFSZ	STACK_5, W
;math.ppas,710 :: 		
$029A	$02F9			SUBWF	STACK_9, F
;math.ppas,711 :: 		
$029B	$0876			MOVF	STACK_6, W
;math.ppas,712 :: 		
$029C	$1C03			BTFSS	STATUS, C
;math.ppas,713 :: 		
$029D	$0F76			INCFSZ	STACK_6, W
;math.ppas,714 :: 		
$029E	$02FA			SUBWF	STACK_10, F
;math.ppas,715 :: 		
$029F	$0877			MOVF	STACK_7, W
;math.ppas,716 :: 		
$02A0	$1C03			BTFSS	STATUS, C
;math.ppas,717 :: 		
$02A1	$0F77			INCFSZ	STACK_7, W
;math.ppas,718 :: 		
$02A2	$02FB			SUBWF	STACK_11, F
;math.ppas,720 :: 		
$02A3	$2AB1			GOTO	SOK22L16
;math.ppas,721 :: 		
$02A4	$	SADD22L16:
;math.ppas,722 :: 		
$02A4	$07F8			ADDWF	STACK_8, F
;math.ppas,723 :: 		
$02A5	$0875			MOVF	STACK_5, W
;math.ppas,724 :: 		
$02A6	$1803			BTFSC	STATUS, C
;math.ppas,725 :: 		
$02A7	$0F75			INCFSZ	STACK_5, W
;math.ppas,726 :: 		
$02A8	$07F9			ADDWF	STACK_9, F
;math.ppas,727 :: 		
$02A9	$0876			MOVF	STACK_6, W
;math.ppas,728 :: 		
$02AA	$1803			BTFSC	STATUS, C
;math.ppas,729 :: 		
$02AB	$0F76			INCFSZ	STACK_6, W
;math.ppas,730 :: 		
$02AC	$07FA			ADDWF	STACK_10, F
;math.ppas,731 :: 		
$02AD	$0877			MOVF	STACK_7, W
;math.ppas,732 :: 		
$02AE	$1803			BTFSC	STATUS, C
;math.ppas,733 :: 		
$02AF	$0F77			INCFSZ	STACK_7, W
;math.ppas,735 :: 		
$02B0	$07FB			ADDWF	STACK_11, F
;math.ppas,736 :: 		
$02B1	$	SOK22L16:
;math.ppas,738 :: 		
$02B1	$0DF1			RLF	STACK_1, F
;math.ppas,739 :: 		
$02B2	$3007			MOVLW	7
;math.ppas,741 :: 		
$02B3	$00FC			MOVWF	STACK_12
;math.ppas,742 :: 		
$02B4	$	LOOPS3232C:
;math.ppas,743 :: 		
$02B4	$0D71			RLF	STACK_1, W
;math.ppas,744 :: 		
$02B5	$0DF8			RLF	STACK_8, F
;math.ppas,745 :: 		
$02B6	$0DF9			RLF	STACK_9, F
;math.ppas,746 :: 		
$02B7	$0DFA			RLF	STACK_10, F
;math.ppas,747 :: 		
$02B8	$0DFB			RLF	STACK_11, F
;math.ppas,748 :: 		
$02B9	$0874			MOVF	STACK_4, W
;math.ppas,749 :: 		
$02BA	$1C71			BTFSS	STACK_1, 0
;math.ppas,751 :: 		
$02BB	$2ACA			GOTO	SADD22LC
;math.ppas,752 :: 		
$02BC	$02F8			SUBWF	STACK_8, F
;math.ppas,753 :: 		
$02BD	$0875			MOVF	STACK_5, W
;math.ppas,754 :: 		
$02BE	$1C03			BTFSS	STATUS, C
;math.ppas,755 :: 		
$02BF	$0F75			INCFSZ	STACK_5, W
;math.ppas,756 :: 		
$02C0	$02F9			SUBWF	STACK_9, F
;math.ppas,757 :: 		
$02C1	$0876			MOVF	STACK_6, W
;math.ppas,758 :: 		
$02C2	$1C03			BTFSS	STATUS, C
;math.ppas,759 :: 		
$02C3	$0F76			INCFSZ	STACK_6, W
;math.ppas,760 :: 		
$02C4	$02FA			SUBWF	STACK_10, F
;math.ppas,761 :: 		
$02C5	$0877			MOVF	STACK_7, W
;math.ppas,762 :: 		
$02C6	$1C03			BTFSS	STATUS, C
;math.ppas,763 :: 		
$02C7	$0F77			INCFSZ	STACK_7, W
;math.ppas,764 :: 		
$02C8	$02FB			SUBWF	STACK_11, F
;math.ppas,766 :: 		
$02C9	$2AD7			GOTO	SOK22LC
;math.ppas,767 :: 		
$02CA	$	SADD22LC:
;math.ppas,768 :: 		
$02CA	$07F8			ADDWF	STACK_8, F
;math.ppas,769 :: 		
$02CB	$0875			MOVF	STACK_5, W
;math.ppas,770 :: 		
$02CC	$1803			BTFSC	STATUS, C
;math.ppas,771 :: 		
$02CD	$0F75			INCFSZ	STACK_5, W
;math.ppas,772 :: 		
$02CE	$07F9			ADDWF	STACK_9, F
;math.ppas,773 :: 		
$02CF	$0876			MOVF	STACK_6, W
;math.ppas,774 :: 		
$02D0	$1803			BTFSC	STATUS, C
;math.ppas,775 :: 		
$02D1	$0F76			INCFSZ	STACK_6, W
;math.ppas,776 :: 		
$02D2	$07FA			ADDWF	STACK_10, F
;math.ppas,777 :: 		
$02D3	$0877			MOVF	STACK_7, W
;math.ppas,778 :: 		
$02D4	$1803			BTFSC	STATUS, C
;math.ppas,779 :: 		
$02D5	$0F77			INCFSZ	STACK_7, W
;math.ppas,781 :: 		
$02D6	$07FB			ADDWF	STACK_11, F
;math.ppas,782 :: 		
$02D7	$	SOK22LC:
;math.ppas,784 :: 		
$02D7	$0DF1			RLF	STACK_1, F
;math.ppas,785 :: 		
$02D8	$0BFC			DECFSZ	STACK_12, F
;math.ppas,787 :: 		
$02D9	$2AB4			GOTO	LOOPS3232C
;math.ppas,788 :: 		
$02DA	$0D70			RLF	STACK_0, W
;math.ppas,789 :: 		
$02DB	$0DF8			RLF	STACK_8, F
;math.ppas,790 :: 		
$02DC	$0DF9			RLF	STACK_9, F
;math.ppas,791 :: 		
$02DD	$0DFA			RLF	STACK_10, F
;math.ppas,792 :: 		
$02DE	$0DFB			RLF	STACK_11, F
;math.ppas,793 :: 		
$02DF	$0874			MOVF	STACK_4, W
;math.ppas,794 :: 		
$02E0	$1C71			BTFSS	STACK_1, 0
;math.ppas,796 :: 		
$02E1	$2AF0			GOTO	SADD22L24
;math.ppas,797 :: 		
$02E2	$02F8			SUBWF	STACK_8, F
;math.ppas,798 :: 		
$02E3	$0875			MOVF	STACK_5, W
;math.ppas,799 :: 		
$02E4	$1C03			BTFSS	STATUS, C
;math.ppas,800 :: 		
$02E5	$0F75			INCFSZ	STACK_5, W
;math.ppas,801 :: 		
$02E6	$02F9			SUBWF	STACK_9, F
;math.ppas,802 :: 		
$02E7	$0876			MOVF	STACK_6, W
;math.ppas,803 :: 		
$02E8	$1C03			BTFSS	STATUS, C
;math.ppas,804 :: 		
$02E9	$0F76			INCFSZ	STACK_6, W
;math.ppas,805 :: 		
$02EA	$02FA			SUBWF	STACK_10, F
;math.ppas,806 :: 		
$02EB	$0877			MOVF	STACK_7, W
;math.ppas,807 :: 		
$02EC	$1C03			BTFSS	STATUS, C
;math.ppas,808 :: 		
$02ED	$0F77			INCFSZ	STACK_7, W
;math.ppas,809 :: 		
$02EE	$02FB			SUBWF	STACK_11, F
;math.ppas,811 :: 		
$02EF	$2AFD			GOTO	SOK22L24
;math.ppas,812 :: 		
$02F0	$	SADD22L24:
;math.ppas,813 :: 		
$02F0	$07F8			ADDWF	STACK_8, F
;math.ppas,814 :: 		
$02F1	$0875			MOVF	STACK_5, W
;math.ppas,815 :: 		
$02F2	$1803			BTFSC	STATUS, C
;math.ppas,816 :: 		
$02F3	$0F75			INCFSZ	STACK_5, W
;math.ppas,817 :: 		
$02F4	$07F9			ADDWF	STACK_9, F
;math.ppas,818 :: 		
$02F5	$0876			MOVF	STACK_6, W
;math.ppas,819 :: 		
$02F6	$1803			BTFSC	STATUS, C
;math.ppas,820 :: 		
$02F7	$0F76			INCFSZ	STACK_6, W
;math.ppas,821 :: 		
$02F8	$07FA			ADDWF	STACK_10, F
;math.ppas,822 :: 		
$02F9	$0877			MOVF	STACK_7, W
;math.ppas,823 :: 		
$02FA	$1803			BTFSC	STATUS, C
;math.ppas,824 :: 		
$02FB	$0F77			INCFSZ	STACK_7, W
;math.ppas,826 :: 		
$02FC	$07FB			ADDWF	STACK_11, F
;math.ppas,827 :: 		
$02FD	$	SOK22L24:
;math.ppas,829 :: 		
$02FD	$0DF0			RLF	STACK_0, F
;math.ppas,830 :: 		
$02FE	$3007			MOVLW	7
;math.ppas,832 :: 		
$02FF	$00FC			MOVWF	STACK_12
;math.ppas,833 :: 		
$0300	$	LOOPS3232D:
;math.ppas,834 :: 		
$0300	$0D70			RLF	STACK_0, W
;math.ppas,835 :: 		
$0301	$0DF8			RLF	STACK_8, F
;math.ppas,836 :: 		
$0302	$0DF9			RLF	STACK_9, F
;math.ppas,837 :: 		
$0303	$0DFA			RLF	STACK_10, F
;math.ppas,838 :: 		
$0304	$0DFB			RLF	STACK_11, F
;math.ppas,839 :: 		
$0305	$0874			MOVF	STACK_4, W
;math.ppas,840 :: 		
$0306	$1C70			BTFSS	STACK_0, 0
;math.ppas,842 :: 		
$0307	$2B16			GOTO	SADD22LD
;math.ppas,843 :: 		
$0308	$02F8			SUBWF	STACK_8, F
;math.ppas,844 :: 		
$0309	$0875			MOVF	STACK_5, W
;math.ppas,845 :: 		
$030A	$1C03			BTFSS	STATUS, C
;math.ppas,846 :: 		
$030B	$0F75			INCFSZ	STACK_5, W
;math.ppas,847 :: 		
$030C	$02F9			SUBWF	STACK_9, F
;math.ppas,848 :: 		
$030D	$0876			MOVF	STACK_6, W
;math.ppas,849 :: 		
$030E	$1C03			BTFSS	STATUS, C
;math.ppas,850 :: 		
$030F	$0F76			INCFSZ	STACK_6, W
;math.ppas,851 :: 		
$0310	$02FA			SUBWF	STACK_10, F
;math.ppas,852 :: 		
$0311	$0877			MOVF	STACK_7, W
;math.ppas,853 :: 		
$0312	$1C03			BTFSS	STATUS, C
;math.ppas,854 :: 		
$0313	$0F77			INCFSZ	STACK_7, W
;math.ppas,855 :: 		
$0314	$02FB			SUBWF	STACK_11, F
;math.ppas,857 :: 		
$0315	$2B23			GOTO	SOK22LD
;math.ppas,858 :: 		
$0316	$	SADD22LD:
;math.ppas,859 :: 		
$0316	$07F8			ADDWF	STACK_8, F
;math.ppas,860 :: 		
$0317	$0875			MOVF	STACK_5, W
;math.ppas,861 :: 		
$0318	$1803			BTFSC	STATUS, C
;math.ppas,862 :: 		
$0319	$0F75			INCFSZ	STACK_5, W
;math.ppas,863 :: 		
$031A	$07F9			ADDWF	STACK_9, F
;math.ppas,864 :: 		
$031B	$0876			MOVF	STACK_6, W
;math.ppas,865 :: 		
$031C	$1803			BTFSC	STATUS, C
;math.ppas,866 :: 		
$031D	$0F76			INCFSZ	STACK_6, W
;math.ppas,867 :: 		
$031E	$07FA			ADDWF	STACK_10, F
;math.ppas,868 :: 		
$031F	$0877			MOVF	STACK_7, W
;math.ppas,870 :: 		
$0320	$1803			BTFSC	STATUS, C
;math.ppas,871 :: 		
$0321	$0F77			INCFSZ	STACK_7, W
;math.ppas,873 :: 		
$0322	$07FB			ADDWF	STACK_11, F
;math.ppas,874 :: 		
$0323	$	SOK22LD:
;math.ppas,876 :: 		
$0323	$0DF0			RLF	STACK_0, F
;math.ppas,877 :: 		
$0324	$0BFC			DECFSZ	STACK_12, F
;math.ppas,879 :: 		
$0325	$2B00			GOTO	LOOPS3232D
;math.ppas,880 :: 		
$0326	$1870			BTFSC	STACK_0, 0
;math.ppas,881 :: 		
$0327	$2B36			GOTO	SOK22L
;math.ppas,882 :: 		
$0328	$0874			MOVF	STACK_4, W
;math.ppas,883 :: 		
$0329	$07F8			ADDWF	STACK_8, F
;math.ppas,884 :: 		
$032A	$0875			MOVF	STACK_5, W
;math.ppas,885 :: 		
$032B	$1803			BTFSC	STATUS, C
;math.ppas,886 :: 		
$032C	$0F75			INCFSZ	STACK_5, W
;math.ppas,887 :: 		
$032D	$07F9			ADDWF	STACK_9, F
;math.ppas,888 :: 		
$032E	$0876			MOVF	STACK_6, W
;math.ppas,889 :: 		
$032F	$1803			BTFSC	STATUS, C
;math.ppas,890 :: 		
$0330	$0F76			INCFSZ	STACK_6, W
;math.ppas,891 :: 		
$0331	$07FA			ADDWF	STACK_10, F
;math.ppas,892 :: 		
$0332	$0877			MOVF	STACK_7, W
;math.ppas,893 :: 		
$0333	$1803			BTFSC	STATUS, C
;math.ppas,894 :: 		
$0334	$0F77			INCFSZ	STACK_7, W
;math.ppas,895 :: 		
$0335	$07FB			ADDWF	STACK_11, F
;math.ppas,896 :: 		
$0336	$	SOK22L:
;math.ppas,897 :: 		
$0336	$	math_L_9:
;math.ppas,898 :: 		
$0336	$0008			RETURN
$065D	$	_comfrem:
$065D	$1303			BCF	STATUS, RP1
$065E	$1283			BCF	STATUS, RP0
;math.ppas,901 :: 		
;math.ppas,903 :: 		
$065F	$09FB			COMF	STACK_11, F
;math.ppas,904 :: 		
$0660	$09FA			COMF	STACK_10, F
;math.ppas,905 :: 		
$0661	$09F9			COMF	STACK_9, F
;math.ppas,906 :: 		
$0662	$09F8			COMF	STACK_8, F
;math.ppas,907 :: 		
$0663	$0AF8			INCF	STACK_8, F
;math.ppas,908 :: 		
$0664	$1903			BTFSC	STATUS, Z
;math.ppas,909 :: 		
$0665	$0AF9			INCF	STACK_9, F
;math.ppas,910 :: 		
$0666	$1903			BTFSC	STATUS, Z
;math.ppas,911 :: 		
$0667	$0AFA			INCF	STACK_10, F
;math.ppas,912 :: 		
$0668	$1903			BTFSC	STATUS, Z
;math.ppas,913 :: 		
$0669	$0AFB			INCF	STACK_11, F
;math.ppas,914 :: 		
$066A	$	math_L_10:
;math.ppas,915 :: 		
$066A	$0008			RETURN
$066B	$	_usart_data_ready:
;USART_b75.ppas,48 :: 		
;USART_b75.ppas,50 :: 		
$066B	$1303			BCF	STATUS, RP1
$066C	$1283			BCF	STATUS, RP0
$066D	$080C			MOVF	PIR1, 0
$066E	$00F1			MOVWF	STACK_1
$066F	$3000			MOVLW	0
$0670	$1AF1			BTFSC	STACK_1, 5
$0671	$3001			MOVLW	1
$0672	$00F1			MOVWF	STACK_1
$0673	$0871			MOVF	STACK_1, 0
$0674	$00C7			MOVWF	_usart_data_ready_local_result
$0675	$	USART_b75_L_18:
;USART_b75.ppas,51 :: 		
$0675	$0847			MOVF	_usart_data_ready_local_result, 0
$0676	$00F0			MOVWF	STACK_0
$0677	$0008			RETURN
$064A	$	_usart_read:
;USART_b75.ppas,54 :: 		
;USART_b75.ppas,55 :: 		
$064A	$1303			BCF	STATUS, RP1
$064B	$1283			BCF	STATUS, RP0
$064C	$081A			MOVF	RCREG, 0
$064D	$00C7			MOVWF	_usart_read_local_result
;USART_b75.ppas,61 :: 		
$064E	$0818			MOVF	RCSTA, 0
$064F	$00F1			MOVWF	STACK_1
$0650	$3000			MOVLW	0
$0651	$18F1			BTFSC	STACK_1, 1
$0652	$3001			MOVLW	1
$0653	$00F1			MOVWF	STACK_1
$0654	$0871			MOVF	STACK_1, 0
$0655	$3A01			XORLW	1
$0656	$1D03			BTFSS	STATUS, Z
$0657	$2E5A			GOTO	USART_b75_L_21
$0658	$	USART_b75_L_20:
;USART_b75.ppas,63 :: 		
$0658	$1218			BCF	RCSTA, 4
$0659	$	USART_b75_L_24:
;USART_b75.ppas,64 :: 		
$0659	$	USART_b75_L_25:
$0659	$1618			BSF	RCSTA, 4
$065A	$	USART_b75_L_26:
;USART_b75.ppas,65 :: 		
$065A	$	USART_b75_L_21:
$065A	$	USART_b75_L_22:
$065A	$	USART_b75_L_19:
;USART_b75.ppas,66 :: 		
$065A	$0847			MOVF	_usart_read_local_result, 0
$065B	$00F0			MOVWF	STACK_0
$065C	$0008			RETURN
$0579	$	_mul_32x32_s:
$0579	$1303			BCF	STATUS, RP1
$057A	$1283			BCF	STATUS, RP0
;math.ppas,1675 :: 		
;math.ppas,1680 :: 		
$057B	$01FD			CLRF	STACK_13
;math.ppas,1683 :: 		
$057C	$	_IF_FIRST:
;math.ppas,1684 :: 		
$057C	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1686 :: 		
$057D	$2D8B			GOTO	_IF_SECOND
;math.ppas,1691 :: 		
$057E	$	_INVERCE_FIRST:
;math.ppas,1692 :: 		
$057E	$09F0			COMF	STACK_0, F
;math.ppas,1693 :: 		
$057F	$09F1			COMF	STACK_1, F
;math.ppas,1694 :: 		
$0580	$09F2			COMF	STACK_2, F
;math.ppas,1701 :: 		
$0581	$09F3			COMF	STACK_3, F
;math.ppas,1702 :: 		
$0582	$0AF0			INCF	STACK_0, F
;math.ppas,1703 :: 		
$0583	$1903			BTFSC	STATUS, Z
;math.ppas,1704 :: 		
$0584	$0AF1			INCF	STACK_1, F
;math.ppas,1705 :: 		
$0585	$1903			BTFSC	STATUS, Z
;math.ppas,1706 :: 		
$0586	$0AF2			INCF	STACK_2, F
;math.ppas,1707 :: 		
$0587	$1903			BTFSC	STATUS, Z
;math.ppas,1708 :: 		
$0588	$0AF3			INCF	STACK_3, F
;math.ppas,1709 :: 		
$0589	$3081			MOVLW	129
;math.ppas,1711 :: 		
$058A	$07FD			ADDWF	STACK_13, F
;math.ppas,1714 :: 		
$058B	$	_IF_SECOND:
;math.ppas,1715 :: 		
$058B	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1717 :: 		
$058C	$2D99			GOTO	_MULT
;math.ppas,1722 :: 		
$058D	$	_INBERSE_SECOND:
;math.ppas,1723 :: 		
$058D	$09F4			COMF	STACK_4, F
;math.ppas,1724 :: 		
$058E	$09F5			COMF	STACK_5, F
;math.ppas,1725 :: 		
$058F	$09F6			COMF	STACK_6, F
;math.ppas,1732 :: 		
$0590	$09F7			COMF	STACK_7, F
;math.ppas,1733 :: 		
$0591	$0AF4			INCF	STACK_4, F
;math.ppas,1734 :: 		
$0592	$1903			BTFSC	STATUS, Z
;math.ppas,1735 :: 		
$0593	$0AF5			INCF	STACK_5, F
;math.ppas,1736 :: 		
$0594	$1903			BTFSC	STATUS, Z
;math.ppas,1737 :: 		
$0595	$0AF6			INCF	STACK_6, F
;math.ppas,1738 :: 		
$0596	$1903			BTFSC	STATUS, Z
;math.ppas,1739 :: 		
$0597	$0AF7			INCF	STACK_7, F
;math.ppas,1741 :: 		
$0598	$0AFD			INCF	STACK_13, F
;math.ppas,1742 :: 		
$0599	$	_MULT:
;math.ppas,1744 :: 		
$0599	$25B4			CALL	_mul_32x32_u
;math.ppas,1748 :: 		
$059A	$1C7D			BTFSS	STACK_13, 0
;math.ppas,1754 :: 		
$059B	$2DB3			GOTO	_EXIT
;math.ppas,1755 :: 		
$059C	$09F0			COMF	STACK_0, F
;math.ppas,1756 :: 		
$059D	$09F1			COMF	STACK_1, F
;math.ppas,1757 :: 		
$059E	$09F2			COMF	STACK_2, F
;math.ppas,1763 :: 		
$059F	$09F3			COMF	STACK_3, F
;math.ppas,1764 :: 		
$05A0	$09F8			COMF	STACK_8, F
;math.ppas,1765 :: 		
$05A1	$09F9			COMF	STACK_9, F
;math.ppas,1766 :: 		
$05A2	$09FA			COMF	STACK_10, F
;math.ppas,1776 :: 		
$05A3	$09FB			COMF	STACK_11, F
;math.ppas,1777 :: 		
$05A4	$0AF0			INCF	STACK_0, F
;math.ppas,1778 :: 		
$05A5	$1903			BTFSC	STATUS, Z
;math.ppas,1779 :: 		
$05A6	$0AF1			INCF	STACK_1, F
;math.ppas,1780 :: 		
$05A7	$1903			BTFSC	STATUS, Z
;math.ppas,1781 :: 		
$05A8	$0AF2			INCF	STACK_2, F
;math.ppas,1782 :: 		
$05A9	$1903			BTFSC	STATUS, Z
;math.ppas,1783 :: 		
$05AA	$0AF3			INCF	STACK_3, F
;math.ppas,1784 :: 		
$05AB	$1903			BTFSC	STATUS, Z
;math.ppas,1785 :: 		
$05AC	$0AF8			INCF	STACK_8, F
;math.ppas,1786 :: 		
$05AD	$1903			BTFSC	STATUS, Z
;math.ppas,1787 :: 		
$05AE	$0AF9			INCF	STACK_9, F
;math.ppas,1788 :: 		
$05AF	$1903			BTFSC	STATUS, Z
;math.ppas,1789 :: 		
$05B0	$0AFA			INCF	STACK_10, F
;math.ppas,1790 :: 		
$05B1	$1903			BTFSC	STATUS, Z
;math.ppas,1791 :: 		
$05B2	$0AFB			INCF	STACK_11, F
;math.ppas,1792 :: 		
$05B3	$	_EXIT:
;math.ppas,1793 :: 		
$05B3	$	math_L_14:
;math.ppas,1794 :: 		
$05B3	$0008			RETURN
$0618	$	_div_16x16_u:
$0618	$1303			BCF	STATUS, RP1
$0619	$1283			BCF	STATUS, RP0
;math.ppas,108 :: 		
;math.ppas,110 :: 		
$061A	$01F8			CLRF	STACK_8
;math.ppas,111 :: 		
$061B	$01F9			CLRF	STACK_9
;math.ppas,112 :: 		
$061C	$3010			MOVLW	16
;math.ppas,113 :: 		
$061D	$00FC			MOVWF	STACK_12
;math.ppas,114 :: 		
$061E	$0D71			RLF	STACK_1, W
;math.ppas,115 :: 		
$061F	$0DF8			RLF	STACK_8, F
;math.ppas,116 :: 		
$0620	$0DF9			RLF	STACK_9, F
;math.ppas,117 :: 		
$0621	$0874			MOVF	STACK_4, W
;math.ppas,118 :: 		
$0622	$02F8			SUBWF	STACK_8, F
;math.ppas,119 :: 		
$0623	$0875			MOVF	STACK_5, W
;math.ppas,120 :: 		
$0624	$1C03			BTFSS	STATUS, C
;math.ppas,121 :: 		
$0625	$0F75			INCFSZ	STACK_5, W
;math.ppas,122 :: 		
$0626	$02F9			SUBWF	STACK_9, F
;math.ppas,123 :: 		
$0627	$1803			BTFSC	STATUS, C
;math.ppas,124 :: 		
$0628	$2E30			GOTO	$+8
;math.ppas,125 :: 		
$0629	$0874			MOVF	STACK_4, W
;math.ppas,126 :: 		
$062A	$07F8			ADDWF	STACK_8, F
;math.ppas,127 :: 		
$062B	$0875			MOVF	STACK_5, W
;math.ppas,128 :: 		
$062C	$1803			BTFSC	STATUS, C
;math.ppas,129 :: 		
$062D	$0F75			INCFSZ	STACK_5, W
;math.ppas,130 :: 		
$062E	$07F9			ADDWF	STACK_9, F
;math.ppas,131 :: 		
$062F	$1003			BCF	STATUS, C
;math.ppas,132 :: 		
$0630	$0DF0			RLF	STACK_0, F
;math.ppas,133 :: 		
$0631	$0DF1			RLF	STACK_1, F
;math.ppas,134 :: 		
$0632	$0BFC			DECFSZ	STACK_12, F
;math.ppas,135 :: 		
$0633	$2E1E			GOTO	$-21
;math.ppas,136 :: 		
$0634	$	math_L_3:
;math.ppas,137 :: 		
$0634	$0008			RETURN
$03F9	$	_div_32x32_s:
$03F9	$1303			BCF	STATUS, RP1
$03FA	$1283			BCF	STATUS, RP0
;math.ppas,925 :: 		
;math.ppas,928 :: 		
$03FB	$	FXD3232S:
;math.ppas,929 :: 		
$03FB	$01FC			CLRF	STACK_12
;math.ppas,930 :: 		
$03FC	$1BF7			BTFSC	STACK_7, 7
;math.ppas,932 :: 		
$03FD	$0AFC			INCF	STACK_12, F
;math.ppas,933 :: 		
$03FE	$01FD			CLRF	STACK_13
;math.ppas,934 :: 		
$03FF	$01FB			CLRF	STACK_11
;math.ppas,935 :: 		
$0400	$01FA			CLRF	STACK_10
;math.ppas,936 :: 		
$0401	$01F9			CLRF	STACK_9
;math.ppas,937 :: 		
$0402	$01F8			CLRF	STACK_8
;math.ppas,938 :: 		
$0403	$0873			MOVF	STACK_3, W
;math.ppas,939 :: 		
$0404	$0472			IORWF	STACK_2, W
;math.ppas,940 :: 		
$0405	$0471			IORWF	STACK_1, W
;math.ppas,941 :: 		
$0406	$0470			IORWF	STACK_0, W
;math.ppas,942 :: 		
$0407	$1903			BTFSC	STATUS, Z
;math.ppas,943 :: 		
$0408	$2C8D			GOTO	END_ALL
;math.ppas,944 :: 		
$0409	$0873			MOVF	STACK_3, W
;math.ppas,945 :: 		
$040A	$0677			XORWF	STACK_7, W
;math.ppas,946 :: 		
$040B	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,947 :: 		
$040C	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,951 :: 		
$040D	$09FD			COMF	STACK_13, F
;math.ppas,952 :: 		
$040E	$1FF7			BTFSS	STACK_7, 7
;math.ppas,954 :: 		
$040F	$2C1B			GOTO	CA3232S
;math.ppas,955 :: 		
$0410	$09F4			COMF	STACK_4, F
;math.ppas,956 :: 		
$0411	$09F5			COMF	STACK_5, F
;math.ppas,957 :: 		
$0412	$09F6			COMF	STACK_6, F
;math.ppas,958 :: 		
$0413	$09F7			COMF	STACK_7, F
;math.ppas,959 :: 		
$0414	$0AF4			INCF	STACK_4, F
;math.ppas,960 :: 		
$0415	$1903			BTFSC	STATUS, Z
;math.ppas,961 :: 		
$0416	$0AF5			INCF	STACK_5, F
;math.ppas,962 :: 		
$0417	$1903			BTFSC	STATUS, Z
;math.ppas,963 :: 		
$0418	$0AF6			INCF	STACK_6, F
;math.ppas,964 :: 		
$0419	$1903			BTFSC	STATUS, Z
;math.ppas,966 :: 		
$041A	$0AF7			INCF	STACK_7, F
;math.ppas,967 :: 		
$041B	$	CA3232S:
;math.ppas,968 :: 		
$041B	$1FF3			BTFSS	STACK_3, 7
;math.ppas,970 :: 		
$041C	$2C28			GOTO	C3232SX
;math.ppas,971 :: 		
$041D	$09F0			COMF	STACK_0, F
;math.ppas,972 :: 		
$041E	$09F1			COMF	STACK_1, F
;math.ppas,973 :: 		
$041F	$09F2			COMF	STACK_2, F
;math.ppas,974 :: 		
$0420	$09F3			COMF	STACK_3, F
;math.ppas,975 :: 		
$0421	$0AF0			INCF	STACK_0, F
;math.ppas,976 :: 		
$0422	$1903			BTFSC	STATUS, Z
;math.ppas,977 :: 		
$0423	$0AF1			INCF	STACK_1, F
;math.ppas,978 :: 		
$0424	$1903			BTFSC	STATUS, Z
;math.ppas,979 :: 		
$0425	$0AF2			INCF	STACK_2, F
;math.ppas,980 :: 		
$0426	$1903			BTFSC	STATUS, Z
;math.ppas,982 :: 		
$0427	$0AF3			INCF	STACK_3, F
;math.ppas,983 :: 		
$0428	$	C3232SX:
;math.ppas,984 :: 		
$0428	$0873			MOVF	STACK_3, W
;math.ppas,985 :: 		
$0429	$0477			IORWF	STACK_7, W
;math.ppas,986 :: 		
$042A	$00A0			MOVWF	MATH___MATH_TEMPB
;math.ppas,987 :: 		
$042B	$1BA0			BTFSC	MATH___MATH_TEMPB, 7
;math.ppas,988 :: 		
$042C	$2C49			GOTO	C3232SX1
;math.ppas,989 :: 		
$042D	$	C3232S:
;math.ppas,992 :: 		
$042D	$2209			CALL	_sdiv3232l
;math.ppas,995 :: 		
$042E	$	C3232S2:
;math.ppas,996 :: 		
$042E	$1BFC			BTFSC	STACK_12, 7
;math.ppas,997 :: 		
$042F	$2C66			GOTO	C3232SX4
;math.ppas,998 :: 		
$0430	$	C3232SOK:
;math.ppas,999 :: 		
$0430	$1FFD			BTFSS	STACK_13, 7
;math.ppas,1000 :: 		
$0431	$2C8D			GOTO	END_ALL
;math.ppas,1001 :: 		
$0432	$09F0			COMF	STACK_0, F
;math.ppas,1002 :: 		
$0433	$09F1			COMF	STACK_1, F
;math.ppas,1003 :: 		
$0434	$09F2			COMF	STACK_2, F
;math.ppas,1004 :: 		
$0435	$09F3			COMF	STACK_3, F
;math.ppas,1005 :: 		
$0436	$0AF0			INCF	STACK_0, F
;math.ppas,1006 :: 		
$0437	$1903			BTFSC	STATUS, Z
;math.ppas,1007 :: 		
$0438	$0AF1			INCF	STACK_1, F
;math.ppas,1008 :: 		
$0439	$1903			BTFSC	STATUS, Z
;math.ppas,1009 :: 		
$043A	$0AF2			INCF	STACK_2, F
;math.ppas,1010 :: 		
$043B	$1903			BTFSC	STATUS, Z
;math.ppas,1012 :: 		
$043C	$0AF3			INCF	STACK_3, F
;math.ppas,1013 :: 		
$043D	$09F8			COMF	STACK_8, F
;math.ppas,1014 :: 		
$043E	$09F9			COMF	STACK_9, F
;math.ppas,1015 :: 		
$043F	$09FA			COMF	STACK_10, F
;math.ppas,1016 :: 		
$0440	$09FB			COMF	STACK_11, F
;math.ppas,1017 :: 		
$0441	$0AF8			INCF	STACK_8, F
;math.ppas,1018 :: 		
$0442	$1903			BTFSC	STATUS, Z
;math.ppas,1019 :: 		
$0443	$0AF9			INCF	STACK_9, F
;math.ppas,1020 :: 		
$0444	$1903			BTFSC	STATUS, Z
;math.ppas,1021 :: 		
$0445	$0AFA			INCF	STACK_10, F
;math.ppas,1022 :: 		
$0446	$1903			BTFSC	STATUS, Z
;math.ppas,1024 :: 		
$0447	$0AFB			INCF	STACK_11, F
;math.ppas,1025 :: 		
$0448	$2C8D			GOTO	END_ALL
;math.ppas,1026 :: 		
$0449	$	C3232SX1:
;math.ppas,1027 :: 		
$0449	$1FF7			BTFSS	STACK_7, 7
;math.ppas,1028 :: 		
$044A	$2C60			GOTO	C3232SX3
;math.ppas,1029 :: 		
$044B	$1BF3			BTFSC	STACK_3, 7
;math.ppas,1030 :: 		
$044C	$2C5A			GOTO	C3232SX2
;math.ppas,1031 :: 		
$044D	$0873			MOVF	STACK_3, W
;math.ppas,1032 :: 		
$044E	$00FB			MOVWF	STACK_11
;math.ppas,1033 :: 		
$044F	$0872			MOVF	STACK_2, W
;math.ppas,1034 :: 		
$0450	$00FA			MOVWF	STACK_10
;math.ppas,1035 :: 		
$0451	$0871			MOVF	STACK_1, W
;math.ppas,1036 :: 		
$0452	$00F9			MOVWF	STACK_9
;math.ppas,1037 :: 		
$0453	$0870			MOVF	STACK_0, W
;math.ppas,1038 :: 		
$0454	$00F8			MOVWF	STACK_8
;math.ppas,1039 :: 		
$0455	$01F3			CLRF	STACK_3
;math.ppas,1040 :: 		
$0456	$01F2			CLRF	STACK_2
;math.ppas,1041 :: 		
$0457	$01F1			CLRF	STACK_1
;math.ppas,1042 :: 		
$0458	$01F0			CLRF	STACK_0
;math.ppas,1043 :: 		
$0459	$2C30			GOTO	C3232SOK
;math.ppas,1044 :: 		
$045A	$	C3232SX2:
;math.ppas,1045 :: 		
$045A	$01F3			CLRF	STACK_3
;math.ppas,1046 :: 		
$045B	$01F2			CLRF	STACK_2
;math.ppas,1047 :: 		
$045C	$01F1			CLRF	STACK_1
;math.ppas,1048 :: 		
$045D	$01F0			CLRF	STACK_0
;math.ppas,1049 :: 		
$045E	$0AF0			INCF	STACK_0, F
;math.ppas,1051 :: 		
$045F	$3400			RETLW	0X00
;math.ppas,1052 :: 		
$0460	$	C3232SX3:
;math.ppas,1053 :: 		
$0460	$09F3			COMF	STACK_3, F
;math.ppas,1054 :: 		
$0461	$09F2			COMF	STACK_2, F
;math.ppas,1055 :: 		
$0462	$09F1			COMF	STACK_1, F
;math.ppas,1057 :: 		
$0463	$09F0			COMF	STACK_0, F
;math.ppas,1059 :: 		
$0464	$17FC			BSF	STACK_12, 7
;math.ppas,1060 :: 		
$0465	$2C2D			GOTO	C3232S
;math.ppas,1061 :: 		
$0466	$	C3232SX4:
;math.ppas,1062 :: 		
$0466	$0AF8			INCF	STACK_8, F
;math.ppas,1063 :: 		
$0467	$1903			BTFSC	STATUS, Z
;math.ppas,1064 :: 		
$0468	$0AF9			INCF	STACK_9, F
;math.ppas,1065 :: 		
$0469	$1903			BTFSC	STATUS, Z
;math.ppas,1066 :: 		
$046A	$0AFA			INCF	STACK_10, F
;math.ppas,1067 :: 		
$046B	$1903			BTFSC	STATUS, Z
;math.ppas,1068 :: 		
$046C	$0AFB			INCF	STACK_11, F
;math.ppas,1069 :: 		
$046D	$0874			MOVF	STACK_4, W
;math.ppas,1070 :: 		
$046E	$0278			SUBWF	STACK_8, W
;math.ppas,1071 :: 		
$046F	$1D03			BTFSS	STATUS, Z
;math.ppas,1072 :: 		
$0470	$2C30			GOTO	C3232SOK
;math.ppas,1073 :: 		
$0471	$0875			MOVF	STACK_5, W
;math.ppas,1074 :: 		
$0472	$0279			SUBWF	STACK_9, W
;math.ppas,1075 :: 		
$0473	$1D03			BTFSS	STATUS, Z
;math.ppas,1076 :: 		
$0474	$2C30			GOTO	C3232SOK
;math.ppas,1077 :: 		
$0475	$0876			MOVF	STACK_6, W
;math.ppas,1078 :: 		
$0476	$027A			SUBWF	STACK_10, W
;math.ppas,1079 :: 		
$0477	$1D03			BTFSS	STATUS, Z
;math.ppas,1080 :: 		
$0478	$2C30			GOTO	C3232SOK
;math.ppas,1081 :: 		
$0479	$0877			MOVF	STACK_7, W
;math.ppas,1082 :: 		
$047A	$027B			SUBWF	STACK_11, W
;math.ppas,1083 :: 		
$047B	$1D03			BTFSS	STATUS, Z
;math.ppas,1084 :: 		
$047C	$2C30			GOTO	C3232SOK
;math.ppas,1085 :: 		
$047D	$01FB			CLRF	STACK_11
;math.ppas,1086 :: 		
$047E	$01FA			CLRF	STACK_10
;math.ppas,1087 :: 		
$047F	$01F9			CLRF	STACK_9
;math.ppas,1088 :: 		
$0480	$01F8			CLRF	STACK_8
;math.ppas,1089 :: 		
$0481	$0AF0			INCF	STACK_0, F
;math.ppas,1090 :: 		
$0482	$1903			BTFSC	STATUS, Z
;math.ppas,1091 :: 		
$0483	$0AF1			INCF	STACK_1, F
;math.ppas,1092 :: 		
$0484	$1903			BTFSC	STATUS, Z
;math.ppas,1093 :: 		
$0485	$0AF2			INCF	STACK_2, F
;math.ppas,1094 :: 		
$0486	$1903			BTFSC	STATUS, Z
;math.ppas,1095 :: 		
$0487	$0AF3			INCF	STACK_3, F
;math.ppas,1096 :: 		
$0488	$1FF3			BTFSS	STACK_3, 7
;math.ppas,1097 :: 		
$0489	$2C30			GOTO	C3232SOK
;math.ppas,1098 :: 		
$048A	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1099 :: 		
$048B	$1620			BSF	MATH___MATH_TEMPB, 4
;math.ppas,1100 :: 		
$048C	$34FF			RETLW	0XFF
;math.ppas,1101 :: 		
$048D	$	END_ALL:
;math.ppas,1102 :: 		
$048D	$01A0			CLRF	MATH___MATH_TEMPB
;math.ppas,1103 :: 		
$048E	$1C7C			BTFSS	STACK_12, 0
;math.ppas,1104 :: 		
$048F	$2C91			GOTO	AVOID_COMFREM
;math.ppas,1106 :: 		
$0490	$265D			CALL	_comfrem
;math.ppas,1108 :: 		
$0491	$	AVOID_COMFREM:
;math.ppas,1109 :: 		
$0491	$3F00			ADDLW	0X00
;math.ppas,1110 :: 		
$0492	$	math_L_11:
;math.ppas,1111 :: 		
$0492	$0008			RETURN
$05EB	$	_div_16x16_s_l:
$05EB	$1303			BCF	STATUS, RP1
$05EC	$1283			BCF	STATUS, RP0
;math.ppas,291 :: 		
;math.ppas,293 :: 		
$05ED	$0D71			RLF	STACK_1, W
;math.ppas,294 :: 		
$05EE	$0DF8			RLF	STACK_8, F
;math.ppas,295 :: 		
$05EF	$0DF9			RLF	STACK_9, F
;math.ppas,296 :: 		
$05F0	$0874			MOVF	STACK_4, W
;math.ppas,297 :: 		
$05F1	$02F8			SUBWF	STACK_8, F
;math.ppas,298 :: 		
$05F2	$0875			MOVF	STACK_5, W
;math.ppas,299 :: 		
$05F3	$1C03			BTFSS	STATUS, C
;math.ppas,300 :: 		
$05F4	$0F75			INCFSZ	STACK_5, W
;math.ppas,301 :: 		
$05F5	$02F9			SUBWF	STACK_9, F
;math.ppas,302 :: 		
$05F6	$0DF0			RLF	STACK_0, F
;math.ppas,304 :: 		
$05F7	$0DF1			RLF	STACK_1, F
;math.ppas,305 :: 		
$05F8	$300F			MOVLW	15
;math.ppas,307 :: 		
$05F9	$00FC			MOVWF	STACK_12
;math.ppas,308 :: 		
$05FA	$0D71			RLF	STACK_1, W
;math.ppas,309 :: 		
$05FB	$0DF8			RLF	STACK_8, F
;math.ppas,310 :: 		
$05FC	$0DF9			RLF	STACK_9, F
;math.ppas,312 :: 		
$05FD	$0874			MOVF	STACK_4, W
;math.ppas,313 :: 		
$05FE	$1C70			BTFSS	STACK_0, 0
;math.ppas,314 :: 		
$05FF	$2E06			GOTO	$+7
;math.ppas,315 :: 		
$0600	$02F8			SUBWF	STACK_8, F
;math.ppas,316 :: 		
$0601	$0875			MOVF	STACK_5, W
;math.ppas,317 :: 		
$0602	$1C03			BTFSS	STATUS, C
;math.ppas,318 :: 		
$0603	$0F75			INCFSZ	STACK_5, W
;math.ppas,319 :: 		
$0604	$02F9			SUBWF	STACK_9, F
;math.ppas,321 :: 		
$0605	$2E0B			GOTO	$+6
;math.ppas,322 :: 		
$0606	$07F8			ADDWF	STACK_8, F
;math.ppas,323 :: 		
$0607	$0875			MOVF	STACK_5, W
;math.ppas,324 :: 		
$0608	$1803			BTFSC	STATUS, C
;math.ppas,325 :: 		
$0609	$0F75			INCFSZ	STACK_5, W
;math.ppas,327 :: 		
$060A	$07F9			ADDWF	STACK_9, F
;math.ppas,328 :: 		
$060B	$0DF0			RLF	STACK_0, F
;math.ppas,330 :: 		
$060C	$0DF1			RLF	STACK_1, F
;math.ppas,331 :: 		
$060D	$0BFC			DECFSZ	STACK_12, F
;math.ppas,333 :: 		
$060E	$2DFA			GOTO	$-20
;math.ppas,334 :: 		
$060F	$1870			BTFSC	STACK_0, 0
;math.ppas,335 :: 		
$0610	$2E17			GOTO	$+7
;math.ppas,336 :: 		
$0611	$0874			MOVF	STACK_4, W
;math.ppas,337 :: 		
$0612	$07F8			ADDWF	STACK_8, F
;math.ppas,338 :: 		
$0613	$0875			MOVF	STACK_5, W
;math.ppas,339 :: 		
$0614	$1803			BTFSC	STATUS, C
;math.ppas,340 :: 		
$0615	$0F75			INCFSZ	STACK_5, W
;math.ppas,341 :: 		
$0616	$07F9			ADDWF	STACK_9, F
;math.ppas,342 :: 		
$0617	$	math_L_6:
;math.ppas,343 :: 		
$0617	$0008			RETURN
$04ED	$	_usart_read_text:
;USART_b75.ppas,78 :: 		
;USART_b75.ppas,79 :: 		
$04ED	$1303			BCF	STATUS, RP1
$04EE	$1283			BCF	STATUS, RP0
$04EF	$01BC			CLRF	_usart_read_text_local_i, 1
;USART_b75.ppas,80 :: 		
$04F0	$01BD			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,81 :: 		
$04F1	$01C0			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,82 :: 		
$04F2	$083B			MOVF	FARG_Usart_Read_Text+1, 0
$04F3	$0084			MOVWF	FSR
$04F4	$0800			MOVF	INDF, 0
$04F5	$00BF			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,83 :: 		
$04F6	$	USART_b75_L_29:
;USART_b75.ppas,85 :: 		
$04F6	$266B			CALL	_usart_data_ready
$04F7	$0870			MOVF	STACK_0, 0
$04F8	$3A00			XORLW	0
$04F9	$1903			BTFSC	STATUS, Z
$04FA	$2D26			GOTO	USART_b75_L_34
$04FB	$	USART_b75_L_33:
;USART_b75.ppas,87 :: 		
$04FB	$264A			CALL	_usart_read
$04FC	$0870			MOVF	STACK_0, 0
$04FD	$00BE			MOVWF	_usart_read_text_local_data
;USART_b75.ppas,88 :: 		
$04FE	$083C			MOVF	_usart_read_text_local_i, 0
$04FF	$073A			ADDWF	FARG_Usart_Read_Text, 0
$0500	$00F1			MOVWF	STACK_1
$0501	$0871			MOVF	STACK_1, 0
$0502	$0084			MOVWF	FSR
$0503	$0871			MOVF	STACK_1, 0
$0504	$0084			MOVWF	FSR
$0505	$0870			MOVF	STACK_0, 0
$0506	$0080			MOVWF	INDF
;USART_b75.ppas,89 :: 		
$0507	$083E			MOVF	_usart_read_text_local_data, 0
$0508	$063F			XORWF	_usart_read_text_local_data2, 0
$0509	$1D03			BTFSS	STATUS, Z
$050A	$2D10			GOTO	USART_b75_L_37
$050B	$	USART_b75_L_36:
;USART_b75.ppas,91 :: 		
$050B	$083D			MOVF	_usart_read_text_local_j, 0
$050C	$023C			SUBWF	_usart_read_text_local_i, 0
$050D	$00C0			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,92 :: 		
$050E	$0ABD			INCF	_usart_read_text_local_j, 1
;USART_b75.ppas,93 :: 		
$050F	$2D12			GOTO	USART_b75_L_38
;USART_b75.ppas,94 :: 		
$0510	$	USART_b75_L_37:
;USART_b75.ppas,96 :: 		
$0510	$01BD			CLRF	_usart_read_text_local_j, 1
;USART_b75.ppas,97 :: 		
$0511	$01C0			CLRF	_usart_read_text_local_lasti, 1
;USART_b75.ppas,98 :: 		
$0512	$	USART_b75_L_38:
;USART_b75.ppas,100 :: 		
$0512	$083D			MOVF	_usart_read_text_local_j, 0
$0513	$073B			ADDWF	FARG_Usart_Read_Text+1, 0
$0514	$0084			MOVWF	FSR
$0515	$0800			MOVF	INDF, 0
$0516	$00F1			MOVWF	STACK_1
$0517	$0871			MOVF	STACK_1, 0
$0518	$00BF			MOVWF	_usart_read_text_local_data2
;USART_b75.ppas,102 :: 		
$0519	$0871			MOVF	STACK_1, 0
$051A	$3A00			XORLW	0
$051B	$1D03			BTFSS	STATUS, Z
$051C	$2D1E			GOTO	USART_b75_L_40
$051D	$	USART_b75_L_39:
;USART_b75.ppas,103 :: 		
$051D	$2D27			GOTO	USART_b75_L_30
$051E	$	USART_b75_L_40:
$051E	$	USART_b75_L_41:
;USART_b75.ppas,105 :: 		
$051E	$0ABC			INCF	_usart_read_text_local_i, 1
;USART_b75.ppas,106 :: 		
$051F	$083C			MOVF	_usart_read_text_local_i, 0
$0520	$3C14			SUBLW	20
$0521	$1803			BTFSC	STATUS, C
$0522	$2D26			GOTO	USART_b75_L_43
$0523	$	USART_b75_L_42:
;USART_b75.ppas,108 :: 		
$0523	$3013			MOVLW	19
$0524	$00C0			MOVWF	_usart_read_text_local_lasti
;USART_b75.ppas,109 :: 		
$0525	$2D27			GOTO	USART_b75_L_30
;USART_b75.ppas,110 :: 		
$0526	$	USART_b75_L_43:
$0526	$	USART_b75_L_44:
;USART_b75.ppas,111 :: 		
$0526	$	USART_b75_L_34:
$0526	$	USART_b75_L_35:
;USART_b75.ppas,112 :: 		
$0526	$2CF6			GOTO	USART_b75_L_29
$0527	$	USART_b75_L_30:
;USART_b75.ppas,113 :: 		
$0527	$0840			MOVF	_usart_read_text_local_lasti, 0
$0528	$073A			ADDWF	FARG_Usart_Read_Text, 0
$0529	$00F0			MOVWF	STACK_0
$052A	$0870			MOVF	STACK_0, 0
$052B	$0084			MOVWF	FSR
$052C	$0870			MOVF	STACK_0, 0
$052D	$0084			MOVWF	FSR
$052E	$0180			CLRF	INDF, 1
$052F	$	USART_b75_L_27:
;USART_b75.ppas,114 :: 		
$052F	$0008			RETURN
$0337	$	_strtoint:
;conv.ppas,343 :: 		
;conv.ppas,345 :: 		
$0337	$1303			BCF	STATUS, RP1
$0338	$1283			BCF	STATUS, RP0
$0339	$01BB			CLRF	_strtoint_local_result
$033A	$01BC			CLRF	_strtoint_local_result+1
;conv.ppas,346 :: 		
$033B	$3010			MOVLW	16
$033C	$00BF			MOVWF	_strtoint_local_ep
$033D	$3027			MOVLW	39
$033E	$00C0			MOVWF	_strtoint_local_ep+1
;conv.ppas,347 :: 		
$033F	$01BD			CLRF	_strtoint_local_i
$0340	$01BE			CLRF	_strtoint_local_i+1
;conv.ppas,348 :: 		
$0341	$01C3			CLRF	_strtoint_local_tmp
$0342	$01C4			CLRF	_strtoint_local_tmp+1
$0343	$01C5			CLRF	_strtoint_local_tmp+2
$0344	$01C6			CLRF	_strtoint_local_tmp+3
;conv.ppas,349 :: 		
$0345	$01C1			CLRF	_strtoint_local_negative
$0346	$01C2			CLRF	_strtoint_local_negative+1
;conv.ppas,353 :: 		
$0347	$	conv_L_172:
$0347	$083D			MOVF	_strtoint_local_i, 0
$0348	$073A			ADDWF	FARG_StrToInt, 0
$0349	$0084			MOVWF	FSR
$034A	$0800			MOVF	INDF, 0
$034B	$00F4			MOVWF	STACK_4
$034C	$0874			MOVF	STACK_4, 0
$034D	$3A00			XORLW	0
$034E	$1903			BTFSC	STATUS, Z
$034F	$2BB3			GOTO	conv_L_173
;conv.ppas,355 :: 		
$0350	$083D			MOVF	_strtoint_local_i, 0
$0351	$073A			ADDWF	FARG_StrToInt, 0
$0352	$0084			MOVWF	FSR
$0353	$0800			MOVF	INDF, 0
$0354	$00F4			MOVWF	STACK_4
$0355	$0874			MOVF	STACK_4, 0
$0356	$3A2D			XORLW	45
$0357	$1D03			BTFSS	STATUS, Z
$0358	$2B60			GOTO	conv_L_177
$0359	$	conv_L_176:
;conv.ppas,357 :: 		
$0359	$30FF			MOVLW	255
$035A	$00C1			MOVWF	_strtoint_local_negative
$035B	$01C2			CLRF	_strtoint_local_negative+1
;conv.ppas,358 :: 		
$035C	$0ABD			INCF	_strtoint_local_i, 1
$035D	$1903			BTFSC	STATUS, Z
$035E	$0ABE			INCF	_strtoint_local_i+1, 1
;conv.ppas,359 :: 		
$035F	$2B47			GOTO	conv_L_172
;conv.ppas,360 :: 		
$0360	$	conv_L_177:
$0360	$	conv_L_178:
;conv.ppas,361 :: 		
$0360	$083D			MOVF	_strtoint_local_i, 0
$0361	$073A			ADDWF	FARG_StrToInt, 0
$0362	$0084			MOVWF	FSR
$0363	$0800			MOVF	INDF, 0
$0364	$00F4			MOVWF	STACK_4
$0365	$0874			MOVF	STACK_4, 0
$0366	$3A20			XORLW	32
$0367	$1903			BTFSC	STATUS, Z
$0368	$2BA3			GOTO	conv_L_180
$0369	$	conv_L_179:
;conv.ppas,362 :: 		
$0369	$083D			MOVF	_strtoint_local_i, 0
$036A	$073A			ADDWF	FARG_StrToInt, 0
$036B	$0084			MOVWF	FSR
$036C	$0800			MOVF	INDF, 0
$036D	$00F0			MOVWF	STACK_0
$036E	$3030			MOVLW	48
$036F	$00F8			MOVWF	STACK_8
$0370	$01F9			CLRF	STACK_8+1
$0371	$01FA			CLRF	STACK_8+2
$0372	$01FB			CLRF	STACK_8+3
$0373	$0870			MOVF	STACK_0, 0
$0374	$00F4			MOVWF	STACK_4
$0375	$01F5			CLRF	STACK_4+1
$0376	$01F6			CLRF	STACK_4+2
$0377	$01F7			CLRF	STACK_4+3
$0378	$0874			MOVF	STACK_4, 0
$0379	$00F0			MOVWF	STACK_0
$037A	$0875			MOVF	STACK_4+1, 0
$037B	$00F1			MOVWF	STACK_0+1
$037C	$0876			MOVF	STACK_4+2, 0
$037D	$00F2			MOVWF	STACK_0+2
$037E	$0877			MOVF	STACK_4+3, 0
$037F	$00F3			MOVWF	STACK_0+3
$0380	$0878			MOVF	STACK_8, 0
$0381	$02F0			SUBWF	STACK_0, 1
$0382	$0879			MOVF	STACK_8+1, 0
$0383	$1C03			BTFSS	STATUS, C
$0384	$0F79			INCFSZ	STACK_8+1, 0
$0385	$02F1			SUBWF	STACK_0+1, 1
$0386	$087A			MOVF	STACK_8+2, 0
$0387	$1C03			BTFSS	STATUS, C
$0388	$0F7A			INCFSZ	STACK_8+2, 0
$0389	$02F2			SUBWF	STACK_0+2, 1
$038A	$087B			MOVF	STACK_8+3, 0
$038B	$1C03			BTFSS	STATUS, C
$038C	$0F7B			INCFSZ	STACK_8+3, 0
$038D	$02F3			SUBWF	STACK_0+3, 1
$038E	$083F			MOVF	_strtoint_local_ep, 0
$038F	$00F4			MOVWF	STACK_4
$0390	$0840			MOVF	_strtoint_local_ep+1, 0
$0391	$00F5			MOVWF	STACK_4+1
$0392	$01F6			CLRF	STACK_4+2
$0393	$01F7			CLRF	STACK_4+3
$0394	$2579			CALL	_mul_32x32_s
$0395	$0870			MOVF	STACK_0, 0
$0396	$07C3			ADDWF	_strtoint_local_tmp, 1
$0397	$0871			MOVF	STACK_0+1, 0
$0398	$1803			BTFSC	STATUS, C
$0399	$0F71			INCFSZ	STACK_0+1, 0
$039A	$07C4			ADDWF	_strtoint_local_tmp+1, 1
$039B	$0872			MOVF	STACK_0+2, 0
$039C	$1803			BTFSC	STATUS, C
$039D	$0F72			INCFSZ	STACK_0+2, 0
$039E	$07C5			ADDWF	_strtoint_local_tmp+2, 1
$039F	$0873			MOVF	STACK_0+3, 0
$03A0	$1803			BTFSC	STATUS, C
$03A1	$0F73			INCFSZ	STACK_0+3, 0
$03A2	$07C6			ADDWF	_strtoint_local_tmp+3, 1
$03A3	$	conv_L_180:
$03A3	$	conv_L_181:
;conv.ppas,363 :: 		
$03A3	$300A			MOVLW	10
$03A4	$00F4			MOVWF	STACK_4
$03A5	$01F5			CLRF	STACK_4+1
$03A6	$083F			MOVF	_strtoint_local_ep, 0
$03A7	$00F0			MOVWF	STACK_0
$03A8	$0840			MOVF	_strtoint_local_ep+1, 0
$03A9	$00F1			MOVWF	STACK_0+1
$03AA	$2618			CALL	_div_16x16_u
$03AB	$0870			MOVF	STACK_0, 0
$03AC	$00BF			MOVWF	_strtoint_local_ep
$03AD	$0871			MOVF	STACK_0+1, 0
$03AE	$00C0			MOVWF	_strtoint_local_ep+1
;conv.ppas,365 :: 		
$03AF	$0ABD			INCF	_strtoint_local_i, 1
$03B0	$1903			BTFSC	STATUS, Z
$03B1	$0ABE			INCF	_strtoint_local_i+1, 1
;conv.ppas,366 :: 		
$03B2	$2B47			GOTO	conv_L_172
$03B3	$	conv_L_173:
;conv.ppas,370 :: 		
$03B3	$0841			MOVF	_strtoint_local_negative, 0
$03B4	$0442			IORWF	_strtoint_local_negative+1, 0
$03B5	$1903			BTFSC	STATUS, Z
$03B6	$2BBB			GOTO	conv_L_183
$03B7	$	conv_L_182:
$03B7	$3006			MOVLW	6
$03B8	$00BF			MOVWF	_strtoint_local_ep
$03B9	$01C0			CLRF	_strtoint_local_ep+1
$03BA	$2BBE			GOTO	conv_L_184
;conv.ppas,371 :: 		
$03BB	$	conv_L_183:
$03BB	$3005			MOVLW	5
$03BC	$00BF			MOVWF	_strtoint_local_ep
$03BD	$01C0			CLRF	_strtoint_local_ep+1
$03BE	$	conv_L_184:
;conv.ppas,373 :: 		
$03BE	$	conv_L_186:
$03BE	$083E			MOVF	_strtoint_local_i+1, 0
$03BF	$0640			XORWF	_strtoint_local_ep+1, 0
$03C0	$1D03			BTFSS	STATUS, Z
$03C1	$2BC4			GOTO	L_StrToInt_20
$03C2	$083F			MOVF	_strtoint_local_ep, 0
$03C3	$063D			XORWF	_strtoint_local_i, 0
$03C4	$	L_StrToInt_20:
$03C4	$1903			BTFSC	STATUS, Z
$03C5	$2BE0			GOTO	conv_L_187
;conv.ppas,375 :: 		
$03C6	$300A			MOVLW	10
$03C7	$00F4			MOVWF	STACK_4
$03C8	$01F5			CLRF	STACK_4+1
$03C9	$01F6			CLRF	STACK_4+2
$03CA	$01F7			CLRF	STACK_4+3
$03CB	$0843			MOVF	_strtoint_local_tmp, 0
$03CC	$00F0			MOVWF	STACK_0
$03CD	$0844			MOVF	_strtoint_local_tmp+1, 0
$03CE	$00F1			MOVWF	STACK_0+1
$03CF	$0845			MOVF	_strtoint_local_tmp+2, 0
$03D0	$00F2			MOVWF	STACK_0+2
$03D1	$0846			MOVF	_strtoint_local_tmp+3, 0
$03D2	$00F3			MOVWF	STACK_0+3
$03D3	$23F9			CALL	_div_32x32_s
$03D4	$0870			MOVF	STACK_0, 0
$03D5	$00C3			MOVWF	_strtoint_local_tmp
$03D6	$0871			MOVF	STACK_0+1, 0
$03D7	$00C4			MOVWF	_strtoint_local_tmp+1
$03D8	$0872			MOVF	STACK_0+2, 0
$03D9	$00C5			MOVWF	_strtoint_local_tmp+2
$03DA	$0873			MOVF	STACK_0+3, 0
$03DB	$00C6			MOVWF	_strtoint_local_tmp+3
;conv.ppas,376 :: 		
$03DC	$0ABD			INCF	_strtoint_local_i, 1
$03DD	$1903			BTFSC	STATUS, Z
$03DE	$0ABE			INCF	_strtoint_local_i+1, 1
;conv.ppas,377 :: 		
$03DF	$2BBE			GOTO	conv_L_186
$03E0	$	conv_L_187:
;conv.ppas,380 :: 		
$03E0	$0843			MOVF	_strtoint_local_tmp, 0
$03E1	$00BB			MOVWF	_strtoint_local_result
$03E2	$0844			MOVF	_strtoint_local_tmp+1, 0
$03E3	$00BC			MOVWF	_strtoint_local_result+1
;conv.ppas,382 :: 		
$03E4	$3000			MOVLW	0
$03E5	$0642			XORWF	_strtoint_local_negative+1, 0
$03E6	$1D03			BTFSS	STATUS, Z
$03E7	$2BEA			GOTO	L_StrToInt_21
$03E8	$30FF			MOVLW	255
$03E9	$0641			XORWF	_strtoint_local_negative, 0
$03EA	$	L_StrToInt_21:
$03EA	$1D03			BTFSS	STATUS, Z
$03EB	$2BF4			GOTO	conv_L_191
$03EC	$	conv_L_190:
;conv.ppas,383 :: 		
$03EC	$083B			MOVF	_strtoint_local_result, 0
$03ED	$3C00			SUBLW	0
$03EE	$00BB			MOVWF	_strtoint_local_result
$03EF	$083C			MOVF	_strtoint_local_result+1, 0
$03F0	$1C03			BTFSS	STATUS, C
$03F1	$3F01			ADDLW	1
$03F2	$01BC			CLRF	_strtoint_local_result+1
$03F3	$02BC			SUBWF	_strtoint_local_result+1, 1
$03F4	$	conv_L_191:
$03F4	$	conv_L_192:
$03F4	$	conv_L_170:
;conv.ppas,384 :: 		
$03F4	$083B			MOVF	_strtoint_local_result, 0
$03F5	$00F0			MOVWF	STACK_0
$03F6	$083C			MOVF	_strtoint_local_result+1, 0
$03F7	$00F1			MOVWF	STACK_0+1
$03F8	$0008			RETURN
$0635	$	_usart_init:
;USART_b75.ppas,22 :: 		
;USART_b75.ppas,24 :: 		
$0635	$	USART_b75_L_1:
$0635	$1303			BCF	STATUS, RP1
$0636	$1683			BSF	STATUS, RP0
$0637	$1698			BSF	TXSTA, 5
$0638	$	USART_b75_L_2:
;USART_b75.ppas,25 :: 		
$0638	$3090			MOVLW	144
$0639	$1283			BCF	STATUS, RP0
$063A	$0098			MOVWF	RCSTA
;USART_b75.ppas,31 :: 		
$063B	$	USART_b75_L_3:
$063B	$1683			BSF	STATUS, RP0
$063C	$1686			BSF	TRISB, 5
$063D	$	USART_b75_L_4:
;USART_b75.ppas,32 :: 		
$063D	$	USART_b75_L_5:
$063D	$1786			BSF	TRISB, 7
$063E	$	USART_b75_L_6:
;USART_b75.ppas,35 :: 		
$063E	$	USART_b75_L_8:
$063E	$1283			BCF	STATUS, RP0
$063F	$080C			MOVF	PIR1, 0
$0640	$00F1			MOVWF	STACK_1
$0641	$3000			MOVLW	0
$0642	$1AF1			BTFSC	STACK_1, 5
$0643	$3001			MOVLW	1
$0644	$00F1			MOVWF	STACK_1
$0645	$0871			MOVF	STACK_1, 0
$0646	$3A01			XORLW	1
$0647	$1903			BTFSC	STATUS, Z
$0648	$2E3E			GOTO	USART_b75_L_8
;USART_b75.ppas,36 :: 		
$0649	$	USART_b75_L_9:
$0649	$	USART_b75_L_0:
;USART_b75.ppas,37 :: 		
$0649	$0008			RETURN
$0493	$	_div_16x16_s:
$0493	$1303			BCF	STATUS, RP1
$0494	$1283			BCF	STATUS, RP0
;math.ppas,346 :: 		
;math.ppas,348 :: 		
$0495	$01FD			CLRF	STACK_13
;math.ppas,349 :: 		
$0496	$01F9			CLRF	STACK_9
;math.ppas,350 :: 		
$0497	$01F8			CLRF	STACK_8
;math.ppas,351 :: 		
$0498	$0871			MOVF	STACK_1, W
;math.ppas,352 :: 		
$0499	$0470			IORWF	STACK_0, W
;math.ppas,353 :: 		
$049A	$1903			BTFSC	STATUS, Z
;math.ppas,355 :: 		
$049B	$3400			RETLW	0
;math.ppas,356 :: 		
$049C	$0871			MOVF	STACK_1, W
;math.ppas,357 :: 		
$049D	$0675			XORWF	STACK_5, W
;math.ppas,358 :: 		
$049E	$00FA			MOVWF	STACK_10
;math.ppas,359 :: 		
$049F	$1BFA			BTFSC	STACK_10, 7
;math.ppas,361 :: 		
$04A0	$09FD			COMF	STACK_13, F
;math.ppas,363 :: 		
$04A1	$01FB			CLRF	STACK_11
;math.ppas,364 :: 		
$04A2	$1FF5			BTFSS	STACK_5, 7
;math.ppas,366 :: 		
$04A3	$2CA9			GOTO	$+6
;math.ppas,367 :: 		
$04A4	$09F4			COMF	STACK_4, F
;math.ppas,368 :: 		
$04A5	$09F5			COMF	STACK_5, F
;math.ppas,369 :: 		
$04A6	$0AF4			INCF	STACK_4, F
;math.ppas,370 :: 		
$04A7	$1903			BTFSC	STATUS, Z
;math.ppas,372 :: 		
$04A8	$0AF5			INCF	STACK_5, F
;math.ppas,373 :: 		
$04A9	$1FF1			BTFSS	STACK_1, 7
;math.ppas,375 :: 		
$04AA	$2CB0			GOTO	$+6
;math.ppas,376 :: 		
$04AB	$09F0			COMF	STACK_0, F
;math.ppas,377 :: 		
$04AC	$09F1			COMF	STACK_1, F
;math.ppas,378 :: 		
$04AD	$0AF0			INCF	STACK_0, F
;math.ppas,379 :: 		
$04AE	$1903			BTFSC	STATUS, Z
;math.ppas,381 :: 		
$04AF	$0AF1			INCF	STACK_1, F
;math.ppas,382 :: 		
$04B0	$0871			MOVF	STACK_1, W
;math.ppas,383 :: 		
$04B1	$0475			IORWF	STACK_5, W
;math.ppas,384 :: 		
$04B2	$00FA			MOVWF	STACK_10
;math.ppas,385 :: 		
$04B3	$1BFA			BTFSC	STACK_10, 7
;math.ppas,386 :: 		
$04B4	$2CC5			GOTO	$+17
;math.ppas,388 :: 		
$04B5	$25EB			CALL	_div_16x16_s_l
;math.ppas,390 :: 		
$04B6	$187B			BTFSC	STACK_11, 0
;math.ppas,392 :: 		
$04B7	$2CD8			GOTO	$+33
;math.ppas,393 :: 		
$04B8	$1FFD			BTFSS	STACK_13, 7
;math.ppas,395 :: 		
$04B9	$3400			RETLW	0
;math.ppas,396 :: 		
$04BA	$09F0			COMF	STACK_0, F
;math.ppas,397 :: 		
$04BB	$09F1			COMF	STACK_1, F
;math.ppas,398 :: 		
$04BC	$0AF0			INCF	STACK_0, F
;math.ppas,399 :: 		
$04BD	$1903			BTFSC	STATUS, Z
;math.ppas,401 :: 		
$04BE	$0AF1			INCF	STACK_1, F
;math.ppas,402 :: 		
$04BF	$09F8			COMF	STACK_8, F
;math.ppas,403 :: 		
$04C0	$09F9			COMF	STACK_9, F
;math.ppas,404 :: 		
$04C1	$0AF8			INCF	STACK_8, F
;math.ppas,405 :: 		
$04C2	$1903			BTFSC	STATUS, Z
;math.ppas,407 :: 		
$04C3	$0AF9			INCF	STACK_9, F
;math.ppas,409 :: 		
$04C4	$3400			RETLW	0
;math.ppas,410 :: 		
$04C5	$1FF5			BTFSS	STACK_5, 7
;math.ppas,411 :: 		
$04C6	$2CD4			GOTO	$+14
;math.ppas,412 :: 		
$04C7	$1BF1			BTFSC	STACK_1, 7
;math.ppas,413 :: 		
$04C8	$2CD0			GOTO	$+8
;math.ppas,414 :: 		
$04C9	$0871			MOVF	STACK_1, W
;math.ppas,415 :: 		
$04CA	$00F9			MOVWF	STACK_9
;math.ppas,416 :: 		
$04CB	$0870			MOVF	STACK_0, W
;math.ppas,417 :: 		
$04CC	$00F8			MOVWF	STACK_8
;math.ppas,418 :: 		
$04CD	$01F1			CLRF	STACK_1
;math.ppas,419 :: 		
$04CE	$01F0			CLRF	STACK_0
;math.ppas,420 :: 		
$04CF	$2CB8			GOTO	$-23
;math.ppas,421 :: 		
$04D0	$01F1			CLRF	STACK_1
;math.ppas,422 :: 		
$04D1	$01F0			CLRF	STACK_0
;math.ppas,423 :: 		
$04D2	$0AF0			INCF	STACK_0, F
;math.ppas,425 :: 		
$04D3	$3400			RETLW	0
;math.ppas,426 :: 		
$04D4	$09F1			COMF	STACK_1, F
;math.ppas,427 :: 		
$04D5	$09F0			COMF	STACK_0, F
;math.ppas,428 :: 		
$04D6	$0AFB			INCF	STACK_11, F
;math.ppas,430 :: 		
$04D7	$2CB5			GOTO	$-34
;math.ppas,431 :: 		
$04D8	$0AF8			INCF	STACK_8, F
;math.ppas,432 :: 		
$04D9	$1903			BTFSC	STATUS, Z
;math.ppas,433 :: 		
$04DA	$0AF9			INCF	STACK_9, F
;math.ppas,434 :: 		
$04DB	$0874			MOVF	STACK_4, W
;math.ppas,435 :: 		
$04DC	$0278			SUBWF	STACK_8, W
;math.ppas,436 :: 		
$04DD	$1D03			BTFSS	STATUS, Z
;math.ppas,437 :: 		
$04DE	$2CB8			GOTO	$-38
;math.ppas,438 :: 		
$04DF	$0875			MOVF	STACK_5, W
;math.ppas,439 :: 		
$04E0	$0279			SUBWF	STACK_9, W
;math.ppas,440 :: 		
$04E1	$1D03			BTFSS	STATUS, Z
;math.ppas,441 :: 		
$04E2	$2CB8			GOTO	$-42
;math.ppas,442 :: 		
$04E3	$01F9			CLRF	STACK_9
;math.ppas,443 :: 		
$04E4	$01F8			CLRF	STACK_8
;math.ppas,444 :: 		
$04E5	$0AF0			INCF	STACK_0, F
;math.ppas,445 :: 		
$04E6	$1903			BTFSC	STATUS, Z
;math.ppas,446 :: 		
$04E7	$0AF1			INCF	STACK_1, F
;math.ppas,447 :: 		
$04E8	$1FF1			BTFSS	STACK_1, 7
;math.ppas,448 :: 		
$04E9	$2CB8			GOTO	$-49
;math.ppas,449 :: 		
$04EA	$0000			NOP
;math.ppas,450 :: 		
$04EB	$34FF			RETLW	255
;math.ppas,451 :: 		
$04EC	$	math_L_7:
;math.ppas,452 :: 		
$04EC	$0008			RETURN
$0530	$	_mul_16x16_s:
$0530	$1303			BCF	STATUS, RP1
$0531	$1283			BCF	STATUS, RP0
;math.ppas,203 :: 		
;math.ppas,205 :: 		
$0532	$01FB			CLRF	STACK_11
;math.ppas,206 :: 		
$0533	$01FA			CLRF	STACK_10
;math.ppas,207 :: 		
$0534	$01F9			CLRF	STACK_9
;math.ppas,208 :: 		
$0535	$3080			MOVLW	128
;math.ppas,210 :: 		
$0536	$00F8			MOVWF	STACK_8
;math.ppas,212 :: 		
$0537	$01FD			CLRF	STACK_13
;math.ppas,213 :: 		
$0538	$1FF1			BTFSS	STACK_1, 7
;math.ppas,214 :: 		
$0539	$2D40			GOTO	$+7
;math.ppas,215 :: 		
$053A	$09F1			COMF	STACK_1, F
;math.ppas,216 :: 		
$053B	$09F0			COMF	STACK_0, F
;math.ppas,217 :: 		
$053C	$0AF0			INCF	STACK_0, F
;math.ppas,218 :: 		
$053D	$1903			BTFSC	STATUS, Z
;math.ppas,219 :: 		
$053E	$0AF1			INCF	STACK_1, F
;math.ppas,221 :: 		
$053F	$0AFD			INCF	STACK_13, F
;math.ppas,222 :: 		
$0540	$1FF5			BTFSS	STACK_5, 7
;math.ppas,223 :: 		
$0541	$2D48			GOTO	$+7
;math.ppas,224 :: 		
$0542	$09F5			COMF	STACK_5, F
;math.ppas,225 :: 		
$0543	$09F4			COMF	STACK_4, F
;math.ppas,226 :: 		
$0544	$0AF4			INCF	STACK_4, F
;math.ppas,227 :: 		
$0545	$1903			BTFSC	STATUS, Z
;math.ppas,228 :: 		
$0546	$0AF5			INCF	STACK_5, F
;math.ppas,230 :: 		
$0547	$0AFD			INCF	STACK_13, F
;math.ppas,231 :: 		
$0548	$0CF1			RRF	STACK_1, F
;math.ppas,233 :: 		
$0549	$0CF0			RRF	STACK_0, F
;math.ppas,234 :: 		
$054A	$1C03			BTFSS	STATUS, C
;math.ppas,235 :: 		
$054B	$2D55			GOTO	$+10
;math.ppas,236 :: 		
$054C	$0874			MOVF	STACK_4, W
;math.ppas,238 :: 		
$054D	$07F9			ADDWF	STACK_9, F
;math.ppas,239 :: 		
$054E	$0875			MOVF	STACK_5, W
;math.ppas,240 :: 		
$054F	$1803			BTFSC	STATUS, C
;math.ppas,241 :: 		
$0550	$0F75			INCFSZ	STACK_5, W
;math.ppas,242 :: 		
$0551	$07FA			ADDWF	STACK_10, F
;math.ppas,243 :: 		
$0552	$1803			BTFSC	STATUS, C
;math.ppas,244 :: 		
$0553	$0AFB			INCF	STACK_11, F
;math.ppas,246 :: 		
$0554	$1003			BCF	STATUS, C
;math.ppas,247 :: 		
$0555	$1FF0			BTFSS	STACK_0, 7
;math.ppas,248 :: 		
$0556	$2D5D			GOTO	$+7
;math.ppas,249 :: 		
$0557	$0874			MOVF	STACK_4, W
;math.ppas,250 :: 		
$0558	$07FA			ADDWF	STACK_10, F
;math.ppas,251 :: 		
$0559	$1803			BTFSC	STATUS, C
;math.ppas,252 :: 		
$055A	$0AFB			INCF	STACK_11, F
;math.ppas,253 :: 		
$055B	$0875			MOVF	STACK_5, W
;math.ppas,255 :: 		
$055C	$07FB			ADDWF	STACK_11, F
;math.ppas,256 :: 		
$055D	$0CFB			RRF	STACK_11, F
;math.ppas,257 :: 		
$055E	$0CFA			RRF	STACK_10, F
;math.ppas,258 :: 		
$055F	$0CF9			RRF	STACK_9, F
;math.ppas,260 :: 		
$0560	$0CF8			RRF	STACK_8, F
;math.ppas,261 :: 		
$0561	$1C03			BTFSS	STATUS, C
;math.ppas,262 :: 		
$0562	$2D48			GOTO	$-26
;math.ppas,263 :: 		
$0563	$1C7D			BTFSS	STACK_13, 0
;math.ppas,265 :: 		
$0564	$2D70			GOTO	$+12
;math.ppas,266 :: 		
$0565	$09FB			COMF	STACK_11, F
;math.ppas,267 :: 		
$0566	$09FA			COMF	STACK_10, F
;math.ppas,268 :: 		
$0567	$09F9			COMF	STACK_9, F
;math.ppas,270 :: 		
$0568	$09F8			COMF	STACK_8, F
;math.ppas,271 :: 		
$0569	$0AF8			INCF	STACK_8, F
;math.ppas,272 :: 		
$056A	$1903			BTFSC	STATUS, Z
;math.ppas,273 :: 		
$056B	$0AF9			INCF	STACK_9, F
;math.ppas,274 :: 		
$056C	$1903			BTFSC	STATUS, Z
;math.ppas,275 :: 		
$056D	$0AFA			INCF	STACK_10, F
;math.ppas,276 :: 		
$056E	$1903			BTFSC	STATUS, Z
;math.ppas,278 :: 		
$056F	$0AFB			INCF	STACK_11, F
;math.ppas,279 :: 		
$0570	$087B			MOVF	STACK_11, W
;math.ppas,280 :: 		
$0571	$00F3			MOVWF	STACK_3
;math.ppas,281 :: 		
$0572	$087A			MOVF	STACK_10, W
;math.ppas,282 :: 		
$0573	$00F2			MOVWF	STACK_2
;math.ppas,283 :: 		
$0574	$0879			MOVF	STACK_9, W
;math.ppas,284 :: 		
$0575	$00F1			MOVWF	STACK_1
;math.ppas,285 :: 		
$0576	$0878			MOVF	STACK_8, W
;math.ppas,286 :: 		
$0577	$00F0			MOVWF	STACK_0
;math.ppas,287 :: 		
$0578	$	math_L_5:
;math.ppas,288 :: 		
$0578	$0008			RETURN
$0004	$	_main:
;Pic2.pbas,10 :: 		main:
$0004	$	_main_main:
;Pic2.pbas,12 :: 		TRISA=%11010000
$0004	$30D0			MOVLW	208
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0085			MOVWF	TRISA
;Pic2.pbas,13 :: 		TRISB=%01101111
$0008	$306F			MOVLW	111
$0009	$0086			MOVWF	TRISB
;Pic2.pbas,14 :: 		TRISC=%00000000
$000A	$0187			CLRF	TRISC, 1
;Pic2.pbas,15 :: 		INTCON=%00000000
$000B	$018B			CLRF	INTCON, 1
;Pic2.pbas,16 :: 		ANSEL=%00000000
$000C	$1703			BSF	STATUS, RP1
$000D	$1283			BCF	STATUS, RP0
$000E	$019E			CLRF	ANSEL, 1
;Pic2.pbas,17 :: 		ANSELH=%00000000
$000F	$019F			CLRF	ANSELH, 1
;Pic2.pbas,20 :: 		portc = 0
$0010	$1303			BCF	STATUS, RP1
$0011	$0187			CLRF	PORTC, 1
;Pic2.pbas,21 :: 		senha = 0
$0012	$01A1			CLRF	_senha
$0013	$01A2			CLRF	_senha+1
;Pic2.pbas,22 :: 		uni = 0
$0014	$01A3			CLRF	_uni
$0015	$01A4			CLRF	_uni+1
;Pic2.pbas,23 :: 		dez = 0
$0016	$01A5			CLRF	_dez
$0017	$01A6			CLRF	_dez+1
;Pic2.pbas,24 :: 		cent = 0
$0018	$01A7			CLRF	_cent
$0019	$01A8			CLRF	_cent+1
;Pic2.pbas,25 :: 		tipo = 0
$001A	$01A9			CLRF	_tipo
$001B	$01AA			CLRF	_tipo+1
;Pic2.pbas,26 :: 		USART_INIT(9600)
$001C	$3019			MOVLW	25
$001D	$1683			BSF	STATUS, RP0
$001E	$0099			MOVWF	SPBRG
$001F	$1518			BSF	TXSTA, BRGH
$0020	$2635			CALL	_usart_init
;Pic2.pbas,28 :: 		executa:
$0021	$	_main_executa:
;Pic2.pbas,31 :: 		Usart_Read_Text(recebe,"/")
$0021	$302B			MOVLW	_recebe
$0022	$00BA			MOVWF	FARG_Usart_Read_Text
$0023	$302F			MOVLW	47
$0024	$00B2			MOVWF	?main_Local_Text+0
$0025	$01B3			CLRF	?main_Local_Text+1
$0026	$3032			MOVLW	?main_Local_Text
$0027	$00BB			MOVWF	FARG_Usart_Read_Text+1
$0028	$24ED			CALL	_usart_read_text
;Pic2.pbas,33 :: 		senha = StrToInt(recebe)
$0029	$302B			MOVLW	_recebe
$002A	$00BA			MOVWF	FARG_StrToInt
$002B	$2337			CALL	_strtoint
$002C	$0870			MOVF	STACK_0, 0
$002D	$00A1			MOVWF	_senha
$002E	$0871			MOVF	STACK_0+1, 0
$002F	$00A2			MOVWF	_senha+1
;Pic2.pbas,34 :: 		tipo = senha div 1000
$0030	$30E8			MOVLW	232
$0031	$00F4			MOVWF	STACK_4
$0032	$3003			MOVLW	3
$0033	$00F5			MOVWF	STACK_4+1
$0034	$2493			CALL	_div_16x16_s
$0035	$0870			MOVF	STACK_0, 0
$0036	$00A9			MOVWF	_tipo
$0037	$0871			MOVF	STACK_0+1, 0
$0038	$00AA			MOVWF	_tipo+1
;Pic2.pbas,35 :: 		if tipo = 1 then
$0039	$3000			MOVLW	0
$003A	$0671			XORWF	STACK_0+1, 0
$003B	$1D03			BTFSS	STATUS, Z
$003C	$283F			GOTO	L_main_0
$003D	$3001			MOVLW	1
$003E	$0670			XORWF	STACK_0, 0
$003F	$	L_main_0:
$003F	$1D03			BTFSS	STATUS, Z
$0040	$2920			GOTO	Pic2_L_2
$0041	$	Pic2_L_1:
;Pic2.pbas,36 :: 		cent = senha div 100 - (tipo * 10)
$0041	$3064			MOVLW	100
$0042	$00F4			MOVWF	STACK_4
$0043	$01F5			CLRF	STACK_4+1
$0044	$0821			MOVF	_senha, 0
$0045	$00F0			MOVWF	STACK_0
$0046	$0822			MOVF	_senha+1, 0
$0047	$00F1			MOVWF	STACK_0+1
$0048	$2493			CALL	_div_16x16_s
$0049	$0870			MOVF	STACK_0, 0
$004A	$00B4			MOVWF	FLOC_main+2
$004B	$0871			MOVF	STACK_0+1, 0
$004C	$00B5			MOVWF	FLOC_main+3
$004D	$0829			MOVF	_tipo, 0
$004E	$00F0			MOVWF	STACK_0
$004F	$082A			MOVF	_tipo+1, 0
$0050	$00F1			MOVWF	STACK_0+1
$0051	$300A			MOVLW	10
$0052	$00F4			MOVWF	STACK_4
$0053	$01F5			CLRF	STACK_4+1
$0054	$2530			CALL	_mul_16x16_s
$0055	$0870			MOVF	STACK_0, 0
$0056	$0234			SUBWF	FLOC_main+2, 0
$0057	$00B8			MOVWF	FLOC_main+6
$0058	$0871			MOVF	STACK_0+1, 0
$0059	$1C03			BTFSS	STATUS, C
$005A	$3F01			ADDLW	1
$005B	$0235			SUBWF	FLOC_main+3, 0
$005C	$00B9			MOVWF	FLOC_main+7
$005D	$0838			MOVF	FLOC_main+6, 0
$005E	$00A7			MOVWF	_cent
$005F	$0839			MOVF	FLOC_main+7, 0
$0060	$00A8			MOVWF	_cent+1
;Pic2.pbas,37 :: 		dez = senha div 10 - (cent * 10) - (tipo * 100)
$0061	$300A			MOVLW	10
$0062	$00F4			MOVWF	STACK_4
$0063	$01F5			CLRF	STACK_4+1
$0064	$0821			MOVF	_senha, 0
$0065	$00F0			MOVWF	STACK_0
$0066	$0822			MOVF	_senha+1, 0
$0067	$00F1			MOVWF	STACK_0+1
$0068	$2493			CALL	_div_16x16_s
$0069	$0870			MOVF	STACK_0, 0
$006A	$00B4			MOVWF	FLOC_main+2
$006B	$0871			MOVF	STACK_0+1, 0
$006C	$00B5			MOVWF	FLOC_main+3
$006D	$0838			MOVF	FLOC_main+6, 0
$006E	$00F0			MOVWF	STACK_0
$006F	$0839			MOVF	FLOC_main+7, 0
$0070	$00F1			MOVWF	STACK_0+1
$0071	$300A			MOVLW	10
$0072	$00F4			MOVWF	STACK_4
$0073	$01F5			CLRF	STACK_4+1
$0074	$2530			CALL	_mul_16x16_s
$0075	$0870			MOVF	STACK_0, 0
$0076	$02B4			SUBWF	FLOC_main+2, 1
$0077	$1C03			BTFSS	STATUS, C
$0078	$03B5			DECF	FLOC_main+3, 1
$0079	$0871			MOVF	STACK_0+1, 0
$007A	$02B5			SUBWF	FLOC_main+3, 1
$007B	$0829			MOVF	_tipo, 0
$007C	$00F0			MOVWF	STACK_0
$007D	$082A			MOVF	_tipo+1, 0
$007E	$00F1			MOVWF	STACK_0+1
$007F	$3064			MOVLW	100
$0080	$00F4			MOVWF	STACK_4
$0081	$01F5			CLRF	STACK_4+1
$0082	$2530			CALL	_mul_16x16_s
$0083	$0870			MOVF	STACK_0, 0
$0084	$0234			SUBWF	FLOC_main+2, 0
$0085	$00B6			MOVWF	FLOC_main+4
$0086	$0871			MOVF	STACK_0+1, 0
$0087	$1C03			BTFSS	STATUS, C
$0088	$3F01			ADDLW	1
$0089	$0235			SUBWF	FLOC_main+3, 0
$008A	$00B7			MOVWF	FLOC_main+5
$008B	$0836			MOVF	FLOC_main+4, 0
$008C	$00A5			MOVWF	_dez
$008D	$0837			MOVF	FLOC_main+5, 0
$008E	$00A6			MOVWF	_dez+1
;Pic2.pbas,38 :: 		uni = senha - (dez * 10) - (cent * 100) - (tipo * 1000)
$008F	$0836			MOVF	FLOC_main+4, 0
$0090	$00F0			MOVWF	STACK_0
$0091	$0837			MOVF	FLOC_main+5, 0
$0092	$00F1			MOVWF	STACK_0+1
$0093	$300A			MOVLW	10
$0094	$00F4			MOVWF	STACK_4
$0095	$01F5			CLRF	STACK_4+1
$0096	$2530			CALL	_mul_16x16_s
$0097	$0870			MOVF	STACK_0, 0
$0098	$0221			SUBWF	_senha, 0
$0099	$00B4			MOVWF	FLOC_main+2
$009A	$0871			MOVF	STACK_0+1, 0
$009B	$1C03			BTFSS	STATUS, C
$009C	$3F01			ADDLW	1
$009D	$0222			SUBWF	_senha+1, 0
$009E	$00B5			MOVWF	FLOC_main+3
$009F	$0838			MOVF	FLOC_main+6, 0
$00A0	$00F0			MOVWF	STACK_0
$00A1	$0839			MOVF	FLOC_main+7, 0
$00A2	$00F1			MOVWF	STACK_0+1
$00A3	$3064			MOVLW	100
$00A4	$00F4			MOVWF	STACK_4
$00A5	$01F5			CLRF	STACK_4+1
$00A6	$2530			CALL	_mul_16x16_s
$00A7	$0870			MOVF	STACK_0, 0
$00A8	$02B4			SUBWF	FLOC_main+2, 1
$00A9	$1C03			BTFSS	STATUS, C
$00AA	$03B5			DECF	FLOC_main+3, 1
$00AB	$0871			MOVF	STACK_0+1, 0
$00AC	$02B5			SUBWF	FLOC_main+3, 1
$00AD	$0829			MOVF	_tipo, 0
$00AE	$00F0			MOVWF	STACK_0
$00AF	$082A			MOVF	_tipo+1, 0
$00B0	$00F1			MOVWF	STACK_0+1
$00B1	$30E8			MOVLW	232
$00B2	$00F4			MOVWF	STACK_4
$00B3	$3003			MOVLW	3
$00B4	$00F5			MOVWF	STACK_4+1
$00B5	$2530			CALL	_mul_16x16_s
$00B6	$0870			MOVF	STACK_0, 0
$00B7	$0234			SUBWF	FLOC_main+2, 0
$00B8	$00F0			MOVWF	STACK_0
$00B9	$0871			MOVF	STACK_0+1, 0
$00BA	$1C03			BTFSS	STATUS, C
$00BB	$3F01			ADDLW	1
$00BC	$0235			SUBWF	FLOC_main+3, 0
$00BD	$00F1			MOVWF	STACK_0+1
$00BE	$0870			MOVF	STACK_0, 0
$00BF	$00A3			MOVWF	_uni
$00C0	$0871			MOVF	STACK_0+1, 0
$00C1	$00A4			MOVWF	_uni+1
;Pic2.pbas,40 :: 		portc = uni + 16
$00C2	$3010			MOVLW	16
$00C3	$07F0			ADDWF	STACK_0, 1
$00C4	$1803			BTFSC	STATUS, C
$00C5	$0AF1			INCF	STACK_0+1, 1
$00C6	$0870			MOVF	STACK_0, 0
$00C7	$0087			MOVWF	PORTC
;Pic2.pbas,41 :: 		delay_ms(5)
$00C8	$3007			MOVLW	7
$00C9	$00FB			MOVWF	STACK_11
$00CA	$30FF			MOVLW	255
$00CB	$00FA			MOVWF	STACK_10
$00CC	$0BFB			DECFSZ	STACK_11, F
$00CD	$28CF			GOTO	$+2
$00CE	$28D2			GOTO	$+4
$00CF	$0BFA			DECFSZ	STACK_10, F
$00D0	$28CF			GOTO	$-1
$00D1	$28CC			GOTO	$-5
$00D2	$3078			MOVLW	120
$00D3	$00FA			MOVWF	STACK_10
$00D4	$0BFA			DECFSZ	STACK_10, F
$00D5	$28D4			GOTO	$-1
$00D6	$0000			NOP
$00D7	$0000			NOP
;Pic2.pbas,43 :: 		portc = dez + 32
$00D8	$3020			MOVLW	32
$00D9	$0736			ADDWF	FLOC_main+4, 0
$00DA	$00F0			MOVWF	STACK_0
$00DB	$0837			MOVF	FLOC_main+5, 0
$00DC	$1803			BTFSC	STATUS, C
$00DD	$3F01			ADDLW	1
$00DE	$00F1			MOVWF	STACK_0+1
$00DF	$3000			MOVLW	0
$00E0	$07F1			ADDWF	STACK_0+1, 1
$00E1	$0870			MOVF	STACK_0, 0
$00E2	$0087			MOVWF	PORTC
;Pic2.pbas,44 :: 		delay_ms(5)
$00E3	$3007			MOVLW	7
$00E4	$00FB			MOVWF	STACK_11
$00E5	$30FF			MOVLW	255
$00E6	$00FA			MOVWF	STACK_10
$00E7	$0BFB			DECFSZ	STACK_11, F
$00E8	$28EA			GOTO	$+2
$00E9	$28ED			GOTO	$+4
$00EA	$0BFA			DECFSZ	STACK_10, F
$00EB	$28EA			GOTO	$-1
$00EC	$28E7			GOTO	$-5
$00ED	$3078			MOVLW	120
$00EE	$00FA			MOVWF	STACK_10
$00EF	$0BFA			DECFSZ	STACK_10, F
$00F0	$28EF			GOTO	$-1
$00F1	$0000			NOP
$00F2	$0000			NOP
;Pic2.pbas,46 :: 		portc = cent + 64
$00F3	$3040			MOVLW	64
$00F4	$0738			ADDWF	FLOC_main+6, 0
$00F5	$00F0			MOVWF	STACK_0
$00F6	$0839			MOVF	FLOC_main+7, 0
$00F7	$1803			BTFSC	STATUS, C
$00F8	$3F01			ADDLW	1
$00F9	$00F1			MOVWF	STACK_0+1
$00FA	$3000			MOVLW	0
$00FB	$07F1			ADDWF	STACK_0+1, 1
$00FC	$0870			MOVF	STACK_0, 0
$00FD	$0087			MOVWF	PORTC
;Pic2.pbas,47 :: 		delay_ms(5)
$00FE	$3007			MOVLW	7
$00FF	$00FB			MOVWF	STACK_11
$0100	$30FF			MOVLW	255
$0101	$00FA			MOVWF	STACK_10
$0102	$0BFB			DECFSZ	STACK_11, F
$0103	$2905			GOTO	$+2
$0104	$2908			GOTO	$+4
$0105	$0BFA			DECFSZ	STACK_10, F
$0106	$2905			GOTO	$-1
$0107	$2902			GOTO	$-5
$0108	$3078			MOVLW	120
$0109	$00FA			MOVWF	STACK_10
$010A	$0BFA			DECFSZ	STACK_10, F
$010B	$290A			GOTO	$-1
$010C	$0000			NOP
$010D	$0000			NOP
;Pic2.pbas,49 :: 		portc = 129
$010E	$3081			MOVLW	129
$010F	$0087			MOVWF	PORTC
;Pic2.pbas,50 :: 		delay_ms(5)
$0110	$3007			MOVLW	7
$0111	$00FB			MOVWF	STACK_11
$0112	$30FF			MOVLW	255
$0113	$00FA			MOVWF	STACK_10
$0114	$0BFB			DECFSZ	STACK_11, F
$0115	$2917			GOTO	$+2
$0116	$291A			GOTO	$+4
$0117	$0BFA			DECFSZ	STACK_10, F
$0118	$2917			GOTO	$-1
$0119	$2914			GOTO	$-5
$011A	$3078			MOVLW	120
$011B	$00FA			MOVWF	STACK_10
$011C	$0BFA			DECFSZ	STACK_10, F
$011D	$291C			GOTO	$-1
$011E	$0000			NOP
$011F	$0000			NOP
$0120	$	Pic2_L_2:
;Pic2.pbas,52 :: 		end if
$0120	$	Pic2_L_3:
;Pic2.pbas,53 :: 		if tipo = 2 then
$0120	$3000			MOVLW	0
$0121	$062A			XORWF	_tipo+1, 0
$0122	$1D03			BTFSS	STATUS, Z
$0123	$2926			GOTO	L_main_1
$0124	$3002			MOVLW	2
$0125	$0629			XORWF	_tipo, 0
$0126	$	L_main_1:
$0126	$1D03			BTFSS	STATUS, Z
$0127	$2A07			GOTO	Pic2_L_5
$0128	$	Pic2_L_4:
;Pic2.pbas,54 :: 		cent = senha div 100 - (tipo * 10)
$0128	$3064			MOVLW	100
$0129	$00F4			MOVWF	STACK_4
$012A	$01F5			CLRF	STACK_4+1
$012B	$0821			MOVF	_senha, 0
$012C	$00F0			MOVWF	STACK_0
$012D	$0822			MOVF	_senha+1, 0
$012E	$00F1			MOVWF	STACK_0+1
$012F	$2493			CALL	_div_16x16_s
$0130	$0870			MOVF	STACK_0, 0
$0131	$00B4			MOVWF	FLOC_main+2
$0132	$0871			MOVF	STACK_0+1, 0
$0133	$00B5			MOVWF	FLOC_main+3
$0134	$0829			MOVF	_tipo, 0
$0135	$00F0			MOVWF	STACK_0
$0136	$082A			MOVF	_tipo+1, 0
$0137	$00F1			MOVWF	STACK_0+1
$0138	$300A			MOVLW	10
$0139	$00F4			MOVWF	STACK_4
$013A	$01F5			CLRF	STACK_4+1
$013B	$2530			CALL	_mul_16x16_s
$013C	$0870			MOVF	STACK_0, 0
$013D	$0234			SUBWF	FLOC_main+2, 0
$013E	$00B8			MOVWF	FLOC_main+6
$013F	$0871			MOVF	STACK_0+1, 0
$0140	$1C03			BTFSS	STATUS, C
$0141	$3F01			ADDLW	1
$0142	$0235			SUBWF	FLOC_main+3, 0
$0143	$00B9			MOVWF	FLOC_main+7
$0144	$0838			MOVF	FLOC_main+6, 0
$0145	$00A7			MOVWF	_cent
$0146	$0839			MOVF	FLOC_main+7, 0
$0147	$00A8			MOVWF	_cent+1
;Pic2.pbas,55 :: 		dez = senha div 10 - (cent * 10) - (tipo * 100)
$0148	$300A			MOVLW	10
$0149	$00F4			MOVWF	STACK_4
$014A	$01F5			CLRF	STACK_4+1
$014B	$0821			MOVF	_senha, 0
$014C	$00F0			MOVWF	STACK_0
$014D	$0822			MOVF	_senha+1, 0
$014E	$00F1			MOVWF	STACK_0+1
$014F	$2493			CALL	_div_16x16_s
$0150	$0870			MOVF	STACK_0, 0
$0151	$00B4			MOVWF	FLOC_main+2
$0152	$0871			MOVF	STACK_0+1, 0
$0153	$00B5			MOVWF	FLOC_main+3
$0154	$0838			MOVF	FLOC_main+6, 0
$0155	$00F0			MOVWF	STACK_0
$0156	$0839			MOVF	FLOC_main+7, 0
$0157	$00F1			MOVWF	STACK_0+1
$0158	$300A			MOVLW	10
$0159	$00F4			MOVWF	STACK_4
$015A	$01F5			CLRF	STACK_4+1
$015B	$2530			CALL	_mul_16x16_s
$015C	$0870			MOVF	STACK_0, 0
$015D	$02B4			SUBWF	FLOC_main+2, 1
$015E	$1C03			BTFSS	STATUS, C
$015F	$03B5			DECF	FLOC_main+3, 1
$0160	$0871			MOVF	STACK_0+1, 0
$0161	$02B5			SUBWF	FLOC_main+3, 1
$0162	$0829			MOVF	_tipo, 0
$0163	$00F0			MOVWF	STACK_0
$0164	$082A			MOVF	_tipo+1, 0
$0165	$00F1			MOVWF	STACK_0+1
$0166	$3064			MOVLW	100
$0167	$00F4			MOVWF	STACK_4
$0168	$01F5			CLRF	STACK_4+1
$0169	$2530			CALL	_mul_16x16_s
$016A	$0870			MOVF	STACK_0, 0
$016B	$0234			SUBWF	FLOC_main+2, 0
$016C	$00B6			MOVWF	FLOC_main+4
$016D	$0871			MOVF	STACK_0+1, 0
$016E	$1C03			BTFSS	STATUS, C
$016F	$3F01			ADDLW	1
$0170	$0235			SUBWF	FLOC_main+3, 0
$0171	$00B7			MOVWF	FLOC_main+5
$0172	$0836			MOVF	FLOC_main+4, 0
$0173	$00A5			MOVWF	_dez
$0174	$0837			MOVF	FLOC_main+5, 0
$0175	$00A6			MOVWF	_dez+1
;Pic2.pbas,56 :: 		uni = senha - (dez * 10) - (cent * 100) - (tipo * 1000)
$0176	$0836			MOVF	FLOC_main+4, 0
$0177	$00F0			MOVWF	STACK_0
$0178	$0837			MOVF	FLOC_main+5, 0
$0179	$00F1			MOVWF	STACK_0+1
$017A	$300A			MOVLW	10
$017B	$00F4			MOVWF	STACK_4
$017C	$01F5			CLRF	STACK_4+1
$017D	$2530			CALL	_mul_16x16_s
$017E	$0870			MOVF	STACK_0, 0
$017F	$0221			SUBWF	_senha, 0
$0180	$00B4			MOVWF	FLOC_main+2
$0181	$0871			MOVF	STACK_0+1, 0
$0182	$1C03			BTFSS	STATUS, C
$0183	$3F01			ADDLW	1
$0184	$0222			SUBWF	_senha+1, 0
$0185	$00B5			MOVWF	FLOC_main+3
$0186	$0838			MOVF	FLOC_main+6, 0
$0187	$00F0			MOVWF	STACK_0
$0188	$0839			MOVF	FLOC_main+7, 0
$0189	$00F1			MOVWF	STACK_0+1
$018A	$3064			MOVLW	100
$018B	$00F4			MOVWF	STACK_4
$018C	$01F5			CLRF	STACK_4+1
$018D	$2530			CALL	_mul_16x16_s
$018E	$0870			MOVF	STACK_0, 0
$018F	$02B4			SUBWF	FLOC_main+2, 1
$0190	$1C03			BTFSS	STATUS, C
$0191	$03B5			DECF	FLOC_main+3, 1
$0192	$0871			MOVF	STACK_0+1, 0
$0193	$02B5			SUBWF	FLOC_main+3, 1
$0194	$0829			MOVF	_tipo, 0
$0195	$00F0			MOVWF	STACK_0
$0196	$082A			MOVF	_tipo+1, 0
$0197	$00F1			MOVWF	STACK_0+1
$0198	$30E8			MOVLW	232
$0199	$00F4			MOVWF	STACK_4
$019A	$3003			MOVLW	3
$019B	$00F5			MOVWF	STACK_4+1
$019C	$2530			CALL	_mul_16x16_s
$019D	$0870			MOVF	STACK_0, 0
$019E	$0234			SUBWF	FLOC_main+2, 0
$019F	$00F0			MOVWF	STACK_0
$01A0	$0871			MOVF	STACK_0+1, 0
$01A1	$1C03			BTFSS	STATUS, C
$01A2	$3F01			ADDLW	1
$01A3	$0235			SUBWF	FLOC_main+3, 0
$01A4	$00F1			MOVWF	STACK_0+1
$01A5	$0870			MOVF	STACK_0, 0
$01A6	$00A3			MOVWF	_uni
$01A7	$0871			MOVF	STACK_0+1, 0
$01A8	$00A4			MOVWF	_uni+1
;Pic2.pbas,58 :: 		portc = uni + 16
$01A9	$3010			MOVLW	16
$01AA	$07F0			ADDWF	STACK_0, 1
$01AB	$1803			BTFSC	STATUS, C
$01AC	$0AF1			INCF	STACK_0+1, 1
$01AD	$0870			MOVF	STACK_0, 0
$01AE	$0087			MOVWF	PORTC
;Pic2.pbas,59 :: 		delay_ms(5)
$01AF	$3007			MOVLW	7
$01B0	$00FB			MOVWF	STACK_11
$01B1	$30FF			MOVLW	255
$01B2	$00FA			MOVWF	STACK_10
$01B3	$0BFB			DECFSZ	STACK_11, F
$01B4	$29B6			GOTO	$+2
$01B5	$29B9			GOTO	$+4
$01B6	$0BFA			DECFSZ	STACK_10, F
$01B7	$29B6			GOTO	$-1
$01B8	$29B3			GOTO	$-5
$01B9	$3078			MOVLW	120
$01BA	$00FA			MOVWF	STACK_10
$01BB	$0BFA			DECFSZ	STACK_10, F
$01BC	$29BB			GOTO	$-1
$01BD	$0000			NOP
$01BE	$0000			NOP
;Pic2.pbas,61 :: 		portc = dez + 32
$01BF	$3020			MOVLW	32
$01C0	$0736			ADDWF	FLOC_main+4, 0
$01C1	$00F0			MOVWF	STACK_0
$01C2	$0837			MOVF	FLOC_main+5, 0
$01C3	$1803			BTFSC	STATUS, C
$01C4	$3F01			ADDLW	1
$01C5	$00F1			MOVWF	STACK_0+1
$01C6	$3000			MOVLW	0
$01C7	$07F1			ADDWF	STACK_0+1, 1
$01C8	$0870			MOVF	STACK_0, 0
$01C9	$0087			MOVWF	PORTC
;Pic2.pbas,62 :: 		delay_ms(5)
$01CA	$3007			MOVLW	7
$01CB	$00FB			MOVWF	STACK_11
$01CC	$30FF			MOVLW	255
$01CD	$00FA			MOVWF	STACK_10
$01CE	$0BFB			DECFSZ	STACK_11, F
$01CF	$29D1			GOTO	$+2
$01D0	$29D4			GOTO	$+4
$01D1	$0BFA			DECFSZ	STACK_10, F
$01D2	$29D1			GOTO	$-1
$01D3	$29CE			GOTO	$-5
$01D4	$3078			MOVLW	120
$01D5	$00FA			MOVWF	STACK_10
$01D6	$0BFA			DECFSZ	STACK_10, F
$01D7	$29D6			GOTO	$-1
$01D8	$0000			NOP
$01D9	$0000			NOP
;Pic2.pbas,64 :: 		portc = cent + 64
$01DA	$3040			MOVLW	64
$01DB	$0738			ADDWF	FLOC_main+6, 0
$01DC	$00F0			MOVWF	STACK_0
$01DD	$0839			MOVF	FLOC_main+7, 0
$01DE	$1803			BTFSC	STATUS, C
$01DF	$3F01			ADDLW	1
$01E0	$00F1			MOVWF	STACK_0+1
$01E1	$3000			MOVLW	0
$01E2	$07F1			ADDWF	STACK_0+1, 1
$01E3	$0870			MOVF	STACK_0, 0
$01E4	$0087			MOVWF	PORTC
;Pic2.pbas,65 :: 		delay_ms(5)
$01E5	$3007			MOVLW	7
$01E6	$00FB			MOVWF	STACK_11
$01E7	$30FF			MOVLW	255
$01E8	$00FA			MOVWF	STACK_10
$01E9	$0BFB			DECFSZ	STACK_11, F
$01EA	$29EC			GOTO	$+2
$01EB	$29EF			GOTO	$+4
$01EC	$0BFA			DECFSZ	STACK_10, F
$01ED	$29EC			GOTO	$-1
$01EE	$29E9			GOTO	$-5
$01EF	$3078			MOVLW	120
$01F0	$00FA			MOVWF	STACK_10
$01F1	$0BFA			DECFSZ	STACK_10, F
$01F2	$29F1			GOTO	$-1
$01F3	$0000			NOP
$01F4	$0000			NOP
;Pic2.pbas,67 :: 		portc = 130
$01F5	$3082			MOVLW	130
$01F6	$0087			MOVWF	PORTC
;Pic2.pbas,68 :: 		delay_ms(5)
$01F7	$3007			MOVLW	7
$01F8	$00FB			MOVWF	STACK_11
$01F9	$30FF			MOVLW	255
$01FA	$00FA			MOVWF	STACK_10
$01FB	$0BFB			DECFSZ	STACK_11, F
$01FC	$29FE			GOTO	$+2
$01FD	$2A01			GOTO	$+4
$01FE	$0BFA			DECFSZ	STACK_10, F
$01FF	$29FE			GOTO	$-1
$0200	$29FB			GOTO	$-5
$0201	$3078			MOVLW	120
$0202	$00FA			MOVWF	STACK_10
$0203	$0BFA			DECFSZ	STACK_10, F
$0204	$2A03			GOTO	$-1
$0205	$0000			NOP
$0206	$0000			NOP
$0207	$	Pic2_L_5:
;Pic2.pbas,69 :: 		end if
$0207	$	Pic2_L_6:
;Pic2.pbas,73 :: 		goto executa
$0207	$2821			GOTO	_main_executa
$0208	$2A08			GOTO	$
