;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 10/04/2020 18:04:34
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0018	$	_usart_init:
;USART_b75.ppas,22 :: 		
;USART_b75.ppas,24 :: 		
$0018	$	USART_b75_L_1:
$0018	$1303			BCF	STATUS, RP1
$0019	$1683			BSF	STATUS, RP0
$001A	$1698			BSF	TXSTA, 5
$001B	$	USART_b75_L_2:
;USART_b75.ppas,25 :: 		
$001B	$3090			MOVLW	144
$001C	$1283			BCF	STATUS, RP0
$001D	$0098			MOVWF	RCSTA
;USART_b75.ppas,31 :: 		
$001E	$	USART_b75_L_3:
$001E	$1683			BSF	STATUS, RP0
$001F	$1686			BSF	TRISB, 5
$0020	$	USART_b75_L_4:
;USART_b75.ppas,32 :: 		
$0020	$	USART_b75_L_5:
$0020	$1786			BSF	TRISB, 7
$0021	$	USART_b75_L_6:
;USART_b75.ppas,35 :: 		
$0021	$	USART_b75_L_8:
$0021	$1283			BCF	STATUS, RP0
$0022	$080C			MOVF	PIR1, 0
$0023	$00F1			MOVWF	STACK_1
$0024	$3000			MOVLW	0
$0025	$1AF1			BTFSC	STACK_1, 5
$0026	$3001			MOVLW	1
$0027	$00F1			MOVWF	STACK_1
$0028	$0871			MOVF	STACK_1, 0
$0029	$3A01			XORLW	1
$002A	$1903			BTFSC	STATUS, Z
$002B	$2821			GOTO	USART_b75_L_8
;USART_b75.ppas,36 :: 		
$002C	$	USART_b75_L_9:
$002C	$	USART_b75_L_0:
;USART_b75.ppas,37 :: 		
$002C	$0008			RETURN
$0004	$	_main:
;SistemaDeContagemMercado.pbas,1 :: 		program SistemaDeContagemMercado
$0004	$	_main_main:
;SistemaDeContagemMercado.pbas,3 :: 		inicio:
$0004	$	_main_inicio:
;SistemaDeContagemMercado.pbas,4 :: 		TRISA=%11111111
$0004	$30FF			MOVLW	255
$0005	$1303			BCF	STATUS, RP1
$0006	$1683			BSF	STATUS, RP0
$0007	$0085			MOVWF	TRISA
;SistemaDeContagemMercado.pbas,5 :: 		TRISB=%11111111
$0008	$30FF			MOVLW	255
$0009	$0086			MOVWF	TRISB
;SistemaDeContagemMercado.pbas,6 :: 		TRISC=%00000000
$000A	$0187			CLRF	TRISC, 1
;SistemaDeContagemMercado.pbas,7 :: 		INTCON=%00000000
$000B	$018B			CLRF	INTCON, 1
;SistemaDeContagemMercado.pbas,8 :: 		ANSEL=%00000000
$000C	$1703			BSF	STATUS, RP1
$000D	$1283			BCF	STATUS, RP0
$000E	$019E			CLRF	ANSEL, 1
;SistemaDeContagemMercado.pbas,9 :: 		ANSELH=%00000000
$000F	$019F			CLRF	ANSELH, 1
;SistemaDeContagemMercado.pbas,11 :: 		Usart_Init(9600)
$0010	$3019			MOVLW	25
$0011	$1303			BCF	STATUS, RP1
$0012	$1683			BSF	STATUS, RP0
$0013	$0099			MOVWF	SPBRG
$0014	$1518			BSF	TXSTA, BRGH
$0015	$2018			CALL	_usart_init
;SistemaDeContagemMercado.pbas,13 :: 		executa:
$0016	$	_main_executa:
;SistemaDeContagemMercado.pbas,15 :: 		goto executa
$0016	$2816			GOTO	_main_executa
$0017	$2817			GOTO	$
